import { activeConflicts } from './conflict';
import { conflictConfig as config } from './conflictConfig';
import type { ConflictAction, EventContext, EventEffect, GameEventDefinition } from './types';
export function contextConflict(c:EventContext){
  if(c.conflictId)return c.game.world.internalConflicts?.[c.conflictId];
  const owner=c.jurisdiction.kind==='country'?c.jurisdiction.id:c.game.world.regions[c.jurisdiction.id].ownerCountryId;
  return activeConflicts(c.game.world).filter(conflict=>[conflict.parentCountryId,conflict.breakawayCountryId].includes(owner)).sort((a,b)=>a.id.localeCompare(b.id))[0];
}
const parentSide=(c:EventContext)=>{const conflict=contextConflict(c)!;const owner=c.jurisdiction.kind==='country'?c.jurisdiction.id:c.game.world.regions[c.jurisdiction.id].ownerCountryId;return owner===conflict.parentCountryId;};
const stages=[
  {id:'corridor',title:'주요 비행회랑 봉쇄',description:'양측 관제기관이 주요 회랑의 비행권을 놓고 대치하고 있습니다. 강경 압박은 긴장을 높이고 공동 중재는 정치적 충돌을 줄일 기회가 됩니다.',actions:['blockade','negotiate','recognize'],eligible:(c:EventContext)=>contextConflict(c)!.status==='political_standoff'},
  {id:'escalation',title:'대형 횃대 관제권 충돌',description:'강경 선언과 봉쇄 이후 대형 횃대의 관제권을 둘러싼 충돌이 확대됐습니다. 편대 간 무력충돌을 지속할지 휴전·협상으로 전환할지 결정합니다.',actions:['escalate','negotiate','ceasefire'],eligible:(c:EventContext)=>{const x=contextConflict(c)!;return x.status==='political_standoff'&&x.monthsInConflict>=3&&x.tension>=65&&x.lastHardlineTurn!==null&&c.game.world.countries[x.breakawayCountryId].identity?.territorialDispute==='parent_claims_reunification';}},
  {id:'supply',title:'곡물 보급 횃대 단절',description:'안전한 횃대와 곡물 저장망의 연결이 끊어져 양측 비행 보급 편대의 부담이 커졌습니다. 지속 대응과 휴전 중 선택이 필요합니다.',actions:['supply','ceasefire','negotiate'],eligible:(c:EventContext)=>contextConflict(c)!.status==='armed_conflict'},
  {id:'ceasefire',title:'대편대 휴전 제안',description:'분쟁 피로와 낮아진 전쟁 지지로 대표 편대가 비행 회랑의 상호 정지를 제안했습니다. 휴전 중에는 통제율과 영토 분쟁이 유지됩니다.',actions:['ceasefire','negotiate','pressure'],eligible:(c:EventContext)=>{const x=contextConflict(c)!;return x.status==='armed_conflict'&&(x.parentFatigue+x.breakawayFatigue>=50||Math.min(x.parentWarSupport,x.breakawayWarSupport)<40||x.monthsInConflict>=36);}},
  {id:'administration',title:'둥지권 행정기관 이탈',description:'일부 둥지권의 공동 행정기관이 기존 운영망으로 복귀하려 하고 있습니다. 관제권 변화를 수용하거나 중재회의에 참여할 수 있습니다.',actions:['administrative_shift','negotiate','ceasefire'],eligible:(c:EventContext)=>contextConflict(c)!.status==='armed_conflict'},
  {id:'finance',title:'전시 재정 부담 확대',description:'화물 편대 우회와 긴급 횃대 유지 비용이 국고를 압박합니다. 대응을 지속하면 피로가 늘고 협상은 부담을 줄일 수 있습니다.',actions:['supply','negotiate','ceasefire'],eligible:(c:EventContext)=>contextConflict(c)!.status==='armed_conflict'},
  {id:'refuge',title:'피난 철새 무리 증가',description:'분쟁 둥지권을 떠난 철새 무리가 임시 횃대에 모였습니다. 안전한 비행 회랑 확보와 휴전 협상이 정착 부담을 줄일 수 있습니다.',actions:['supply','ceasefire','negotiate'],eligible:(c:EventContext)=>{const x=contextConflict(c)!;return x.status==='armed_conflict'&&x.monthsInConflict>=12;}},
  {id:'mediation',title:'공동 중재회의 제안',description:'여러 둥지권의 대표들이 회랑 통제와 자치권 문제를 함께 논의할 중재회의를 요청했습니다. 장기 분쟁일수록 합의 압력이 커집니다.',actions:['negotiate','ceasefire','fail_negotiation'],eligible:(c:EventContext)=>['political_standoff','ceasefire','armed_conflict'].includes(contextConflict(c)!.status)},
  {id:'stalemate',title:'장기 교착에 대한 횃대 여론 악화',description:'통제권 변화 없는 장기 대치가 공동 횃대의 여론을 악화시켰습니다. 분쟁 피로를 감수할지 협상으로 전환할지 결정해야 합니다.',actions:['public_opinion','negotiate','ceasefire'],eligible:(c:EventContext)=>{const x=contextConflict(c)!;return x.status==='armed_conflict'&&(x.stalemateMonths>=12||x.monthsInConflict>=24);}},
  {id:'autonomy',title:'확대 자치 재통합 협정 초안',description:'공동 둥지권의 확대 자치와 비행 회랑 권한 보장을 조건으로 재통합 초안이 제출됐습니다. 국가 존속과 실제 자치 수준에 영향을 줍니다.',actions:['accept_autonomy','recognize','fail_negotiation'],eligible:(c:EventContext)=>contextConflict(c)!.status==='negotiation'},
  {id:'recognition',title:'독립 승인 비행헌장 협정',description:'부모국과 신생국의 대표들이 독립을 최종 인정할 비행헌장을 검토합니다. 승인에는 부모국의 단기 통합 부담이 따릅니다.',actions:['recognize','accept_autonomy','fail_negotiation'],eligible:(c:EventContext)=>contextConflict(c)!.status==='negotiation'},
  {id:'parent-victory',title:'둥지권 재통합 최종 절차',description:'부모국의 결정적 회랑 통제가 일정 기간 유지됐습니다. 재통합을 확정하거나 확대 자치 협상으로 전환할 수 있습니다.',actions:['force_reintegrate','negotiate','recognize'],eligible:(c:EventContext)=>contextConflict(c)!.parentDominanceMonths>=config.dominanceMonths},
  {id:'breakaway-victory',title:'독립 비행권 방어 성공',description:'신생국 편대의 높은 회랑 통제와 전쟁 지지가 지속됐습니다. 독립을 확정하거나 둥지권 협상을 이어갈 수 있습니다.',actions:['defend_independence','negotiate','ceasefire'],eligible:(c:EventContext)=>{const x=contextConflict(c)!;return x.breakawayDominanceMonths>=config.dominanceMonths&&x.breakawayWarSupport>=35;}},
  {id:'long-mediation',title:'장기 분쟁 종결 중재회의',description:'십 년에 걸친 분쟁 이후 공동 횃대의 대표들이 종결 절차를 요청했습니다. 중재안은 현재 통제권에 따라 독립 승인 또는 확대 자치 재통합을 제안합니다.',actions:['negotiate','negotiate','negotiate'],eligible:(c:EventContext)=>contextConflict(c)!.monthsInConflict>=config.mandatoryMediationMonths&&contextConflict(c)!.status!=='negotiation'},
] as const;
const labels:Record<ConflictAction,string>={pressure:'재통합 압박 / 방어 지속',blockade:'비행회랑 압박 강화',escalate:'무력충돌 대응 지속',ceasefire:'대편대 휴전 수용',negotiate:'공동 중재 협상',fail_negotiation:'협상안 거부',recognize:'독립 최종 인정',accept_autonomy:'확대 자치 재통합 수용',force_reintegrate:'둥지권 재통합 확정',defend_independence:'독립 방어 성공 확정',supply:'곡물·횃대 보급 부담 감수',administrative_shift:'행정기관 복귀 수용',public_opinion:'분쟁 대응 지속'};
export const conflictEventDefinitions:readonly GameEventDefinition[]=stages.map(stage=>({id:`conflict-${stage.id}`,title:stage.title,description:stage.description,category:'governance',tone:'mixed',baseMonthlyChance:.04,cooldownMonths:stage.id==='long-mediation'?1:6,conflictEvent:true,priority:['parent-victory','breakaway-victory','long-mediation'].includes(stage.id),tags:['internal_conflict'],nonPlayerChoiceId:['autonomy','recognition','parent-victory','breakaway-victory'].includes(stage.id)?'invest':'balance',
  eligible:c=>!!contextConflict(c)&&stage.eligible(c),
  calculateChance:c=>{const x=contextConflict(c)!;return stage.id==='escalation'?.04+x.tension*.002:stage.id==='ceasefire'||stage.id==='mediation'?.04+(x.parentFatigue+x.breakawayFatigue)*.002+x.monthsInConflict*.001:.04;},
  severity:c=>contextConflict(c)!.status==='armed_conflict'?3:2,
  choices:stage.actions.map((action,i)=>({id:['invest','balance','restrict'][i],label:labels[action],labelFor:c=>action==='recognize'&&!parentSide(c)?'독립 최종 승인 요청·수용':action==='pressure'&&!parentSide(c)?'독립 비행권 방어 지속':labels[action],preview:action==='recognize'||action==='defend_independence'?'독립국 지위를 확정하고 분쟁을 종결합니다. 부모국의 통합·안정에 비용이 남습니다.':action==='accept_autonomy'?'확대 자치로 재통합합니다. 신생국 운영 중이라면 게임이 종료됩니다.':action==='force_reintegrate'?'재통합을 확정합니다. 3개월 복구 비용과 생활·종족정치 부담이 남습니다.':action==='ceasefire'?'통제율을 고정하고 분쟁 피해를 중단합니다. 영토 분쟁은 계속됩니다.':action==='negotiate'?'공동 협상을 시작하며 통제율을 유지하고 피로를 회복합니다.':action==='administrative_shift'?'독립국 통제율이 2%p 줄어듭니다. 분쟁은 계속됩니다.':action==='supply'||action==='public_opinion'?'대응을 지속하면서 양측 분쟁 피로가 늘어납니다.':'강경 대응으로 긴장이 높아집니다. 충돌 지속 또는 재개 가능성이 남습니다.',effects:c=>{const x=contextConflict(c)!;const chosen:ConflictAction=action;
    // 장기 종결 회의는 모든 선택이 협상을 시작하며 이후 확정 협정을 제시합니다.
    const effects:EventEffect[]=[{kind:'conflict',conflictId:x.id,action:chosen}];return {immediate:effects};}})),
}));
