import {casusBelliLabels} from './warfareConfig';
import {evaluateAchievements} from './achievements';
import {countries,regions} from './data';
import {derivedCountryRuntime} from './runtime';
import {technologyDefinition} from './technologyDefinitions';
import {historyConfig as config,historyWarResultLabels} from './historyConfig';
import {crisisDefinitions} from './crisisConfig';
import type {GameState,GameDate} from './types';
import type {HistoryState,HistoricalEvent,YearlyWorldSnapshot,CountryYearSnapshot,HistoricalImportance,HistoricalPeak,HistoricalTerritorialChange} from './historyTypes';
const copyDate=(d:GameDate)=>({...d});
const monthsBefore=(d:GameDate,months:number):GameDate=>{const index=d.year*12+d.month-1-months;return {year:Math.floor(index/12),month:(index%12+12)%12+1};};
const dateIndex=(d:GameDate)=>d.year*12+d.month;
export const historicalCountryName=(g:GameState,id:string)=>g.world.countries[id]?.identity?.name??g.history?.countries[id]?.currentOrFinalName??g.world.retiredCountryIdentities?.[id]?.name??countries.find(c=>c.id===id)?.name??id;
const regionName=(g:GameState,id:string)=>g.world.regions[id]?.regionIdentity?.name??regions.find(r=>r.id===id)?.name??id;
export function technologyHistoryScore(t:GameState['world']['countries'][string]['technology']):number {return t?Math.min(100,Object.values(t.domains).reduce((s,d)=>s+d.level+Math.min(99,d.progress)/100,0)/60*100):0;}
export function makeYearlySnapshot(g:GameState,year=g.date.year):YearlyWorldSnapshot {
 const list:CountryYearSnapshot[]=Object.keys(g.world.countries).sort().map(id=>{const c=derivedCountryRuntime(g.world,id),s=c.social!,v=c.governance!;return {countryId:id,countryName:historicalCountryName(g,id),population:c.population.total,gdp:c.economy.gdp,gdpPerCapita:c.population.total>0?c.economy.gdp*1e9/c.population.total:0,growth:c.economy.growth,unemployment:c.economy.unemployment,inflation:c.economy.inflation,treasury:c.fiscal.treasury,debt:c.fiscal.debt,approval:v?.approval??0,stability:v?.stability??0,integration:v?.integration??0,livingStandard:s?.livingStandard??0,education:s?.education??0,healthcare:s?.healthcare??0,publicSafety:s?.publicSafety??0,inequality:s?.inequality??0,technologyScore:technologyHistoryScore(c.technology),militaryCapability:c.military?.capability??0,regionCount:Object.values(g.world.regions).filter(r=>r.ownerCountryId===id).length};});
 return {year,date:copyDate(g.date),countries:list,totalWorldPopulation:list.reduce((s,c)=>s+c.population,0),totalWorldGDP:list.reduce((s,c)=>s+c.gdp,0),activeCountryCount:list.length,activeWarCount:Object.values(g.world.warfare?.wars??{}).filter(w=>w.status!=='resolved').length,activeCrisisCount:Object.keys(g.world.crises?.activeCrises??{}).length};
}
function emptyHistory(g:GameState):HistoryState {return {schemaVersion:1,timeline:[],yearlySnapshots:[],baseline:null,countries:{},wars:{},internalConflicts:{},elections:[],crises:{},technologyMilestones:[],worldFirstTechnology:{},nextHistoricalEventId:1,sourceCursors:{},seenSources:{},career:{startDate:copyDate(g.date),endDate:null,endReason:null,officesHeld:[],electionsWon:0,warsDuringRule:0,countriesFoundedDuringRule:0,majorCrises:0}};}
export function recordHistoricalEvent(g:GameState,event:Omit<HistoricalEvent,'id'|'order'>):GameState {
 const h=g.history??emptyHistory(g);if(h.seenSources[event.sourceKey])return g;
 const {metadata,regionIds,...data}=event; const n=h.nextHistoricalEventId;return {...g,history:{...h,nextHistoricalEventId:n+1,seenSources:{...h.seenSources,[event.sourceKey]:true},timeline:[...h.timeline,{...data,...(regionIds?{regionIds:[...regionIds]}:{}),date:copyDate(event.date),countryIds:[...event.countryIds],countryNames:[...event.countryNames],...(metadata?{metadata:structuredClone(metadata)}:{}),id:'history-'+n,order:n}]}};
}
/** One archive collector, used at command boundaries and once after the complete monthly pipeline.
 * Runtime source IDs/cursors deduplicate domain and event descriptions of the same outcome.
 * No RNG, no gameplay writes, no monthly world copies. */
export function collectHistory(previous:GameState,next:GameState,annual=false):GameState {
 if(next===previous&&next.history)return next;
 const original=next.history??previous.history??emptyHistory(previous);
 // Initially known technologies predate this campaign; later research cannot claim their world-first status.
 if(!next.history&&!previous.history){for(const [id,c] of Object.entries(previous.world.countries)){for(const techId of c.technology?.unlockedTechnologies??[]){if(original.worldFirstTechnology[techId])continue;const def=technologyDefinition(techId);original.worldFirstTechnology[techId]={id:'baseline:'+techId,date:copyDate(previous.date),countryId:id,countryName:historicalCountryName(previous,id),jurisdictionId:id,jurisdictionName:historicalCountryName(previous,id),technologyId:techId,technologyName:def.name,worldFirst:false,importance:'minor'};}}}
 let g:GameState={...next,history:{...original,countries:{...original.countries},wars:{...original.wars},internalConflicts:{...original.internalConflicts},crises:{...original.crises},elections:[...original.elections],technologyMilestones:[...original.technologyMilestones],worldFirstTechnology:{...original.worldFirstTechnology},sourceCursors:{...original.sourceCursors},career:{...original.career,officesHeld:original.career.officesHeld.map(p=>({...p}))}}};
 const emit=(key:string,category:HistoricalEvent['category'],importance:HistoricalEvent['importance'],title:string,ids:string[],date=next.date,metadata?:HistoricalEvent['metadata'],description=title)=>{g=recordHistoricalEvent(g,{sourceKey:key,date,category,importance,title,description,countryIds:ids,countryNames:ids.map(id=>historicalCountryName(g,id)),metadata});};
 for(const b of next.world.statePolitics?.blocs??[]){const before=previous.world.statePolitics?.blocs.find(x=>x.id===b.id);if(before?.active&&!b.active)emit('bloc-ended:'+b.id,'politics','major','연방 정치 공동전선 해체',['pigeon'],next.date,{purpose:b.purpose,reason:b.endReason??''});}
 const peak=(old:HistoricalPeak,value:number):HistoricalPeak=>value>old.value?{value,date:copyDate(next.date)}:old;
 for(const [id,c] of Object.entries(next.world.countries)){const h=g.history!,old=h.countries[id],name=historicalCountryName(g,id),origin=c.identity?.originCountryId??null;
  if(!old){const founded=copyDate(c.identity?.foundedDate??next.date),kind=c.identity?.isDynamic?(c.identity.status==='established'?'legal_independence':'unilateral_independence'):'initial';h.countries[id]={countryId:id,nameAtFounding:name,currentOrFinalName:name,foundedDate:founded,dissolvedDate:null,originCountryId:origin,primarySpeciesId:c.identity?.primarySpeciesId??countries.find(x=>x.id===id)?.speciesIds[0]??'sparrow',foundingType:kind,endType:'active',predecessorNames:origin?[historicalCountryName(g,origin)]:[],successorCountryIds:[],peakPopulation:{value:c.population.total,date:founded},peakGDP:{value:c.economy.gdp,date:founded},peakTechnology:{value:technologyHistoryScore(c.technology),date:founded},longestWarMonths:0,electionsHeld:0,territorialChanges:[]};emit('founded:'+id,'country','historic',name+(kind==='initial'?'의 역사 기록 시작':' 창건'),origin?[origin,id]:[id],founded, {foundingType:kind},kind==='initial'?'2030년의 국가 운영 기록이 시작되었다.':name+'의 둥지권과 비행회랑에 새 국기가 게양되었다.');}
  else h.countries[id]={...old,currentOrFinalName:name,peakPopulation:peak(old.peakPopulation,c.population.total),peakGDP:peak(old.peakGDP,c.economy.gdp),peakTechnology:peak(old.peakTechnology,technologyHistoryScore(c.technology))};
 }
 for(const [id,old] of Object.entries(g.history!.countries)){if(next.world.countries[id])continue; if(old.dissolvedDate){if(Object.values(next.world.internalConflicts??{}).some(c=>c.breakawayCountryId===id&&c.resolution?.includes('reintegration')))g.history!.countries[id]={...old,endType:'reunified'};continue;}const conflict=Object.values(next.world.internalConflicts??{}).find(c=>c.breakawayCountryId===id&&c.resolution?.includes('reintegration')),owned=Object.values(previous.world.regions).filter(r=>r.ownerCountryId===id),successors=[...new Set(owned.map(r=>next.world.regions[r.id]?.ownerCountryId).filter((x):x is string=>!!x&&x!==id))];g.history!.countries[id]={...old,dissolvedDate:copyDate(next.date),endType:conflict?'reunified':next.player.defeatedCountryId===id?'state_defeat':'annexed',successorCountryIds:successors};emit('dissolved:'+id,'country','historic',old.currentOrFinalName+' 소멸',[id,...successors]);}
 for(const [id,r] of Object.entries(next.world.regions)){const before=previous.world.regions[id];if(!before||before.ownerCountryId===r.ownerCountryId)continue;const change:HistoricalTerritorialChange={date:copyDate(next.date),regionId:id,regionName:regionName(g,id),fromId:before.ownerCountryId,fromName:historicalCountryName(g,before.ownerCountryId),toId:r.ownerCountryId,toName:historicalCountryName(g,r.ownerCountryId)};const key=`territory:${id}:${next.turn}:${change.fromId}:${change.toId}`;if(g.history!.seenSources[key])continue;
  for(const owner of [change.fromId,change.toId]){const old=g.history!.countries[owner];if(old)g.history!.countries[owner]={...old,territorialChanges:[...old.territorialChanges,change]};}
  emit(key,'independence','historic',change.regionName+'의 둥지권 이관',[change.fromId,change.toId],next.date,{regionId:id});
 }
 for(const w of Object.values(next.world.warfare?.wars??{})){const old=g.history!.wars[w.id],changes=[...(old?.territorialChanges??[])];
  for(const f of w.fronts){const before=previous.world.regions[f.regionId],after=next.world.regions[f.regionId];if(before&&after&&before.ownerCountryId!==after.ownerCountryId&&!changes.some(c=>c.regionId===f.regionId&&dateIndex(c.date)===dateIndex(next.date)))changes.push({date:copyDate(next.date),regionId:f.regionId,regionName:regionName(g,f.regionId),fromId:before.ownerCountryId,fromName:historicalCountryName(g,before.ownerCountryId),toId:after.ownerCountryId,toName:historicalCountryName(g,after.ownerCountryId)});}
  g.history!.wars[w.id]={legitimacy:w.legitimacy??'justified',...(w.casusBelliType?{casusBelliType:w.casusBelliType}:{}),warId:w.id,startedDate:copyDate(w.startedDate),endedDate:w.resolvedDate?copyDate(w.resolvedDate):null,attackerIds:[...w.attackers],defenderIds:[...w.defenders],attackerNames:w.attackers.map(id=>w.countryNames[id]??historicalCountryName(g,id)),defenderNames:w.defenders.map(id=>w.countryNames[id]??historicalCountryName(g,id)),warGoal:w.warGoal,durationMonths:w.monthsAtWar,status:w.status,result:w.resolution,territorialChanges:[...changes],reparations:old?.reparations??0};
  if(!old)emit('war-start:'+w.id,'war','historic',`${w.countryNames[w.primaryAttacker]} — ${w.countryNames[w.primaryDefender]} 전쟁 발발`,[...w.attackers,...w.defenders],w.startedDate,{warId:w.id,goal:w.warGoal,legitimacy:w.legitimacy??'justified',...(w.casusBelliType?{casusBelliType:w.casusBelliType}:{})},w.legitimacy==='unjustified'?`${w.countryNames[w.primaryAttacker]}이 전쟁명분 없이 ${w.countryNames[w.primaryDefender]}을 침공했다.`:`${w.countryNames[w.primaryAttacker]}이 ${w.casusBelliType?casusBelliLabels[w.casusBelliType]:'기존 전쟁명분'}을 명분으로 ${w.countryNames[w.primaryDefender]}에 선전포고했다.`);
  if(old&&old.status!==w.status&&w.status!=='resolved')emit(`war-status:${w.id}:${next.turn}:${w.status}`,'peace','major',w.status==='ceasefire'?'대편대 휴전':'비행회랑 평화협상',[...w.attackers,...w.defenders],next.date,{warId:w.id});
  if(w.resolvedDate&&!old?.endedDate){if(w.resolution==='reparations'){const payer=previous.world.countries[w.primaryDefender];g.history!.wars[w.id].reparations=payer?Math.min(payer.fiscal.treasury,payer.economy.gdp*.01):0;}emit('war-end:'+w.id,'peace','historic','전쟁 종료 · '+(w.resolution?historyWarResultLabels[w.resolution]:'평화 합의'),[...w.attackers,...w.defenders],w.resolvedDate,{warId:w.id,durationMonths:w.monthsAtWar});}
  for(const id of [...w.attackers,...w.defenders]){const c=g.history!.countries[id];if(c&&c.longestWarMonths<w.monthsAtWar)g.history!.countries[id]={...c,longestWarMonths:w.monthsAtWar};}
 }
 for(const c of Object.values(next.world.internalConflicts??{})){const old=g.history!.internalConflicts[c.id];g.history!.internalConflicts[c.id]={conflictId:c.id,parentId:c.parentCountryId,breakawayId:c.breakawayCountryId,parentName:c.parentName,breakawayName:c.breakawayName,startedDate:copyDate(c.startedDate),endedDate:c.resolvedDate?copyDate(c.resolvedDate):null,durationMonths:c.monthsInConflict,status:c.status,result:c.resolution,independent:c.resolution?!c.resolution.includes('reintegration'):null};if(!old||old.status!==c.status)emit(`conflict:${c.id}:${c.status}:${next.turn}`,'independence',c.status==='resolved'?'historic':'major',c.breakawayName+' · '+({armed_conflict:'내전 발발',resolved:'분쟁 종결',ceasefire:'내전 휴전',negotiation:'재통합·독립 협상',political_standoff:'독립을 둘러싼 대치'}[c.status]),[c.parentCountryId,c.breakawayCountryId],next.date,{conflictId:c.id,result:c.resolution??''});}
 const fresh=<T extends {id:string}>(key:string,items:T[])=>{const cursor=g.history!.sourceCursors[key],found=cursor?items.findIndex(e=>e.id===cursor):-1;g.history!.sourceCursors[key]=items[0]?.id??cursor??null;return (found<0?items:items.slice(0,found)).slice().reverse();};
 for(const e of fresh('diplomacy',next.world.diplomacy?.history??[])){if(!e.accepted||['improve','country_removed','support_parent'].includes(e.action))continue;emit('dip:'+e.id,'diplomacy',['recognize','withdraw_recognition','sanction','lift_sanctions','defense','break_defense'].includes(e.action)?'major':'minor',e.summary,[e.actorId,e.targetId],e.date,{action:e.action});}
 for(const e of fresh('technology',next.world.technologyHistory??[])){const id=next.world.regions[e.jurisdictionId]?.ownerCountryId??e.jurisdictionId,def=technologyDefinition(e.technologyId),first=!g.history!.worldFirstTechnology[e.technologyId],importance:HistoricalImportance=first&&def.resultLevel>=config.technologyHistoricLevel?'historic':def.resultLevel>=config.technologyMajorLevel?'major':'minor';const record={...e,countryId:id,countryName:historicalCountryName(g,id),worldFirst:first,importance};g.history!.technologyMilestones.push(record);if(first)g.history!.worldFirstTechnology[e.technologyId]=record;emit('tech:'+e.id,'technology',importance,`${e.jurisdictionName}${first?'이 세계 최초로':'의'} ${e.technologyName} 실용화`,[id],e.date,{worldFirst:first,technologyId:e.technologyId});}
 const election=next.player.career.lastElection;if(election&&!g.history!.elections.some(e=>e.id==='election:'+election.turn)){const id=next.player.controlledCountryId,record={id:'election:'+election.turn,date:copyDate(election.date),countryId:id,countryName:historicalCountryName(g,id),regionId:next.player.controlledRegionId,office:next.player.career.office,termNumber:election.termNumber,reelectionChance:election.snapshot.reelectionChance,result:election.won?'won' as const:'lost' as const};g.history!.elections.push(record);const c=g.history!.countries[id];if(c)g.history!.countries[id]={...c,electionsHeld:c.electionsHeld+1};emit(record.id,'election','major',record.countryName+' · 제'+record.termNumber+'기 선거 '+(election.won?'승리':'패배'),[id],election.date,{chance:record.reelectionChance,result:record.result});}
 for(const c of Object.values(next.world.crises?.activeCrises??{})){const old=g.history!.crises[c.id],id=c.jurisdictionKind==='country'?c.jurisdictionId:next.world.regions[c.jurisdictionId]?.ownerCountryId; if(!id)continue;g.history!.crises[c.id]={crisisId:c.id,type:c.type,countryId:old?.countryId??id,countryName:old?.countryName??historicalCountryName(g,id),jurisdictionId:c.originJurisdictionId??c.jurisdictionId,jurisdictionName:old?.jurisdictionName??(c.jurisdictionKind==='region'?regionName(g,c.jurisdictionId):historicalCountryName(g,id)),startedDate:old?.startedDate??monthsBefore(next.date,next.turn-c.startedTurn),endedDate:null,maxSeverity:Math.max(old?.maxSeverity??0,c.severity),durationMonths:c.elapsedMonths,totalFiscalCost:c.totalFiscalCost,totalPopulationImpact:c.totalPopulationImpact,endReason:null};if(c.severity>=config.crisisMajorSeverity)emit('crisis-start:'+c.id,'crisis',c.severity>=config.crisisHistoricSeverity?'historic':'major',g.history!.crises[c.id].jurisdictionName+' · '+crisisDefinitions[c.type].name+' 발생',[id],g.history!.crises[c.id].startedDate,{type:c.type,severity:c.severity});}
 for(const e of fresh('crises',next.world.crises?.history??[])){if(!['complete','retired'].includes(e.action))continue;const old=g.history!.crises[e.crisisId];if(!old)continue;g.history!.crises[e.crisisId]={...old,endedDate:copyDate(e.date),durationMonths:e.elapsedMonths,totalFiscalCost:e.fiscalCost,totalPopulationImpact:e.populationImpact,endReason:e.action};if(old.maxSeverity>=config.crisisMajorSeverity)emit('crisis-end:'+e.crisisId,'crisis',old.maxSeverity>=config.crisisHistoricSeverity||e.elapsedMonths>=config.crisisHistoricMonths||e.fiscalCost>(next.world.countries[old.countryId]?.economy.gdp??Infinity)*config.crisisHistoricCostGDP?'historic':'major',e.summary,[old.countryId],e.date,{cost:e.fiscalCost,populationImpact:e.populationImpact});}
 for(const e of next.events.history.filter(e=>e.turn===next.turn&&e.severity>=2&&['autonomy-protest','separatist-protest','federal-grievance','domestic-unrest','state-dispute'].includes(e.eventId))){const owner=e.jurisdiction.kind==='country'?e.jurisdiction.id:next.world.regions[e.jurisdiction.id]?.ownerCountryId;if(owner)emit('conflict-event:'+e.id,'politics','major',e.title+' · '+e.choiceLabel,[owner],e.date,{eventId:e.eventId,choiceId:e.choiceId});}
 // Store referendum metadata even when the domain API is called outside the event engine.
 for(const [kind,entries] of [['country',next.world.countries],['region',next.world.regions]] as const)for(const [id,r] of Object.entries(entries))for(const [sp,m] of Object.entries(r.secession??{}) as [string,import("./types").SecessionMovementState][]){const before=(kind==='country'?previous.world.countries[id]:previous.world.regions[id])?.secession?.[sp as import('./types').SpeciesId];const ownerId=kind==='country'?id:next.world.regions[id].ownerCountryId;if(before&&m.phase!==before.phase&&['organizing','referendum_campaign','referendum_scheduled','unilateral_crisis'].includes(m.phase))emit('movement:'+kind+':'+id+':'+sp+':'+m.phase+':'+next.turn,'independence','major',historicalCountryName(g,ownerId)+' · '+({organizing:'자치운동 시작',referendum_campaign:'주민투표 요구',referendum_scheduled:'주민투표 승인',unilateral_crisis:'독립을 둘러싼 위기'}[m.phase as 'organizing']),[ownerId]);const vote=m.lastReferendumResult;if(!vote)continue;const owner=kind==='country'?id:next.world.regions[id].ownerCountryId;emit(`referendum:${kind}:${id}:${sp}:${dateIndex(vote.date)}`,'independence','major',regionName(g,id)+' 주민투표 '+(vote.passed?'가결':'부결'),[owner],vote.date,{yesShare:vote.yesShare,passed:vote.passed});}
 for(const [id,c] of Object.entries(g.history!.crises)){if(!c.endedDate&&!next.world.crises?.activeCrises[id])g.history!.crises[id]={...c,endedDate:copyDate(next.date),endReason:'merged_or_retired'};}
 const h=g.history!,career=h.career,last=career.officesHeld.at(-1),p=next.player; if(!last||!next.gameOverReason&&(last.countryId!==p.controlledCountryId||last.regionId!==p.controlledRegionId||last.office!==p.career.office)){if(last)last.endDate=copyDate(next.date);career.officesHeld.push({countryId:p.controlledCountryId,countryName:historicalCountryName(g,p.controlledCountryId),regionId:p.controlledRegionId,office:p.career.office,startDate:copyDate(next.date),endDate:null});}
 career.electionsWon=h.elections.filter(e=>e.result==='won').length;career.warsDuringRule=Object.values(h.wars).filter(w=>[...w.attackerIds,...w.defenderIds].some(id=>career.officesHeld.some(o=>o.countryId===id&&dateIndex(o.startDate)<=dateIndex(w.startedDate)&&(!o.endDate||dateIndex(o.endDate)>=dateIndex(w.startedDate))))).length;career.countriesFoundedDuringRule=Object.values(h.countries).filter(c=>c.foundingType!=='initial').length;career.majorCrises=Object.values(h.crises).filter(c=>c.maxSeverity>=config.crisisMajorSeverity&&career.officesHeld.some(o=>o.countryId===c.countryId)).length;
 if(next.gameOverReason&&!career.endDate){career.endDate=copyDate(next.date);career.endReason=next.gameOverReason;if(career.officesHeld.at(-1))career.officesHeld.at(-1)!.endDate=copyDate(next.date);emit('career-end','politics','major','지도자의 통치 종료',[p.defeatedCountryId??p.controlledCountryId],next.date,{reason:next.gameOverReason});}
 if(!h.baseline)h.baseline=makeYearlySnapshot(g);
 if(annual&&next.date.month===1&&next.date.year>previous.date.year&&!h.yearlySnapshots.some(s=>s.year===next.date.year-1))h.yearlySnapshots=[...h.yearlySnapshots,makeYearlySnapshot(g,next.date.year-1)];
 return g.player.origin?evaluateAchievements(previous,g,annual):g;
}










