import type {GameDate, SpeciesId, GameOverReason, WarGoal, WarResolution, ConflictResolution, CrisisType} from './types';
export type HistoricalEventCategory='politics'|'election'|'independence'|'diplomacy'|'war'|'peace'|'technology'|'crisis'|'economy'|'society'|'country';
export type HistoricalImportance='minor'|'major'|'historic';
export interface HistoricalEvent {id:string;sourceKey:string;order:number;date:GameDate;category:HistoricalEventCategory;importance:HistoricalImportance;title:string;description:string;countryIds:string[];countryNames:string[];regionIds?:string[];metadata?:Record<string,string|number|boolean|string[]>}
export interface HistoricalPeak {value:number;date:GameDate}
export interface CountryYearSnapshot {countryId:string;countryName:string;population:number;gdp:number;gdpPerCapita:number;growth:number;unemployment:number;inflation:number;treasury:number;debt:number;approval:number;stability:number;integration:number;livingStandard:number;education:number;healthcare:number;publicSafety:number;inequality:number;technologyScore:number;militaryCapability:number;regionCount:number}
export interface YearlyWorldSnapshot {year:number;date:GameDate;countries:CountryYearSnapshot[];totalWorldPopulation:number;totalWorldGDP:number;activeCountryCount:number;activeWarCount:number;activeCrisisCount:number}
export interface HistoricalTerritorialChange {date:GameDate;regionId:string;regionName:string;fromId:string;fromName:string;toId:string;toName:string}
export interface CountryHistoricalRecord {countryId:string;nameAtFounding:string;currentOrFinalName:string;foundedDate:GameDate;dissolvedDate:GameDate|null;originCountryId:string|null;primarySpeciesId:SpeciesId;foundingType:'initial'|'legal_independence'|'unilateral_independence';endType:'active'|'reunified'|'annexed'|'state_defeat';predecessorNames:string[];successorCountryIds:string[];peakPopulation:HistoricalPeak;peakGDP:HistoricalPeak;peakTechnology:HistoricalPeak;longestWarMonths:number;electionsHeld:number;territorialChanges:HistoricalTerritorialChange[]}
export interface WarHistoricalRecord {warId:string;startedDate:GameDate;endedDate:GameDate|null;attackerIds:string[];defenderIds:string[];attackerNames:string[];defenderNames:string[];warGoal:WarGoal;durationMonths:number;status:string;result:WarResolution|null;territorialChanges:HistoricalTerritorialChange[];reparations:number}
export interface InternalConflictHistoricalRecord {conflictId:string;parentId:string;breakawayId:string;parentName:string;breakawayName:string;startedDate:GameDate;endedDate:GameDate|null;durationMonths:number;status:string;result:ConflictResolution|null;independent:boolean|null}
export interface ElectionHistoricalRecord {id:string;date:GameDate;countryId:string;countryName:string;regionId:string|null;office:string;termNumber:number;reelectionChance:number;result:'won'|'lost'}
export interface TechnologyHistoricalRecord {id:string;date:GameDate;countryId:string;countryName:string;jurisdictionId:string;jurisdictionName:string;technologyId:string;technologyName:string;worldFirst:boolean;importance:HistoricalImportance}
export interface CrisisHistoricalRecord {crisisId:string;type:CrisisType;countryId:string;countryName:string;jurisdictionId:string;jurisdictionName:string;startedDate:GameDate;endedDate:GameDate|null;maxSeverity:number;durationMonths:number;totalFiscalCost:number;totalPopulationImpact:number;endReason:string|null}
export interface HistoricalOfficePeriod {countryId:string;countryName:string;regionId:string|null;office:string;startDate:GameDate;endDate:GameDate|null}
export interface CareerHistoricalSummary {startDate:GameDate;endDate:GameDate|null;endReason:GameOverReason|null;officesHeld:HistoricalOfficePeriod[];electionsWon:number;warsDuringRule:number;countriesFoundedDuringRule:number;majorCrises:number}
export interface HistoryState {schemaVersion:1;timeline:HistoricalEvent[];yearlySnapshots:YearlyWorldSnapshot[];baseline:YearlyWorldSnapshot|null;countries:Record<string,CountryHistoricalRecord>;wars:Record<string,WarHistoricalRecord>;internalConflicts:Record<string,InternalConflictHistoricalRecord>;elections:ElectionHistoricalRecord[];crises:Record<string,CrisisHistoricalRecord>;technologyMilestones:TechnologyHistoricalRecord[];worldFirstTechnology:Record<string,TechnologyHistoricalRecord>;career:CareerHistoricalSummary;nextHistoricalEventId:number;sourceCursors:Record<string,string|null>;seenSources:Record<string,true>}
