import {assessConflictPressure} from './conflictPressure';
import {federalStateIds,isActiveFederalState} from './stateRelationsModel';
import {getStateRelation} from './stateRelations';
import type {EventContext,GameEventDefinition,EventEffect} from './types';
export function statePairTarget(c:EventContext){if(c.statePairTarget)return c.statePairTarget;if(c.jurisdiction.kind!=='region'||!isActiveFederalState(c.game.world,c.jurisdiction.id))return undefined;const a=c.jurisdiction.id,b=federalStateIds.filter(id=>id!==a&&isActiveFederalState(c.game.world,id)).sort((x,y)=>getStateRelation(c.game,a,y).rivalry-getStateRelation(c.game,a,x).rivalry||x.localeCompare(y))[0];return b?{actorStateId:a,targetStateId:b}:undefined;}
const lead=(c:EventContext)=>Object.values(c.runtime.population.species).sort((a,b)=>b.population-a.population)[0].speciesId;
const change=(c:EventContext,metric:'satisfaction'|'autonomyDemand'|'independenceSentiment',delta:number):EventEffect=>({kind:'species',speciesId:lead(c),metric,delta});
export const pressureEventDefinitions:readonly GameEventDefinition[]=[
 {id:'state-dispute',title:'주간 정책 분쟁',description:'연방 예산과 지역 정책을 둘러싼 갈등이 공개적인 주정부 분쟁으로 이어졌습니다.',category:'governance',tone:'negative',conflictFamily:'state_rivalry',statePairEvent:true,baseMonthlyChance:.008,cooldownMonths:12,tags:['state-rivalry'],nonPlayerChoiceId:'balance',eligible:c=>!!statePairTarget(c)&&(c.conflictPressure??assessConflictPressure(c.game,c.jurisdiction)).interstatePressure>=32,calculateChance:()=>.008,severity:()=>2,choices:[
 {id:'invest',label:'공동 조정안 제시',preview:'협상으로 관계 회복·경쟁 완화',effects:c=>({immediate:[{kind:'state_politics',...statePairTarget(c)!,action:'negotiate'}]})},
 {id:'balance',label:'연방 중재 요청',preview:'연방의 실제 이해관계에 따라 중재',effects:c=>({immediate:[{kind:'state_politics',...statePairTarget(c)!,action:'mediate'}]})},
 {id:'restrict',label:'상대 정책 공개 견제',preview:'관계 악화·경쟁 상승·주민 반응',effects:c=>({immediate:[{kind:'state_politics',...statePairTarget(c)!,action:'counter_policy'}]})}]},
 ...(['autonomy-protest','separatist-protest','federal-grievance','domestic-unrest'] as const).map((id):GameEventDefinition=>({id,title:({'autonomy-protest':'대규모 자치권 시위','separatist-protest':'분리주의 독립 집회','federal-grievance':'연방정책에 대한 집단 항의','domestic-unrest':'반정부 시위'})[id],description:'누적된 불만을 가진 주민들이 정부의 공식적인 대응을 요구하고 있습니다. 협상과 진압은 서로 다른 후속 결과를 만듭니다.',category:'governance',tone:'negative',conflictFamily:id==='autonomy-protest'?'autonomy':id==='separatist-protest'?'separatism':id==='federal-grievance'?'federal':'domestic_unrest',baseMonthlyChance:.009,cooldownMonths:12,tags:['political-protest'],nonPlayerChoiceId:'balance',eligible:c=>{const p=(c.conflictPressure??assessConflictPressure(c.game,c.jurisdiction));return id==='autonomy-protest'?p.separatistPressure>=42:id==='separatist-protest'?c.runtime.speciesPolitics[lead(c)]!.independenceSentiment>=60&&p.separatistPressure>=55:id==='federal-grievance'?p.federalPressure>=45:p.domesticPressure>=55&&c.runtime.governance.approval<55&&c.runtime.governance.stability<55;},calculateChance:()=>.009,severity:c=>(c.conflictPressure??assessConflictPressure(c.game,c.jurisdiction)).separatistPressure>=75?3:2,choices:[
 {id:'invest',label:'대표단과 양보 협상',preview:'만족 회복·자치와 독립 압력 감소·재정 부담',effects:c=>({immediate:[change(c,'satisfaction',5),change(c,'autonomyDemand',-5),change(c,'independenceSentiment',-3),{kind:'treasury',amount:-c.runtime.economy.gdp*.001},{kind:'governance',metric:'stability',delta:2}]})},
 {id:'balance',label:'공식 협의와 질서 유지',preview:'제한적 만족 개선·대립 지속',effects:c=>({immediate:[change(c,'satisfaction',1),{kind:'governance',metric:'stability',delta:.5}]})},
 {id:'restrict',label:'강경 진압',preview:'단기 질서·주민불만·자치 및 독립 압력 증가',effects:c=>({immediate:[change(c,'satisfaction',-6),change(c,'autonomyDemand',5),change(c,'independenceSentiment',4),{kind:'governance',metric:'stability',delta:1},{kind:'governance',metric:'integration',delta:-2}]})}]}))
];
