import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createGame as initialGame, advanceMonth } from '../src/game/engine';
import { getGovernment, governmentDescriptors, governmentRuntime, controlledGovernmentId } from '../src/game/government';
import { synchronizeGovernmentAI, inferGovernmentProfile } from '../src/game/aiState';
import { updateDomesticAI, adjustAIResearch, isGovernmentAIEnabled, recordAIDecision } from '../src/game/ai';
import { calculateAIUrgencies, chooseAIStrategy, chooseAITaxPolicy, chooseAIBudgetPolicy, desiredAIBudget, scoreTaxPolicy, researchDomainScore, aiUtility } from '../src/game/aiEvaluation';
import { chooseDomesticAIEvent, scoreAIEventEffects, isDomesticAIEvent } from '../src/game/aiEvents';
import { aiConfig, profileResearch } from '../src/game/aiConfig';
import { setGovernmentTaxPolicy, setControlledTaxPolicy } from '../src/game/taxPolicy';
import { setGovernmentBudgetPolicy, setControlledBudgetPolicy } from '../src/game/budgetPolicy';
import { setGovernmentResearch, researchBlock, updateWorldTechnology } from '../src/game/technology';
import { validateTaxPolicy } from '../src/game/fiscal';
import { validateBudgetPolicy } from '../src/game/budget';
import { startCrisis } from '../src/game/crisis';
import { eventContext, getEventDefinition, generateWorldEvents, resolvePendingEvent } from '../src/game/events';
import { createBreakawayCountry } from '../src/game/secession';
import { transferWarTerritory } from '../src/game/warfareEffects';
import { addCasusBelli } from '../src/game/casusBelli';
import { declareWar } from '../src/game/warfare';
import { createSeededRandom } from '../src/game/random';
import { technologyDomains } from '../src/game/technologyConfig';
import type { AIUrgencies, GameState, GovernmentAIState, EventEffect, AIGovernmentProfile } from '../src/game/types';
const owl='region:owl-state',eagle='region:eagle-state',duck='region:duck-state',fed='country:pigeon',sparrow='country:sparrow';
const opts={strategicAI:false,economyRandom:()=>.5,mortalityRandom:()=>.99,mortalityRiskOverride:0,electionRandom:()=>0,eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,crisisRandom:()=>.99,warRandom:()=>.5,conflictRandom:()=>.5};
const state=(g:GameState,id=owl)=>g.world.governmentAI![id];
const urgency=(g:GameState,id=owl)=>calculateAIUrgencies(g,getGovernment(g.world,id),state(g,id));
const runtime=(g:GameState,id=owl)=>governmentRuntime(g.world,getGovernment(g.world,id));
const blank:AIUrgencies={recession:0,unemployment:0,inflation:0,fiscal:0,social:0,instability:0,crisis:0,researchLag:0};
function independent(g=createGame('pigeon','eagle-state')){const r=g.world.regions['eagle-state'];Object.assign(r.speciesPolitics.eagle!,{satisfaction:10,autonomyDemand:90,independenceSentiment:90});Object.assign(r.secession!.eagle!,{phase:'transition',monthsInPhase:6,lastReferendumResult:{date:g.date,yesShare:80,passed:true}});return createBreakawayCountry(g,{kind:'region',id:r.id},'eagle');}
function verify(g:GameState){for(const r of [...Object.values(g.world.countries),...Object.values(g.world.regions)]){assert.ok(Number.isFinite(r.economy.gdp)&&r.economy.gdp>=0);assert.ok(Math.abs(r.economy.gdp-Object.values(r.economy.industries).reduce((n,i)=>n+i.output,0))<1e-5*Math.max(1,r.economy.gdp));assert.equal(r.population.total,Object.values(r.population.species).reduce((n,p)=>n+p.population,0));assert.ok(Number.isFinite(r.fiscal.debt)&&r.fiscal.debt>=0);validateTaxPolicy(r.fiscal.taxPolicy);validateBudgetPolicy(r.fiscal.budgetPolicy);}
 for(const [id,s] of Object.entries(g.world.governmentAI!)){assert.ok(governmentDescriptors(g.world).some(g=>g.id===id));assert.ok(s.recentDecisions.length<=36);assert.ok(s.economicHistory.length<=12);for(const n of Object.values(s.policyCooldowns))assert.ok(n>=0&&n<=6);}}
test('초기 6개 정부 AI 상태 존재·입력 월기록 없음',()=>{const g=createGame('sparrow');assert.equal(Object.keys(g.world.governmentAI!).length,6);for(const s of Object.values(g.world.governmentAI!))assert.equal(s.recentDecisions.length,0);});
for(const [id,profile] of [[sparrow,'industrial'],[fed,'balanced'],['region:pigeon-state','social'],[eagle,'security'],[owl,'research'],[duck,'agricultural']] as const)test(id+' 초기 profile',()=>assert.equal(state(createGame('sparrow'),id).profile,profile));
test('세계 초기 상태는 플레이어 선택과 독립·실행 여부만 제어',()=>{const a=createGame('sparrow'),b=createGame('pigeon','eagle-state');assert.deepEqual(a.world,b.world);assert.equal(isGovernmentAIEnabled(a,sparrow),false);assert.equal(isGovernmentAIEnabled(b,eagle),false);assert.equal(isGovernmentAIEnabled(b,fed),true);});
test('플레이어 세율·예산·연구는 AI가 변경하지 않음',()=>{const g=createGame('pigeon','owl-state'),before=structuredClone(runtime(g,owl)),n=updateDomesticAI(g);assert.deepEqual(runtime(n,owl),before);assert.equal(state(n,owl).lastDecisionMonth,0);});
test('신생국 primary 성향·정부 중복 방지·즉시 control 제외',()=>{const g=independent();assert.equal(state(g,'country:eagle-republic-1').profile,'security');assert.equal(g.world.governmentAI![eagle],undefined);assert.equal(isGovernmentAIEnabled(g,'country:eagle-republic-1'),false);});
test('일반 신생국 산업 구조와 부모 성향으로 추론',()=>{const g=createGame('sparrow'),c=structuredClone(g.world.countries.sparrow);c.id='crow-country';c.identity={...c.identity!,id:c.id,primarySpeciesId:'crow',originCountryId:'sparrow',isDynamic:true};g.world.countries[c.id]=c;const d=getGovernment(g.world,'country:'+c.id);assert.ok(['industrial','balanced'].includes(inferGovernmentProfile(g.world,d)));});
test('삭제 국가·행정 영토 AI 정리',()=>{let g=independent();g.player.controlledCountryId='sparrow';g.player.controlledRegionId=null;g=transferWarTerritory(g,['eagle-state'],'sparrow');assert.equal(g.world.governmentAI!['country:eagle-republic-1'],undefined);assert.equal(g.world.governmentAI![eagle],undefined);verify(g);});
for(const [metric,change] of [['recession',(g:GameState)=>{runtime(g).economy.growth=-10;}],['unemployment',(g:GameState)=>{runtime(g).economy.unemployment=14;}],['inflation',(g:GameState)=>{runtime(g).economy.inflation=12;}],['fiscal',(g:GameState)=>{runtime(g).fiscal.debt=runtime(g).economy.gdp*2;runtime(g).fiscal.monthlyBalance=-10;}],['social',(g:GameState)=>{Object.assign(runtime(g).social!,{livingStandard:15,healthcare:15,publicSafety:15,inequality:80});}],['instability',(g:GameState)=>{Object.assign(runtime(g).governance!,{stability:10,integration:10});}]] as const)test(metric+' urgency 상승·범위',()=>{const g=createGame('sparrow'),a=urgency(g)[metric];change(g);const u=urgency(g);assert.ok(u[metric]>a);for(const n of Object.values(u))assert.ok(n>=0&&n<=100);});
test('심각한 다중 위기 urgency 증가·현재 공개 state만 사용',()=>{let g=createGame('sparrow'),a=urgency(g,duck).crisis;g=startCrisis(g,{kind:'region',id:'duck-state'},'wetland_drought',90);assert.ok(urgency(g,duck).crisis>a);g=startCrisis(g,{kind:'region',id:'duck-state'},'reed_fire',90);assert.ok(urgency(g,duck).crisis>=70);});
test('12개월 성장 이력과 GDP 추세로 침체 완화',()=>{const g=createGame('sparrow');runtime(g).economy.growth=-5;const a=urgency(g).recession;state(g).economicHistory=Array.from({length:11},()=>({gdp:runtime(g).economy.gdp*.95,growth:3,balance:0}));assert.ok(urgency(g).recession<a);});
test('기술격차 urgency 현재세계 평균 비교',()=>{const g=createGame('sparrow');for(const d of Object.values(runtime(g).technology!.domains))d.level=0;assert.ok(urgency(g).researchLag>40);});
for(const [strategy,u] of [['normal',blank],['growth',{...blank,unemployment:100,recession:80}],['fiscal_repair',{...blank,fiscal:95}],['social_recovery',{...blank,social:95}],['research_push',{...blank,researchLag:95}],['crisis_response',{...blank,crisis:95}]] as const)test('전략 '+strategy,()=>{const s={...state(createGame('sparrow')),strategyMonths:6};assert.equal(chooseAIStrategy(s,u),strategy);});
test('security 전쟁/평시 전략·6개월 유지',()=>{const s={...state(createGame('sparrow')),strategyMonths:6};assert.equal(chooseAIStrategy(s,blank,true),'security_focus');assert.equal(chooseAIStrategy({...s,currentStrategy:'security_focus',strategyMonths:6},blank,false),'normal');});
test('strategy hysteresis·극심한 위기 즉시 전환',()=>{const s={...state(createGame('sparrow')),strategyMonths:2};assert.equal(chooseAIStrategy(s,{...blank,fiscal:95}),'normal');assert.equal(chooseAIStrategy(s,{...blank,crisis:90}),'crisis_response');assert.equal(chooseAIStrategy({...s,currentStrategy:'growth',strategyMonths:8},{...blank,unemployment:60,fiscal:55}),'growth');});
test('고부채 세입 확보·세율 변화 제한',()=>{const g=createGame('sparrow'),r=runtime(g);r.fiscal.debt=r.economy.gdp*3;r.fiscal.monthlyBalance=-15;r.fiscal.treasury=0;const s={...state(g),currentStrategy:'fiscal_repair' as const},p=chooseAITaxPolicy(g,getGovernment(g.world,owl),s,urgency(g));assert.ok(Object.values(p).reduce((n,x)=>n+x,0)>Object.values(r.fiscal.taxPolicy).reduce((n,x)=>n+x,0));for(const k of Object.keys(p) as (keyof typeof p)[])assert.ok(Math.abs(p[k]-r.fiscal.taxPolicy[k])<=.5);});
test('침체에서는 법인/소득세 인상 억제·극단 부채 예외',()=>{const g=createGame('sparrow'),r=runtime(g),p=chooseAITaxPolicy(g,getGovernment(g.world,owl),state(g),{...blank,recession:95,unemployment:95,fiscal:60});assert.ok(p.incomeTaxRate<=r.fiscal.taxPolicy.incomeTaxRate);assert.ok(p.corporateTaxRate<=r.fiscal.taxPolicy.corporateTaxRate);});
test('고물가 소비세 인상 억제·utility 점수도 감소',()=>{const g=createGame('sparrow'),r=runtime(g),u={...blank,fiscal:90,inflation:95};const p=chooseAITaxPolicy(g,getGovernment(g.world,owl),state(g),u);assert.ok(p.consumptionTaxRate<=r.fiscal.taxPolicy.consumptionTaxRate);assert.ok(scoreTaxPolicy(g,getGovernment(g.world,owl),state(g),u,{...r.fiscal.taxPolicy,consumptionTaxRate:r.fiscal.taxPolicy.consumptionTaxRate+.5}).social<0);});
test('세율 API player/AI validation 동일·미래 효과',()=>{const g=createGame('sparrow'),r=runtime(g),policy={...r.fiscal.taxPolicy,incomeTaxRate:12},n=setGovernmentTaxPolicy(g,owl,policy,{log:false});assert.equal(runtime(n).fiscal.taxPolicy.incomeTaxRate,12);assert.equal(runtime(n).fiscal.treasury,r.fiscal.treasury);assert.deepEqual(runtime(n).economy,r.economy);assert.throws(()=>setGovernmentTaxPolicy(g,owl,{...policy,incomeTaxRate:41}));assert.throws(()=>setControlledTaxPolicy(g,{...g.world.countries.sparrow.fiscal.taxPolicy,incomeTaxRate:41}));});
test('예산'+' API 동일 상한·총합·정밀도·권한',()=>{const g=createGame('sparrow'),r=runtime(g),policy={...r.fiscal.budgetPolicy,healthcare:2};const n=setGovernmentBudgetPolicy(g,owl,policy,{log:false});assert.equal(runtime(n).fiscal.budgetPolicy.healthcare,2);assert.deepEqual(n.world.countries.sparrow,g.world.countries.sparrow);assert.throws(()=>setGovernmentBudgetPolicy(g,owl,{...policy,defense:11}));assert.throws(()=>setControlledBudgetPolicy(g,{...g.world.countries.sparrow.fiscal.budgetPolicy,defense:11}));});
test('연방 AI가 주 재정·연구를 수정하지 않음',()=>{const g=createGame('sparrow'),regions=structuredClone(g.world.regions);const n=setGovernmentBudgetPolicy(g,fed,{...g.world.countries.pigeon.fiscal.budgetPolicy,infrastructure:2},{log:false});assert.deepEqual(n.world.regions,regions);assert.throws(()=>setGovernmentResearch(g,fed,'medicine',null));});
test('주 AI가 연방 국고·다른 국가 세율을 수정하지 않음',()=>{const g=createGame('sparrow'),before=structuredClone(g.world.countries);const n=setGovernmentTaxPolicy(g,owl,{...runtime(g).fiscal.taxPolicy,incomeTaxRate:10},{log:false});assert.deepEqual(n.world.countries,before);});
test('사건 대기 중 NPC API 가능·player API 차단',()=>{const g=createGame('sparrow');g.events.pendingEvent={id:'x',eventId:'storm',turn:1,date:g.date,jurisdiction:{kind:'country',id:'sparrow'},severity:2};assert.throws(()=>setControlledBudgetPolicy(g,g.world.countries.sparrow.fiscal.budgetPolicy));assert.doesNotThrow(()=>setGovernmentBudgetPolicy(g,owl,{...runtime(g).fiscal.budgetPolicy,healthcare:2},{log:false}));});
for(const [type,key] of [['respiratory_outbreak','healthcare'],['great_storm','infrastructure'],['wetland_drought','infrastructure']] as const)test(type+' 예산 대응 우선·분야 .3 제한',()=>{let g=createGame('sparrow');g=startCrisis(g,{kind:'region',id:'eagle-state'},type,100);const s={...state(g,eagle),currentStrategy:'crisis_response' as const},p=chooseAIBudgetPolicy(g,getGovernment(g.world,eagle),s,urgency(g,eagle)),r=runtime(g,eagle);assert.ok(p[key]>r.fiscal.budgetPolicy[key]);for(const k of Object.keys(p) as (keyof typeof p)[])assert.ok(Math.abs(p[k]-r.fiscal.budgetPolicy[k])<.300001);});
test('실업 growth/불평등 welfare 목표 개선',()=>{const g=createGame('sparrow'),d=getGovernment(g.world,owl),s=state(g),r=runtime(g);const a=desiredAIBudget(g,d,s,blank);r.social!.inequality=85;const b=desiredAIBudget(g,d,s,{...blank,unemployment:95,social:80});assert.ok(b.industrySupport>a.industrySupport);assert.ok(b.welfare>a.welfare);});
for(const profile of ['industrial','social','research','agricultural','security','balanced'] as AIGovernmentProfile[])test(profile+' 고유 예산/연구 우선순위',()=>{const g=createGame('sparrow'),s={...state(g),profile},target=desiredAIBudget(g,getGovernment(g.world,owl),s,blank);assert.ok(Object.values(target).every(n=>n>=0));const first=profileResearch[profile][0],score=researchDomainScore(g,getGovernment(g.world,owl),s,blank,first);assert.ok(Number.isFinite(score));});
test('재정 수리 긴축에도 보건·복지 floor 보호',()=>{const g=createGame('sparrow'),d=getGovernment(g.world,owl),s={...state(g),currentStrategy:'fiscal_repair' as const},p=chooseAIBudgetPolicy(g,d,s,{...blank,fiscal:100,recession:80,social:90});assert.ok(p.healthcare>=.3);assert.ok(p.welfare>=.3);validateBudgetPolicy(p);});
test('연구 실제 API 선행·슬롯 validation·진척 보존',()=>{let g=createGame('sparrow'),r=runtime(g);const id=r.technology!.domains.information.currentResearchId!;r.technology!.researchProgress[id]=70;r.technology!.domains.information.progress=70;g=setGovernmentResearch(g,owl,'information',null,{log:false});g=setGovernmentResearch(g,owl,'information',id,{log:false});assert.equal(runtime(g).technology!.domains.information.progress,70);assert.throws(()=>setGovernmentResearch(g,owl,'agriculture','agriculture-6',{log:false}));});
test('70% 연구 작은 priority 차이로 교체하지 않음',()=>{const g=createGame('sparrow'),r=runtime(g),id=r.technology!.domains.information.currentResearchId!;r.technology!.researchProgress[id]=70;r.technology!.domains.information.progress=70;const n=adjustAIResearch(g,getGovernment(g.world,owl),state(g),blank);assert.equal(runtime(n).technology!.domains.information.currentResearchId,id);});
test('질병 medicine·전쟁 military 연구 점수 상승',()=>{let g=createGame('sparrow'),d=getGovernment(g.world,eagle),s=state(g,eagle);const a=researchDomainScore(g,d,s,blank,'medicine');g=startCrisis(g,{kind:'region',id:'eagle-state'},'respiratory_outbreak',100);assert.ok(researchDomainScore(g,d,s,blank,'medicine')>a+30);let w=addCasusBelli(g,'pigeon','sparrow','border_incident');w=declareWar(w,'pigeon',Object.values(w.world.warfare!.casusBelli)[0].id,'punitive');assert.ok(researchDomainScore(w,d,s,blank,'military')>researchDomainScore(g,d,s,blank,'military'));});
test('정책/연구 cooldown과 당월 idempotency',()=>{let g=updateDomesticAI(createGame('sparrow'));const copy=structuredClone(g);assert.deepEqual(updateDomesticAI(g),copy);const first=state(g).policyCooldowns;g=updateDomesticAI({...g,turn:g.turn+1});for(const k of ['taxes','budget','research'] as const)if(first[k])assert.equal(state(g).policyCooldowns[k],first[k]-1);});
test('NPC 정책 결산 당월 숫자 변경 없음·다음 달 효과',()=>{const g=createGame('sparrow'),before=structuredClone(runtime(g)),n=updateDomesticAI(g);assert.deepEqual(runtime(n).economy,before.economy);assert.equal(runtime(n).fiscal.treasury,before.fiscal.treasury);assert.equal(runtime(n).fiscal.monthlyBalance,before.fiscal.monthlyBalance);assert.notDeepEqual(runtime(n).fiscal.budgetPolicy,before.fiscal.budgetPolicy);const a=advanceMonth(n,opts),b=advanceMonth(g,{...opts,domesticAI:false});assert.notDeepEqual(runtime(a).economy,runtime(b).economy);});
test('AI records 날짜·이유·상한·무결정 로그 없음',()=>{let g=createGame('sparrow');for(let i=0;i<100;i++)g=recordAIDecision(g,owl,{type:'strategy',summary:'검증',reasonCodes:['HIGH_DEBT']});assert.equal(state(g).recentDecisions.length,36);assert.equal(state(g).recentDecisions[0].governmentId,owl);const before=g.logs.length;g=updateDomesticAI(g);assert.equal(g.logs.length,before);});
test('AI 전체 순수 함수·고정 상태 동일 결과',()=>{const g=createGame('sparrow'),before=structuredClone(g);const a=updateDomesticAI(g),b=updateDomesticAI(g);assert.deepEqual(a,b);assert.deepEqual(g,before);});
test('같은 폭풍 재정여유/부채위기 선택 다양성',()=>{const g=createGame('sparrow'),d={kind:'region' as const,id:'owl-state'},r=runtime(g);r.fiscal.treasury=r.economy.gdp;r.fiscal.debt=0;r.fiscal.monthlyBalance=5;const rich=chooseDomesticAIEvent(eventContext(g,d),getEventDefinition('storm'),3);r.fiscal.treasury=0;r.fiscal.debt=r.economy.gdp*4;r.fiscal.monthlyBalance=-30;const poor=chooseDomesticAIEvent(eventContext(g,d),getEventDefinition('storm'),3);assert.notEqual(rich.choiceId,poor.choiceId);console.log('AI STORM',rich,poor);});
test('severity 높음·회복력·보건 대응 utility 실효',()=>{const g=createGame('sparrow'),c=eventContext(g,{kind:'region',id:'eagle-state'});const low=scoreAIEventEffects(c,[{kind:'start_crisis',crisisType:'respiratory_outbreak',severity:20,sourceEventId:'x',protection:.4}]).crisis,high=scoreAIEventEffects(c,[{kind:'start_crisis',crisisType:'respiratory_outbreak',severity:100,sourceEventId:'x',protection:.4}]).crisis;assert.ok(high>low);});
test('모든 국내 effect union 유한 점수·기술 직접해금 없음',()=>{const g=createGame('sparrow'),c=eventContext(g,{kind:'country',id:'sparrow'});const effects:EventEffect[]=[{kind:'treasury',amount:-1},{kind:'industry',industryId:'services',multiplier:.99},{kind:'population',speciesId:'sparrow',ratio:.001,flow:'death'},{kind:'social',metric:'inequality',delta:-1},{kind:'species',speciesId:'sparrow',metric:'satisfaction',delta:1},{kind:'governance',metric:'approval',delta:1},{kind:'inflation',delta:.1},{kind:'research',domain:'medicine',progress:2},{kind:'crisis_recovery',crisisId:'x',value:10},{kind:'leader_risk',value:5,months:2}];const before=structuredClone(g);assert.ok(Number.isFinite(scoreAIEventEffects(c,effects).total));assert.deepEqual(g,before);});
for(const id of ['secession-eagle-approval','war-border-incident','diplomacy-trade-offer'])test(id+' 미존재/전략 사건 fallback 안전',()=>{const g=createGame('sparrow'),c=eventContext(g,{kind:'country',id:'sparrow'});let e;try{e=getEventDefinition(id);}catch{e={...getEventDefinition('storm'),id,warEvent:true};}assert.equal(isDomesticAIEvent(c,e,2),false);assert.equal(chooseDomesticAIEvent(c,e,2).choiceId,e.nonPlayerChoiceId);});
test('scoring 불가능 fallback·미래 outcome/RNG 소비 없음',()=>{const g=createGame('sparrow'),c=eventContext(g,{kind:'country',id:'sparrow'}),e={...getEventDefinition('storm'),choices:[{...getEventDefinition('storm').choices[0],effects:()=>{throw new Error('범위 밖');}}]};assert.equal(chooseDomesticAIEvent(c,e,2).choiceId,e.nonPlayerChoiceId);});
test('NPC 사건 실제 AI choice·player dialogue 유지',()=>{const g=createGame('sparrow'),n=generateWorldEvents(g,{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>.5});assert.ok(n.events.pendingEvent);assert.equal(n.events.history.length,4);assert.ok(Object.values(n.world.governmentAI!).some(s=>s.recentDecisions.some(d=>d.type==='event')));assert.ok(n.events.history.every(e=>!e.playerChoice));});
test('기존 RNG 소비 AI on/off 동일',()=>{for(const on of [false,true]){let economy=0,mortality=0,events=0,crisis=0;advanceMonth(createGame('sparrow'),{...opts,domesticAI:on,economyRandom:()=>{economy++;return .5},mortalityRandom:()=>{mortality++;return .99},eventOccurrenceRandom:()=>{events++;return .999999},crisisRandom:()=>{crisis++;return .99}});assert.equal(economy,30);assert.equal(mortality,1);assert.equal(events,5);assert.equal(crisis,0);}});
test('AI 종료 후 실행/API 차단',()=>{const g=createGame('sparrow');g.gameOverReason='death';g.player.alive=false;assert.equal(updateDomesticAI(g),g);assert.throws(()=>setGovernmentBudgetPolicy(g,owl,runtime(g).fiscal.budgetPolicy));});
test('신생 NPC 국가 세금/예산/연구·위기 대응 E2E',()=>{let g=independent();g.player.controlledCountryId='sparrow';g.player.controlledRegionId=null;g=startCrisis(g,{kind:'region',id:'eagle-state'},'respiratory_outbreak',95);g=advanceMonth(g,opts);const id='country:eagle-republic-1';assert.equal(isGovernmentAIEnabled(g,id),true);assert.equal(state(g,id).currentStrategy,'crisis_response');assert.ok(state(g,id).recentDecisions.some(d=>d.type==='budget'));assert.ok(runtime(g,id).fiscal.budgetPolicy.healthcare>.8);verify(g);});
test('플레이어 전환 즉시 AI OFF·정책 유지·직접 변경',()=>{let g=updateDomesticAI(createGame('sparrow'));const policy=structuredClone(runtime(g).fiscal.budgetPolicy);g.player.controlledCountryId='pigeon';g.player.controlledRegionId='owl-state';g={...g,turn:g.turn+1};const n=updateDomesticAI(g);assert.equal(controlledGovernmentId(n),owl);assert.equal(isGovernmentAIEnabled(n,owl),false);assert.deepEqual(runtime(n).fiscal.budgetPolicy,policy);const changed=setControlledBudgetPolicy(n,{...policy,healthcare:2});assert.equal(runtime(changed).fiscal.budgetPolicy.healthcare,2);});
test('세계 평균·공개 지표 utility 가중 전략',()=>{const parts={growth:1,fiscal:2,social:3,stability:4,research:5,crisis:6};assert.ok(aiUtility(parts,'crisis_response').total>aiUtility(parts,'normal').total);});
test('국제지원 높은 위기·우호 관계 수락',()=>{let g=createGame('sparrow'),pair=Object.values(g.world.diplomacy!.relations)[0];pair.relations=80;pair.recognizedAbyB=pair.recognizedBbyA=true;g=startCrisis(g,{kind:'region',id:'owl-state'},'great_storm',95);const c=eventContext(g,{kind:'region',id:'owl-state'}),choice=chooseDomesticAIEvent(c,getEventDefinition('international-rescue'),3);assert.notEqual(choice.choiceId,'restrict');});
function simulate(seed:number,months:number){let g=createGame('pigeon','pigeon-state');const random={economyRandom:createSeededRandom(seed),eventOccurrenceRandom:createSeededRandom(seed+1),eventOutcomeRandom:createSeededRandom(seed+2),crisisRandom:createSeededRandom(seed+3),warRandom:createSeededRandom(seed+4)};let decisions=0,maxDebt=0;const taxes=new Map<string,{turn:number;values:Record<string,number>}>();let reversals=0,changes=0;
 for(let i=0;i<months;i++){g=advanceMonth(g,{...opts,...random});if(g.events.pendingEvent)g=resolvePendingEvent(g,getEventDefinition(g.events.pendingEvent.eventId).nonPlayerChoiceId,random.eventOutcomeRandom);verify(g);assert.equal(g.gameOverReason,null);
  for(const d of governmentDescriptors(g.world)){if(!isGovernmentAIEnabled(g,d.id))continue;const r=governmentRuntime(g.world,d),s=state(g,d.id);maxDebt=Math.max(maxDebt,r.fiscal.debt/Math.max(1,r.economy.gdp));for(const record of s.recentDecisions.filter(r=>r.turn===g.turn&&r.type!=='event'))decisions++;
   const prior=taxes.get(d.id),values={...r.fiscal.taxPolicy};if(prior&&JSON.stringify(prior.values)!==JSON.stringify(values)){changes++;assert.ok(g.turn-prior.turn>=6||prior.turn===1);const delta=Object.values(values).reduce((n,v)=>n+v,0)-Object.values(prior.values).reduce((n,v)=>n+v,0);const old=s.recentDecisions.find(rec=>rec.type==='tax'&&rec.turn<g.turn);if(old&&delta<0&&s.currentStrategy==='fiscal_repair')reversals++;taxes.set(d.id,{turn:g.turn,values});}else if(!prior)taxes.set(d.id,{turn:1,values});}
 }
 assert.ok(decisions>10);assert.ok(maxDebt<1,`debt ratio ${maxDebt}`);const budgetSet=new Set(governmentDescriptors(g.world).filter(d=>isGovernmentAIEnabled(g,d.id)).map(d=>JSON.stringify(governmentRuntime(g.world,d).fiscal.budgetPolicy)));assert.ok(budgetSet.size>=3);assert.ok(Object.values(g.world.governmentAI!).every(s=>s.recentDecisions.length<=36));const discoveries=g.world.technologyHistory?.length??0;assert.ok(discoveries>0);const result={seed,months,decisions,maxDebt,changes,reversals,discoveries,budgetVariants:budgetSet.size,crisesStarted:(g.world.crises?.nextId??1)-1,owlResearch:g.world.regions['owl-state'].fiscal.budgetPolicy.research,eagleResearch:g.world.regions['eagle-state'].fiscal.budgetPolicy.research};console.log('AI LONG',JSON.stringify(result));return {game:g,result};}
for(const seed of [91,2030,4412,8451,9966])test(seed+' ×600개월 AI-on 경제·정책·연구·위기·다양성·무폭주',()=>{const {game,result}=simulate(seed,600);assert.ok(result.crisesStarted>0);assert.ok(result.owlResearch>result.eagleResearch);assert.ok(game.world.regions['owl-state'].technology!.domains.information.level>=game.world.regions['eagle-state'].technology!.domains.information.level);});
test('1200개월 AI endurance·기술 소진 안전·기록 상한',()=>simulate(99101,1200));
test('profile별 utility 가중치와 균형 기본값',()=>{const p={growth:10,fiscal:10,social:10,stability:10,research:10,crisis:10};assert.equal(aiUtility(p,'normal').total,60);for(const profile of ['industrial','social','research','agricultural','security'] as const)assert.ok(aiUtility(p,'normal',profile).total>60);});
test('국제지원 적격 파트너 없거나 제재 중이면 거절',()=>{let g=startCrisis(createGame('sparrow'),{kind:'region',id:'owl-state'},'great_storm',95);for(const pair of Object.values(g.world.diplomacy!.relations)){pair.relations=80;pair.recognizedAbyB=pair.recognizedBbyA=true;pair.sanctionsAtoB=true;}assert.equal(chooseDomesticAIEvent(eventContext(g,{kind:'region',id:'owl-state'}),getEventDefinition('international-rescue'),3).choiceId,'restrict');});
test('전쟁 종료 후 독수리 임시 방어 예산 목표 정상화',()=>{const g=createGame('sparrow'),d=getGovernment(g.world,eagle),s=state(g,eagle),peace=desiredAIBudget(g,d,s,blank);let w=addCasusBelli(g,'pigeon','sparrow','border_incident');w=declareWar(w,'pigeon',Object.values(w.world.warfare!.casusBelli)[0].id,'punitive');const war=desiredAIBudget(w,d,s,blank);assert.ok(war.defense>peace.defense);assert.ok(war.infrastructure>peace.infrastructure);for(const entry of Object.values(w.world.warfare!.wars))entry.status='resolved';assert.deepEqual(desiredAIBudget(w,d,s,blank),peace);});
test('영토 편입 후 위기는 새 소유국 정부가 대응',()=>{let g=createGame('pigeon','pigeon-state');g=startCrisis(g,{kind:'region',id:'eagle-state'},'respiratory_outbreak',95);g=transferWarTerritory(g,['eagle-state'],'sparrow');g=advanceMonth(g,opts);assert.equal(g.world.regions['eagle-state'].simulationRole,'administrative');assert.equal(g.world.governmentAI![eagle],undefined);assert.equal(state(g,sparrow).currentStrategy,'crisis_response');assert.ok(state(g,sparrow).recentDecisions.some(d=>d.type==='budget'));});
test('플레이어 사건 대기에도 NPC 월말 정책 결정 실행',()=>{const g=advanceMonth(createGame('sparrow'),{...opts,eventOccurrenceRandom:()=>0});assert.ok(g.events.pendingEvent);assert.equal(state(g).lastDecisionMonth,g.turn);assert.ok(state(g).recentDecisions.some(d=>d.type==='budget'));});
test('동일 초기 조건에서 부엉이 research profile 실제 연구 발전 우위',()=>{let a=createGame('sparrow'),b=structuredClone(a);state(b).profile='security';let capacityA=0,capacityB=0;for(let i=0;i<600;i++){a=updateDomesticAI(a);b=updateDomesticAI(b);a=updateWorldTechnology(a);b=updateWorldTechnology(b);capacityA+=runtime(a).technology!.researchCapacity;capacityB+=runtime(b).technology!.researchCapacity;a={...a,turn:a.turn+1};b={...b,turn:b.turn+1};}const completedA=(a.world.technologyHistory??[]).filter(h=>h.jurisdictionId==='owl-state').length,completedB=(b.world.technologyHistory??[]).filter(h=>h.jurisdictionId==='owl-state').length;console.log('AI RESEARCH controlled comparison',{capacityA,capacityB,completedA,completedB});assert.ok(capacityA>capacityB);assert.ok(runtime(a).technology!.domains.information.level+runtime(a).technology!.domains.information.progress/100>runtime(b).technology!.domains.information.level+runtime(b).technology!.domains.information.progress/100);});

function createGame(...args:Parameters<typeof initialGame>){return {...initialGame(...args),policyScheduleEnabled:false};}

