import {chooseStrategicEvent} from '../src/game/strategicEvents';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {pressureFixture as fixture} from './pressureFixtures';
import {assessConflictPressure,nonlinearConflictMultiplier,getConflictEventFamilyMultiplier,conflictFamily} from '../src/game/conflictPressure';
import {calculateEventChance,eventContext,getEventDefinition,generateWorldEvents,resolvePendingEvent,tickEventState} from '../src/game/events';
import {performStateAction,applyStatePoliticalActionEffects,getStateRelation,selectStateResponse,shouldMediateStatePair,updateStatePoliticalAI,updateStateRelations} from '../src/game/stateRelations';
import {statePairKey} from '../src/game/stateRelationsModel';import {createSaveData,serializeSave,deserializeSave,validateGameState} from '../src/game/save';
import {canOrganize,canRequestReferendum,canDeclareUnilaterally,applySecessionAction} from '../src/game/secession';
import {clock} from './federalFixtures';import {advanceMonth} from '../src/game/engine';
const j={kind:'region',id:'eagle-state'} as const,a=j.id,b='duck-state';
const pending=(g:ReturnType<typeof fixture>,id:string)=>({...g,events:{...g.events,pendingEvent:{id:'test:'+id,eventId:id,turn:g.turn,date:g.date,jurisdiction:j,severity:3 as const,...(id==='state-dispute'?{statePairTarget:{actorStateId:a,targetStateId:b}}:{})}}});
for(const family of ['autonomy','separatism','federal','state_rivalry','species','domestic_unrest','diplomatic','casus_belli'] as const){
 test(family+' pressure bounded',()=>{const g=fixture();for(const v of Object.values(assessConflictPressure(g,j)))assert.ok(v>=0&&v<=100);assert.ok(getConflictEventFamilyMultiplier(g,j,family)<=12);});
 test(family+' stable vs unstable',()=>{const g=fixture(),s=fixture('stable');if(['diplomatic','casus_belli'].includes(family)){const r=Object.values(g.world.diplomacy!.relations)[0];Object.assign(r,{relations:-70,trust:5,threat:90});if(family==='casus_belli'){g.world.strategicAI!.pigeon.foreignPolicy='assertive';const e=getEventDefinition('diplomacy-boundary'),c=eventContext(g,j,undefined,'sparrow');assert.equal(chooseStrategicEvent(c,e,2).choiceId,'restrict');const n=resolvePendingEvent({...pending(g,'diplomacy-boundary'),events:{...pending(g,'diplomacy-boundary').events,pendingEvent:{...pending(g,'diplomacy-boundary').events.pendingEvent!,diplomaticTargetId:'sparrow'}}},'restrict',()=>.5);assert.ok(Object.keys(n.world.warfare!.casusBelli).length);}}assert.ok(getConflictEventFamilyMultiplier(g,j,family)>getConflictEventFamilyMultiplier(s,j,family));});
}
for(const value of [20,40,60,75,85,100])test('nonlinear pressure '+value,()=>{assert.ok(nonlinearConflictMultiplier(value)>=1);if(value>25)assert.ok(nonlinearConflictMultiplier(value)>nonlinearConflictMultiplier(value-10));});
for(const id of ['autonomy-protest','separatist-protest','federal-grievance','domestic-unrest','state-dispute']){
 test(id+' actual candidate pressure',()=>assert.ok(calculateEventChance(id,fixture(),j)>calculateEventChance(id,fixture('stable'),j)));
 for(const choice of ['invest','balance','restrict'])test(id+' '+choice+' real resolution',()=>{const g=pending(fixture(),id),n=resolvePendingEvent(g,choice,()=>.5,()=>.5,false);assert.equal(n.events.pendingEvent,null);assert.equal(n.events.history[0].choiceId,choice);validateGameState(n);});
}
test('non-family event unaffected',()=>{const g=fixture(),id='successful-nesting';const e=getEventDefinition(id);assert.equal(conflictFamily(e),undefined);if(e.eligible(eventContext(g,j)))assert.equal(calculateEventChance(id,g,j),Math.min(.4,e.calculateChance(eventContext(g,j))));});
for(const independence of [30,65,85])test('independence gradient '+independence,()=>{const g=fixture();g.world.regions[a].speciesPolitics.eagle!.independenceSentiment=independence;const p=assessConflictPressure(g,j);assert.ok(p.separatistPressure>0);if(independence<60)assert.equal(calculateEventChance('separatist-protest',g,j),0);});
test('low integration increases pressure',()=>{const g=fixture(),p=assessConflictPressure(g,j).separatistPressure;g.world.regions[a].governance.integration=0;assert.ok(assessConflictPressure(g,j).separatistPressure>=p);});
test('rejection increases pressure',()=>{const g=fixture('moderate'),p=assessConflictPressure(g,j).federalPressure;g.world.federalPolitics=fixture().world.federalPolitics;assert.ok(assessConflictPressure(g,j).federalPressure>p);});
test('crackdown boosts followup / compromise reduces it',()=>{const g=pending(fixture(), 'autonomy-protest'),hard=resolvePendingEvent(g,'restrict',()=>.5),soft=resolvePendingEvent(g,'invest',()=>.5);assert.ok(assessConflictPressure(hard,j).separatistPressure>assessConflictPressure(soft,j).separatistPressure);assert.ok(getConflictEventFamilyMultiplier(hard,j,'autonomy')>getConflictEventFamilyMultiplier(soft,j,'autonomy'));assert.ok(soft.world.regions[a].speciesPolitics.eagle!.satisfaction>g.world.regions[a].speciesPolitics.eagle!.satisfaction);assert.ok(soft.world.regions[a].speciesPolitics.eagle!.autonomyDemand<g.world.regions[a].speciesPolitics.eagle!.autonomyDemand);});
test('memory expires',()=>{const hard=resolvePendingEvent(pending(fixture(),'autonomy-protest'),'restrict',()=>.5);const later=clock(hard,13);assert.ok(getConflictEventFamilyMultiplier(hard,j,'autonomy')>getConflictEventFamilyMultiplier(later,j,'autonomy'));});
test('organize charter request preserves phase and time gates',()=>{let g=fixture();const r=g.world.regions[a];assert.ok(canOrganize(eventContext(g,j).runtime,'eagle'));g=applySecessionAction(g,j,'eagle','organize');assert.throws(()=>applySecessionAction(g,j,'eagle','charter'));g=clock(g,6);g.world.regions[a].secession!.eagle!.monthsInPhase=6;g=applySecessionAction(g,j,'eagle','charter');assert.equal(canRequestReferendum(eventContext(g,j).runtime,'eagle'),false);Object.assign(g.world.regions[a].secession!.eagle!,{monthsInPhase:24,monthsActive:30});assert.ok(canRequestReferendum(eventContext(g,j).runtime,'eagle'));g=applySecessionAction(g,j,'eagle','request');assert.equal(g.world.regions[a].secession!.eagle!.phase,'referendum_campaign');});
test('unilateral progression and existing internal conflict',()=>{let g=fixture();Object.assign(g.world.regions[a].secession!.eagle!,{phase:'autonomy_campaign',monthsActive:36,lastRefusalTurn:g.turn});assert.ok(canDeclareUnilaterally(g,eventContext(g,j).runtime,'eagle'));assert.ok(calculateEventChance('secession-eagle-declaration',g,j)>0);g=resolvePendingEvent(pending(g,'secession-eagle-declaration'),'restrict',()=>.5,()=>.5,false);assert.equal(g.world.countries['eagle-republic-1'].identity!.status,'disputed_breakaway');assert.ok(Object.keys(g.world.internalConflicts!).length);});
test('pair frozen at occurrence and correct effect',()=>{const g=pending(fixture(),'state-dispute'),unrelated=getStateRelation(g,a,'owl-state').relations,n=resolvePendingEvent(g,'restrict',()=>.5);assert.equal(n.events.history[0].statePairTarget!.targetStateId,b);assert.ok(getStateRelation(n,a,b).rivalry>getStateRelation(g,a,b).rivalry);assert.equal(getStateRelation(n,a,'owl-state').relations,unrelated);});
test('pending guard still public / effects share domain',()=>{const g=pending(fixture(),'state-dispute');assert.throws(()=>performStateAction(g,a,b,'counter_policy'));const n=applyStatePoliticalActionEffects(g,a,b,'counter_policy');assert.ok(getStateRelation(n,a,b).history.length);assert.equal(advanceMonth(g).turn,g.turn);});
test('inactive pair rejects effect',()=>{const g=fixture();g.world.regions[b].ownerCountryId='sparrow';assert.throws(()=>applyStatePoliticalActionEffects(g,a,b,'counter_policy'));});
test('moderate repeated disputes trigger mediation',()=>{let g=fixture('moderate');Object.assign(getStateRelation(g,a,b),{relations:48,rivalry:46});g=performStateAction(g,a,b,'criticize');g=clock(g,3);g=performStateAction(g,a,b,'counter_policy');assert.ok(shouldMediateStatePair(g,a,b));});
test('natural joint autonomy same API and bloc',()=>{let g=fixture();g.player.controlledRegionId=null;g.player.controlledCountryId='sparrow';g=clock(g,5);for(const id of ['pigeon-state','owl-state'])g.world.regions[id].ownerCountryId='sparrow';g.world.statePolitics!.relations[statePairKey(a,b)].active=true;g=updateStatePoliticalAI(g,true);assert.ok(g.world.statePolitics!.blocs.some(b=>b.purpose==='autonomy'));});
for(const purpose of ['autonomy','economic','anti_rival'] as const)test('purpose consistent '+purpose,()=>{const g=fixture(),response=selectStateResponse(g,a,b,'cooperate',purpose),n=performStateAction(g,a,b,'cooperate',purpose,'owl-state');assert.equal(getStateRelation(n,a,b).history.at(-1)!.response,response);assert.equal(n.world.statePolitics!.blocs.at(-1)?.purpose,purpose);});
test('repeated attack diminishes both relations and rivalry but not zero',()=>{let g=fixture();const first=performStateAction(g,a,b,'criticize'),d=getStateRelation(g,a,b).relations-getStateRelation(first,a,b).relations;g=clock(first,3);const n=performStateAction(g,a,b,'criticize'),r=getStateRelation(g,a,b).relations-getStateRelation(n,a,b).relations;assert.ok(r>0&&r<d);assert.ok(getStateRelation(n,a,b).rivalry-getStateRelation(g,a,b).rivalry<getStateRelation(first,a,b).rivalry-getStateRelation(fixture(),a,b).rivalry);});
test('v5 missing mandatory statePolitics invalid',()=>{const d=createSaveData(fixture(),'test');d.saveVersion=5;delete d.game.world.statePolitics;assert.throws(()=>deserializeSave(JSON.stringify(d)));});
test('v4 initializes missing map and no retro memory',()=>{const d=createSaveData(fixture(),'test');d.saveVersion=4;delete d.game.world.statePolitics;const n=deserializeSave(JSON.stringify(d));assert.ok(n.game.world.statePolitics);assert.equal(n.game.events.history.length,0);});
test('event memory and explicit target save roundtrip',()=>{const g=resolvePendingEvent(pending(fixture(),'state-dispute'),'restrict',()=>.5);assert.deepEqual(deserializeSave(serializeSave(createSaveData(g,'test'))).game,g);assert.deepEqual(deserializeSave(serializeSave(createSaveData(pending(fixture(),'state-dispute'),'pending'))).game.events.pendingEvent!.statePairTarget,{actorStateId:a,targetStateId:b});});
test('bad pair save rejected',()=>{const d=createSaveData(pending(fixture(),'state-dispute'),'test');d.game.events.pendingEvent!.statePairTarget!.targetStateId='sparrow';assert.throws(()=>deserializeSave(JSON.stringify(d)));});
test('natural candidate target retained',()=>{const g=generateWorldEvents(fixture(),{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>.5,strategicAI:false});if(g.events.pendingEvent?.eventId==='state-dispute')assert.equal(g.events.pendingEvent.statePairTarget!.actorStateId,a);assert.ok(g.events.pendingEvent);});
test('cooldown and history major',()=>{const g=resolvePendingEvent(pending(fixture(),'autonomy-protest'),'restrict',()=>.5);assert.equal(calculateEventChance('autonomy-protest',g,j),0);assert.ok(g.history!.timeline.some(e=>e.sourceKey==='conflict-event:test:autonomy-protest'));assert.ok(calculateEventChance('autonomy-protest',tickEventState(clock(g,12)),j)===0);});
test('large conflict persists and recovers',()=>{let g=fixture();for(let i=0;i<36;i++)g=updateStateRelations(clock(g,1));assert.ok(getStateRelation(g,a,'owl-state').rivalry>60);});

test('v5 migration preserves all state and memory',()=>{const g=resolvePendingEvent(pending(fixture(),'autonomy-protest'),'restrict',()=>.5),d=createSaveData(g,'old');d.saveVersion=5;const n=deserializeSave(JSON.stringify(d));assert.equal(n.saveVersion,7);assert.deepEqual({...n.game,annual:undefined},{...g,annual:undefined});assert.equal(n.game.annual!.snapshot.turn,g.turn);assert.deepEqual(n.game.annual!.summaries,[]);});
