const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const mobile=!!process.env.BIRD_MOBILE,context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BIRD_TEST_URL||'http://127.0.0.1:5175');
 await page.getByRole('button',{name:'튜토리얼 건너뛰기',exact:true}).click();await page.getByRole('button',{name:'공화국 운영 시작',exact:true}).click();
 const state=()=>page.evaluate(()=>window.birdKingdomDebug.getGameState());
 const nav=async name=>{const b=page.getByRole('button',{name:'메뉴 열기',exact:true});if(await b.isVisible())await b.click();await page.getByRole('navigation',{name:'정부 운영 메뉴'}).getByRole('button',{name,exact:true}).click();};
 await nav('외교');await page.getByText('전쟁명분: 없음',{exact:true}).waitFor();assert.equal(await page.locator('.war-declaration').getByRole('button',{name:'선전포고',exact:true}).isEnabled(),true);
 await page.locator('.war-declaration').getByRole('button',{name:'선전포고',exact:true}).click();await page.getByRole('dialog',{name:'선전포고 확인'}).waitFor();await page.getByRole('combobox',{name:'전쟁 목표'}).selectOption('punitive');
 await page.getByRole('button',{name:'선전포고 확정',exact:true}).click();await page.getByRole('dialog',{name:'명분 없이 전쟁을 시작하시겠습니까?'}).waitFor();assert.equal(Object.keys((await state()).world.warfare.wars).length,0);
 await page.getByRole('button',{name:'침략전쟁 시작',exact:true}).click();assert.equal((await state()).world.warfare.wars['war-1'].legitimacy,'unjustified');await nav('군사');await page.getByText('정당성: 침략전쟁',{exact:true}).waitFor();
 await page.screenshot({path:'.test-output/conflict-invasion-'+(mobile?'mobile':'pc')+'.png'});
 await nav('기록');await page.getByText(/전쟁명분 없이 .*침공했다/).waitFor();console.log('PASS real CB-free declaration, warning, additional confirmation, war/history legitimacy');
 await page.getByRole('button',{name:'저장 / 불러오기',exact:true}).click();await page.locator('[data-slot="manual-1"]').getByRole('button',{name:'저장',exact:true}).click();if(await page.locator('.save-confirm').count())await page.locator('.save-confirm').getByRole('button',{name:'확인',exact:true}).click();await page.getByText('저장되었습니다.',{exact:true}).waitFor();await page.keyboard.press('Escape');await page.reload();await page.getByRole('button',{name:'이어하기',exact:true}).click();await page.locator('[data-slot="manual-1"]').getByRole('button',{name:'불러오기',exact:true}).click();await page.locator('.topbar').waitFor();assert.equal((await state()).world.warfare.wars['war-1'].legitimacy,'unjustified');assert.equal((await state()).world.warfare.aggressionHistory.length,1);console.log('PASS invasion manual save/reload/load');
 await page.evaluate(async()=>{const {createGame}=await import('/src/game/engine.ts');const {addCasusBelli}=await import('/src/game/casusBelli.ts');window.birdKingdomDebug.setGameState(addCasusBelli(createGame('sparrow',undefined,41027),'sparrow','pigeon','territorial_dispute','duck-state'));});
 await nav('외교');await page.locator('.war-declaration').getByText('영토 분쟁',{exact:true}).waitFor();await page.locator('.war-declaration').getByRole('button',{name:'선전포고',exact:true}).click();await page.getByRole('dialog',{name:'선전포고 확인'}).waitFor();await page.getByRole('button',{name:'선전포고 확정',exact:true}).click();assert.equal((await state()).world.warfare.wars['war-1'].legitimacy,'justified');assert.equal((await state()).world.warfare.casusBelli['cb-1'].consumed,true);await nav('군사');await page.getByText('정당성: 정당화됨',{exact:true}).waitFor();console.log('PASS valid territorial CB consumption, single confirmation and justified war');
 const baseline=await page.evaluate(async()=>{const {createGame}=await import('/src/game/engine.ts'),{createBreakawayCountry}=await import('/src/game/secession.ts'),{getBilateralRelation}=await import('/src/game/diplomacy.ts'),{scoreDiplomaticAction,assessCountry}=await import('/src/game/strategicEvaluation.ts');let g=createGame('sparrow',undefined,41027),r=g.world.regions['owl-state'];Object.assign(r.speciesPolitics.owl,{satisfaction:10,autonomyDemand:95,independenceSentiment:95});r.governance.integration=20;Object.assign(r.secession.owl,{phase:'transition',monthsActive:30,monthsInPhase:6,lastRefusalTurn:g.turn,lastReferendumResult:{date:g.date,passed:true,yesShare:90}});g=createBreakawayCountry(g,{kind:'region',id:r.id},'owl',false);Object.assign(getBilateralRelation(g.world,'owl-republic-1','pigeon'),{relations:80,trust:85,nonAggressionPact:true});window.birdKingdomDebug.setGameState(g);return {relation:{...getBilateralRelation(g.world,'owl-republic-1','sparrow')},sanction:scoreDiplomaticAction(g,'owl-republic-1','sparrow','sanction').total,defense:scoreDiplomaticAction(g,'owl-republic-1','pigeon','defense').total,alliance:assessCountry(g,'owl-republic-1','pigeon').allianceValue};});
 await nav('외교');await page.locator('.diplomatic-country').filter({has:page.getByText('비둘기민주연방',{exact:true})}).click();await page.locator('.war-declaration').getByRole('button',{name:'선전포고',exact:true}).click();await page.getByRole('combobox',{name:'전쟁 목표'}).selectOption('punitive');await page.getByRole('button',{name:'선전포고 확정',exact:true}).click();await page.getByRole('button',{name:'침략전쟁 시작',exact:true}).click();
 const reaction=await page.evaluate(async()=>{const {getBilateralRelation}=await import('/src/game/diplomacy.ts'),{scoreDiplomaticAction,assessCountry}=await import('/src/game/strategicEvaluation.ts');const g=window.birdKingdomDebug.getGameState();return {relation:getBilateralRelation(g.world,'owl-republic-1','sparrow'),sanction:scoreDiplomaticAction(g,'owl-republic-1','sparrow','sanction').total,defense:scoreDiplomaticAction(g,'owl-republic-1','pigeon','defense').total,alliance:assessCountry(g,'owl-republic-1','pigeon').allianceValue,pacts:Object.values(g.world.diplomacy.relations).some(r=>r.defensePact),sanctions:Object.values(g.world.diplomacy.relations).some(r=>r.sanctionsAtoB||r.sanctionsBtoA)};});
 assert.ok(reaction.relation.relations<baseline.relation.relations);assert.ok(reaction.relation.trust<baseline.relation.trust);assert.ok(reaction.relation.threat>baseline.relation.threat);assert.ok(reaction.sanction>baseline.sanction);assert.ok(reaction.defense>baseline.defense);assert.equal(reaction.pacts,false);assert.equal(reaction.sanctions,false);
 const decisions=await page.evaluate(async()=>{const {updateStrategicAI}=await import('/src/game/strategicAI.ts');const d=window.birdKingdomDebug;let g=d.getGameState();g={...g,turn:12,date:{year:2030,month:12}};g=updateStrategicAI(g,{autonomousWorld:true});d.setGameState(g);return g.world.strategicAI['owl-republic-1'];});assert.ok(decisions.targetAssessments.sparrow.threat>0);assert.ok(decisions.recentStrategicDecisions.length>0);console.log('PASS third sovereign reaction and actual strategic AI path',JSON.stringify({before:{sanction:baseline.sanction,defense:baseline.defense},after:{sanction:reaction.sanction,defense:reaction.defense},choices:decisions.recentStrategicDecisions.map(d=>d.action)}));
 if(mobile){for(const width of [320,390,640]){await page.setViewportSize({width,height:844});await nav('외교');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await nav('군사');await page.getByText('정당성: 침략전쟁',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}}
 if(mobile){for(const width of [320,390,640]){await page.setViewportSize({width,height:844});await page.evaluate(async()=>{const {createGame}=await import('/src/game/engine.ts');window.birdKingdomDebug.setGameState(createGame('sparrow',undefined,41027));});await nav('외교');await page.locator('.war-declaration').getByRole('button',{name:'선전포고',exact:true}).click();assert.equal(await page.getByRole('dialog').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}),true);await page.getByRole('combobox',{name:'전쟁 목표'}).selectOption('punitive');await page.getByRole('button',{name:'선전포고 확정',exact:true}).click();await page.getByRole('dialog',{name:'명분 없이 전쟁을 시작하시겠습니까?'}).waitFor();await page.screenshot({path:'.test-output/conflict-warning-'+width+'.png'});await page.getByRole('button',{name:'침략전쟁 시작',exact:true}).click();assert.equal((await state()).world.warfare.wars['war-1'].legitimacy,'unjustified');}}
 assert.deepEqual(errors,[]);console.log('CONFLICT_BROWSER_RESULT 0',mobile?'mobile':'pc');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
