import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createGame, advanceMonth } from './legacyEngine';
import { createBreakawayCountry } from '../src/game/secession';
import { activeConflicts, applyConflictAction, calculateConflictCapability, calculateConflictLogistics, calculateWarSupport, resolveMonthlyConflict, resolveConflictOutcome, updateWorldConflicts } from '../src/game/conflict';
import { allEventDefinitions, calculateEventChance, generateWorldEvents, resolvePendingEvent } from './legacyEvents';
import { countryInfo, derivedCountryRuntime, ownedRegions, refreshCountryAggregates } from '../src/game/runtime';
import { createSeededRandom } from '../src/game/random';
import type { GameState, Jurisdiction, SpeciesId } from '../src/game/types';
const eagle:Jurisdiction={kind:'region',id:'eagle-state'},sparrow:Jurisdiction={kind:'country',id:'sparrow'};
const opts={economyRandom:()=>.5,mortalityRandom:()=>.99,electionRandom:()=>0,eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,secessionRandom:()=>.5,conflictRandom:()=>.5};
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<Math.max(1,Math.abs(b))*1e-9,`${a} != ${b}`);
function scenario(j=eagle,id:SpeciesId='eagle'){let g=j.kind==='region'?createGame('pigeon',j.id):createGame('sparrow');const r=j.kind==='region'?g.world.regions[j.id]:g.world.countries[j.id];Object.assign(r.speciesPolitics![id]!,{satisfaction:10,autonomyDemand:90,independenceSentiment:90});r.governance!.integration=20;Object.assign(r.secession![id]!,{phase:'unilateral_crisis',monthsActive:24,lastRefusalTurn:g.turn});return createBreakawayCountry(g,j,id,true);}
function first(g:GameState){return Object.values(g.world.internalConflicts!)[0];}
function arm(g:GameState){const c=first(g);c.monthsInConflict=3;c.tension=80;c.lastHardlineTurn=g.turn;g.world.countries[c.breakawayCountryId].identity!.territorialDispute='parent_claims_reunification';return applyConflictAction(g,c.id,'escalate');}
function verify(g:GameState){for(const r of Object.values(g.world.regions))assert.ok(g.world.countries[r.ownerCountryId]);for(const c of activeConflicts(g.world)){assert.ok(g.world.countries[c.parentCountryId]&&g.world.countries[c.breakawayCountryId]);for(const key of ['territorialControl','tension','parentCapability','breakawayCapability','parentLogistics','breakawayLogistics','parentFatigue','breakawayFatigue','parentWarSupport','breakawayWarSupport'] as const)assert.ok(Number.isFinite(c[key])&&c[key]>=0&&c[key]<=100);}for(const r of [...Object.values(g.world.countries),...Object.values(g.world.regions)]){near(r.economy.gdp,Object.values(r.economy.industries).reduce((s,i)=>s+i.output,0));assert.equal(r.population.total,Object.values(r.population.species).reduce((s,p)=>s+p.population,0));for(const v of [r.fiscal.treasury,r.fiscal.debt,r.economy.gdp])assert.ok(Number.isFinite(v)&&v>=0);}for(const c of Object.values(g.world.countries))if(c.simulationMode==='aggregate_regions')near(c.economy.gdp,ownedRegions(g.world,c.id).reduce((s,r)=>s+r.economy.gdp,0));}
function freeze<T>(v:T):T{if(v&&typeof v==='object'){Object.freeze(v);Object.values(v).forEach(freeze);}return v;}
test('정상세계 빈분쟁·일방독립 대치 생성·기존주70/동적60·초기지지',()=>{assert.deepEqual(createGame('sparrow').world.internalConflicts,{});const a=scenario(),b=scenario(sparrow,'crow');assert.equal(first(a).status,'political_standoff');assert.equal(first(a).territorialControl,70);assert.equal(first(b).territorialControl,60);assert.equal(first(a).foundingIndependence,90);verify(a);verify(b);});
test('대치에서 자동전쟁/RNG 소비 없음·최소기간·강경/긴장/영토방침 모두필수',()=>{const g=scenario();assert.throws(()=>applyConflictAction(g,first(g).id,'escalate'));const n=updateWorldConflicts(g,()=>{throw new Error('대치 RNG')});assert.equal(first(n).status,'political_standoff');assert.equal(first(n).territorialControl,70);assert.equal(first(n).monthsInConflict,1);});
for(const input of ['gdp','defense','budget','population','stability','safety','treasury'])test(`${input} 상승 수행력 반영·작은 예산 영향`,()=>{const g=scenario(),r=derivedCountryRuntime(g.world,'eagle-republic-1'),base=calculateConflictCapability(r);const copy=structuredClone(r);if(input==='gdp')copy.economy.gdp*=4;if(input==='defense')copy.economy.industries.defense.output*=4;if(input==='budget')copy.fiscal.budgetPolicy.defense+=2;if(input==='population')copy.population.total*=4;if(input==='stability')copy.governance!.stability+=10;if(input==='safety')copy.social!.publicSafety+=10;if(input==='treasury')copy.fiscal.treasury*=4;assert.ok(calculateConflictCapability(copy)>base);if(input==='budget')assert.ok(calculateConflictCapability(copy)-base<3);});
test('규모로그보정·10배GDP는10배전력 아님·국방산업 비중 의미',()=>{const g=createGame('sparrow'),r=derivedCountryRuntime(g.world,'sparrow'),larger=structuredClone(r);larger.economy.gdp*=10;assert.ok(calculateConflictCapability(larger)<calculateConflictCapability(r)*2);assert.ok(calculateConflictCapability(g.world.regions['eagle-state'])>=0);});
test('보급 국고/인프라/식량/통제 반영·신생 행정패널티',()=>{const g=scenario(),r=derivedCountryRuntime(g.world,'eagle-republic-1'),base=calculateConflictLogistics(r,50,8),n=structuredClone(r);n.fiscal.treasury*=2;n.fiscal.budgetPolicy.infrastructure+=2;n.economy.industries.agriculture.output*=2;assert.ok(calculateConflictLogistics(n,70,3)>base);assert.ok(calculateConflictLogistics(r,50,3)>base);});
test('초기독립85 지지는52보다높음·피로 지지하락',()=>{const g=scenario(),c=first(g),r=derivedCountryRuntime(g.world,c.breakawayCountryId);assert.ok(calculateWarSupport(r,{...c,foundingIndependence:85},'breakaway')>calculateWarSupport(r,{...c,foundingIndependence:52},'breakaway'));assert.ok(calculateWarSupport(r,{...c,breakawayFatigue:80},'breakaway')<calculateWarSupport(r,c,'breakaway'));});
test('분쟁 월간통제 최대5·피로증가·고정 RNG 재현·invalid RNG 거부·불변',()=>{const g=arm(scenario()),before=structuredClone(g),c=first(g);const n=resolveMonthlyConflict(freeze(g),c,()=>.5);assert.deepEqual(g,before);assert.ok(Math.abs(n.territorialControl-c.territorialControl)<=5);assert.ok(n.parentFatigue>c.parentFatigue);assert.deepEqual(n,resolveMonthlyConflict(g,c,()=>.5));assert.throws(()=>resolveMonthlyConflict(g,c,()=>NaN));});
test('강한전력차에서 RNG가 우세를 뒤집지 않음',()=>{const g=arm(scenario());const r=g.world.regions[eagle.id];for(const i of Object.values(r.economy.industries))i.output*=.0001;r.economy.gdp=Object.values(r.economy.industries).reduce((s,i)=>s+i.output,0);r.population.total=0;r.population.species={};r.fiscal.treasury=0;r.governance.stability=0;r.social.publicSafety=0;const c=first(g);for(const random of [()=>0,()=>.999])assert.ok(resolveMonthlyConflict(g,c,random).territorialControl<c.territorialControl);});
test('armed 경제/국고/사회/피로 실제피해·연방합·소규모이동·개인mortality 불변',()=>{const g=arm(scenario());first(g).monthsInConflict=12;const before=structuredClone(g),n=updateWorldConflicts(g,()=>.5),r=n.world.regions[eagle.id];assert.ok(r.economy.gdp<before.world.regions[eagle.id].economy.gdp);assert.ok(r.fiscal.treasury<before.world.regions[eagle.id].fiscal.treasury);assert.ok(r.social.publicSafety<before.world.regions[eagle.id].social.publicSafety);assert.ok(r.population.total<before.world.regions[eagle.id].population.total);assert.deepEqual(n.player,g.player);verify(n);});
test('국고0 긴급분쟁 비용 부채 충당',()=>{const g=arm(scenario());g.world.regions[eagle.id].fiscal.treasury=0;const n=updateWorldConflicts(g,()=>.5);assert.equal(n.world.regions[eagle.id].fiscal.treasury,0);assert.ok(n.world.regions[eagle.id].fiscal.debt>g.world.regions[eagle.id].fiscal.debt);});
test('피난철새/둥지과밀/회랑혼잡 후속확률 상승',()=>{const g=scenario(),base=calculateEventChance('migrant-refuge',g,eagle),n=arm(g);assert.ok(calculateEventChance('migrant-refuge',n,eagle)>base);});
test('휴전 통제 고정·피로 감소·RNG 없음·협상 긴장 감소',()=>{let g=arm(scenario());first(g).parentFatigue=50;first(g).breakawayFatigue=60;g=applyConflictAction(g,first(g).id,'ceasefire');const before=structuredClone(first(g));g=updateWorldConflicts(g,()=>{throw new Error('휴전 RNG')});assert.equal(first(g).territorialControl,before.territorialControl);assert.ok(first(g).parentFatigue<before.parentFatigue);g=applyConflictAction(g,first(g).id,'negotiate');assert.equal(first(g).status,'negotiation');});
test('독립승인 established·분쟁제거·경력/게임계속·부모비용',()=>{const g=scenario(),career=structuredClone(g.player.career),n=resolveConflictOutcome(g,first(g).id,'independence_recognized');assert.equal(n.world.countries['eagle-republic-1'].identity!.status,'established');assert.equal(n.world.countries['eagle-republic-1'].identity!.territorialDispute,'none');assert.equal(first(n).status,'resolved');assert.deepEqual(n.player.career,career);assert.equal(n.gameOverReason,null);verify(n);});
test('협상재통합 주 owner복원·국가삭제·집계/재정 보존·확대자치80·state_defeat',()=>{let g=scenario();g=applyConflictAction(g,first(g).id,'negotiate');const p=g.world.countries.pigeon,b=g.world.countries['eagle-republic-1'],pop=p.population.total+b.population.total,gdp=p.economy.gdp+b.economy.gdp,treasury=g.world.regions[eagle.id].fiscal.treasury;g=resolveConflictOutcome(g,first(g).id,'negotiated_reintegration');assert.equal(g.world.countries['eagle-republic-1'],undefined);assert.equal(g.world.regions[eagle.id].ownerCountryId,'pigeon');assert.equal(g.world.countries.pigeon.population.total,pop);near(g.world.countries.pigeon.economy.gdp,gdp);assert.equal(g.world.regions[eagle.id].fiscal.treasury,treasury);assert.equal(g.world.regions[eagle.id].secession!.eagle!.grantedAutonomy,80);assert.equal(g.gameOverReason,'state_defeat');assert.ok(g.player.alive);assert.equal(countryInfo(g,'eagle-republic-1').name,'독수리공화국');verify(g);assert.equal(advanceMonth(g,opts),g);});
for(const negotiated of [true,false])test(`중앙국 ${negotiated?'협상':'강제'} 재통합 인구/GDP/산업/국고/부채 보존·행정영토 중복0·부모계속`,()=>{let g=scenario(sparrow,'crow');const parent=structuredClone(g.world.countries.sparrow),child=structuredClone(g.world.countries['crow-republic-1']);if(negotiated)g=applyConflictAction(g,first(g).id,'negotiate');else first(g).parentDominanceMonths=3;g=resolveConflictOutcome(g,first(g).id,negotiated?'negotiated_reintegration':'forced_reintegration');const p=g.world.countries.sparrow;assert.equal(p.population.total,parent.population.total+child.population.total);near(p.economy.gdp,parent.economy.gdp+child.economy.gdp);near(p.fiscal.treasury,parent.fiscal.treasury+child.fiscal.treasury);near(p.fiscal.debt,parent.fiscal.debt+child.fiscal.debt);for(const id of Object.keys(p.economy.industries) as (keyof typeof p.economy.industries)[])near(p.economy.industries[id].output,parent.economy.industries[id].output+child.economy.industries[id].output);assert.equal(g.world.regions['crow-nest-1'].simulationRole,'administrative');assert.equal(g.world.regions['crow-nest-1'].ownerCountryId,'sparrow');assert.equal(g.world.regions['crow-nest-1'].economy.gdp,0);assert.equal(g.gameOverReason,null);assert.ok(p.speciesPolitics!.crow!.independenceSentiment>0);verify(g);const next=advanceMonth(g,opts);assert.equal(next.world.regions['crow-nest-1'].population.total,0);assert.ok(next.world.countries.sparrow.population.total>0);verify(next);});
test('최소3개월 결정적통제·독립방어 지지35 조건·후보우선',()=>{const g=arm(scenario());assert.throws(()=>resolveConflictOutcome(g,first(g).id,'independence_defended'));first(g).territorialControl=95;first(g).breakawayDominanceMonths=3;first(g).breakawayWarSupport=70;const n=generateWorldEvents(g,opts);assert.equal(n.events.pendingEvent!.eventId,'conflict-breakaway-victory');const done=resolvePendingEvent(n,'invest',()=>.5);assert.equal(first(done).resolution,'independence_defended');assert.equal(done.gameOverReason,null);});
test('다중분쟁 두건 유지·parent capability분산·한건삭제가 다른소유권 안변경',()=>{let g=scenario(sparrow,'crow');const r=g.world.countries.sparrow;Object.assign(r.speciesPolitics!.swallow!,{satisfaction:10,autonomyDemand:90,independenceSentiment:90});r.governance!.integration=20;Object.assign(r.secession!.swallow!,{phase:'unilateral_crisis',monthsActive:24,lastRefusalTurn:g.turn});g=createBreakawayCountry(g,sparrow,'swallow',true);assert.equal(activeConflicts(g.world).length,2);const c=first(g),before=calculateConflictCapability(derivedCountryRuntime(g.world,'sparrow'));g=updateWorldConflicts(g,()=>.5);assert.ok(first(g).parentCapability<before);g=applyConflictAction(g,c.id,'negotiate');g=resolveConflictOutcome(g,c.id,'negotiated_reintegration');assert.equal(g.world.regions['swallow-nest-1'].ownerCountryId,'swallow-republic-1');assert.equal(activeConflicts(g.world).length,1);verify(g);});
test('conflict RNG 고정재현·비분쟁월 기존상태/스트림 무영향',()=>{const g=arm(scenario());assert.deepEqual(updateWorldConflicts(g,createSeededRandom(42)),updateWorldConflicts(g,createSeededRandom(42)));const normal=createGame('sparrow');assert.deepEqual(advanceMonth(normal,{...opts,conflictRandom:()=>{throw new Error('분쟁없음')}}),advanceMonth(normal,{...opts,conflictRandom:()=>.2}));});
test('장기교착 피로·협상확률 증가·120개월 종결 중재 후보',()=>{let g=arm(scenario());const c=first(g);c.territorialControl=50;c.stalemateMonths=12;const base=calculateEventChance('conflict-mediation',g,eagle);for(let i=0;i<120;i++)g=updateWorldConflicts(g,()=>.5);assert.ok(first(g).parentFatigue>80);assert.ok(calculateEventChance('conflict-mediation',g,eagle)>base);assert.ok(calculateEventChance('conflict-long-mediation',g,eagle)>0);verify(g);});
test('전쟁중 48개월 선거 유지·패배/사망 RNG 기존동작',()=>{const g=arm(scenario());g.player.career.monthsInCurrentTerm=47;const n=advanceMonth(g,opts);assert.equal(n.player.career.termNumber,2);assert.ok(n.player.career.lastElection!.won);assert.equal(first(n).status,'armed_conflict');});
test('삭제참조 snapshot·active효과/쿨다운 정리·resolved conflict 역사유지',()=>{let g=scenario(sparrow,'crow');const id='crow-republic-1';g.events.history.push({id:'history',eventId:'flight-festival',jurisdiction:{kind:'country',id},date:g.date,turn:g.turn,severity:1,choiceId:'balance',choiceLabel:'행사',category:'social',title:'기념 비행',playerChoice:false,jurisdictionName:'까마귀공화국'});g.events.cooldowns[`country:${id}:storm`]=6;g.events.activeEffects.push({id:'active',sourceEventId:'storm',jurisdiction:{kind:'country',id},remainingMonths:3,effects:[]});g=applyConflictAction(g,first(g).id,'negotiate');g=resolveConflictOutcome(g,first(g).id,'negotiated_reintegration');assert.equal(g.events.activeEffects.length,0);assert.equal(g.events.cooldowns[`country:${id}:storm`],undefined);assert.equal(g.events.history[0].jurisdictionName,'까마귀공화국');assert.equal(first(g).breakawayName,'까마귀공화국');verify(g);});
test('14개 실제 분쟁 사건·모든 선택 작동 및 병력수치 없음',()=>{const events=allEventDefinitions.filter(e=>e.conflictEvent);assert.equal(events.length,14);for(const e of events){assert.equal(e.choices.length,3);assert.ok(e.description.length>30);}});
test('정상600개월 국가2·활성분쟁0·세계 불변조건',()=>{let g=createGame('sparrow');const streams={economyRandom:createSeededRandom(2030),eventOccurrenceRandom:createSeededRandom(5544),eventOutcomeRandom:createSeededRandom(9966),secessionRandom:createSeededRandom(600),conflictRandom:createSeededRandom(601)};for(let i=0;i<600;i++){g=advanceMonth(g,{...opts,...streams});if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',streams.eventOutcomeRandom,streams.secessionRandom);verify(g);}assert.equal(Object.keys(g.world.countries).length,2);assert.equal(activeConflicts(g.world).length,0);console.log('CONFLICT NORMAL600',JSON.stringify({countries:2,conflicts:0}));});

test('독수리 일방독립→3년 무력충돌→휴전→협상→독립승인 E2E',()=>{let g=arm(scenario());const career=structuredClone(g.player.career);for(let i=0;i<36;i++){g=advanceMonth(g,opts);if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',()=>.5);verify(g);}assert.ok(first(g).monthsInConflict>=39);g=applyConflictAction(g,first(g).id,'ceasefire');const control=first(g).territorialControl;g=advanceMonth(g,opts);if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',()=>.5);near(first(g).territorialControl,control);g=applyConflictAction(g,first(g).id,'negotiate');g=resolveConflictOutcome(g,first(g).id,'independence_recognized');assert.equal(first(g).resolution,'independence_recognized');assert.equal(g.world.countries['eagle-republic-1'].identity!.status,'established');assert.equal(g.player.career.office,career.office);assert.equal(g.gameOverReason,null);verify(g);});
for(const winner of ['parent','breakaway'])test(winner+' 실제 월간 우세→통제3개월→최종 사건→승리 E2E',()=>{let g=arm(scenario());const c=first(g);const weak=winner==='parent'?g.world.regions[eagle.id]:g.world.regions['pigeon-state'];const targets=winner==='parent'?[weak]:ownedRegions(g.world,'pigeon');for(const r of targets){for(const i of Object.values(r.economy.industries))i.output=0;r.economy.gdp=0;r.fiscal.treasury=0;r.fiscal.budgetPolicy.defense=0;r.fiscal.budgetPolicy.infrastructure=0;r.governance.stability=0;r.social.publicSafety=0;for(const p of Object.values(r.population.species))p.population=0;r.population.total=0;}g.world=refreshCountryAggregates(g.world);let months=0;while((winner==='parent'?first(g).parentDominanceMonths:first(g).breakawayDominanceMonths)<3&&months<100){g=updateWorldConflicts(g,()=>.5);months++;verify(g);}assert.ok(months<100);assert.ok(winner==='parent'?first(g).territorialControl<=10:first(g).territorialControl>=90);g=generateWorldEvents(g,opts);assert.equal(g.events.pendingEvent!.eventId,'conflict-'+(winner==='parent'?'parent':'breakaway')+'-victory');g=resolvePendingEvent(g,'invest',()=>.5);assert.equal(first(g).status,'resolved');if(winner==='parent'){assert.equal(g.world.countries[c.breakawayCountryId],undefined);assert.equal(g.gameOverReason,'state_defeat');}else{assert.equal(g.world.countries[c.breakawayCountryId].identity!.status,'established');assert.equal(g.gameOverReason,null);}verify(g);console.log('CONFLICT VICTORY',winner,months);});
test('강제 재통합 복구비·생활부담은 후속3개월·즉시자산보존',()=>{let g=scenario(sparrow,'crow');first(g).parentDominanceMonths=3;g=resolveConflictOutcome(g,first(g).id,'forced_reintegration');assert.equal(g.events.activeEffects.length,1);assert.equal(g.events.activeEffects[0].remainingMonths,3);assert.ok(g.events.activeEffects[0].effects.some(e=>e.kind==='treasury'&&e.amount<0));assert.ok(g.events.activeEffects[0].effects.some(e=>e.kind==='social'&&e.delta<0));for(let i=0;i<3;i++)g=advanceMonth(g,opts);assert.equal(g.events.activeEffects.length,0);verify(g);});
test('휴전은 경제전쟁피해를 중단하고 영토분쟁 보존',()=>{let g=arm(scenario());g=applyConflictAction(g,first(g).id,'ceasefire');const before=structuredClone(g.world);g=updateWorldConflicts(g,()=>{throw new Error('휴전');});assert.deepEqual(g.world.countries,before.countries);assert.deepEqual(g.world.regions,before.regions);assert.equal(g.world.countries['eagle-republic-1'].identity!.status,'disputed_breakaway');});

for(const definition of allEventDefinitions.filter(e=>e.conflictEvent))test(definition.id+' 세 선택의 실제 해석·기록·참조 안전',()=>{for(const choice of ['invest','balance','restrict']){let g=arm(scenario());const c=first(g);c.monthsInConflict=36;c.parentFatigue=60;c.breakawayFatigue=60;c.stalemateMonths=12;if(definition.id==='conflict-corridor'||definition.id==='conflict-escalation')c.status='political_standoff';if(definition.id==='conflict-autonomy'||definition.id==='conflict-recognition')c.status='negotiation';if(definition.id==='conflict-parent-victory'){c.territorialControl=5;c.parentDominanceMonths=3;}if(definition.id==='conflict-breakaway-victory'){c.territorialControl=95;c.breakawayDominanceMonths=3;c.breakawayWarSupport=70;}if(definition.id==='conflict-long-mediation')c.monthsInConflict=120;assert.ok(calculateEventChance(definition.id,g,eagle)>0);g.events.pendingEvent={id:'verify-'+definition.id,eventId:definition.id,jurisdiction:eagle,conflictId:c.id,date:g.date,turn:g.turn,severity:3,jurisdictionName:'독수리공화국'};g=resolvePendingEvent(g,choice,()=>.5);assert.equal(g.events.pendingEvent,null);assert.ok(g.events.history.some(e=>e.eventId===definition.id&&e.choiceId===choice&&e.jurisdictionName==='독수리공화국'));verify(g);}});
