import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createGame, advanceMonth } from './legacyEngine';
import { startCrisis, crisesFor, crisisRuntime, calculateCrisisDamage, calculateCrisisSeverity, calculateCrisisResilience, getCrisisImpact, getCrisisIndustryModifiers, updateWorldCrises, recoverCrisis, calculateDiseaseSpreadPressure, diseaseConnection, calculateLeaderRisk, updateLeaderRisk, applyCrisisSpeciesPressure, synchronizeCrises, crisisMilitaryPenalty } from '../src/game/crisis';
import { crisisDefinitions, crisisConfig, crisisSeverityLabel, leaderRiskLabel } from '../src/game/crisisConfig';
import { crisisEventDefinitions, crisisAidPartner } from '../src/game/crisisEvents';
import { calculateEventChance, eventContext, getEventDefinition, generateWorldEvents, resolvePendingEvent, tickEventState } from './legacyEvents';
import { applyEventEffects } from '../src/game/eventEffects';
import { calculateBaseMonthlyMortalityRisk, calculateMonthlyMortalityRisk } from '../src/game/mortality';
import { createSeededRandom } from '../src/game/random';
import { updateWorldPopulation } from '../src/game/population';
import { updateWorldSocial } from '../src/game/social';
import { updateWorldMilitary } from '../src/game/military';
import { technologyDefinitions } from '../src/game/technologyDefinitions';
import { createBreakawayCountry } from '../src/game/secession';
import { transferWarTerritory } from '../src/game/warfareEffects';
import { addCasusBelli } from '../src/game/casusBelli';
import { declareWar } from '../src/game/warfare';
import { resolveConflictOutcome } from '../src/game/conflict';
import type { CrisisType, GameState, Jurisdiction } from '../src/game/types';
const sparrow:Jurisdiction={kind:'country',id:'sparrow'},duck:Jurisdiction={kind:'region',id:'duck-state'},owl:Jurisdiction={kind:'region',id:'owl-state'},eagle:Jurisdiction={kind:'region',id:'eagle-state'};
const opts={economyRandom:()=>.5,eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,electionRandom:()=>0,mortalityRandom:()=>.99,crisisRandom:()=>.99,warRandom:()=>.5,conflictRandom:()=>.5};
const active=(g:GameState)=>Object.values(g.world.crises!.activeCrises);
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6*Math.max(1,a,b),`${a} != ${b}`);
function quality(g:GameState,high:boolean,j=sparrow){const r=crisisRuntime(g.world,j)!;for(const key of ['healthcare','publicSafety','livingStandard'] as const)r.social[key]=high?90:15;r.governance.stability=high?90:15;r.fiscal.treasury=high?r.economy.gdp:0;r.fiscal.budgetPolicy.infrastructure=high?6:0;r.fiscal.budgetPolicy.healthcare=high?6:0;for(const d of Object.values(r.technology!.domains))d.level=high?10:0;r.technology!.unlockedTechnologies=high?technologyDefinitions.map(d=>d.id):[];return g;}
function invariant(g:GameState){for(const r of [...Object.values(g.world.countries),...Object.values(g.world.regions)]){near(r.economy.gdp,Object.values(r.economy.industries).reduce((s,i)=>s+i.output,0));assert.ok(Number.isFinite(r.fiscal.debt)&&r.fiscal.debt>=0);assert.ok(r.fiscal.treasury>=0);assert.equal(r.population.total,Object.values(r.population.species).reduce((s,p)=>s+p.population,0));for(const p of Object.values(r.population.species))assert.ok(p.population>=0&&Number.isSafeInteger(p.population));}for(const c of active(g)){assert.ok(crisisRuntime(g.world,{kind:c.jurisdictionKind,id:c.jurisdictionId}));for(const key of ['severity','intensity','recoveryProgress','spreadPressure'] as const)assert.ok(c[key]>=0&&c[key]<=100);}}
function independent(g=createGame('pigeon','eagle-state'),disputed=false){const r=g.world.regions[eagle.id];Object.assign(r.speciesPolitics.eagle!,{satisfaction:10,autonomyDemand:90,independenceSentiment:90});r.governance.integration=20;Object.assign(r.secession!.eagle!,{phase:disputed?'unilateral_crisis':'transition',monthsInPhase:6,monthsActive:24,lastRefusalTurn:g.turn,lastReferendumResult:{date:g.date,yesShare:80,passed:true}});return createBreakawayCountry(g,eagle,'eagle',disputed);}
function warGame(){let g=addCasusBelli(createGame('sparrow'),'sparrow','pigeon','border_incident');return declareWar(g,'sparrow',Object.values(g.world.warfare!.casusBelli)[0].id,'punitive');}
test('위기 빈 초기화와 게임 간 독립',()=>{const a=createGame('sparrow'),b=createGame('sparrow');assert.deepEqual(a.world.crises,{activeCrises:{},history:[],nextId:1});assert.notEqual(a.world.crises,b.world.crises);});
for(const type of Object.keys(crisisDefinitions) as CrisisType[]){
 test(type+' 생성·범위·중복 방지·불변',()=>{const g=createGame('sparrow'),before=structuredClone(g),n=startCrisis(g,sparrow,type,80);assert.deepEqual(g,before);assert.equal(active(n).length,1);assert.equal(active(n)[0].type,type);assert.equal(startCrisis(n,sparrow,type,100),n);invariant(n);});
 test(type+' 경제 성장·생산성 부담·고회복력 완화',()=>{const low=startCrisis(quality(createGame('sparrow'),false),sparrow,type,85),high=startCrisis(quality(createGame('sparrow'),true),sparrow,type,85);const a=getCrisisIndustryModifiers(low.world,sparrow),b=getCrisisIndustryModifiers(high.world,sparrow);for(const id of crisisDefinitions[type].industries){assert.ok(a[id]!.annualGrowthAdjustment!<0);assert.ok(a[id]!.annualGrowthAdjustment!<b[id]!.annualGrowthAdjustment!);assert.ok(a[id]!.productivityMultiplier!<b[id]!.productivityMultiplier!);}assert.ok(calculateCrisisDamage(active(high)[0],crisisRuntime(high.world,sparrow)!)>0);});
 test(type+' 재정 자동 비용·국고 부족 부채·GDP 보존',()=>{let g=startCrisis(quality(createGame('sparrow'),false),sparrow,type,90),r=g.world.countries.sparrow;const n=updateWorldCrises(g,()=>.99);assert.ok(active(n)[0].totalFiscalCost>0);assert.ok(n.world.countries.sparrow.fiscal.debt>r.fiscal.debt);assert.equal(n.world.countries.sparrow.economy.gdp,r.economy.gdp);assert.equal(n.world.countries.sparrow.fiscal.hasIssuedDebt,true);invariant(n);});
 test(type+' 인구 흐름 집계·양수·이동 영향',()=>{const g=startCrisis(createGame('sparrow'),sparrow,type,90),w=updateWorldPopulation(g.world),normal=updateWorldPopulation(createGame('sparrow').world);assert.ok(w.countries.sparrow.population.netMigrationLastMonth<normal.countries.sparrow.population.netMigrationLastMonth);assert.ok(w.countries.sparrow.population.deathsLastMonth>=normal.countries.sparrow.population.deathsLastMonth);invariant({...g,world:w});});
 test(type+' 회복 완료·최대 기간·종료 후 modifier 제거',()=>{let g=startCrisis(quality(createGame('sparrow'),false),sparrow,type,100),months=0;while(active(g).length&&months<30){g={...g,turn:g.turn+1};g=updateWorldCrises(g,()=>.99);months++;invariant(g);}assert.ok(months<=crisisDefinitions[type].maxMonths);assert.equal(active(g).length,0);assert.deepEqual(getCrisisIndustryModifiers(g.world,sparrow),{});assert.equal(g.world.crises!.history[0].action,'complete');assert.ok(g.world.crises!.history[0].fiscalCost>0);});
}
test('같은 관할 다중 위기 허용·다른 관할 같은 유형 허용',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm');g=startCrisis(g,sparrow,'seed_blight');g=startCrisis(g,eagle,'great_storm');assert.equal(active(g).length,3);});
test('강도 입력·회복 값 clamp',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm',999);assert.equal(active(g)[0].severity,100);g=recoverCrisis(g,active(g)[0].id,999);assert.equal(active(g).length,0);assert.equal(g.world.crises!.history[0].action,'complete');assert.equal(active(startCrisis(createGame('sparrow'),sparrow,'great_storm',-1))[0].severity,0);});
for(const [key,resKey] of [['infrastructure','infrastructure'],['medicine','medical'],['agriculture','foodSecurity'],['information','emergencyResponse']] as const)test(key+' 기술 상승 → 회복력 개선',()=>{const g=quality(createGame('sparrow'),false),r=crisisRuntime(g.world,sparrow)!,a=calculateCrisisResilience(r);r.technology!.domains[key].level=10;assert.ok(calculateCrisisResilience(r)[resKey]>a[resKey]);});
test('보건 수준 상승 → 의료 회복력·질병 피해 감소',()=>{const g=startCrisis(createGame('sparrow'),sparrow,'respiratory_outbreak',90),r=crisisRuntime(g.world,sparrow)!;r.social.healthcare=10;const d=calculateCrisisDamage(active(g)[0],r);r.social.healthcare=90;assert.ok(calculateCrisisDamage(active(g)[0],r)<d);});
test('치안 상승 → 긴급 대응력 개선',()=>{const r=crisisRuntime(createGame('sparrow').world,sparrow)!;r.social.publicSafety=0;const a=calculateCrisisResilience(r).emergencyResponse;r.social.publicSafety=100;assert.ok(calculateCrisisResilience(r).emergencyResponse>a);});
test('국고·인프라 예산 → 기반 회복력 개선',()=>{const r=crisisRuntime(quality(createGame('sparrow'),false).world,sparrow)!,a=calculateCrisisResilience(r).infrastructure;r.fiscal.treasury=r.economy.gdp;r.fiscal.budgetPolicy.infrastructure=6;assert.ok(calculateCrisisResilience(r).infrastructure>a);});
test('시기·최근 사건·기존 위기가 강도에 반영',()=>{let g=createGame('sparrow');g.date.month=1;const a=calculateCrisisSeverity(g,sparrow,'great_storm');g.date.month=7;assert.ok(calculateCrisisSeverity(g,sparrow,'great_storm')>a);g=startCrisis(g,sparrow,'seed_blight',50);assert.ok(calculateCrisisSeverity(g,sparrow,'great_storm')>a+6);g.events.history.push({id:'past',eventId:'storm',date:g.date,turn:g.turn,jurisdiction:sparrow,severity:2,choiceId:'balance',choiceLabel:'보호',title:'폭풍',category:'disaster',playerChoice:true});assert.ok(calculateCrisisSeverity(g,sparrow,'great_storm')>a+9);});
test('8A 실용 기술 피해 modifier 실제 완화',()=>{const g=startCrisis(createGame('sparrow'),sparrow,'great_storm',90),r=crisisRuntime(g.world,sparrow)!;r.technology!.unlockedTechnologies=[];const low=calculateCrisisDamage(active(g)[0],r);r.technology!.unlockedTechnologies=technologyDefinitions.map(d=>d.id);assert.ok(calculateCrisisDamage(active(g)[0],r)<low);});
test('폭풍 경보 보호 vs 활동 유지 비용 균형',()=>{const g=createGame('sparrow');g.events.pendingEvent={id:'storm',eventId:'storm',date:g.date,turn:g.turn,jurisdiction:sparrow,severity:3};const invest=resolvePendingEvent(g,'invest',()=>.5),keep=resolvePendingEvent(g,'restrict',()=>.5);assert.ok(invest.world.countries.sparrow.fiscal.treasury<keep.world.countries.sparrow.fiscal.treasury);assert.ok(active(invest)[0].responseProtection>active(keep)[0].responseProtection);assert.ok(active(invest)[0].activityReduction>active(keep)[0].activityReduction);assert.equal(invest.events.activeEffects.length,0);});
test('기존 6개 ID 모두 위기 트리거·지속 산업 효과 없음',()=>{for(const id of ['storm','hail','wetland-drought','nest-cliff','seed-disease','feather-mites']){const g=createGame('pigeon','duck-state');g.events.pendingEvent={id,eventId:id,date:g.date,turn:g.turn,jurisdiction:duck,severity:2};const n=resolvePendingEvent(g,'balance',()=>.5);assert.equal(active(n).length,1);assert.equal(n.events.activeEffects.length,0);}});
test('재난·질병 23개 사건 모두 실제 선택·효과·기본 대응',()=>{assert.equal(crisisEventDefinitions.length+6,23);for(const e of crisisEventDefinitions){assert.equal(e.choices.length,3);assert.ok(e.choices.some(c=>c.id===e.nonPlayerChoiceId));assert.ok(e.description.length>25);}for(const id of ['reed-fire','corridor-icing','respiratory-outbreak','wetland-contamination']){const g=createGame('pigeon','duck-state');g.events.pendingEvent={id,eventId:id,date:g.date,turn:g.turn,jurisdiction:duck,severity:3};const n=resolvePendingEvent(g,'balance',()=>.5);assert.equal(active(n).length,1);invariant(n);}});
test('화재 가뭄 연쇄·오리·여름 발생 상승',()=>{let g=createGame('pigeon','duck-state');g.date.month=1;const a=calculateEventChance('reed-fire',g,duck);g.date.month=7;assert.ok(calculateEventChance('reed-fire',g,duck)>a);const b=calculateEventChance('reed-fire',g,duck);g=startCrisis(g,duck,'wetland_drought',80);assert.ok(calculateEventChance('reed-fire',g,duck)>b);});
test('겨울 결빙 발생 확률 상승·Lv10도 발생 가능',()=>{const g=quality(createGame('sparrow'),true);g.date.month=7;const a=calculateEventChance('corridor-icing',g,sparrow);g.date.month=1;assert.ok(calculateEventChance('corridor-icing',g,sparrow)>a);assert.ok(a>0);});
test('호흡기 자연사망 부담은 진드기보다 큼',()=>{const a=startCrisis(createGame('sparrow'),sparrow,'respiratory_outbreak',80),b=startCrisis(createGame('sparrow'),sparrow,'feather_mite_outbreak',80);assert.ok(getCrisisImpact(a.world,sparrow).mortalityMultiplier>getCrisisImpact(b.world,sparrow).mortalityMultiplier);});
test('심각한 위기의 생활·치안·보건 목표 압박',()=>{const g=startCrisis(createGame('sparrow'),sparrow,'respiratory_outbreak',100),a=updateWorldSocial(g.world).countries.sparrow.social!,b=updateWorldSocial(createGame('sparrow').world).countries.sparrow.social!;assert.ok(a.livingStandard<b.livingStandard);assert.ok(a.healthcare<b.healthcare);assert.ok(a.publicSafety<b.publicSafety);});
test('오리 만족 추가 압박·월 변화 기록',()=>{const g=startCrisis(createGame('pigeon','duck-state'),duck,'wetland_drought',90),p=g.world.regions[duck.id].speciesPolitics.duck!,w=applyCrisisSpeciesPressure(g.world),n=w.regions[duck.id].speciesPolitics.duck!;assert.ok(n.satisfaction<p.satisfaction);near(n.satisfactionDeltaLastMonth-p.satisfactionDeltaLastMonth,n.satisfaction-p.satisfaction);});
test('사회 정상화는 복구 후 점진적',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm',100);for(let i=0;i<3;i++)g={...g,world:updateWorldSocial(g.world)};const low=g.world.countries.sparrow.social!.publicSafety;g.world.crises!.activeCrises={};g={...g,world:updateWorldSocial(g.world)};assert.ok(g.world.countries.sparrow.social!.publicSafety>low);});
test('누적 위기 modifier 보수적 clamp',()=>{let g=quality(createGame('sparrow'),false);for(const t of Object.keys(crisisDefinitions) as CrisisType[])g=startCrisis(g,sparrow,t,100);const impact=getCrisisImpact(g.world,sparrow);assert.ok(impact.mortalityMultiplier<=1.8);assert.ok(impact.migrationAdjustment>=-.35);assert.ok(impact.logisticsPenalty<=15);for(const m of Object.values(getCrisisIndustryModifiers(g.world,sparrow)))assert.ok(m.annualGrowthAdjustment!>=-.09);});
test('이전 월 위기가 경제에만 한 번 적용·GDP 합계 유지',()=>{const g=startCrisis(createGame('sparrow'),sparrow,'great_storm',90),a=advanceMonth(g,opts),b=advanceMonth(createGame('sparrow'),opts);assert.ok(a.world.countries.sparrow.economy.gdp<b.world.countries.sparrow.economy.gdp);assert.equal(a.events.activeEffects.length,0);invariant(a);});
test('다음 월 정상 RNG 소비: 경제30/사망1/위기0',()=>{let e=0,m=0,c=0;advanceMonth(createGame('sparrow'),{...opts,economyRandom:()=>{e++;return .5},mortalityRandom:()=>{m++;return .99},crisisRandom:()=>{c++;return .5}});assert.equal(e,30);assert.equal(m,1);assert.equal(c,0);});
test('질병 확산 한 source·한 달 최대1·동월 연쇄 없음',()=>{const g=startCrisis(createGame('pigeon','eagle-state'),eagle,'respiratory_outbreak',90),n=updateWorldCrises(g,()=>0);assert.equal(active(n).length,2);assert.equal(active(n).filter(c=>c.elapsedMonths===0).length,1);assert.equal(active(n).filter(c=>c.elapsedMonths===1).length,1);});
test('crisisRandom 고정 재현·입력 불변',()=>{const g=startCrisis(createGame('sparrow'),duck,'respiratory_outbreak',90),copy=structuredClone(g);assert.deepEqual(updateWorldCrises(g,createSeededRandom(123)),updateWorldCrises(g,createSeededRandom(123)));assert.deepEqual(g,copy);});
test('spread 압력 무역·철새협정·이동·보건 반영',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'respiratory_outbreak',90);const c=active(g)[0],a=calculateDiseaseSpreadPressure(g.world,c),pair=Object.values(g.world.diplomacy!.relations)[0];pair.tradeLevel=100;pair.migratoryPassageAgreement=true;g.world.countries.sparrow.population.netMigrationLastMonth=100000;assert.ok(calculateDiseaseSpreadPressure(g.world,c)>a);g.world.countries.sparrow.social!.healthcare=100;assert.ok(calculateDiseaseSpreadPressure(g.world,c)<=100);});
test('연결 없으면 확산 RNG 소비 없음',()=>{const g=startCrisis(createGame('sparrow'),sparrow,'respiratory_outbreak',90);g.world.diplomacy!.relations={};for(const r of Object.values(g.world.regions))r.population.netMigrationLastMonth=0;assert.equal(diseaseConnection(g.world,sparrow,duck),0);updateWorldCrises(g,()=>{throw new Error('확산 후보 없음');});});
test('war가 무역 감염 경로 차단·철새 경로 유지',()=>{const g=warGame(),pair=Object.values(g.world.diplomacy!.relations)[0];pair.tradeLevel=100;pair.migratoryPassageAgreement=false;assert.equal(diseaseConnection(g.world,sparrow,duck),0);pair.migratoryPassageAgreement=true;assert.ok(diseaseConnection(g.world,sparrow,duck)>0);});
test('격리된 질병 확산 금지',()=>{let g=startCrisis(createGame('sparrow'),duck,'respiratory_outbreak',90);g=recoverCrisis(g,active(g)[0].id,18);const n=updateWorldCrises(g,()=>{throw new Error('격리 RNG');});assert.equal(active(n).length,1);});
test('위기 invalid RNG 거부',()=>{const g=startCrisis(createGame('sparrow'),duck,'respiratory_outbreak',90);assert.throws(()=>updateWorldCrises(g,()=>1));});
test('추가 복구 지출·지지도·현장 위험 2개월',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm',90);const x=active(g)[0];g.events.pendingEvent={id:'field',eventId:'storm-warning',date:g.date,turn:g.turn,jurisdiction:sparrow,severity:3,crisisId:x.id};const n=resolvePendingEvent(g,'invest',()=>.5);assert.ok(active(n)[0].recoveryProgress>x.recoveryProgress);assert.ok(n.world.countries.sparrow.fiscal.treasury<g.world.countries.sparrow.fiscal.treasury);assert.ok(n.world.countries.sparrow.governance!.approval>g.world.countries.sparrow.governance!.approval);assert.equal(n.player.temporaryLeaderRiskModifiers!.length,1);assert.ok(calculateLeaderRisk(n).situationalRisk>calculateLeaderRisk(g).situationalRisk);assert.equal(updateLeaderRisk({...n,turn:n.turn+3}).player.temporaryLeaderRiskModifiers!.length,0);});
test('중앙 지휘 노출 감소·회복 절충',()=>{const g=startCrisis(createGame('sparrow'),sparrow,'great_storm',90),n=applyEventEffects(g,sparrow,[{kind:'leader_risk',value:-5,months:2}]);assert.ok(calculateLeaderRisk(n).situationalRisk<calculateLeaderRisk(g).situationalRisk);});
test('NPC 현장 대응은 플레이어 노출을 만들지 않음',()=>{const g=startCrisis(createGame('sparrow'),duck,'great_storm',90),n=applyEventEffects(g,duck,[{kind:'leader_risk',value:12,months:2}]);assert.deepEqual(n.player,g.player);});
test('정상 상황 위험0·자연사망 결과 정확 유지',()=>{const g=updateLeaderRisk(createGame('sparrow'));assert.equal(g.player.leaderRisk!.situationalRisk,0);assert.equal(calculateMonthlyMortalityRisk(g),calculateBaseMonthlyMortalityRisk(g.player.ageMonths));});
for(const type of ['great_storm','respiratory_outbreak'] as const)test(type+' 지도자 노출·고기술 완화·사망 가산 한도',()=>{const low=updateLeaderRisk(startCrisis(quality(createGame('sparrow'),false),sparrow,type,100)),high=updateLeaderRisk(startCrisis(quality(createGame('sparrow'),true),sparrow,type,100));assert.ok(low.player.leaderRisk!.situationalRisk>high.player.leaderRisk!.situationalRisk);assert.ok(low.player.currentMortalityRisk<.001);assert.ok(calculateMonthlyMortalityRisk(low)>calculateBaseMonthlyMortalityRisk(low.player.ageMonths));assert.ok(low.player.leaderRisk!.mortalityModifierLastMonth<=crisisConfig.maxLeaderMortalityAddition);});
test('compound 상황 위험 clamp·정상화 위험 감소',()=>{let g=warGame();g.world.countries.sparrow.governance!.stability=0;g.world.countries.sparrow.governance!.approval=0;g=startCrisis(g,sparrow,'great_storm',100);g=startCrisis(g,sparrow,'respiratory_outbreak',100);const risk=calculateLeaderRisk(g);assert.ok(risk.situationalRisk>45);assert.ok(risk.conflictExposure>0&&risk.politicalRisk>0);assert.ok(risk.situationalRisk<=100);assert.ok(risk.mortalityModifierLastMonth<=.0003);g.world.crises!.activeCrises={};g.world.warfare!.wars={};g.world.countries.sparrow.governance!.stability=90;g.world.countries.sparrow.governance!.approval=90;assert.equal(calculateLeaderRisk(g).situationalRisk,0);console.log('CRISIS COMPOUND',JSON.stringify(risk));});
test('위험 사망도 기존 mortalityRandom 1회·종료 후 진행 차단',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm',100),m=0;g=advanceMonth(g,{...opts,mortalityRandom:()=>{m++;return 0;}});assert.equal(m,1);assert.equal(g.gameOverReason,'death');assert.equal(advanceMonth(g,opts),g);});
test('crisisRandom만 변화 → 경제·선거·사망 RNG 소비 동일',()=>{const g=startCrisis(createGame('sparrow'),duck,'respiratory_outbreak',90);for(const value of [0,.99]){let e=0,m=0,o=0,u=0;advanceMonth(g,{...opts,crisisRandom:()=>value,economyRandom:()=>{e++;return .5},mortalityRandom:()=>{m++;return .99},eventOccurrenceRandom:()=>{o++;return .999999},eventOutcomeRandom:()=>{u++;return .5}});assert.equal(e,30);assert.equal(m,1);assert.equal(o,5);assert.equal(u,0);}});
test('국제지원 승인·좋은 관계·무제재 조건·거절 무벌점',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm',90),pair=Object.values(g.world.diplomacy!.relations)[0];pair.relations=80;pair.recognizedAbyB=pair.recognizedBbyA=true;assert.equal(crisisAidPartner(eventContext(g,sparrow)),'pigeon');pair.sanctionsAtoB=true;assert.equal(crisisAidPartner(eventContext(g,sparrow)),undefined);pair.sanctionsAtoB=false;g.events.pendingEvent={id:'aid',eventId:'international-rescue',date:g.date,turn:g.turn,jurisdiction:sparrow,severity:3,crisisId:active(g)[0].id};const n=resolvePendingEvent(g,'invest',()=>.5),reject=resolvePendingEvent(g,'restrict',()=>.5);assert.ok(n.world.countries.sparrow.fiscal.treasury>g.world.countries.sparrow.fiscal.treasury);assert.ok(active(n)[0].recoveryProgress>0);assert.equal(n.world.crises!.history[0].action,'aid');assert.equal(Object.values(reject.world.diplomacy!.relations)[0].relations,pair.relations);});
test('회복 비용·기간 저/고회복력 비교',()=>{const results=[];for(const high of [false,true]){let g=quality(createGame('sparrow'),high);g=startCrisis(g,sparrow,'great_storm',90);g=startCrisis(g,sparrow,'respiratory_outbreak',90);let months=0;while(active(g).length&&months<30){g={...g,turn:g.turn+1};g=updateWorldCrises(g,()=>.99);months++;}results.push({months,cost:g.world.crises!.history.filter(h=>h.action==='complete').reduce((s,h)=>s+h.fiscalCost,0)});}assert.ok(results[0].months>results[1].months);assert.ok(results[0].cost>results[1].cost);console.log('CRISIS RESILIENCE',JSON.stringify(results));});
test('오리주 가뭄→화재 농업·이동·만족·복구 E2E',()=>{let g=createGame('pigeon','duck-state'),baseline=structuredClone(g);g=startCrisis(g,duck,'wetland_drought',85);g=startCrisis(g,duck,'reed_fire',85);g=advanceMonth(g,opts);baseline=advanceMonth(baseline,opts);assert.ok(g.world.regions[duck.id].economy.industries.agriculture.output<baseline.world.regions[duck.id].economy.industries.agriculture.output);assert.ok(g.world.regions[duck.id].population.netMigrationLastMonth<baseline.world.regions[duck.id].population.netMigrationLastMonth);assert.ok(g.world.regions[duck.id].speciesPolitics.duck!.satisfaction<baseline.world.regions[duck.id].speciesPolitics.duck!.satisfaction);for(let i=0;i<20;i++)g=advanceMonth(g,opts);assert.equal(active(g).length,0);invariant(g);});
test('부엉이주 동일 호흡기 위기 대응 우위',()=>{const g=startCrisis(startCrisis(createGame('sparrow'),owl,'respiratory_outbreak',85),eagle,'respiratory_outbreak',85),a=crisesFor(g.world,owl)[0],b=crisesFor(g.world,eagle)[0];assert.ok(calculateCrisisDamage(a,crisisRuntime(g.world,owl)!)<calculateCrisisDamage(b,crisisRuntime(g.world,eagle)!));const n=updateWorldCrises(g,()=>.99);assert.ok(crisesFor(n.world,owl)[0].recoveryProgress>crisesFor(n.world,eagle)[0].recoveryProgress);});
test('전쟁+폭풍 보급 부담·피로·회복 저하·전쟁 불변',()=>{const normal=startCrisis(createGame('sparrow'),sparrow,'great_storm',90),war=startCrisis(warGame(),sparrow,'great_storm',90);assert.ok(crisisMilitaryPenalty(war.world,'sparrow')>0);const m=updateWorldMilitary(war.world).countries.sparrow.military!,base=updateWorldMilitary(warGame().world).countries.sparrow.military!;assert.ok(m.logistics<base.logistics);assert.ok(m.fatigue>base.fatigue);const a=updateWorldCrises(normal,()=>.99),b=updateWorldCrises(war,()=>.99);assert.ok(active(b)[0].recoveryProgress<active(a)[0].recoveryProgress);const n=advanceMonth(war,opts);invariant(n);assert.ok(n.world.warfare!.wars['war-1'].participants.sparrow);});
test('독립 owner 변경 후 영토 위기 유지',()=>{const g=startCrisis(createGame('pigeon','eagle-state'),eagle,'respiratory_outbreak',80),id=active(g)[0].id,n=independent(g);assert.equal(n.world.crises!.activeCrises[id].jurisdictionId,eagle.id);assert.equal(n.world.regions[eagle.id].ownerCountryId,'eagle-republic-1');assert.ok(n.world.crises!.history.some(h=>h.action==='transfer'));invariant(advanceMonth(n,opts));});
test('직접 국가 분리도 위기 부담 복사·과거 비용 보존',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm',80),r=g.world.countries.sparrow;Object.assign(r.speciesPolitics!.crow!,{satisfaction:10,autonomyDemand:90,independenceSentiment:90});Object.assign(r.secession!.crow!,{phase:'transition',monthsInPhase:6,lastReferendumResult:{date:g.date,yesShare:80,passed:true}});g=updateWorldCrises(g,()=>.99);const cost=active(g)[0].totalFiscalCost;g=createBreakawayCountry(g,sparrow,'crow');assert.equal(active(g).length,2);near(active(g).reduce((s,c)=>s+c.totalFiscalCost,0),cost);assert.ok(crisesFor(g.world,{kind:'region',id:'crow-nest-1'}).length);invariant(g);});
test('전쟁 영토 흡수·동적 국가 삭제·행정영토 대응 승계',()=>{let g=independent(startCrisis(createGame('pigeon','eagle-state'),eagle,'great_storm',80));g.player.controlledCountryId='sparrow';g.player.controlledRegionId=null;const id=active(g)[0].id;g=transferWarTerritory(g,[eagle.id],'sparrow');assert.equal(g.world.countries['eagle-republic-1'],undefined);assert.equal(g.world.regions[eagle.id].simulationRole,'administrative');assert.equal(g.world.crises!.activeCrises[id].jurisdictionId,'sparrow');assert.equal(g.world.crises!.activeCrises[id].originJurisdictionId,eagle.id);invariant(advanceMonth(g,opts));});
test('내전 재통합 후 연방 영토 위기 유지',()=>{let g=independent(startCrisis(createGame('pigeon','eagle-state'),eagle,'great_storm',80),true),conflict=Object.values(g.world.internalConflicts!)[0],id=active(g)[0].id;g.player.controlledCountryId='sparrow';g.player.controlledRegionId=null;conflict.parentDominanceMonths=3;g=resolveConflictOutcome(g,conflict.id,'forced_reintegration');assert.equal(g.world.crises!.activeCrises[id].jurisdictionId,eagle.id);assert.equal(g.world.regions[eagle.id].ownerCountryId,'pigeon');invariant(g);});
test('없는 country 위기 정리·없는 관할 생성 거부',()=>{const g=startCrisis(createGame('sparrow'),sparrow,'great_storm',80);delete g.world.countries.sparrow;assert.equal(Object.keys(synchronizeCrises(g.world).crises!.activeCrises).length,0);assert.throws(()=>startCrisis(createGame('sparrow'),{kind:'region',id:'missing'},'great_storm'));});
test('NPC 위기 자동 대응·플레이어 dialog 없음·회복',()=>{const g=startCrisis(createGame('sparrow'),duck,'respiratory_outbreak',90),n=generateWorldEvents(g,{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>.5});assert.ok(n.events.history.filter(e=>e.jurisdiction.id===duck.id).every(e=>!e.playerChoice&&e.choiceId===getEventDefinition(e.eventId).nonPlayerChoiceId));assert.notEqual(n.events.pendingEvent?.jurisdiction.id,duck.id);assert.ok(active(updateWorldCrises(g,()=>.99))[0].recoveryProgress>0);});
test('동적 NPC 지역 의료 위기 비용·회복 정상',()=>{let g=independent();g.player.controlledCountryId='sparrow';g.player.controlledRegionId=null;g=startCrisis(g,eagle,'respiratory_outbreak',85);const n=advanceMonth(g,opts);assert.ok(active(n)[0].elapsedMonths>0);assert.ok(active(n)[0].totalFiscalCost>0);assert.equal(n.events.pendingEvent,null);invariant(n);});
test('위기 및 지도자 UI 범주 경계',()=>{assert.deepEqual([0,25,50,75,100].map(crisisSeverityLabel),['경미','주의','심각','재난적','재난적']);assert.deepEqual([0,20,40,60,80,100].map(leaderRiskLabel),['평온','주의','높음','위험','극심','극심']);});
for(const e of crisisEventDefinitions)test(e.id+' 실제 조건·3선택 해결·기록·입력 불변',()=>{
 let g=createGame('pigeon','duck-state');const pair=Object.values(g.world.diplomacy!.relations)[0];pair.relations=80;pair.recognizedAbyB=pair.recognizedBbyA=true;
 if(e.crisisEvent){let found:GameState|undefined;for(const type of Object.keys(crisisDefinitions) as CrisisType[]){const candidate=startCrisis(g,duck,type,90);active(candidate)[0].elapsedMonths=3;active(candidate)[0].recoveryProgress=85;if(e.eligible(eventContext(candidate,duck))){found=candidate;break;}}assert.ok(found,e.id+' 활성 조건');g=found!;}
 assert.ok(e.eligible(eventContext(g,duck)));const original=structuredClone(g);
 for(const choice of e.choices){const pending={id:e.id,eventId:e.id,date:g.date,turn:g.turn,jurisdiction:duck,severity:3 as const,...(e.crisisEvent?{crisisId:active(g)[0].id}:{})};const n=resolvePendingEvent({...g,events:{...g.events,pendingEvent:pending}},choice.id,()=>.5);assert.equal(n.events.pendingEvent,null);assert.equal(n.events.history[0].choiceId,choice.id);assert.equal(n.events.history[0].eventId,e.id);invariant(n);}
 assert.deepEqual(g,original);
});
test('월간 인구피해 실제 초과 사망·이동 합계와 정확히 일치',()=>{const g=startCrisis(startCrisis(createGame('sparrow'),sparrow,'great_storm',90),sparrow,'respiratory_outbreak',90),n=updateWorldPopulation(g.world),normal=updateWorldPopulation(g.world,{...g.world,crises:{activeCrises:{},history:[],nextId:1}}),a=n.countries.sparrow.population,b=normal.countries.sparrow.population;assert.equal(Object.values(n.crises!.activeCrises).reduce((s,c)=>s+c.totalPopulationImpact,0),Math.max(0,a.deathsLastMonth-b.deathsLastMonth)+Math.max(0,b.netMigrationLastMonth-a.netMigrationLastMonth));});
test('위기 긴급대응비 지출·재정수지 결산 일치',()=>{const g=advanceMonth(startCrisis(createGame('sparrow'),sparrow,'great_storm',90),opts),f=g.world.countries.sparrow.fiscal;assert.ok(f.expenditure.emergency!>0);near(f.expenditure.total,f.expenditure.programTotal+f.expenditure.interest+f.expenditure.emergency!);near(f.monthlyBalance,f.revenue.total-f.expenditure.total);});
test('복구100 즉시 종료·다음 달 대응비 추가 없음',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'great_storm',90);g=recoverCrisis(g,active(g)[0].id,100);assert.equal(active(g).length,0);const treasury=g.world.countries.sparrow.fiscal.treasury;assert.equal(updateWorldCrises(g,()=>{throw new Error('완료 RNG');}).world.countries.sparrow.fiscal.treasury,treasury);});
test('현장 노출 정확히 다음2개월 이후 만료',()=>{let g=applyEventEffects(createGame('sparrow'),sparrow,[{kind:'leader_risk',value:12,months:2}]);const start=g.turn;for(let i=1;i<=3;i++){g=advanceMonth(g,opts);assert.equal(g.turn,start+i);assert.equal(g.player.temporaryLeaderRiskModifiers!.length,i<=2?1:0);}});
test('위기 원인·역사 관할명 snapshot은 국가 삭제 후 보존',()=>{let g=independent(startCrisis(createGame('pigeon','eagle-state'),eagle,'respiratory_outbreak',90));const names=g.world.crises!.history.map(h=>h.jurisdictionName);g.player.controlledCountryId='sparrow';g.player.controlledRegionId=null;g=transferWarTerritory(g,[eagle.id],'sparrow');assert.ok(g.world.crises!.history.some(h=>names.includes(h.jurisdictionName)));assert.ok(g.world.crises!.history.every(h=>h.jurisdictionName&&h.summary));});
test('위기 회복 비용도 누적 집계·초기 대응비 보존',()=>{let g=createGame('sparrow');g.events.pendingEvent={id:'storm',eventId:'storm',date:g.date,turn:g.turn,jurisdiction:sparrow,severity:3};g=resolvePendingEvent(g,'balance',()=>.5);assert.ok(active(g)[0].totalFiscalCost>0);assert.ok(active(g)[0].totalPopulationImpact>0);const id=active(g)[0].id,cost=active(g)[0].totalFiscalCost;g=applyEventEffects(g,sparrow,[{kind:'treasury',amount:-5},{kind:'crisis_recovery',crisisId:id,value:8}]);near(active(g)[0].totalFiscalCost,cost+5);});
test('구버전 진드기 지속 효과를 위기로 이전·산업 이중 차감 없음',()=>{const g=createGame('sparrow');g.events.activeEffects=[{id:'old-mites',sourceEventId:'feather-mites',jurisdiction:sparrow,remainingMonths:3,effects:[{kind:'industry',industryId:'services',multiplier:.99}]}];const n=tickEventState(g);assert.equal(active(n)[0].type,'feather_mite_outbreak');assert.equal(n.events.activeEffects.length,0);assert.equal(n.world.countries.sparrow.economy.gdp,g.world.countries.sparrow.economy.gdp);assert.equal(active(tickEventState(n)).length,1);});
test('동적 독립국 지도자 현장 대응도 영토 관할에 정확 연결',()=>{let g=independent();assert.equal(g.player.controlledRegionId,null);g=startCrisis(g,eagle,'great_storm',90);g=applyEventEffects(g,eagle,[{kind:'leader_risk',value:12,months:2}]);assert.equal(g.player.temporaryLeaderRiskModifiers!.length,1);assert.equal(g.player.temporaryLeaderRiskModifiers![0].jurisdiction.id,eagle.id);assert.ok(calculateLeaderRisk(g).factors.includes('현장 지휘'));});
test('600개월 실제 발생·종료·비상시 아닌 기간·장기 지표 안전',()=>{let g=createGame('sparrow'),starts=0,quiet=0,maxRisk=0;const economy=createSeededRandom(2030),occurrence=createSeededRandom(5544),outcome=createSeededRandom(9966),crisis=createSeededRandom(8451);for(let i=0;i<600;i++){g=advanceMonth(g,{...opts,economyRandom:economy,eventOccurrenceRandom:occurrence,eventOutcomeRandom:outcome,crisisRandom:crisis});if(g.events.pendingEvent)g=resolvePendingEvent(g,getEventDefinition(g.events.pendingEvent.eventId).nonPlayerChoiceId,outcome);starts=Math.max(starts,g.world.crises!.nextId-1);if(!crisesFor(g.world,sparrow).length)quiet++;maxRisk=Math.max(maxRisk,g.player.leaderRisk?.mortalityModifierLastMonth??0);invariant(g);assert.equal(g.gameOverReason,null);}const ends=g.world.crises!.history.filter(h=>h.action==='complete').length;assert.ok(starts>0&&ends>0);assert.ok(quiet>250,`평온 ${quiet}`);assert.ok(g.world.countries.sparrow.economy.gdp>100&&g.world.countries.sparrow.economy.gdp<100000);assert.ok(g.world.countries.sparrow.population.total<1e9);assert.ok(maxRisk<=.0003);console.log('CRISIS NORMAL600',JSON.stringify({starts,ends,quiet,gdp:g.world.countries.sparrow.economy.gdp,population:g.world.countries.sparrow.population.total,maxRisk,active:active(g).length}));});

test('일반 우박은 1~3개월 짧은 복구·다른 재난에 물가 강제 재설정 없음',()=>{let g=startCrisis(createGame('sparrow'),sparrow,'hail_damage',60),months=0;while(active(g).length&&months<6){g=updateWorldCrises({...g,turn:g.turn+1},()=>.99);months++;}assert.ok(months<=3);let storm=startCrisis(createGame('sparrow'),sparrow,'great_storm',90);storm.world.countries.sparrow.economy.inflation=-4;assert.equal(updateWorldCrises(storm,()=>.99).world.countries.sparrow.economy.inflation,-4);});
test('전체 월 엔진 저/고회복력 복합위기 피해·기간·비용 E2E',()=>{
 const results=[];for(const high of [false,true]){let g=quality(createGame('sparrow'),high);g=startCrisis(g,sparrow,'great_storm',90);g=startCrisis(g,sparrow,'respiratory_outbreak',90);let months=0;while(active(g).length&&months<24){g=advanceMonth(g,opts);months++;invariant(g);}assert.equal(active(g).length,0);const completed=g.world.crises!.history.filter(h=>h.action==='complete');results.push({months,cost:completed.reduce((s,h)=>s+h.fiscalCost,0),populationImpact:completed.reduce((s,h)=>s+h.populationImpact,0)});}
 assert.ok(results[0].months>results[1].months);assert.ok(results[0].cost>results[1].cost);assert.ok(results[0].populationImpact>results[1].populationImpact);console.log('CRISIS ENGINE RESILIENCE',JSON.stringify(results));
});
