import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createGame,advanceMonth} from '../src/game/engine';
import {difficultyConfig,difficultyNames,isPlayerJurisdiction,jurisdictionDifficulty} from '../src/game/difficulty';
import {createSaveData,serializeSave,deserializeSave,saveConfig} from '../src/game/save';
import {calculateBaseMonthlyMortalityRisk,calculateMonthlyMortalityRisk} from '../src/game/mortality';
import {createElectionSnapshot} from '../src/game/election';
import {startCrisis,updateWorldCrises,updateLeaderRisk,getCrisisImpact} from '../src/game/crisis';
import {setControlledTaxPolicy} from '../src/game/taxPolicy';
import {policyChangeBlock} from '../src/game/policySchedule';
import {updateEconomy} from '../src/game/economy';
import {calculateDebtInterestRate} from '../src/game/fiscal';
import {balanceConfig} from '../src/game/balanceConfig';
import {distribution,percentile,runSimulation,assertWorld,modules,scenario} from '../simulation/harness';
import type {Difficulty} from '../src/game/difficulty';
const fresh=(d:Difficulty='normal')=>createGame('sparrow',undefined,41,d);
for(const d of difficultyNames){
 test('난이도 초기화 '+d,()=>assert.equal(fresh(d).difficulty,d));
 test('난이도 전체 save/load '+d,()=>assert.equal(deserializeSave(serializeSave(createSaveData(fresh(d),'x'))).game.difficulty,d));
 test('자연 노화 난이도 불변 '+d,()=>{const g=fresh(d);for(const age of [12,120,720,1200]){g.player.ageMonths=age;assert.equal(calculateMonthlyMortalityRisk(g),calculateBaseMonthlyMortalityRisk(age));}});
 test('플레이어 경제 위기 modifier만 '+d,()=>{const g=fresh(d);assert.equal(jurisdictionDifficulty(g,{kind:'country',id:'sparrow'}).crisisDamage,difficultyConfig[d].modifiers.crisisDamage);assert.deepEqual(jurisdictionDifficulty(g,{kind:'region',id:'owl-state'}),difficultyConfig.normal.modifiers);});
 test('AI 시작 자원/정보 난이도 동일 '+d,()=>{assert.deepEqual(fresh(d).world,fresh().world);assert.deepEqual(fresh(d).random,fresh().random);});
 test('난이도 정책 주기 불변 '+d,()=>{let g=fresh(d);g=setControlledTaxPolicy(g,{...g.world.countries.sparrow.fiscal.taxPolicy,incomeTaxRate:16});assert.equal(g.policySchedules!['country:sparrow'].taxNextChangeTurn,4);assert.ok(policyChangeBlock(g,'country:sparrow','tax'));});
 test('NPC 위기 계산 난이도 불변 '+d,()=>{const a=startCrisis(fresh(d),{kind:'region',id:'duck-state'},'great_storm',95),b=startCrisis(fresh(),{kind:'region',id:'duck-state'},'great_storm',95);assert.deepEqual(updateWorldCrises(a,()=>.99).world.regions['duck-state'],updateWorldCrises(b,()=>.99).world.regions['duck-state']);});
}
test('세이브 schema6 앱 버전과 분리',()=>assert.equal(saveConfig.version,7));
test('10A v1 난이도 없는 저장 normal migration',()=>{const d:any=createSaveData(fresh(),'x');d.saveVersion=1;delete d.game.difficulty;const next=deserializeSave(JSON.stringify(d));assert.equal(next.saveVersion,saveConfig.version);assert.equal(next.game.difficulty,'normal');assert.deepEqual(next.game.world,{...d.game.world,federalPolitics:d.game.world.federalPolitics??{}});assert.deepEqual(next.game.random,d.game.random);});
for(const invalid of ['expert','',null,3])test('잘못된 난이도 거부 '+invalid,()=>{assert.throws(()=>createGame('sparrow',undefined,1,invalid as Difficulty));const d:any=createSaveData(fresh(),'x');d.game.difficulty=invalid;assert.throws(()=>deserializeSave(JSON.stringify(d)));});
test('난이도 v2 필수 필드 누락 거부',()=>{const d:any=createSaveData(fresh(),'x');delete d.game.difficulty;assert.throws(()=>deserializeSave(JSON.stringify(d)));});
test('normal 기본/명시 세계 RNG 동일',()=>{let a=fresh(),b={...fresh(),difficulty:undefined};for(let i=0;i<12;i++){const o={autonomousWorld:true,mortalityRiskOverride:0,electionRandom:()=>0};a=advanceMonth(a,o);b=advanceMonth(b,o);}assert.deepEqual(a.world,b.world);assert.deepEqual(a.random,b.random);});
test('선거 허용도 smallpp 순서 clamp',()=>{const e=createElectionSnapshot(fresh('easy')).reelectionChance,n=createElectionSnapshot(fresh()).reelectionChance,h=createElectionSnapshot(fresh('hard')).reelectionChance;assert.ok(e>n&&n>h);assert.ok(Math.abs((e-n)-.04)<1e-10);assert.ok(Math.abs((n-h)-.04)<1e-10);});
test('상황 사망만 10% 순서',()=>{const risks=difficultyNames.map(d=>{const g=updateLeaderRisk(startCrisis(fresh(d),{kind:'country',id:'sparrow'},'great_storm',95));return calculateMonthlyMortalityRisk(g)-calculateBaseMonthlyMortalityRisk(12);});assert.ok(risks[0]<risks[1]&&risks[1]<risks[2]);assert.ok(Math.abs(risks[0]/risks[1]-.9)<1e-9);});
test('위기 피해/회복 쉬움<보통<어려움',()=>{const values=difficultyNames.map(d=>{const g=startCrisis(fresh(d),{kind:'country',id:'sparrow'},'great_storm',95),b=updateWorldCrises(g,()=>.99);return {cost:b.world.crises!.activeCrises['crisis-1'].totalFiscalCost,recovery:b.world.crises!.activeCrises['crisis-1'].recoveryProgress};});assert.ok(values[0].cost<values[1].cost&&values[1].cost<values[2].cost);assert.ok(values[0].recovery>values[1].recovery&&values[1].recovery>values[2].recovery);});
test('인구 사회 위기 영향에도 배율 적용',()=>{const g=startCrisis(fresh(),{kind:'country',id:'sparrow'},'great_storm',95),j={kind:'country' as const,id:'sparrow'};assert.ok(getCrisisImpact(g.world,j,.9).damage<getCrisisImpact(g.world,j,1.1).damage);});
test('연방 선택 주에만 적용 aggregate 이중적용 없음',()=>{const g=createGame('pigeon','eagle-state',1,'hard');assert.ok(isPlayerJurisdiction(g,{kind:'region',id:'eagle-state'}));assert.ok(!isPlayerJurisdiction(g,{kind:'country',id:'pigeon'}));assert.ok(!isPlayerJurisdiction(g,{kind:'region',id:'duck-state'}));});
test('작은 경제 충격과 중립 난수 차이 없음',()=>{const g=fresh().world.countries.sparrow.economy;assert.deepEqual(updateEconomy(g,{random:()=>.5,shockMultiplier:.9}),updateEconomy(g,{random:()=>.5,shockMultiplier:1.1}));});
test('극단 음의 산업 충격만 작은 차이',()=>{const g=fresh().world.countries.sparrow.economy;assert.ok(updateEconomy(g,{random:()=>0,shockMultiplier:.9}).gdp>updateEconomy(g,{random:()=>0,shockMultiplier:1.1}).gdp);});
test('고부채 이자 기존 안전구간과 100% 유지',()=>{assert.equal(calculateDebtInterestRate(600,1000),3);assert.ok(Math.abs(calculateDebtInterestRate(1000,1000)-6.2)<1e-10);assert.ok(calculateDebtInterestRate(3000,1000)>6.2&&calculateDebtInterestRate(3000,1000)<8);assert.equal(calculateDebtInterestRate(100,0),20);});
test('고부채 양의 GDP 이자 단조/유한',()=>{let last=0;for(let i=0;i<100;i++){const n=calculateDebtInterestRate(i*100,1000);assert.ok(n>=last&&Number.isFinite(n));last=n;}});
test('산업 과점 압력은 첫 달 기존 산출 유지',()=>{const g=fresh().world.countries.sparrow.economy;const shares=Object.fromEntries(Object.entries(g.industries).map(([id,s])=>[id,s.output/g.gdp]));assert.deepEqual(updateEconomy(g,{random:()=>.5}),updateEconomy(g,{random:()=>.5,referenceShares:shares}));});
test('산업 과점시 해당 산업 성장 완화',()=>{const g=structuredClone(fresh().world.countries.sparrow.economy);g.industries.advanced.output=g.gdp*.8;const a=updateEconomy(g,{random:()=>.5}),b=updateEconomy(g,{random:()=>.5,referenceShares:{advanced:.15}});assert.ok(b.industries.advanced.output<a.industries.advanced.output);assert.equal(b.industries.agriculture.output,a.industries.agriculture.output);});
test('BalanceConfig 12축 설정 검사',()=>{for(const k of ['economy','fiscal','population','social','politics','elections','events','secession','diplomacy','warfare','technology','crisis','mortality'])assert.ok(k in balanceConfig);});
test('배치 요약 평균 median p90',()=>{const d=distribution([1,2,3,4,10]);assert.equal(d.mean,4);assert.equal(d.median,3);assert.equal(d.max,10);assert.equal(percentile([], .9),0);assert.equal(distribution([]).count,0);});
test('harness deterministic 기록 재현',async()=>{const a=await runSimulation(71,12),b=await runSimulation(71,12);assert.deepEqual(a,b);});
for(const name of ['recession','debt','disease','storm','separatism','war','asymmetric','multiwar','prosperity'])test('stress scenario invariant '+name,async()=>{const m=await modules();let g=await scenario(fresh(),name,m);for(let i=0;i<12;i++)g=advanceMonth(g,{autonomousWorld:true,mortalityRiskOverride:0,electionRandom:()=>0});assertWorld(g);assert.equal(g.turn,13);});
import {getGovernment,governmentRuntime} from '../src/game/government';
import {calculateAIUrgencies,chooseAITaxPolicy} from '../src/game/aiEvaluation';
test('심각한 고부채 AI는 공통 정책 범위 내 1.5pp 대응·일반 주기 유지',()=>{const g=fresh(),id='region:owl-state',d=getGovernment(g.world,id),r=governmentRuntime(g.world,d);r.fiscal.debt=r.economy.gdp*3;r.fiscal.treasury=0;r.fiscal.monthlyBalance=-r.economy.gdp*.03;const s={...g.world.governmentAI![id],currentStrategy:'fiscal_repair' as const};const u=calculateAIUrgencies(g,d,s);assert.ok(u.fiscal>=85);const p=chooseAITaxPolicy(g,d,s,u);assert.ok(Math.max(...Object.keys(p).map(k=>Math.abs(p[k as keyof typeof p]-r.fiscal.taxPolicy[k as keyof typeof p])))===1.5);assert.equal(g.policySchedules![id].taxNextChangeTurn,1);});
