import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createGame, advanceMonth } from './legacyEngine';
import { createBreakawayCountry } from '../src/game/secession';
import { applyConflictAction, resolveConflictOutcome } from '../src/game/conflict';
import { calculateDiplomaticAcceptance, calculateDiplomaticThreat, createBilateralRelation, getBilateralRelation, getDiplomaticActionBlock, getDiplomaticCooldown, getDiplomaticPairKey, isRecognized, isSanctioning, performDiplomaticAction, relationCategory, synchronizeDiplomacy, threatCategory, updateWorldDiplomacy } from '../src/game/diplomacy';
import { getDiplomaticTradeModifiers, getPassageMigrationAdjustment } from '../src/game/diplomacyEffects';
import { allEventDefinitions, calculateEventChance, generateWorldEvents, resolvePendingEvent } from './legacyEvents';
import { refreshCountryAggregates, ownedRegions } from '../src/game/runtime';
import { createSeededRandom } from '../src/game/random';
import type { DiplomaticAction, GameState } from '../src/game/types';
const opts={economyRandom:()=>.5,mortalityRandom:()=>.99,electionRandom:()=>0,eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,secessionRandom:()=>.5,conflictRandom:()=>.5};
const rel=(g:GameState,a='sparrow',b='pigeon')=>getBilateralRelation(g.world,a,b)!;
function reset(g:GameState){g=structuredClone(g);for(const r of Object.values(g.world.diplomacy!.relations)){r.lastActionTurnA=null;r.lastActionTurnB=null;}return g;}
function act(g:GameState,action:DiplomaticAction,target='pigeon',actor='sparrow'){return performDiplomaticAction(g,actor,target,action);}
function rich(){const g=createGame('sparrow');Object.assign(rel(g),{relations:75,trust:80,threat:10,nonAggressionPact:true});return g;}
function independent(disputed=false){let g=createGame('pigeon','eagle-state');const r=g.world.regions['eagle-state'];Object.assign(r.speciesPolitics.eagle!,{satisfaction:10,autonomyDemand:90,independenceSentiment:90});r.governance.integration=20;Object.assign(r.secession!.eagle!,{phase:disputed?'unilateral_crisis':'transition',monthsInPhase:6,lastReferendumResult:{date:g.date,yesShare:80,passed:true},monthsActive:24,lastRefusalTurn:g.turn});return createBreakawayCountry(g,{kind:'region',id:r.id},'eagle',disputed);}
function validate(g:GameState){const ids=Object.keys(g.world.countries);assert.equal(Object.keys(g.world.diplomacy!.relations).length,ids.length*(ids.length-1)/2);for(const r of Object.values(g.world.diplomacy!.relations)){assert.ok(g.world.countries[r.countryA]&&g.world.countries[r.countryB]);assert.ok(r.countryA!==r.countryB);for(const n of [r.trust,r.threat,r.threatAtoB,r.threatBtoA,r.tradeLevel])assert.ok(Number.isFinite(n)&&n>=0&&n<=100);assert.ok(r.relations>=-100&&r.relations<=100);assert.ok(!r.defensePact||r.nonAggressionPact);}
  for(const r of [...Object.values(g.world.countries),...Object.values(g.world.regions)]){assert.ok(Number.isFinite(r.economy.gdp));assert.ok(Math.abs(r.economy.gdp-Object.values(r.economy.industries).reduce((s,i)=>s+i.output,0))<1e-6*Math.max(1,r.economy.gdp));assert.equal(r.population.total,Object.values(r.population.species).reduce((s,p)=>s+p.population,0));}}
function freeze<T>(x:T):T{if(x&&typeof x==='object'){Object.freeze(x);Object.values(x).forEach(freeze);}return x;}
test('초기 두 국가 한 pair',()=>{const g=createGame('sparrow');assert.equal(Object.keys(g.world.diplomacy!.relations).length,1);validate(g);});
for(const [key,value] of [['relations',20],['trust',45],['threat',25],['tradeLevel',35]] as const)test('초기 '+key,()=>assert.equal(rel(createGame('sparrow'))[key],value));
test('시작 mutual recognition',()=>{const r=rel(createGame('sparrow'));assert.ok(r.recognizedAbyB&&r.recognizedBbyA);});
test('pair 역순 동일',()=>assert.equal(getDiplomaticPairKey('sparrow','pigeon'),getDiplomaticPairKey('pigeon','sparrow')));
test('pair 자기/빈 국가 금지',()=>{assert.throws(()=>getDiplomaticPairKey('a','a'));assert.throws(()=>getDiplomaticPairKey('','a'));});
test('동적 ID 및 구분자 충돌 방지',()=>{assert.equal(getDiplomaticPairKey('eagle-republic-1','pigeon'),getDiplomaticPairKey('pigeon','eagle-republic-1'));assert.notEqual(getDiplomaticPairKey('a|b','c'),getDiplomaticPairKey('a','b|c'));});
test('생성국은 모든 국가와 즉시 관계 생성',()=>{const g=independent();assert.equal(Object.keys(g.world.diplomacy!.relations).length,3);validate(g);});
test('합법독립 부모 우호·신뢰·승인',()=>{const r=rel(independent(),'pigeon','eagle-republic-1');assert.equal(r.relations,20);assert.equal(r.trust,40);assert.ok(isRecognized(r,'pigeon'));});
test('established라도 제3국 자동 승인 아님',()=>assert.equal(isRecognized(rel(independent(),'sparrow','eagle-republic-1'),'sparrow'),false));
test('일방독립 부모 냉각·낮은 신뢰',()=>{const g=independent(true);assert.ok(rel(g,'pigeon','eagle-republic-1').relations<rel(g,'sparrow','eagle-republic-1').relations);assert.equal(rel(g,'pigeon','eagle-republic-1').trust,12);});
test('평화최종독립 부모관계-15·신뢰25',()=>{let g=independent(true);g=resolveConflictOutcome(g,'internal-1','independence_recognized');assert.equal(rel(g,'pigeon','eagle-republic-1').relations,-15);assert.equal(rel(g,'pigeon','eagle-republic-1').trust,25);assert.ok(isRecognized(rel(g,'pigeon','eagle-republic-1'),'pigeon'));});
test('내전후 독립 부모관계-45·신뢰10',()=>{let g=independent(true);Object.assign(g.world.internalConflicts!['internal-1'],{breakawayDominanceMonths:3,breakawayWarSupport:70});g=resolveConflictOutcome(g,'internal-1','independence_defended');assert.equal(rel(g,'pigeon','eagle-republic-1').relations,-45);assert.equal(rel(g,'pigeon','eagle-republic-1').trust,10);});
test('삭제국 외교 pair 제거·history 이름 보존',()=>{let g=independent(true);g=act(g,'recognize','eagle-republic-1');g=applyConflictAction(g,'internal-1','negotiate');g=resolveConflictOutcome(g,'internal-1','negotiated_reintegration');assert.equal(Object.keys(g.world.diplomacy!.relations).length,1);assert.ok(g.world.diplomacy!.history.some(h=>h.targetName==='독수리공화국'));assert.equal(g.world.diplomacy!.history[0].relationSnapshots!.length,2);validate(g);});
test('사절단 비용 국고 감소',()=>{const g=createGame('sparrow'),n=act(g,'improve');assert.ok(n.world.countries.sparrow.fiscal.treasury<g.world.countries.sparrow.fiscal.treasury);});
test('관계개선 관계+6·신뢰+1 별도',()=>{const n=act(createGame('sparrow'),'improve');assert.equal(rel(n).relations,26);assert.equal(rel(n).trust,46);});
test('외교 cooldown3·연타 차단·3개월후 허용',()=>{let g=act(createGame('sparrow'),'improve');assert.equal(getDiplomaticCooldown(rel(g),'sparrow',g.turn),3);assert.throws(()=>act(g,'trade'));for(let i=0;i<3;i++)g=advanceMonth(g,opts);assert.equal(getDiplomaticCooldown(rel(g),'sparrow',g.turn),0);assert.equal(getDiplomaticActionBlock(g,'sparrow','pigeon','trade'),null);});
test('방향별 cooldown',()=>{const g=act(createGame('sparrow'),'improve');assert.equal(getDiplomaticCooldown(rel(g),'pigeon',g.turn),0);});
test('action 입력 불변',()=>{const g=freeze(createGame('sparrow')),before=structuredClone(g);act(g,'improve');assert.deepEqual(g,before);});
test('국고부족 비용 거절',()=>{const g=createGame('sparrow');g.world.countries.sparrow.fiscal.treasury=0;assert.throws(()=>act(g,'improve'));});
test('불가침 조건 관계20 신뢰35',()=>{const g=createGame('sparrow');rel(g).trust=34;assert.throws(()=>act(g,'non_aggression'));rel(g).trust=45;rel(g).relations=19;assert.throws(()=>act(g,'non_aggression'));});
test('불가침 성립 및 관계/신뢰',()=>{const g=act(createGame('sparrow'),'non_aggression');assert.ok(rel(g).nonAggressionPact);assert.ok(rel(g).trust>45&&rel(g).relations>20);});
test('방위 더 엄격 및 불가침 필수',()=>{const g=createGame('sparrow');assert.throws(()=>act(g,'defense'));Object.assign(rel(g),{relations:75,trust:80});assert.throws(()=>act(g,'defense'));});
test('방위 성립·불가침 포함',()=>{const g=act(rich(),'defense');assert.ok(rel(g).defensePact&&rel(g).nonAggressionPact);});
for(const action of ['break_non_aggression','break_defense'] as const)test(action+' 신뢰하락·위협 충격',()=>{let g=rich();if(action==='break_defense')g=reset(act(g,'defense'));g=act(g,action);assert.ok(rel(g).trust<80);assert.equal(rel(g).threatShockMonths,12);});
test('수락점수 결정론적·제재/분쟁 거절',()=>{const g=createGame('sparrow'),r=rel(g);assert.equal(calculateDiplomaticAcceptance(g.world,'sparrow','pigeon',r),calculateDiplomaticAcceptance(g.world,'sparrow','pigeon',r));r.sanctionsAtoB=true;assert.ok(calculateDiplomaticAcceptance(g.world,'sparrow','pigeon',r)<40);});
test('조건통과해도 상대가 거절할 수 있음',()=>{const g=createGame('sparrow');Object.assign(rel(g),{relations:20,trust:35,threat:100});const n=act(g,'non_aggression');assert.equal(rel(n).nonAggressionPact,false);assert.equal(n.world.diplomacy!.history[0].accepted,false);assert.equal(getDiplomaticCooldown(rel(n),'sparrow',n.turn),3);});
test('미승인 신생국 승인',()=>{const n=act(independent(),'recognize','eagle-republic-1');assert.ok(isRecognized(rel(n,'sparrow','eagle-republic-1'),'sparrow'));assert.equal(rel(n,'sparrow','eagle-republic-1').relations,15);});
test('제3국 disputed 승인·부모항의·분쟁유지',()=>{const g=independent(true),before=rel(g).relations,n=act(g,'recognize','eagle-republic-1');assert.ok(rel(n).relations<before);assert.equal(n.world.internalConflicts!['internal-1'].status,'political_standoff');assert.equal(n.world.countries['eagle-republic-1'].identity!.status,'disputed_breakaway');});
test('승인 철회·신뢰 급락·무역충격',()=>{let g=reset(act(independent(),'recognize','eagle-republic-1'));const trust=rel(g,'sparrow','eagle-republic-1').trust;g=act(g,'withdraw_recognition','eagle-republic-1');assert.equal(isRecognized(rel(g,'sparrow','eagle-republic-1'),'sparrow'),false);assert.equal(rel(g,'sparrow','eagle-republic-1').trust,trust-20);assert.equal(rel(g,'sparrow','eagle-republic-1').disruptionMonths,6);});
test('기존국 승인변경 금지',()=>assert.throws(()=>act(createGame('sparrow'),'withdraw_recognition')));
test('제재 방향성·관계 신뢰 무역 하락',()=>{const n=act(createGame('sparrow'),'sanction');assert.ok(isSanctioning(rel(n),'sparrow'));assert.equal(isSanctioning(rel(n),'pigeon'),false);assert.equal(rel(n).relations,0);assert.equal(rel(n).trust,33);assert.equal(rel(n).tradeLevel,21);});
test('제재해제 방향성 및 미부과 금지',()=>{let g=reset(act(createGame('sparrow'),'sanction'));assert.throws(()=>act(g,'lift_sanctions','sparrow','pigeon'));g=act(g,'lift_sanctions');assert.equal(isSanctioning(rel(g),'sparrow'),false);});
test('제재중 무역협정 불가',()=>assert.throws(()=>act(reset(act(createGame('sparrow'),'sanction')),'trade')));
test('무역협정 trade+15 및 반복최대100',()=>{let g=act(createGame('sparrow'),'trade');assert.equal(rel(g).tradeLevel,50);for(let i=0;i<4;i++)g=act(reset(g),'trade');assert.equal(rel(g).tradeLevel,100);assert.throws(()=>act(reset(g),'trade'));});
test('높은무역 작은 긍정 modifier·총합 제한',()=>{const g=createGame('sparrow');rel(g).tradeLevel=100;const m=getDiplomaticTradeModifiers(g.world,'sparrow');assert.ok(m.manufacturing!.annualGrowthAdjustment!>0&&m.manufacturing!.annualGrowthAdjustment!<=.006);assert.equal(m.defense,undefined);});
test('시작 무역은 경제프로필에 반영·기존431 경로보존',()=>assert.equal(getDiplomaticTradeModifiers(createGame('sparrow').world,'sparrow').services!.annualGrowthAdjustment,0));
test('제재 targetmodifier 부담·제재국도손실',()=>{const g=act(createGame('sparrow'),'sanction'),a=getDiplomaticTradeModifiers(g.world,'sparrow').services!.annualGrowthAdjustment!,b=getDiplomaticTradeModifiers(g.world,'pigeon').services!.annualGrowthAdjustment!;assert.ok(a<0&&b<a);});
test('무역+제재 월 GDP합계·연방 소유 region 적용',()=>{const g=createGame('sparrow');rel(g).tradeLevel=100;const base=advanceMonth(createGame('sparrow'),opts),n=advanceMonth(g,opts);assert.ok(n.world.countries.sparrow.economy.gdp>base.world.countries.sparrow.economy.gdp);for(const id of Object.keys(n.world.regions))assert.ok(n.world.regions[id].economy.gdp>base.world.regions[id].economy.gdp);validate(n);});
test('신생국 trade modifier 현재 소유region 적용',()=>{let g=act(independent(),'recognize','eagle-republic-1');g=act(reset(g),'improve','eagle-republic-1');g=act(reset(g),'trade','eagle-republic-1');const n=advanceMonth(g,opts);assert.ok(getDiplomaticTradeModifiers(g.world,'eagle-republic-1').services!.annualGrowthAdjustment!>0);assert.equal(ownedRegions(n.world,'eagle-republic-1')[0].id,'eagle-state');validate(n);});
test('위협 상대 GDP 증가',()=>{const g=createGame('sparrow'),r=rel(g),base=calculateDiplomaticThreat(g.world,'pigeon','sparrow',r);g.world.countries.sparrow.economy.gdp*=3;assert.ok(calculateDiplomaticThreat(g.world,'pigeon','sparrow',r)>base);});
test('우호관계 위협 감소',()=>{const g=createGame('sparrow'),r=rel(g);assert.ok(calculateDiplomaticThreat(g.world,'sparrow','pigeon',{...r,relations:80})<calculateDiplomaticThreat(g.world,'sparrow','pigeon',{...r,relations:-80}));});
test('영토분쟁 위협 상승 및 방향수치',()=>{const g=independent(true),r=rel(g,'pigeon','eagle-republic-1'),a=calculateDiplomaticThreat(g.world,'pigeon','eagle-republic-1',r);g.world.internalConflicts={};assert.ok(a>calculateDiplomaticThreat(g.world,'pigeon','eagle-republic-1',r));});
test('전 수치 clamp·관계범주 소수 경계',()=>{const g=createGame('sparrow');Object.assign(rel(g),{relations:-100,trust:0,tradeLevel:0,sanctionsAtoB:true});const n={...g,world:updateWorldDiplomacy(g.world)};validate(n);assert.equal(relationCategory(-9.5),'중립');assert.equal(relationCategory(-10),'냉각');assert.equal(threatCategory(39.9),'제한적');});
test('매월 우호기본 고정·조약 신뢰 매우느림',()=>{let g=createGame('sparrow');g={...g,world:updateWorldDiplomacy(g.world)};assert.equal(rel(g).relations,20);assert.equal(rel(g).trust,45);g=act(g,'non_aggression');const trust=rel(g).trust;g={...g,world:updateWorldDiplomacy(g.world)};assert.equal(rel(g).trust,trust+.03);});
test('철새이동 조약 관계·migration 실제 반영',()=>{const g=act(createGame('sparrow'),'passage'),n=advanceMonth(g,opts),base=advanceMonth(createGame('sparrow'),opts);assert.ok(rel(g).migratoryPassageAgreement);assert.ok(getPassageMigrationAdjustment(g.world,'sparrow')>0);assert.ok(n.world.countries.sparrow.population.netMigrationLastMonth>base.world.countries.sparrow.population.netMigrationLastMonth);});
test('철새피난·둥지터 부정효과 협정25%완화',()=>{const g=createGame('sparrow');const pending={id:'refuge',eventId:'migrant-refuge',date:g.date,turn:g.turn,jurisdiction:{kind:'country' as const,id:'sparrow'},severity:3 as const};g.events.pendingEvent=pending;const base=resolvePendingEvent(g,'restrict',()=>.5);let protectedGame=act({...g,events:{...g.events,pendingEvent:null}},'passage');protectedGame.events.pendingEvent=pending;const n=resolvePendingEvent(protectedGame,'restrict',()=>.5);assert.ok(n.world.countries.sparrow.social!.livingStandard>base.world.countries.sparrow.social!.livingStandard);});
test('부모지지 분쟁소유권·통제 변경없음',()=>{let g=independent(true);const c=structuredClone(g.world.internalConflicts);g=act(g,'support_parent');assert.deepEqual(g.world.internalConflicts,c);assert.ok(rel(g).relations>20);});
test('NPC 전체AI/외교RNG 없음·전쟁 자동생성 금지',()=>{let g=createGame('sparrow');rel(g).relations=-100;for(let i=0;i<12;i++)g=advanceMonth(g,opts);assert.deepEqual(g.world.internalConflicts,{});assert.equal(g.world.diplomacy!.history.length,0);});
test('독수리 승인→개선→무역→불가침 E2E·경력 보존',()=>{let g=independent();const career=structuredClone(g.player.career);for(const action of ['recognize','improve','trade','non_aggression'] as const)g=act(reset(g),action,'eagle-republic-1');const r=rel(g,'sparrow','eagle-republic-1');assert.ok(r.nonAggressionPact);assert.ok(r.tradeLevel>=20);assert.deepEqual(g.player.career,career);validate(g);});
test('우호→위기→제재→양국손실→해제 E2E',()=>{let g=rich();rel(g).tradeLevel=85;const before=advanceMonth(g,opts);g=act(g,'sanction');const n=advanceMonth(g,opts);assert.ok(n.world.countries.sparrow.economy.gdp<before.world.countries.sparrow.economy.gdp);assert.ok(n.world.countries.pigeon.economy.gdp<before.world.countries.pigeon.economy.gdp);g=act(reset(n),'lift_sanctions');assert.equal(isSanctioning(rel(g),'sparrow'),false);validate(g);});
test('600개월 외교·세계 유한·경제 합계·누락0',()=>{let g=createGame('sparrow');const streams={...opts,economyRandom:createSeededRandom(2030),eventOccurrenceRandom:createSeededRandom(5544),eventOutcomeRandom:createSeededRandom(9966)};for(let i=0;i<600;i++){g=advanceMonth(g,streams);if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',streams.eventOutcomeRandom);validate(g);}assert.equal(Object.keys(g.world.countries).length,2);console.log('DIPLOMACY600',JSON.stringify({gdp:g.world.countries.sparrow.economy.gdp,pairs:Object.keys(g.world.diplomacy!.relations).length,relations:rel(g).relations,trust:rel(g).trust}));});
test('월 외교 갱신 입력 불변·동기화 역사 보존',()=>{const g=freeze(independent(true)),before=structuredClone(g.world);updateWorldDiplomacy(g.world);synchronizeDiplomacy(g.world);assert.deepEqual(g.world,before);});
test('12개 외교사건 및 보복/승인 후보',()=>{const definitions=allEventDefinitions.filter(e=>e.diplomacyEvent);assert.equal(definitions.length,12);const g=independent(true);assert.ok(calculateEventChance('diplomacy-recognition',g,{kind:'country',id:'sparrow'})>0);assert.equal(calculateEventChance('diplomacy-retaliation',g,{kind:'country',id:'sparrow'}),0);const n=act(g,'sanction');assert.ok(calculateEventChance('diplomacy-retaliation',reset(n),{kind:'country',id:'sparrow'})>0);for(const e of definitions){assert.equal(e.choices.length,3);assert.ok(e.description.length>30);}});
for(const stream of ['mortalityRandom','electionRandom','economyRandom','eventOccurrenceRandom','eventOutcomeRandom','secessionRandom','conflictRandom'] as const)test('외교행동 '+stream+' 스트림 소비 없음',()=>{const g=createGame('sparrow');const calls={count:0};const n=act(g,'improve');advanceMonth(n,{...opts,[stream]:()=>{calls.count++;return stream==='mortalityRandom'?.99:stream==='eventOccurrenceRandom'?.999999:.5;}});assert.equal(calls.count,stream==='mortalityRandom'?1:stream==='economyRandom'?30:stream==='eventOccurrenceRandom'?5:0);});

for(const e of allEventDefinitions.filter(e=>e.diplomacyEvent))test(e.id+' 실제 세 선택·기록·세계안전',()=>{for(const choice of ['invest','balance','restrict']){let g=rich(),target='pigeon';if(e.id==='diplomacy-recognition'){g=independent(true);target='eagle-republic-1';}if(e.id==='diplomacy-protest'){g=reset(act(independent(true),'recognize','eagle-republic-1'));}if(e.id==='diplomacy-retaliation')g=reset(act(createGame('sparrow'),'sanction'));if(e.id==='diplomacy-control')rel(g).nonAggressionPact=false;if(e.id==='diplomacy-trade-dispute')rel(g).relations=0;const j={kind:'country' as const,id:'sparrow'};assert.ok(calculateEventChance(e.id,g,j)>0);g.events.pendingEvent={id:'verify-'+e.id,eventId:e.id,date:g.date,turn:g.turn,jurisdiction:j,severity:2,diplomaticTargetId:target,jurisdictionName:'참새자유공화국'};g=resolvePendingEvent(g,choice,()=>.5);assert.equal(g.events.pendingEvent,null);assert.ok(g.events.history.some(h=>h.eventId===e.id&&h.choiceId===choice));validate(g);}});
test('분쟁 NPC 종결 후 이미 삭제된 외교 대상 미결사건을 제시하지 않음',()=>{let g=independent(true);g.player.controlledCountryId='sparrow';g.player.controlledRegionId=null;Object.assign(g.world.internalConflicts!['internal-1'],{parentDominanceMonths:3,territorialControl:5});g=generateWorldEvents(g,{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>.5});assert.equal(g.world.countries['eagle-republic-1'],undefined);assert.ok(!g.events.pendingEvent?.diplomaticTargetId||!!g.world.countries[g.events.pendingEvent.diplomaticTargetId]);validate(g);});
test('600개월 신생국 포함 모든 pair 누락없이·고정전력 유지',()=>{let g=independent();for(let i=0;i<600;i++){g=advanceMonth(g,opts);if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',()=>.5);validate(g);}assert.equal(Object.keys(g.world.diplomacy!.relations).length,3);assert.equal(Object.keys(g.world.countries).length,3);});
