import assert from 'node:assert/strict';
import {test} from 'node:test';
import {advanceMonth,createGame} from './legacyEngine';
import {calculateEventChance,chooseWeightedEvent,eventContext,generateWorldEvents,getEventDefinition,resolvePendingEvent,tickEventState} from './legacyEvents';
import {applyEventEffects} from '../src/game/eventEffects';
import {eventDefinitions} from '../src/game/eventDefinitions';
import {cooldownKey,hasRecentEvent,isMigrationSeason} from '../src/game/eventHelpers';
import {createSeededRandom} from '../src/game/random';
import {setControlledTaxPolicy} from '../src/game/taxPolicy';
import {setControlledBudgetPolicy} from '../src/game/budgetPolicy';
import type {EventEffect,GameState,Jurisdiction} from '../src/game/types';
const sparrow:Jurisdiction={kind:'country',id:'sparrow'},eagle:Jurisdiction={kind:'region',id:'eagle-state'};
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function freeze<T>(v:T):T{if(v&&typeof v==='object'){Object.freeze(v);Object.values(v).forEach(freeze);}return v;}
function pending(id='migrant-refuge',j:Jurisdiction=sparrow){const g=j.kind==='country'?createGame('sparrow'):createGame('pigeon',j.id);g.events.pendingEvent={id:`1:${j.id}:${id}`,eventId:id,date:{...g.date},turn:g.turn,jurisdiction:j,severity:2};return g;}
function history(g:GameState,id:string,j=sparrow,ago=0){const definition=getEventDefinition(id);g.events.history.unshift({id:`past:${id}`,eventId:id,date:{...g.date},turn:g.turn-ago,jurisdiction:j,severity:1,title:definition.title,category:definition.category,choiceId:'balance',choiceLabel:'기본 대응',playerChoice:true});}
function verify(g:GameState){
  for(const r of [...Object.values(g.world.countries),...Object.values(g.world.regions)]){
    near(r.economy.gdp,Object.values(r.economy.industries).reduce((s,i)=>s+i.output,0));assert.ok(Number.isFinite(r.economy.gdp)&&r.economy.gdp>=0);assert.ok(Number.isFinite(r.fiscal.treasury)&&r.fiscal.treasury>=0);assert.ok(Number.isFinite(r.fiscal.debt)&&r.fiscal.debt>=0);
    assert.equal(r.population.total,Object.values(r.population.species).reduce((s,p)=>s+p.population,0));for(const p of Object.values(r.population.species))assert.ok(Number.isSafeInteger(p.population)&&p.population>=0);
    for(const state of [r.social,r.governance])if(state)for(const [key,value]of Object.entries(state))if(!key.includes('Delta'))assert.ok(Number.isFinite(value)&&value>=0&&value<=100);
    for(const p of Object.values(r.speciesPolitics??{}))for(const key of ['satisfaction','autonomyDemand','independenceSentiment'] as const)assert.ok(Number.isFinite(p[key])&&p[key]>=0&&p[key]<=100);
  }
  near(g.world.countries.pigeon.economy.gdp,Object.values(g.world.regions).reduce((s,r)=>s+r.economy.gdp,0));assert.equal(g.world.countries.pigeon.population.total,Object.values(g.world.regions).reduce((s,r)=>s+r.population.total,0));
}
test('초기EventState는null/빈배열/빈쿨다운·게임간독립',()=>{const a=createGame('sparrow'),b=createGame('sparrow');assert.deepEqual(a.events,{pendingEvent:null,cooldowns:{},activeEffects:[],history:[]});assert.notEqual(a.events,b.events);});
test('29개실제사건·모든카테고리·3선택·기본대응·긍정/혼합1/3이상',()=>{assert.equal(eventDefinitions.length,29);assert.equal(new Set(eventDefinitions.map(e=>e.id)).size,29);assert.equal(new Set(eventDefinitions.map(e=>e.category)).size,7);assert.ok(eventDefinitions.filter(e=>e.tone!=='negative').length>=Math.ceil(29/3));for(const e of eventDefinitions){assert.equal(e.choices.length,3);assert.ok(e.choices.some(c=>c.id===e.nonPlayerChoiceId));assert.ok(e.description.length>25&&e.cooldownMonths>=12);}});
for(const e of eventDefinitions)test(`${e.title}:모든선택실효과·기록/로그/쿨다운·입력불변`,()=>{
  const j=['crow-petition','sparrow-protest'].includes(e.id)?sparrow:eagle;
  for(const choice of e.choices){const g=freeze(pending(e.id,j)),before=structuredClone(g);const n=resolvePendingEvent(g,choice.id,()=>.5);assert.notDeepEqual(n.world,g.world);assert.deepEqual(g,before);assert.equal(n.events.pendingEvent,null);assert.equal(n.events.history[0].choiceId,choice.id);assert.equal(n.events.history[0].title,e.title);assert.equal(n.events.cooldowns[cooldownKey(j,e.id)],e.cooldownMonths);assert.equal(n.logs.filter(l=>l.category==='event').length,1);verify(n);}
});
test('철새 이동기3~5/9~11 확률상승·좋은생활/낮은실업/외부위기 반영',()=>{const g=createGame('sparrow');g.date.month=1;const winter=calculateEventChance('migrant-refuge',g,sparrow);g.date.month=3;assert.ok(calculateEventChance('migrant-refuge',g,sparrow)>winter);g.date.month=1;g.world.countries.sparrow.social!.livingStandard=90;assert.ok(calculateEventChance('migrant-refuge',g,sparrow)>winter);g.world.regions['eagle-state'].governance.stability=10;assert.ok(calculateEventChance('migrant-refuge',g,sparrow)>winter);assert.equal(isMigrationSeason(12),false);});
test('낮은통합/높은불평등 종족갈등 확률상승',()=>{const g=createGame('sparrow'),base=calculateEventChance('nest-conflict',g,sparrow);g.world.countries.sparrow.governance!.integration=20;g.world.countries.sparrow.social!.inequality=80;assert.ok(calculateEventChance('nest-conflict',g,sparrow)>base);});
test('독수리위기 집회/갈등 확률 명확히상승·독립80도 국가생성없음',()=>{const g=createGame('pigeon','eagle-state'),r=g.world.regions[eagle.id],normal=calculateEventChance('eagle-assembly',g,eagle);Object.assign(r.speciesPolitics.eagle!,{satisfaction:10,autonomyDemand:80,independenceSentiment:80});r.governance.integration=20;const crisis=calculateEventChance('eagle-assembly',g,eagle);assert.ok(crisis>normal*3);assert.ok(crisis<=.4);const n=resolvePendingEvent({...g,events:{...g.events,pendingEvent:{id:'crisis',eventId:'eagle-assembly',date:g.date,turn:1,jurisdiction:eagle,severity:3}}},'restrict',()=>.5);assert.deepEqual(Object.keys(n.world.countries),Object.keys(g.world.countries));console.log('EVENT CRISIS',JSON.stringify({assemblyNormal:normal,assemblyCrisis:crisis,conflictCrisis:calculateEventChance('nest-conflict',g,eagle)}));});
test('낮은보건 진드기 확률/강도상승·인프라 삭감 재난강도상승',()=>{const g=createGame('sparrow'),r=g.world.countries.sparrow,normal=calculateEventChance('feather-mites',g,sparrow);r.social!.healthcare=10;assert.ok(calculateEventChance('feather-mites',g,sparrow)>normal);r.social!.publicSafety=80;const mild=getEventDefinition('storm').severity(eventContext(g,sparrow));r.fiscal.budgetPolicy.infrastructure=0;assert.ok(getEventDefinition('storm').severity(eventContext(g,sparrow))>mild);});
test('농업비중 오리주 풍작확률 우위·안정국가 축제/번식긍정후보',()=>{const g=createGame('sparrow');assert.ok(calculateEventChance('grain-harvest',g,{kind:'region',id:'duck-state'})>calculateEventChance('grain-harvest',g,eagle));assert.ok(calculateEventChance('flight-festival',g,sparrow)>0);assert.ok(calculateEventChance('successful-nesting',g,sparrow)>0);});
test('쿨다운지역별확률0·감소·0제거·다른지역무관',()=>{const g=createGame('sparrow');g.events.cooldowns[cooldownKey(sparrow,'storm')]=2;assert.equal(calculateEventChance('storm',g,sparrow),0);assert.ok(calculateEventChance('storm',g,eagle)>0);const a=tickEventState(g);assert.equal(a.events.cooldowns[cooldownKey(sparrow,'storm')],1);const b=tickEventState(a);assert.equal(b.events.cooldowns[cooldownKey(sparrow,'storm')],undefined);assert.ok(calculateEventChance('storm',b,sparrow)>0);});
test('최대개별.4·발생합계.75·빈후보 난수0·입력순서 독립가중선택',()=>{const defs=eventDefinitions.slice(0,3),candidates=defs.map((definition,i)=>({definition,chance:.1*(i+1)}));const rng=()=>{let i=0;return()=>[0,.7][i++]};assert.equal(chooseWeightedEvent(candidates,rng())!.id,chooseWeightedEvent([...candidates].reverse(),rng())!.id);assert.equal(chooseWeightedEvent([],()=>{throw new Error('빈후보 RNG');}),null);assert.equal(chooseWeightedEvent(candidates,()=>.99),null);});
test('pending 생성월1건·실제선택만outcome소비·다음달RNG/정책차단',()=>{const g=createGame('sparrow');let calls=0;const n=generateWorldEvents(g,{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>{calls++;return .5}});assert.ok(n.events.pendingEvent);assert.equal(n.events.history.filter(e=>e.playerChoice).length,0);assert.equal(calls,4);const fail=()=>{throw new Error('pending 월계산');};assert.equal(advanceMonth(n,{economyRandom:fail,eventOccurrenceRandom:fail,mortalityRandom:fail}),n);assert.throws(()=>setControlledTaxPolicy(n,n.world.countries.sparrow.fiscal.taxPolicy));assert.throws(()=>setControlledBudgetPolicy(n,n.world.countries.sparrow.fiscal.budgetPolicy));assert.throws(()=>resolvePendingEvent(n,'bad',fail));const resolved=resolvePendingEvent(n,'balance',()=>.5);assert.equal(resolved.events.pendingEvent,null);assert.equal(resolved.events.history.filter(e=>e.playerChoice).length,1);assert.throws(()=>resolvePendingEvent(resolved,'balance'));});
test('NPC 자동기본선택만·플레이어선택불변·모든지역사건가능',()=>{for(const mode of ['sparrow','eagle']){const g=mode==='sparrow'?createGame('sparrow'):createGame('pigeon','eagle-state');const n=generateWorldEvents(g,{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>.5});assert.equal(n.events.history.length,4);assert.ok(n.events.history.every(e=>e.choiceId===getEventDefinition(e.eventId).nonPlayerChoiceId&&!e.playerChoice));assert.ok(n.events.pendingEvent);verify(n);}});
test('선택효과는지역한곳·연방경제/인구만갱신·GDP/인구합계정확',()=>{const g=createGame('sparrow'),before=structuredClone(g);const effects:EventEffect[]=[{kind:'treasury',amount:-3},{kind:'industry',industryId:'services',multiplier:.8},{kind:'population',speciesId:'eagle',ratio:.01,flow:'migration'}];const n=applyEventEffects(g,eagle,effects);near(n.world.regions[eagle.id].fiscal.treasury,g.world.regions[eagle.id].fiscal.treasury-3);assert.deepEqual(g,before);assert.deepEqual(n.world.countries.sparrow,g.world.countries.sparrow);assert.deepEqual(n.world.regions['owl-state'],g.world.regions['owl-state']);assert.deepEqual(n.world.countries.pigeon.fiscal,g.world.countries.pigeon.fiscal);verify(n);});
test('국고부족은부채충당·사회/정치clamp·없는종족생성없음',()=>{const g=createGame('sparrow');const n=applyEventEffects(g,sparrow,[{kind:'treasury',amount:-g.world.countries.sparrow.fiscal.treasury-10},{kind:'social',metric:'healthcare',delta:1000},{kind:'governance',metric:'integration',delta:-1000},{kind:'species',speciesId:'crow',metric:'satisfaction',delta:-1000},{kind:'population',speciesId:'duck',ratio:1,flow:'migration'}]);assert.equal(n.world.countries.sparrow.fiscal.treasury,0);near(n.world.countries.sparrow.fiscal.debt,g.world.countries.sparrow.fiscal.debt+10);assert.equal(n.world.countries.sparrow.social!.healthcare,100);assert.equal(n.world.countries.sparrow.governance!.integration,0);assert.equal(n.world.countries.sparrow.speciesPolitics!.crow!.satisfaction,0);assert.equal(n.world.countries.sparrow.population.species.duck,undefined);verify(n);});
test('population효과출생/사망/이동기록정확·과도유출음수방지',()=>{const g=createGame('sparrow'),p=g.world.countries.sparrow.population.species.sparrow!;const n=applyEventEffects(g,sparrow,[{kind:'population',speciesId:'sparrow',ratio:.01,flow:'death'}]);assert.equal(n.world.countries.sparrow.population.species.sparrow!.deathsLastMonth,Math.round(p.population*.01));const zero=applyEventEffects(g,sparrow,[{kind:'population',speciesId:'sparrow',ratio:-10,flow:'migration'}]);assert.equal(zero.world.countries.sparrow.population.species.sparrow!.population,0);verify(zero);});
test('종족충돌의다수/소수효과차이·playermortality어떤사건도변경없음',()=>{const g=pending('nest-conflict'),n=resolvePendingEvent(g,'balance',()=>.5);assert.notEqual(n.world.countries.sparrow.speciesPolitics!.sparrow!.satisfaction-g.world.countries.sparrow.speciesPolitics!.sparrow!.satisfaction,n.world.countries.sparrow.speciesPolitics!.crow!.satisfaction-g.world.countries.sparrow.speciesPolitics!.crow!.satisfaction);assert.deepEqual(n.player,g.player);});
test('지속효과선택즉시산업에미적용·다음달시작·정확3회/제거',()=>{const g=pending('flight-corridor'),n=resolvePendingEvent(g,'restrict',()=>.5);near(n.world.countries.sparrow.economy.gdp,g.world.countries.sparrow.economy.gdp);assert.equal(n.events.activeEffects[0].remainingMonths,3);let next=n;const initial=next.world.countries.sparrow.economy.industries.services.output,multiplier=(next.events.activeEffects[0].effects[0] as Extract<EventEffect,{kind:'industry'}>).multiplier;for(let i=0;i<3;i++){next=tickEventState(next);near(next.world.countries.sparrow.economy.industries.services.output,initial*Math.pow(multiplier,i+1));}assert.equal(next.events.activeEffects.length,0);assert.deepEqual(tickEventState(next).world,next.world);});
test('동결입력지속효과불변·월엔진에서날짜전처리·expired0추가적용없음',()=>{const g=resolvePendingEvent(pending('tailwind'),'balance',()=>.5);const n=tickEventState(freeze(g));assert.equal(g.events.activeEffects[0].remainingMonths,4);assert.equal(n.events.activeEffects[0].remainingMonths,3);const expired=structuredClone(g);expired.events.activeEffects[0].remainingMonths=0;assert.deepEqual(tickEventState(expired).world,expired.world);});
for(const [parent,child,j] of [['migrant-refuge','nest-overcrowding',sparrow],['nest-overcrowding','nest-conflict',sparrow],['storm','nest-cliff',sparrow],['nest-cliff','temporary-flock',sparrow],['seed-disease','food-prices',sparrow],['food-prices','sparrow-protest',sparrow],['eagle-petition','eagle-assembly',eagle],['eagle-assembly','federal-autonomy',eagle],['wetland-drought','duck-protest',eagle],['storm','mixed-rescue',sparrow]] as const)test(`${parent}→${child}실제체인/12개월만료/지역격리`,()=>{const g=j.kind==='region'?createGame('pigeon',j.id):createGame('sparrow'),base=calculateEventChance(child,g,j);history(g,parent,j);assert.ok(calculateEventChance(child,g,j)>base);g.turn+=13;assert.equal(hasRecentEvent(g,j,parent,12),false);near(calculateEventChance(child,g,j),base);});
test('발생/결과스트림고정재현·소비는경제/선거/사망과독립',()=>{const g=createGame('sparrow');const opts=()=>({economyRandom:createSeededRandom(20),electionRandom:()=>0,mortalityRandom:()=>.99,eventOccurrenceRandom:createSeededRandom(50),eventOutcomeRandom:createSeededRandom(70)});assert.deepEqual(advanceMonth(g,opts()),advanceMonth(g,opts()));const a=advanceMonth(g,{...opts(),eventOccurrenceRandom:()=>.999}),b=advanceMonth(g,{...opts(),eventOccurrenceRandom:()=>.999,eventOutcomeRandom:()=>0});assert.deepEqual(a,b);let e=0,d=0;const c=advanceMonth(g,{...opts(),economyRandom:()=>{e++;return .5},mortalityRandom:()=>{d++;return .99},eventOccurrenceRandom:()=>0});assert.equal(e,30);assert.equal(d,1);assert.ok(c.events.pendingEvent);});
test('결과난수만변경시효과규모차이·위험개인사망/생존불변',()=>{const g=pending('storm'),a=resolvePendingEvent(g,'balance',()=>0),b=resolvePendingEvent(g,'balance',()=>.99);assert.notDeepEqual(a.world,b.world);assert.deepEqual(a.player,b.player);});
test('선거패배/사망월신규이벤트없음·종료후resolve금지',()=>{for(const death of [true,false]){const g=createGame('sparrow');if(!death)g.player.career.monthsInCurrentTerm=47;const fail=()=>{throw new Error('종료월 사건RNG');};const n=advanceMonth(g,{economyRandom:()=>.5,electionRandom:()=>.999,mortalityRandom:()=>0,mortalityRiskOverride:1,eventOccurrenceRandom:fail,eventOutcomeRandom:fail});assert.equal(n.gameOverReason,death?'death':'election_defeat');assert.equal(n.events.pendingEvent,null);assert.throws(()=>resolvePendingEvent(n,'balance'));}});
test('600개월기본정책전세계사건·빈도/쿨다운/유한/연방/무한루프',()=>{
  let g=createGame('sparrow');const economy=createSeededRandom(2030),occurrence=createSeededRandom(5544),outcome=createSeededRandom(9966);let player=0,positive=0;
  for(let i=0;i<600;i++){g=advanceMonth(g,{economyRandom:economy,electionRandom:()=>0,mortalityRandom:()=>.99,eventOccurrenceRandom:occurrence,eventOutcomeRandom:outcome});if(g.events.pendingEvent){player++;const e=getEventDefinition(g.events.pendingEvent.eventId);if(e.tone!=='negative')positive++;g=resolvePendingEvent(g,e.nonPlayerChoiceId,outcome);}verify(g);assert.equal(g.gameOverReason,null);assert.ok(g.events.activeEffects.every(e=>e.remainingMonths>0));}
  assert.ok(player>60&&player<250,`플레이어 사건${player}`);assert.ok(positive>10);for(const entry of g.events.history){const previous=g.events.history.filter(e=>e.id!==entry.id&&e.eventId===entry.eventId&&e.jurisdiction.id===entry.jurisdiction.id&&e.turn<entry.turn).sort((a,b)=>b.turn-a.turn)[0];if(previous)assert.ok(entry.turn-previous.turn>=getEventDefinition(entry.eventId).cooldownMonths);}
  console.log('EVENT NORMAL600',JSON.stringify({playerEvents:player,monthsPerEvent:600/player,positiveOrMixed:positive,worldEvents:g.events.history.length,activeEffects:g.events.activeEffects.length,gdp:g.world.countries.sparrow.economy.gdp,population:g.world.countries.sparrow.population.total}));
});

test('돌봄부족은출생증가·둥지충돌은종족불만/자치증가에반응',()=>{const g=createGame('sparrow'),r=g.world.countries.sparrow;const birth=calculateEventChance('chick-care',g,sparrow);r.population.birthsLastMonth=r.population.total*.004;assert.ok(calculateEventChance('chick-care',g,sparrow)>birth);const conflict=calculateEventChance('nest-conflict',g,sparrow);Object.assign(r.speciesPolitics.crow,{satisfaction:0,autonomyDemand:100});assert.ok(calculateEventChance('nest-conflict',g,sparrow)>conflict);});
