const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const mobile=!!process.env.BIRD_MOBILE,context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5175');
 await page.getByRole('button',{name:'튜토리얼 건너뛰기',exact:true}).click();await page.getByRole('button',{name:'공화국 운영 시작',exact:true}).click();
 const state=()=>page.evaluate(()=>window.birdKingdomDebug.getGameState());
 const nav=async name=>{const b=page.getByRole('button',{name:'메뉴 열기',exact:true});if(await b.isVisible())await b.click();await page.getByRole('navigation',{name:'정부 운영 메뉴'}).getByRole('button',{name,exact:true}).click();};
 const fixture=async kind=>{await page.evaluate(async kind=>{const {federalFixture}=await import('/tests/federalFixtures.ts');window.birdKingdomDebug.setGameState(federalFixture(kind));window.birdKingdomDebug.setMortalityRisk(0);window.birdKingdomDebug.setElectionRoll(0);window.birdKingdomDebug.setEventRoll(.999999);window.birdKingdomDebug.setCrisisRoll(.999999);window.birdKingdomDebug.setStrategicAIEnabled(false);},kind);await page.locator('.topbar').waitFor();};
 const region=()=>page.getByRole('region',{name:'연방정치',exact:true});
 const action=async label=>{await region().getByRole('button',{name:label,exact:true}).click();};
 const months=async count=>{for(let i=0;i<count;i++)await page.getByRole('button',{name:'다음 달',exact:true}).click();};
 await nav('정치');assert.equal(await region().count(),0);console.log('PASS centralized politics hides federal section');
 // Reckless declaration is a real UI command, not a domain call in evaluate.
 await fixture('weak');await action('일방 독립 선언');await page.getByRole('alertdialog',{name:'일방 독립 확인'}).waitFor();await page.getByRole('button',{name:'일방 독립 확정',exact:true}).click();let g=await state();assert.equal(g.world.countries['eagle-republic-1'].identity.status,'disputed_breakaway');assert.equal(g.world.countries['eagle-republic-1'].identity.territorialDispute,'parent_claims_reunification');assert.ok(g.world.regions['eagle-state'].governance.stability<30);assert.ok(Object.values(g.world.internalConflicts)[0].breakawayWarSupport<40);assert.equal(await region().count(),0);await nav('외교');console.log('PASS reckless independence, backlash, parent hardline, existing conflict and sovereign UI');
 await fixture('partial');await nav('정치');await page.getByRole('combobox',{name:'자치권 요구 수준'}).selectOption('substantial');let before=await state();await action('자치권 확대 요구');g=await state();assert.equal(g.world.federalPolitics['eagle-state'].history.at(-1).response,'partial_concession');assert.equal(g.world.regions['eagle-state'].secession.eagle.grantedAutonomy,before.world.regions['eagle-state'].secession.eagle.grantedAutonomy+7);assert.ok(g.world.regions['eagle-state'].speciesPolitics.eagle.autonomyDemand<before.world.regions['eagle-state'].speciesPolitics.eagle.autonomyDemand);await page.screenshot({path:'.test-output/federal-partial-'+(mobile?'mobile':'pc')+'.png'});console.log('PASS high backing partial concession and actual autonomy/demand change');
 await fixture('weak');await nav('정치');const electionBefore=await page.evaluate(async()=>{const {createElectionSnapshot}=await import('/src/game/election.ts');return createElectionSnapshot(window.birdKingdomDebug.getGameState()).reelectionChance;});
 for(let i=0;i<3;i++){await action('강경 대치 선언');if(i<2)await months(6);}
 const electionAfter=await page.evaluate(async()=>{const {createElectionSnapshot}=await import('/src/game/election.ts');return createElectionSnapshot(window.birdKingdomDebug.getGameState()).reelectionChance;});g=await state();console.log('ELECTION_BACKLASH_PROBE',electionBefore,electionAfter,g.world.regions['eagle-state'].governance);assert.ok(electionAfter<electionBefore);assert.ok(g.world.regions['eagle-state'].governance.approval<35);console.log('PASS repeated hardline actual monthly cadence and reelection decline',electionBefore,electionAfter);
 // Deterministic scenario: political support grows after rejected early demand.
 await fixture('weak');await nav('정치');await action('연방정책 공개 비판');await months(3);await page.getByRole('combobox',{name:'자치권 요구 수준'}).selectOption('maximum');await action('자치권 확대 요구');g=await state();assert.equal(g.world.federalPolitics['eagle-state'].history.at(-1).response,'hardline_rejection');assert.equal(await region().getByRole('button',{name:'주민투표 요구',exact:true}).isEnabled(),false);await months(3);
 await page.evaluate(async()=>{const {federalFixture}=await import('/tests/federalFixtures.ts');const {refreshCountryAggregates}=await import('/src/game/runtime.ts');const g=window.birdKingdomDebug.getGameState(),backed=federalFixture('strong');for(const id of Object.keys(g.world.regions)){g.world.regions[id].governance=backed.world.regions[id].governance;}g.world.regions['eagle-state'].speciesPolitics=backed.world.regions['eagle-state'].speciesPolitics;g.world.regions['eagle-state'].social=backed.world.regions['eagle-state'].social;g.world=refreshCountryAggregates(g.world);window.birdKingdomDebug.setGameState(g);});
 await action('주민투표 요구');g=await state();assert.equal(g.world.regions['eagle-state'].secession.eagle.phase,'referendum_scheduled');assert.equal(g.world.regions['eagle-state'].secession.eagle.referendumScheduledInMonths,6);
 // Roundtrip through actual manual save UI, then continue the ballot and transition.
 await page.getByRole('button',{name:'저장 / 불러오기',exact:true}).click();await page.locator('[data-slot="manual-1"]').getByRole('button',{name:'저장',exact:true}).click();if(await page.locator('.save-confirm').count())await page.locator('.save-confirm').getByRole('button',{name:'확인',exact:true}).click();await page.getByText('저장되었습니다.',{exact:true}).waitFor();await page.keyboard.press('Escape');await page.reload();await page.getByRole('button',{name:'이어하기',exact:true}).click();await page.locator('[data-slot="manual-1"]').getByRole('button',{name:'불러오기',exact:true}).click();await page.locator('.topbar').waitFor();g=await state();assert.equal(g.world.regions['eagle-state'].secession.eagle.referendumScheduledInMonths,6);assert.equal(g.world.federalPolitics['eagle-state'].history.length,3);
 await page.evaluate(()=>{window.birdKingdomDebug.setMortalityRisk(0);window.birdKingdomDebug.setElectionRoll(0);window.birdKingdomDebug.setEventRoll(.999999);window.birdKingdomDebug.setCrisisRoll(.999999);window.birdKingdomDebug.setStrategicAIEnabled(false);window.birdKingdomDebug.setSecessionRoll(.99);});
 for(let i=0;i<12;i++){await months(1);let pending=(await state()).events.pendingEvent;while(pending){assert.equal(await page.getByRole('button',{name:'다음 달',exact:true}).isEnabled(),false);const dialog=page.getByRole('dialog');await dialog.getByRole('button').filter({hasText:/개표|행정 이관|협정|절차|협의|질서|공표|게양/}).first().click();pending=(await state()).events.pendingEvent;}}
 g=await state();assert.equal(g.player.controlledCountryId,'eagle-republic-1');assert.equal(g.world.countries['eagle-republic-1'].identity.status,'established');assert.equal(g.player.career.office,'president');await nav('정치');assert.equal(await region().count(),0);console.log('PASS criticism → demand/rejection → backing fixture → referendum → manual save/load → ballot/transition/founding UI');
 if(mobile){for(const width of [320,390,640]){await page.setViewportSize({width,height:844});await fixture('partial');await nav('정치');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false);await action('일방 독립 선언');await page.getByRole('button',{name:'일방 독립 확정',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'.test-output/federal-mobile-'+width+'.png'});await page.getByRole('button',{name:'취소',exact:true}).click();}}
 assert.deepEqual(errors,[]);console.log('FEDERAL_BROWSER_RESULT 0',mobile?'mobile':'pc');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
