import assert from 'node:assert/strict';
import {test} from 'node:test';
import {advanceMonth,createGame} from './legacyEngine';
import {aggregateFederationGovernance,aggregateSpeciesPoliticalInputs,calculateApprovalTarget,calculateIntegrationTarget,calculateMinorityCrisisPressure,calculateStabilityTarget,updateGovernanceState,updateWorldGovernance} from '../src/game/governance';
import {governanceConfig,governanceKeys,initialGovernance} from '../src/game/governanceConfig';
import {createInitialPopulation,updatePopulation} from '../src/game/population';
import {updateSocialState} from '../src/game/social';
import {updateSpeciesPolitics} from '../src/game/speciesPolitics';
import {createSeededRandom} from '../src/game/random';
import {governanceCategory} from '../src/components/governanceLabels';
import type {GovernanceState} from '../src/game/types';

const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
const runtime=()=>createGame('pigeon','eagle-state').world.regions['eagle-state'];
function neutral(){const r=runtime();r.economy={...r.economy,growth:2,unemployment:5,inflation:2};r.fiscal.monthlyBalance=0;r.fiscal.debt=0;r.social={...r.social,livingStandard:50,publicSafety:50,inequality:50};for(const p of Object.values(r.speciesPolitics)){p.satisfaction=50;p.autonomyDemand=0;p.independenceSentiment=0;}r.governance.approval=50;return r;}
function verify(g:GovernanceState){for(const key of governanceKeys){assert.ok(Number.isFinite(g[key])&&g[key]>=0&&g[key]<=100);assert.ok(Math.abs(g[`${key}DeltaLastMonth`])<=governanceConfig.limit[key]+1e-10);}}
function freeze<T>(v:T):T{if(v&&typeof v==='object'){Object.freeze(v);Object.values(v).forEach(freeze);}return v;}
for(const id of ['sparrow','pigeon-state','eagle-state','owl-state','duck-state'])test(`${id} 기존 초기값64/78/81·월delta0·생활은 사회에만 저장`,()=>{
  const w=createGame('sparrow').world;const r=id==='sparrow'?w.countries.sparrow:w.regions[id];assert.deepEqual(r.governance,initialGovernance);assert.equal('livingStandard' in r.governance!,false);
});
test('중립 조건에서 목표50/65/65이며 지지도·만족도·치안은 별도 값',()=>{const r=neutral();near(calculateApprovalTarget(r),50);near(calculateStabilityTarget(r),65);near(calculateIntegrationTarget(r),65);assert.notEqual(calculateStabilityTarget(r),r.social.publicSafety);});
for(const key of ['livingStandard','publicSafety'] as const)test(`${key} 증가 지지도 상승`,()=>{const r=neutral();assert.ok(calculateApprovalTarget({...r,social:{...r.social,[key]:70}})>50);});
for(const key of ['unemployment','inflation'] as const)test(`${key} 증가 지지도 감소`,()=>{const r=neutral();assert.ok(calculateApprovalTarget({...r,economy:{...r.economy,[key]:10}})<50);});
test('성장 상승·낮은 불평등은 지지도 목표에 긍정',()=>{const r=neutral();assert.ok(calculateApprovalTarget({...r,economy:{...r.economy,growth:4}})>50);assert.ok(calculateApprovalTarget({...r,social:{...r.social,inequality:30}})>50);});
test('인구 가중 만족도·자치·독립은 단순평균과 다름',()=>{const r=neutral();r.population=createInitialPopulation({eagle:90,pigeon:10});r.speciesPolitics.eagle!.satisfaction=80;r.speciesPolitics.pigeon!.satisfaction=5;r.speciesPolitics.eagle!.autonomyDemand=10;r.speciesPolitics.pigeon!.autonomyDemand=90;r.speciesPolitics.eagle!.independenceSentiment=5;r.speciesPolitics.pigeon!.independenceSentiment=85;const p=aggregateSpeciesPoliticalInputs(r.population,r.speciesPolitics);near(p.satisfaction,72.5);near(p.autonomyDemand,18);near(p.independenceSentiment,13);assert.ok(calculateApprovalTarget(r)>50);});
test('낮은 가중 만족도는 지지도 목표 감소',()=>{const r=neutral();for(const p of Object.values(r.speciesPolitics))p.satisfaction=10;assert.ok(calculateApprovalTarget(r)<50);});
for(const key of ['incomeTaxRate','consumptionTaxRate','corporateTaxRate'] as const)test(`${key} 기준 대비 증세는 작은 부담·감세는 작은 이득`,()=>{const r=neutral();const t=(d:number)=>calculateApprovalTarget({...r,fiscal:{...r.fiscal,taxPolicy:{...r.fiscal.taxPolicy,[key]:r.fiscal.baselineTaxPolicy[key]+d}}});assert.ok(t(1)<50&&t(1)>49);assert.ok(t(-1)>50&&t(-1)<51);});
test('재정수지 단위 정규화·영향±0.5 제한·극단부채만 작은 부담',()=>{const r=neutral();for(const sign of [-1,1])near(calculateApprovalTarget({...r,fiscal:{...r.fiscal,monthlyBalance:sign*1e9}}),50+sign*.5);near(calculateApprovalTarget({...r,fiscal:{...r.fiscal,debt:r.economy.gdp*2}}),50);near(calculateApprovalTarget({...r,fiscal:{...r.fiscal,debt:r.economy.gdp*20}}),48);});
test('낮은 치안·고실업·불평등은 안정도 목표 하락',()=>{const r=neutral();assert.ok(calculateStabilityTarget({...r,social:{...r.social,publicSafety:20}})<65);assert.ok(calculateStabilityTarget({...r,economy:{...r.economy,unemployment:15}})<65);assert.ok(calculateStabilityTarget({...r,social:{...r.social,inequality:80}})<65);});
test('지지도50이상 안정도 큰 영향 없음·30미만 추가 악화',()=>{const r=neutral();const t=(approval:number)=>calculateStabilityTarget({...r,governance:{...r.governance,approval}});near(t(80),t(50));assert.ok(t(40)<t(50));assert.ok(t(30)-t(20)>t(40)-t(30));});
for(const key of ['autonomyDemand','independenceSentiment'] as const)test(`${key} 높은 종족정치는 안정도·통합도 감소`,()=>{const r=neutral();const beforeS=calculateStabilityTarget(r),beforeI=calculateIntegrationTarget(r);r.speciesPolitics.eagle![key]=60;assert.ok(calculateStabilityTarget(r)<beforeS);assert.ok(calculateIntegrationTarget(r)<beforeI);});
test('낮은 종족 만족도는 안정도 감소·높은 만족도는 통합도 개선',()=>{const r=neutral();r.speciesPolitics.eagle!.satisfaction=10;assert.ok(calculateStabilityTarget(r)<65);r.speciesPolitics.eagle!.satisfaction=90;assert.ok(calculateIntegrationTarget(r)>65);});
test('통합도에서 독립 성향의 영향은 자치 요구보다 강함',()=>{const r=neutral();const a=structuredClone(r),b=structuredClone(r);a.speciesPolitics.eagle!.autonomyDemand=20;b.speciesPolitics.eagle!.independenceSentiment=20;assert.ok(calculateIntegrationTarget(b)<calculateIntegrationTarget(a));});
test('높은 불평등·낮은 생활수준은 통합도에 작은 부정효과',()=>{const r=neutral();assert.ok(calculateIntegrationTarget({...r,social:{...r.social,inequality:70}})<65);assert.ok(calculateIntegrationTarget({...r,social:{...r.social,livingStandard:30}})<65);});
test('10% 소수 위기는 평균 만족도 높아도 파생 압력 반영·대집단이면 더 큼',()=>{const r=neutral();r.population=createInitialPopulation({eagle:90,pigeon:10});r.speciesPolitics.eagle!.satisfaction=80;Object.assign(r.speciesPolitics.pigeon!,{satisfaction:5,autonomyDemand:80,independenceSentiment:70});const risk=calculateMinorityCrisisPressure(r.population,r.speciesPolitics);near(risk.pressure,10);assert.equal(risk.speciesId,'pigeon');assert.ok(aggregateSpeciesPoliticalInputs(r.population,r.speciesPolitics).satisfaction>70);const small=calculateStabilityTarget(r);r.population=createInitialPopulation({eagle:10,pigeon:90});assert.ok(calculateMinorityCrisisPressure(r.population,r.speciesPolitics).pressure>risk.pressure);assert.ok(calculateStabilityTarget(r)<small);});
test('위기 압력은 최대 인구비중×비선형불만이며 입력 변경·저장 없음',()=>{const r=freeze(runtime()),before=structuredClone(r);assert.deepEqual(calculateMinorityCrisisPressure(r.population,r.speciesPolitics),{pressure:0,speciesId:null});assert.deepEqual(r,before);assert.equal('minorityCrisisPressure' in r,false);});
test('0인구·빈 정치·빈 종족·GDP0에서 NaN/Infinity 없음',()=>{const r=neutral();r.population=createInitialPopulation({});r.speciesPolitics={};r.economy.gdp=0;assert.deepEqual(aggregateSpeciesPoliticalInputs(r.population,r.speciesPolitics),{satisfaction:50,autonomyDemand:0,independenceSentiment:0});assert.deepEqual(calculateMinorityCrisisPressure(r.population,r.speciesPolitics),{pressure:0,speciesId:null});verify(updateGovernanceState(r));});
test('월 이동 목표 기반·상한2/1.2/.6·통합은 가장 느림',()=>{const r=neutral();r.governance={...initialGovernance,approval:40,stability:55,integration:55};const next=updateGovernanceState(r);near(next.approval,40.8);near(next.integration,55.25);assert.ok(next.approvalDeltaLastMonth>next.integrationDeltaLastMonth);for(const key of governanceKeys)near(next[key]-r.governance[key],next[`${key}DeltaLastMonth`]);verify(next);});
test('극단 경제·사회·종족 불만에도 범위와 월 상한',()=>{for(const sign of [-1,1]){const r=neutral();r.economy.unemployment=sign*1e6;r.economy.inflation=sign*1e6;for(const p of Object.values(r.speciesPolitics))Object.assign(p,{satisfaction:sign>0?0:100,autonomyDemand:sign>0?100:0,independenceSentiment:sign>0?100:0});verify(updateGovernanceState(r));}});
test('새 지지도로 안정도 계산하고 통합 목표는 반복계산하지 않음',()=>{const r=neutral();r.governance.approval=10;const n=updateGovernanceState(r);near(n.stability,r.governance.stability+Math.max(-1.2,Math.min(1.2,(calculateStabilityTarget({...r,governance:n})-r.governance.stability)*.05)));});
test('연방 사회와 동일 인구 가중값·delta·빈/0인구 집계',()=>{const a=runtime(),b=runtime();a.population.total=100;b.population.total=300;a.governance={...initialGovernance,approval:20,stability:40,integration:60,approvalDeltaLastMonth:1};b.governance={...initialGovernance,approval:60,stability:80,integration:20,approvalDeltaLastMonth:-1};const n=aggregateFederationGovernance([a,b]);near(n.approval,50);near(n.stability,70);near(n.integration,30);near(n.approvalDeltaLastMonth,-.5);a.population.total=0;b.population.total=0;assert.deepEqual(aggregateFederationGovernance([a,b]),aggregateFederationGovernance([]));});
for(const mode of ['sparrow','eagle'])test(`${mode} 선택 무관 모든 거버넌스 갱신·연방 비저장`,()=>{const g=mode==='sparrow'?createGame('sparrow'):createGame('pigeon','eagle-state');const n=advanceMonth(g,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,economyRandom:()=>.5,electionRandom:()=>0, mortalityRandom:()=>.99});assert.notDeepEqual(n.world.countries.sparrow.governance,g.world.countries.sparrow.governance);for(const id of Object.keys(g.world.regions))assert.notDeepEqual(n.world.regions[id].governance,g.world.regions[id].governance);assert.equal('governance' in g.world.countries.pigeon,false);assert.equal('governance' in n.world.countries.pigeon,false);});
test('세계 업데이트 동결입력 불변·결정론·다른 시스템 객체 보존',()=>{const w=freeze(createGame('sparrow').world),snapshot=structuredClone(w);const n=updateWorldGovernance(w);assert.deepEqual(w,snapshot);assert.deepEqual(n,updateWorldGovernance(w));const r=n.regions['eagle-state'];assert.equal(r.economy,w.regions['eagle-state'].economy);assert.equal(r.population,w.regions['eagle-state'].population);assert.equal(r.speciesPolitics,w.regions['eagle-state'].speciesPolitics);});
test('소유 주를 가진 동적 국가는 거버넌스 중복 제거',()=>{const w=createGame('sparrow').world;w.countries.other={...w.countries.sparrow,id:'other'};w.regions['eagle-state'].ownerCountryId='other';assert.equal('governance' in updateWorldGovernance(w).countries.other,false);});
test('이번 달 종족정치는 이전 통합·거버넌스는 새 종족정치·다음 달 피드백',()=>{const g=createGame('pigeon','eagle-state');const before=g.world.regions['eagle-state'];const n=advanceMonth(g,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,economyRandom:()=>.5,electionRandom:()=>0, mortalityRandom:()=>.99});const r=n.world.regions['eagle-state'];const context={...r,governance:before.governance};assert.deepEqual(r.speciesPolitics,updateSpeciesPolitics(r.id,before.speciesPolitics,context));assert.deepEqual(r.governance,updateGovernanceState(context));assert.notDeepEqual(r.speciesPolitics,updateSpeciesPolitics(r.id,before.speciesPolitics,r));const second=advanceMonth(n,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,economyRandom:()=>.5,electionRandom:()=>0, mortalityRandom:()=>.99}).world.regions[r.id];assert.deepEqual(second.speciesPolitics,updateSpeciesPolitics(r.id,r.speciesPolitics,{...second,governance:r.governance}));});
test('낮은 안정도 상황위험 상승·즉시게임오버/역경제효과/추가RNG/로그 없음',()=>{const g=createGame('pigeon','eagle-state'),changed=structuredClone(g);Object.assign(changed.world.regions['eagle-state'].governance,{approval:0,stability:0,integration:0});let e=0,d=0;const a=advanceMonth(changed,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,economyRandom:()=>{e++;return .5},electionRandom:()=>0, mortalityRandom:()=>{d++;return .99}}),b=advanceMonth(g,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,economyRandom:()=>.5,electionRandom:()=>0, mortalityRandom:()=>.99});assert.equal(e,30);assert.equal(d,1);assert.equal(a.player.alive,true);assert.deepEqual({...a.player,career:undefined,leaderRisk:undefined,currentMortalityRisk:undefined},{...b.player,career:undefined,leaderRisk:undefined,currentMortalityRisk:undefined});assert.ok(a.player.leaderRisk!.politicalRisk>b.player.leaderRisk!.politicalRisk);assert.ok(a.player.currentMortalityRisk>b.player.currentMortalityRisk);assert.ok(a.player.currentMortalityRisk<.001);assert.deepEqual(a.world.regions['eagle-state'].economy,b.world.regions['eagle-state'].economy);assert.deepEqual(a.world.regions['eagle-state'].fiscal,b.world.regions['eagle-state'].fiscal);assert.equal(a.logs.length,2);});
test('사망 월 거버넌스 갱신 이후 사망하며 후속 진행 금지',()=>{const g=createGame('sparrow');const n=advanceMonth(g,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,economyRandom:()=>.5,electionRandom:()=>0, mortalityRandom:()=>.5,mortalityRiskOverride:1});assert.equal(n.player.alive,false);assert.notDeepEqual(n.world.countries.sparrow.governance,g.world.countries.sparrow.governance);assert.equal(advanceMonth(n),n);});
for(const key of governanceKeys)test(`${key} UI 소수값·30/45/65/80 범주 경계`,()=>{const labels={approval:['위기','낮음','보통','높음','압도적 지지'],stability:['심각','불안','보통','안정','매우 안정'],integration:['분열','낮음','보통','높음','매우 높음']};for(const [value,index] of [[0,0],[29.9,0],[30,1],[45,2],[64.9,2],[65,3],[80,4],[100,4]])assert.equal(governanceCategory(key,value),labels[key][index]);});
test('600개월 정상 세계 전체 범위·통합/자치 피드백 안정·기존 시스템 유지',()=>{
  let g=createGame('sparrow');const random=createSeededRandom(2030);for(let i=0;i<600;i++){g=advanceMonth(g,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,economyRandom:random,electionRandom:()=>0, mortalityRandom:()=>.99});for(const r of [g.world.countries.sparrow,...Object.values(g.world.regions)]){verify(r.governance!);assert.ok(Number.isFinite(r.economy.gdp)&&r.economy.gdp>0);assert.ok(Number.isSafeInteger(r.population.total));}assert.equal('governance' in g.world.countries.pigeon,false);}
  for(const r of [g.world.countries.sparrow,...Object.values(g.world.regions)])for(const key of governanceKeys)assert.ok(r.governance![key]>50&&r.governance![key]<85);for(const r of Object.values(g.world.regions))for(const p of Object.values(r.speciesPolitics))assert.ok(p.autonomyDemand<45&&p.independenceSentiment<40);assert.equal(g.logs.filter(l=>l.category==='political').length,12);console.log('GOV NORMAL600',JSON.stringify({sparrow:g.world.countries.sparrow.governance,regions:Object.fromEntries(Object.entries(g.world.regions).map(([id,r])=>[id,r.governance])),federation:aggregateFederationGovernance(Object.values(g.world.regions))}));
});
test('독수리240개월 장기위기: 지지도/안정/통합 하락·자치/독립 상승',()=>{
  const r=runtime(),initial=structuredClone(r);r.economy={...r.economy,growth:-6,unemployment:25,inflation:10};r.fiscal={...r.fiscal,taxPolicy:{incomeTaxRate:40,corporateTaxRate:35,consumptionTaxRate:25},budgetPolicy:{...r.fiscal.budgetPolicy,welfare:0,healthcare:0,education:0,security:0}};
  for(let i=0;i<240;i++){r.population=updatePopulation(r.population,r.economy,r.fiscal,r.social);r.social=updateSocialState(r.id,r);r.speciesPolitics=updateSpeciesPolitics(r.id,r.speciesPolitics,r);r.governance=updateGovernanceState(r);verify(r.governance);if(i===11){assert.ok(r.governance.approval>=40-1e-9);assert.ok(r.governance.stability>=63.6-1e-9);assert.ok(r.governance.integration>=73.8-1e-9);}}
  for(const key of governanceKeys){assert.ok(r.governance[key]<initial.governance[key]);assert.ok(r.governance[key]>0);}assert.ok(r.speciesPolitics.eagle!.autonomyDemand>initial.speciesPolitics.eagle!.autonomyDemand);assert.ok(r.speciesPolitics.eagle!.independenceSentiment>initial.speciesPolitics.eagle!.independenceSentiment);assert.ok(r.speciesPolitics.eagle!.independenceSentiment<100);console.log('GOV CRISIS240',JSON.stringify({governance:r.governance,social:r.social,eagle:r.speciesPolitics.eagle,minority:calculateMinorityCrisisPressure(r.population,r.speciesPolitics)}));
});
