import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createGame,advanceMonth} from '../src/game/engine';
import {collectHistory,recordHistoricalEvent,makeYearlySnapshot,technologyHistoryScore} from '../src/game/history';
import {selectTimeline,selectCountrySeries,selectCountryLineage} from '../src/game/historySelectors';
import {createBreakawayCountry,applySecessionAction} from '../src/game/secession';
import {resolveConflictOutcome,applyConflictAction} from '../src/game/conflict';
import {transferWarTerritory} from '../src/game/warfareEffects';
import {addCasusBelli} from '../src/game/casusBelli';
import {declareWar,applyWarAction} from '../src/game/warfare';
import {resolvePeace} from '../src/game/peace';
import {performDiplomaticAction,getBilateralRelation} from '../src/game/diplomacy';
import {startCrisis,recoverCrisis,updateWorldCrises} from '../src/game/crisis';
import {resolveElection} from '../src/game/election';
import {updateWorldTechnology} from '../src/game/technology';
import {createSeededRandom} from '../src/game/random';
import {derivedCountryRuntime} from '../src/game/runtime';
import type {GameState} from '../src/game/types';
const options={autonomousWorld:true,domesticAI:false,strategicAI:false,mortalityRiskOverride:0,mortalityRandom:()=>.99,electionRandom:()=>0,economyRandom:()=>.5,eventOccurrenceRandom:()=>.99999,eventOutcomeRandom:()=>.5,secessionRandom:()=>.5,conflictRandom:()=>.5,warRandom:()=>.5,crisisRandom:()=>.99};
const step=(g:GameState,n:number)=>{for(let i=0;i<n;i++)g=advanceMonth(g,options);return g;};
function child(g=createGame('sparrow'),disputed=false){const r=g.world.regions['eagle-state'];Object.assign(r.speciesPolitics!.eagle!,{satisfaction:10,autonomyDemand:95,independenceSentiment:95});Object.assign(r.secession!.eagle!,{phase:disputed?'unilateral_crisis':'transition',monthsInPhase:6,monthsActive:30,lastRefusalTurn:g.turn,lastReferendumResult:{date:g.date,passed:true,yesShare:90}});r.governance.integration=20;return createBreakawayCountry(g,{kind:'region',id:r.id},'eagle',disputed);}
const cid='eagle-republic-1';
function war(){let g=createGame('sparrow');g=addCasusBelli(g,'sparrow','pigeon','territorial_dispute','eagle-state');return declareWar(g,'sparrow',Object.keys(g.world.warfare!.casusBelli)[0],'border_claim',true,true);}
function stamp(g:GameState,sourceKey='sample',category:'war'|'diplomacy'='war',importance:'major'|'minor'='major'){return recordHistoricalEvent(g,{sourceKey,date:g.date,category,importance,title:'참새 비행회랑 협정',description:'양국의 항로 관제가 합의되었다.',countryIds:['sparrow'],countryNames:['참새자유공화국']});}
function verify(g:GameState){const h=g.history!;assert.equal(new Set(h.timeline.map(e=>e.id)).size,h.timeline.length);assert.equal(new Set(h.timeline.map(e=>e.sourceKey)).size,h.timeline.length);assert.ok(h.timeline.every(e=>e.countryIds.every(id=>!!h.countries[id])&&e.countryNames.every(n=>n&&!n.includes('Unknown'))));assert.ok(h.yearlySnapshots.every(s=>s.countries.every(c=>Object.values(c).every(v=>typeof v!=='number'||Number.isFinite(v)))));assert.deepEqual(JSON.parse(JSON.stringify(h)),h);}
test('역사 초기화 schema baseline 연간자료분리',()=>{const h=createGame('sparrow').history!;assert.equal(h.schemaVersion,1);assert.equal(h.yearlySnapshots.length,0);assert.equal(h.baseline!.activeCountryCount,2);});
test('시작 국가 두 생애 기록',()=>assert.deepEqual(Object.keys(createGame('sparrow').history!.countries).sort(),['pigeon','sparrow']));
test('시작 창건일 2030/1',()=>assert.deepEqual(createGame('sparrow').history!.countries.sparrow.foundedDate,{year:2030,month:1}));
test('역사 ID deterministic RNG없음',()=>assert.deepEqual(createGame('sparrow').history,createGame('sparrow').history));
test('공통기록 immutable 입력보존',()=>{const g=createGame('sparrow'),s=JSON.stringify(g);stamp(g);assert.equal(JSON.stringify(g),s);});
test('중복 source 단 한번',()=>{const g=stamp(createGame('sparrow'));assert.equal(stamp(g),g);});
test('연표 minor 필터',()=>{const g=stamp(stamp(createGame('sparrow'),'a'),'b','diplomacy','minor');assert.ok(!selectTimeline(g.history!,{majorOnly:true}).some(e=>e.sourceKey==='b'));});
test('연표 category 필터',()=>{const g=stamp(createGame('sparrow'));assert.ok(selectTimeline(g.history!,{category:'war'}).every(e=>e.category==='war'));});
test('연표 국가 필터',()=>{const g=stamp(createGame('sparrow'));assert.ok(selectTimeline(g.history!,{countryId:'pigeon'}).every(e=>e.countryIds.includes('pigeon')));});
test('연표 문자열 검색 이름 문구',()=>assert.equal(selectTimeline(stamp(createGame('sparrow')).history!,{search:'회랑 협정'}).length,1));
test('연표 동일월 order 역순 정순',()=>{const h=stamp(stamp(createGame('sparrow'),'a'),'b').history!;assert.equal(selectTimeline(h)[0].sourceKey,'b');assert.equal(selectTimeline(h,{ascending:true}).at(-1)!.sourceKey,'b');});
test('신생국 생성 즉시 archive',()=>assert.ok(child().history!.countries[cid]));
test('신생국 origin 종류 기록',()=>{const c=child().history!.countries[cid];assert.equal(c.originCountryId,'pigeon');assert.equal(c.foundingType,'legal_independence');});
test('일방독립 종류',()=>assert.equal(child(createGame('sparrow'),true).history!.countries[cid].foundingType,'unilateral_independence'));
test('재통합 소멸날짜 종류 후속',()=>{let g=child(createGame('sparrow'),true);g=applyConflictAction(g,'internal-1','negotiate');g=resolveConflictOutcome(g,'internal-1','negotiated_reintegration');const c=g.history!.countries[cid];assert.deepEqual(c.dissolvedDate,g.date);assert.equal(c.endType,'reunified');assert.deepEqual(c.successorCountryIds,['pigeon']);});
test('영토흡수 삭제해도 이름 생애 유지',()=>{let g=child();g=transferWarTerritory(g,['eagle-state'],'sparrow');assert.ok(!g.world.countries[cid]);assert.equal(g.history!.countries[cid].endType,'annexed');assert.ok(g.history!.timeline.some(e=>e.countryNames.includes('독수리공화국')));});
test('계보 추적',()=>assert.deepEqual(selectCountryLineage(child().history!,cid),['pigeon',cid]));
test('월별 최대 GDP 인구 갱신',()=>{const a=createGame('sparrow'),b=structuredClone(a);b.world.countries.sparrow.economy.gdp*=2;b.world.countries.sparrow.population.total*=2;const c=collectHistory(a,b).history!.countries.sparrow;assert.equal(c.peakGDP.value,b.world.countries.sparrow.economy.gdp);assert.equal(c.peakPopulation.value,b.world.countries.sparrow.population.total);});
test('최대값 감소시 이전최대유지',()=>{const a=createGame('sparrow'),b=structuredClone(a);b.world.countries.sparrow.economy.gdp=1;assert.deepEqual(collectHistory(a,b).history!.countries.sparrow.peakGDP,a.history!.countries.sparrow.peakGDP);});
test('12번 월진행 뒤2030자료 정확한 최종수치',()=>{let g=step(createGame('sparrow'),11);assert.equal(g.history!.yearlySnapshots.length,0);g=step(g,1);const s=g.history!.yearlySnapshots[0];assert.equal(s.year,2030);assert.deepEqual(s.date,{year:2031,month:1});assert.equal(s.countries[1].gdp,g.world.countries.sparrow.economy.gdp);});
test('같은연도 snapshot 중복 방지',()=>{const g=step(createGame('sparrow'),12);assert.equal(collectHistory({...g,date:{year:2030,month:12}},g,true).history!.yearlySnapshots.length,1);});
for(const metric of ['population','gdp','growth','unemployment','inflation','treasury','debt'] as const)test('통계 '+metric+' runtime값',()=>{const g=createGame('sparrow'),c=g.world.countries.sparrow,s=makeYearlySnapshot(g).countries.find(c=>c.countryId==='sparrow')!;assert.equal(s[metric],metric==='population'?c.population.total:metric==='treasury'||metric==='debt'?c.fiscal[metric]:c.economy[metric]);});
for(const metric of ['livingStandard','education','healthcare','publicSafety','inequality'] as const)test('통계 사회 '+metric,()=>{const g=createGame('sparrow');assert.equal(makeYearlySnapshot(g).countries.find(c=>c.countryId==='sparrow')![metric],g.world.countries.sparrow.social![metric]);});
for(const metric of ['approval','stability','integration'] as const)test('통계 거버넌스 '+metric,()=>{const g=createGame('sparrow');assert.equal(makeYearlySnapshot(g).countries.find(c=>c.countryId==='sparrow')![metric],g.world.countries.sparrow.governance![metric]);});
test('통계 기술score별도관찰값',()=>{const g=createGame('sparrow');assert.equal(makeYearlySnapshot(g).countries.find(c=>c.countryId==='sparrow')!.technologyScore,technologyHistoryScore(g.world.countries.sparrow.technology));});
test('군사 snapshot 현재값',()=>{const g=createGame('sparrow');g.world.countries.sparrow.military!.capability=23;assert.equal(makeYearlySnapshot(g).countries.find(c=>c.countryId==='sparrow')!.militaryCapability,23);});
test('0인구 GDP per capita 안전',()=>{const g=createGame('sparrow');g.world.countries.sparrow.population.total=0;assert.equal(makeYearlySnapshot(g).countries.find(c=>c.countryId==='sparrow')!.gdpPerCapita,0);});
test('연방 독립지역제외 실제소유집계',()=>{const g=child(),s=makeYearlySnapshot(g);assert.equal(s.countries.find(c=>c.countryId==='pigeon')!.population,Object.values(g.world.regions).filter(r=>r.ownerCountryId==='pigeon').reduce((t,r)=>t+r.population.total,0));assert.ok(s.countries.some(c=>c.countryId===cid));});
test('세계 합계 이중집계 없음',()=>{const g=child(),s=makeYearlySnapshot(g);assert.equal(s.totalWorldPopulation,s.countries.reduce((t,c)=>t+c.population,0));assert.equal(s.activeCountryCount,3);});
test('소멸국 이전자료보존 null 이후',()=>{let g=step(child(),12);g=transferWarTerritory(g,['eagle-state'],'pigeon');g=step(g,12);const s=selectCountrySeries(g.history!,cid,'gdp');assert.ok(s[0].value!>0);assert.equal(s[1].value,null);});
test('전쟁 선언 즉시 이름 목표 시작기록',()=>{const g=war(),w=Object.values(g.history!.wars)[0];assert.equal(w.warGoal,'border_claim');assert.equal(w.endedDate,null);assert.deepEqual(w.attackerNames,['참새자유공화국']);});
test('전쟁 월수·휴전 기록',()=>{let g=step(war(),5);g=applyWarAction(g,'war-1','ceasefire');assert.equal(g.history!.wars['war-1'].durationMonths,5);assert.ok(g.history!.timeline.some(e=>e.title==='대편대 휴전'));});
test('평화 종료 중복없이 immutable',()=>{let g=applyWarAction(war(),'war-1','negotiate');const prev=JSON.stringify(g);const ended=resolvePeace(g,'war-1','status_quo');assert.equal(JSON.stringify(g),prev);assert.deepEqual(ended.history!.wars['war-1'].endedDate,g.date);assert.equal(ended.history!.timeline.filter(e=>e.sourceKey==='war-end:war-1').length,1);});
test('전쟁 목표영토 이전 archive',()=>{let g=war();const w=g.world.warfare!.wars['war-1'];w.fronts=w.fronts.map(f=>({...f,controllerCountryId:'sparrow',control:98,decisiveMonths:3}));g=applyWarAction(g,'war-1','negotiate');g=resolvePeace(g,'war-1','territory_transfer');assert.equal(g.history!.wars['war-1'].territorialChanges[0].regionId,'eagle-state');assert.ok(g.history!.countries.sparrow.territorialChanges.some(c=>c.toId==='sparrow'));});
test('삭제국가 참여 전쟁 이름유지',()=>{let g=child();g=addCasusBelli(g,'pigeon',cid,'breakaway_claim','eagle-state');g=declareWar(g,'pigeon',Object.keys(g.world.warfare!.casusBelli)[0],'reunification',true,true);g=transferWarTerritory(g,['eagle-state'],'sparrow');assert.equal(g.history!.wars['war-1'].defenderNames[0],'독수리공화국');verify(g);});
test('내부분쟁 시작 종료 독립결과',()=>{let g=child(createGame('sparrow'),true);g=resolveConflictOutcome(g,'internal-1','independence_recognized');assert.equal(g.history!.internalConflicts['internal-1'].independent,true);assert.ok(g.history!.internalConflicts['internal-1'].endedDate);});
test('내전 무력단계 실제 연표',()=>{let g=child(createGame('sparrow'),true);g=applyConflictAction(g,'internal-1','pressure');Object.assign(g.world.internalConflicts!['internal-1'],{monthsInConflict:4,tension:80});g=applyConflictAction(g,'internal-1','escalate');assert.ok(g.history!.timeline.some(e=>e.title.includes('내전 발발')));});
for(const won of [true,false])test('플레이어 선거 '+won+' 종료기록',()=>{const g=createGame('sparrow');g.player.career.monthsInCurrentTerm=48;const e=resolveElection(g,()=>won?0:.9999);assert.equal(e.history!.elections[0].result,won?'won':'lost');assert.equal(e.history!.elections[0].termNumber,1);if(!won){assert.equal(e.history!.career.endReason,'election_defeat');assert.ok(e.history!.career.endDate);}});
test('NPC선거 만들어내지 않음',()=>assert.equal(step(createGame('sparrow'),60).history!.elections.length,1));
test('주지사 독립대통령 직위기간연결',()=>{const g=child(createGame('pigeon','eagle-state'));assert.deepEqual(g.history!.career.officesHeld.map(o=>o.office),['governor','president']);assert.ok(g.history!.career.officesHeld[0].endDate);});
test('사망 종료 마지막역사 확정',()=>{const g=advanceMonth(createGame('sparrow'),{...options,mortalityRiskOverride:1});assert.equal(g.history!.career.endReason,'death');assert.equal(g.history!.career.endDate!.month,2);});
test('국가패배 종료 역사확정',()=>{let g=child(createGame('pigeon','eagle-state'));g=transferWarTerritory(g,['eagle-state'],'sparrow');assert.equal(g.history!.career.endReason,'state_defeat');assert.ok(g.history!.countries[cid].dissolvedDate);assert.ok(g.history!.timeline.find(e=>e.sourceKey==='career-end')!.countryIds.includes(cid));});
function discovery(g:GameState,jid:string,id='information-6'){const before=g;const name=jid==='owl-state'?'부엉이주':'참새자유공화국';return collectHistory(before,{...g,world:{...g.world,technologyHistory:[{id:'t-'+jid+'-'+g.turn,date:g.date,jurisdictionId:jid,jurisdictionName:name,technologyId:id,technologyName:'분산 공중관제 지능망'},...(g.world.technologyHistory??[])]}});}
test('기술 world first 한 번 다른국가는아님',()=>{let g=discovery(createGame('sparrow'),'owl-state');g={...g,date:{year:2035,month:1},turn:61};g=discovery(g,'sparrow');assert.equal(g.history!.technologyMilestones.filter(t=>t.worldFirst).length,1);assert.equal(g.history!.worldFirstTechnology['information-6'].countryId,'pigeon');assert.equal(g.history!.technologyMilestones[1].worldFirst,false);});
test('기술실제연구해금도 자동 기록',()=>{const g=createGame('sparrow'),t=g.world.countries.sparrow.technology!;t.domains.information.currentResearchId='information-2';t.researchProgress['information-2']=9999;const next=updateWorldTechnology(g);assert.ok(next.history!.technologyMilestones.some(t=>t.technologyId==='information-2'));});
test('삭제국 기술 milestone 보존',()=>{let g=child();g=discovery(g,'eagle-state');g=transferWarTerritory(g,['eagle-state'],'pigeon');assert.equal(g.history!.technologyMilestones[0].countryId,cid);});
test('중대위기 발생 종료 피해 보존',()=>{let g=startCrisis(createGame('sparrow'),{kind:'country',id:'sparrow'},'great_storm',95);g=updateWorldCrises(g,()=>.99);const c=Object.values(g.world.crises!.activeCrises)[0];g=recoverCrisis(g,c.id,100);const r=g.history!.crises[c.id];assert.equal(r.maxSeverity,95);assert.ok(r.endedDate);assert.equal(r.totalFiscalCost,c.totalFiscalCost);assert.equal(r.totalPopulationImpact,c.totalPopulationImpact);});
test('경미위기 archive만 timeline spam없음',()=>{const g=startCrisis(createGame('sparrow'),{kind:'country',id:'sparrow'},'great_storm',15);assert.equal(Object.keys(g.history!.crises).length,1);assert.equal(g.history!.timeline.filter(e=>e.category==='crisis').length,0);});
test('재난 영토이관 시작국가 이름고정',()=>{let g=startCrisis(child(),{kind:'region',id:'eagle-state'},'great_storm',85);g=transferWarTerritory(g,['eagle-state'],'sparrow');const r=Object.values(g.history!.crises)[0];assert.equal(r.countryId,cid);assert.equal(r.countryName,'독수리공화국');});
test('역사 RNG소비·게임결과 독립',()=>{const a=createGame('sparrow'),b={...a,history:undefined};assert.deepEqual(advanceMonth(a,options).world,advanceMonth(b,options).world);});
test('일반관계개선 역사제외 방위승격',()=>{let g=createGame('sparrow');g=performDiplomaticAction(g,'sparrow','pigeon','improve');assert.equal(g.history!.timeline.filter(e=>e.category==='diplomacy').length,0);Object.assign(getBilateralRelation(g.world,'sparrow','pigeon')!,{relations:90,trust:95,nonAggressionPact:true,lastActionTurnA:null,lastActionTurnB:null});g.turn+=12;g=performDiplomaticAction(g,'sparrow','pigeon','defense',false,true);assert.equal(g.history!.timeline.filter(e=>e.category==='diplomacy')[0].importance,'major');});
test('국가 탄생→30년→재통합 생애 E2E',()=>{let g=step(child(createGame('sparrow'),true),360);g=applyConflictAction(g,'internal-1','negotiate');g=resolveConflictOutcome(g,'internal-1','negotiated_reintegration');assert.equal(selectCountrySeries(g.history!,cid,'population').filter(p=>p.value!==null).length,30);assert.ok(g.history!.countries[cid].dissolvedDate);assert.equal(g.history!.countries[cid].successorCountryIds[0],'pigeon');assert.equal(g.history!.internalConflicts['internal-1'].independent,false);verify(g);});
function endurance(seed:number,months:number){let g=createGame('sparrow');const rng={economyRandom:createSeededRandom(seed),eventOccurrenceRandom:createSeededRandom(seed+1),eventOutcomeRandom:createSeededRandom(seed+2),secessionRandom:createSeededRandom(seed+3),conflictRandom:createSeededRandom(seed+4),warRandom:createSeededRandom(seed+5),crisisRandom:createSeededRandom(seed+6)};for(let i=0;i<months;i++)g=advanceMonth(g,{...options,...rng,domesticAI:true,strategicAI:true});assert.equal(g.turn,months+1);assert.equal(g.history!.yearlySnapshots.length,months/12);verify(g);const bytes=Buffer.byteLength(JSON.stringify(g.history));assert.ok(bytes<12_000_000);assert.ok(!JSON.stringify(g.history).includes('industries'));assert.equal(selectCountrySeries(g.history!,'sparrow','gdp').length,months/12);console.log('HISTORY LONG',JSON.stringify({seed,months,snapshots:g.history!.yearlySnapshots.length,timeline:g.history!.timeline.length,crises:Object.keys(g.history!.crises).length,bytes}));return g;}
for(const seed of [91,2030,4412,8451,9966])test(seed+'×600 history 자율 참조 크기',()=>endurance(seed,600));
test('2400개월200년 기록·차트 endurance',()=>{const g=endurance(202601,2400);assert.equal(selectCountrySeries(g.history!,'sparrow','population').length,200);assert.equal(g.history!.yearlySnapshots.map(s=>s.activeCountryCount).length,200);});

test('이전에 알려진 초기기술은 새세계최초로 오기록하지 않음',()=>{const g=createGame('sparrow'),id=Object.keys(g.history!.worldFirstTechnology)[0];assert.ok(id);assert.equal(g.history!.worldFirstTechnology[id].worldFirst,false);});
test('실제 부엉이→참새 최첨단 기술경쟁 worldfirst E2E',()=>{let g=createGame('sparrow');const ready=(t:NonNullable<GameState['world']['countries'][string]['technology']>)=>{t.domains.information.level=8;t.domains.information.currentResearchId='information-6';t.unlockedTechnologies=[...new Set([...t.unlockedTechnologies,...[1,2,3,4,5].map(n=>'information-'+n)])];t.researchProgress['information-6']=99999;};ready(g.world.regions['owl-state'].technology!);g=updateWorldTechnology(g);assert.ok(g.history!.worldFirstTechnology['information-6'].worldFirst);assert.equal(g.history!.worldFirstTechnology['information-6'].jurisdictionId,'owl-state');g={...g,date:{year:2035,month:1},turn:61};ready(g.world.countries.sparrow.technology!);g=updateWorldTechnology(g);const rows=g.history!.technologyMilestones.filter(t=>t.technologyId==='information-6');assert.equal(rows.length,2);assert.equal(rows[1].worldFirst,false);});
test('metadata 배열 이름 날짜 snapshot 후입력변경에도 보존',()=>{const g=createGame('sparrow'),input={sourceKey:'copytest',date:{year:2035,month:2},category:'war' as const,importance:'major' as const,title:'기록',description:'기록',countryIds:['sparrow'],countryNames:['참새'],metadata:{regions:['r1']}};const next=recordHistoricalEvent(g,input);input.countryNames[0]='changed';input.date.month=5;input.metadata.regions[0]='changed';const e=next.history!.timeline.at(-1)!;assert.equal(e.countryNames[0],'참새');assert.equal(e.date.month,2);assert.deepEqual(e.metadata!.regions,['r1']);});
test('역사빈자료 추가가 RNG 호출장수를 바꾸지 않음',()=>{const counts:number[]=[];for(const hist of [true,false]){let n=0;const g=createGame('sparrow');if(!hist)g.history=undefined;advanceMonth(g,{...options,economyRandom:()=>{n++;return .5;},mortalityRandom:()=>{n++;return .99;},eventOccurrenceRandom:()=>{n++;return .99999;}});counts.push(n);}assert.equal(counts[0],counts[1]);});

