const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const mobile=!!process.env.BIRD_MOBILE,page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5175');await page.getByRole('button',{name:'튜토리얼 건너뛰기',exact:true}).click();await page.getByRole('button',{name:'공화국 운영 시작',exact:true}).click();
const state=()=>page.evaluate(()=>window.birdKingdomDebug.getGameState());const nav=async()=>{const b=page.getByRole('button',{name:'메뉴 열기',exact:true});if(await b.isVisible())await b.click();await page.getByRole('navigation',{name:'정부 운영 메뉴'}).getByRole('button',{name:'정치',exact:true}).click();};
const fixture=async(level='unstable')=>{await page.evaluate(async level=>{const {pressureFixture}=await import('/tests/pressureFixtures.ts');window.birdKingdomDebug.setGameState(pressureFixture(level));window.birdKingdomDebug.setMortalityRisk(0);window.birdKingdomDebug.setElectionRoll(0);window.birdKingdomDebug.setEventRoll(.999999);window.birdKingdomDebug.setCrisisRoll(.999999);window.birdKingdomDebug.setStrategicAIEnabled(true);},level);await nav();};
// Select a real weighted candidate using a controlled occurrence stream, not fabricated effects.
const event=async id=>{await page.evaluate(async id=>{const {allEventDefinitions,calculateEventChance,generateWorldEvents}=await import('/src/game/events.ts');const g=window.birdKingdomDebug.getGameState(),j={kind:'region',id:'eagle-state'},c=allEventDefinitions.map(definition=>({definition,chance:calculateEventChance(definition.id,g,j)})).filter(x=>x.chance>0).sort((a,b)=>a.definition.id.localeCompare(b.definition.id)),total=c.reduce((s,x)=>s+x.chance,0),index=c.findIndex(x=>x.definition.id===id);if(index<0)throw Error('ineligible '+id);const ticket=(c.slice(0,index).reduce((s,x)=>s+x.chance,0)+c[index].chance/2)/total;let call=0;const n=generateWorldEvents(g,{eventOccurrenceRandom:()=>call++%2?ticket:0,eventOutcomeRandom:()=>.5,strategicAI:false,domesticAI:false});if(n.events.pendingEvent?.eventId!==id)throw Error('wrong weighted event '+n.events.pendingEvent?.eventId);window.birdKingdomDebug.setGameState(n);},id);assert.equal(await page.getByRole('button',{name:'다음 달',exact:true}).isEnabled(),false);};
const month=async()=>{while(await page.locator('.foreign-proposal').count())await page.getByRole('button',{name:'제안 거절',exact:true}).click();if(await page.getByRole('heading',{name:'방위조약 참전 요청'}).count())await page.getByRole('button',{name:'불참',exact:true}).click();await page.getByRole('button',{name:'다음 달',exact:true}).click();};
const choose=async text=>{await page.getByRole('dialog').getByRole('button').filter({hasText:text}).first().click();};
await fixture();await page.evaluate(async()=>{const {federalFixture}=await import('/tests/federalFixtures.ts');window.birdKingdomDebug.setGameState(federalFixture('weak'));});await page.getByRole('region',{name:'연방정치',exact:true}).getByRole('combobox',{name:'자치권 요구 수준'}).selectOption('maximum');await page.getByRole('region',{name:'연방정치',exact:true}).getByRole('button',{name:'자치권 확대 요구',exact:true}).click();let g=await state();assert.equal(g.world.federalPolitics['eagle-state'].history.at(-1).response,'hardline_rejection');await page.evaluate(()=>{const g=window.birdKingdomDebug.getGameState(),r=g.world.regions['eagle-state'];Object.assign(r.speciesPolitics.eagle,{satisfaction:20,autonomyDemand:92,independenceSentiment:88});Object.assign(r.governance,{integration:25,stability:28});window.birdKingdomDebug.setGameState(g);});g=await state();await page.evaluate(()=>window.birdKingdomDebug.setStrategicAIEnabled(false));await event('autonomy-protest');const old=g.world.regions['eagle-state'].speciesPolitics.eagle.independenceSentiment;await choose('강경 진압');g=await state();assert.ok(g.world.regions['eagle-state'].speciesPolitics.eagle.independenceSentiment>old);await event('secession-eagle-organize');await choose('공동');assert.equal((await state()).world.regions['eagle-state'].secession.eagle.phase,'organizing');
// Advance political minimum periods with real monthly calculations. Preserve distressed starting conditions at each milestone.
for(const [months,phaseEvent] of [[6,'secession-eagle-charter'],[18,'secession-eagle-request']]){for(let i=0;i<months;i++)await page.getByRole('button',{name:'다음 달',exact:true}).click();await page.evaluate(()=>{const g=window.birdKingdomDebug.getGameState(),r=g.world.regions['eagle-state'];Object.assign(r.speciesPolitics.eagle,{satisfaction:20,autonomyDemand:92,independenceSentiment:90});r.governance.integration=25;window.birdKingdomDebug.setGameState(g);});await event(phaseEvent);await choose('공동');}
assert.equal((await state()).world.regions['eagle-state'].secession.eagle.phase,'referendum_campaign');console.log('PASS real federal rejection → weighted protest/crackdown → organizing → 6-month charter → 24-month referendum campaign');
await fixture('moderate');await page.evaluate(()=>{const g=window.birdKingdomDebug.getGameState();g.turn=11;g.date={year:2030,month:11};for(const r of Object.values(g.world.statePolitics.relations))r.rivalry=10;const pair=g.world.statePolitics.relations[['eagle-state','owl-state'].sort().join('|')];Object.assign(pair,{relations:45,rivalry:70,cooperation:20});window.birdKingdomDebug.setGameState(g);});await page.getByRole('button',{name:'다음 달',exact:true}).click();g=await state();assert.ok(g.world.statePolitics.relations[['eagle-state','owl-state'].sort().join('|')].mediations.length);console.log('PASS natural federal mediation through real monthly pipeline');
await fixture();await page.evaluate(()=>{const g=window.birdKingdomDebug.getGameState();g.turn=25;g.date={year:2032,month:1};for(const p of Object.values(g.world.federalPolitics)){for(const h of p.history){h.turn=25;h.date=g.date;}}window.birdKingdomDebug.setGameState(g);});for(let i=0;i<5;i++)await month();g=await state();assert.ok(g.world.statePolitics.blocs.some(b=>b.active&&b.purpose==='autonomy'&&b.memberStateIds.includes('eagle-state')&&b.memberStateIds.includes('duck-state')));console.log('PASS shared grievance → NPC joint autonomy → natural bloc and existing federal APIs');
await fixture();const pressure=()=>page.evaluate(async()=>{const {assessConflictPressure,getConflictEventFamilyMultiplier}=await import('/src/game/conflictPressure.ts');const g=window.birdKingdomDebug.getGameState(),j={kind:'region',id:'eagle-state'};return [assessConflictPressure(g,j).separatistPressure,getConflictEventFamilyMultiplier(g,j,'autonomy')];});const before=await pressure();await event('autonomy-protest');await choose('양보 협상');const after=await pressure();assert.ok(after[0]<before[0]&&after[1]<before[1]);console.log('PASS compromise lowers actual pressure and follow-up multiplier',before,after);
if(mobile){for(const width of [320,390,640]){await page.setViewportSize({width,height:844});await fixture();await event('autonomy-protest');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:'.test-output/pressure-mobile-'+width+'.png'});await choose('양보 협상');}}else await page.screenshot({path:'.test-output/pressure-pc.png'});assert.deepEqual(errors,[]);console.log('PRESSURE_BROWSER_RESULT 0',mobile?'mobile':'pc');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
