const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const mobile=!!process.env.BIRD_MOBILE,ctx=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('bird-kingdom:tutorial-offered','true'));await page.goto(process.env.BIRD_TEST_URL||'http://127.0.0.1:5175');
 const fits=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('.patch-new').waitFor();await page.getByRole('button',{name:/패치노트 보기/}).click();const patch=page.getByRole('dialog',{name:'패치노트'});await patch.waitFor();assert.equal(await page.locator('.patch-new').count(),0);await fits();
 await patch.getByText('AI 전략',{exact:true}).scrollIntoViewIfNeeded();assert.equal(await patch.evaluate(el=>el.getAnimations({subtree:true}).length),0);await patch.locator('summary').click();await patch.getByText('v1.0 국가 운영의 시작',{exact:true}).waitFor();await patch.getByRole('button',{name:'닫기',exact:true}).focus();await page.keyboard.press('Shift+Tab');await page.waitForFunction(()=>document.querySelector('.report-dialog').contains(document.activeElement));await page.keyboard.press('Escape');await patch.waitFor({state:'hidden'});await page.reload();assert.equal(await page.locator('.patch-new').count(),0);console.log('PASS patch NEW/read/reload/past/focus/overflow');
 await page.getByRole('button',{name:'새 게임',exact:true}).click();await page.getByRole('button',{name:'공화국 운영 시작',exact:true}).click();
 const state=()=>page.evaluate(()=>window.birdKingdomDebug.getGameState()),button=page.getByRole('button',{name:'다음 달',exact:true});
 async function quiet(){await page.evaluate(()=>{const d=window.birdKingdomDebug;d.setMortalityRisk(0);d.setElectionRoll(0);d.setEventRoll(.999999);d.setCrisisRoll(.999999);d.setStrategicAIEnabled(false);});}
 await quiet();for(let i=0;i<11;i++)await button.click();assert.equal((await state()).annual.summaries.length,0);await button.click();let report=page.getByRole('dialog',{name:'2030년 연간 보고',exact:true});await report.waitFor();assert.equal((await state()).annual.summaries.length,1);await report.getByText('GDP',{exact:true}).waitFor();await report.getByText('총인구',{exact:true}).waitFor();await fits();assert.equal(await report.evaluate(el=>el.getAnimations({subtree:true}).length),0);await report.locator('.report-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);assert.equal(await report.getByRole('button',{name:'닫기',exact:true}).isVisible(),true);await page.screenshot({path:'.test-output/annual-'+(mobile?'mobile':'desktop')+'.png'});await report.getByRole('button',{name:'닫기',exact:true}).click();await button.click();assert.equal((await state()).turn,14);console.log('PASS actual 12 advances, GDP/population, close and continue, no animation');
 const setting=page.getByRole('checkbox',{name:'연간 보고 자동 표시',exact:true});await setting.uncheck();for(let i=0;i<11;i++)await button.click();assert.equal((await state()).annual.summaries.length,2);assert.equal(await page.locator('.annual-dialog').count(),0);
 const nav=async name=>{const menu=page.getByRole('button',{name:'메뉴 열기',exact:true});if(await menu.isVisible())await menu.click();await page.getByRole('navigation',{name:'정부 운영 메뉴'}).getByRole('button',{name,exact:true}).click();};
 await nav('기록');await page.getByRole('button',{name:'연간 보고서',exact:true}).click();await page.locator('.annual-history-card').first().click();await page.getByRole('dialog',{name:'2031년 연간 보고',exact:true}).waitFor();await page.keyboard.press('Escape');await page.reload();await page.getByRole('button',{name:'새 게임',exact:true}).click();await page.getByRole('button',{name:'공화국 운영 시작',exact:true}).click();assert.equal(await setting.isChecked(),false);await quiet();console.log('PASS OFF still generates, History reopen, preference survives reload');
 await setting.check();
 let fixtureSeed=41001;async function fixture(country,region){await page.evaluate(async({country,region,seed})=>{const {createGame}=await import('/src/game/engine.ts');window.birdKingdomDebug.setGameState(createGame(country,region,seed));},{country,region,seed:fixtureSeed++});await quiet();}
 await fixture('pigeon','eagle-state');await page.evaluate(async()=>{const {performFederalAction}=await import('/src/game/federalPolitics.ts');const {performStateAction}=await import('/src/game/stateRelations.ts');const d=window.birdKingdomDebug;let g=performFederalAction(d.getGameState(),'eagle-state','confront');g=performStateAction(g,'eagle-state','duck-state','counter_policy','autonomy',null);d.setGameState(g);});for(let i=0;i<12;i++)await button.click();await page.getByRole('dialog',{name:'2030년 연간 보고',exact:true}).waitFor();let g=await state();assert.equal(g.annual.summaries[0].jurisdictionName,'독수리주');assert.ok(g.annual.summaries[0].majorEvents.some(e=>e.category==='politics'));assert.ok(g.annual.summaries[0].majorEvents.some(e=>e.title.includes('오리주')));await page.keyboard.press('Escape');console.log('PASS federal/state actions through existing APIs appear in report');
 await fixture('pigeon','eagle-state');for(let i=0;i<5;i++)await button.click();await page.evaluate(async()=>{const {performFederalAction}=await import('/src/game/federalPolitics.ts');const {synchronizeAnnualJurisdiction}=await import('/src/game/annual.ts');const d=window.birdKingdomDebug;d.setGameState(synchronizeAnnualJurisdiction(performFederalAction(d.getGameState(),'eagle-state','declare')));});for(let i=0;i<7;i++)await button.click();report=page.getByRole('dialog',{name:'2030년 연간 보고',exact:true});await report.waitFor();g=await state();assert.ok(g.annual.summaries[0].jurisdictionName.includes('공화국'));assert.equal(g.annual.summaries[0].comparisonLabel,'관할 변경 이후');assert.ok(g.annual.summaries[0].majorEvents.some(e=>['country','independence'].includes(e.category)));await fits();await page.keyboard.press('Escape');console.log('PASS midyear independence, founding baseline, independence event');
 await fixture('sparrow',null);await page.evaluate(()=>{for(let i=0;i<32;i++)document.querySelector('.next-month').click();});await page.locator('.annual-dialog').waitFor();assert.equal((await state()).turn,13);assert.equal((await state()).annual.summaries.length,1);await page.keyboard.press('Escape');await page.evaluate(()=>{for(let i=0;i<32;i++)document.querySelector('.next-month').click();});await page.getByRole('dialog',{name:'2031년 연간 보고',exact:true}).waitFor();assert.equal((await state()).turn,25);assert.equal((await state()).annual.summaries.length,2);await page.keyboard.press('Escape');console.log('PASS rapid same-frame clicks cannot skip or duplicate reports');
 await fixture('sparrow',null);await page.evaluate(async()=>{const {createSaveData,deserializeSave}=await import('/src/game/save.ts');const d=window.birdKingdomDebug,g=d.getGameState();g.turn=7;g.date={year:2030,month:7};const save=createSaveData(g,'v6-browser');save.saveVersion=6;delete save.game.annual;const loaded=deserializeSave(JSON.stringify(save));if(loaded.saveVersion!==7||loaded.game.annual.summaries.length)throw Error('migration');d.setGameState(loaded.game);});for(let i=0;i<6;i++)await button.click();await page.locator('.annual-dialog').waitFor();assert.equal((await state()).annual.summaries[0].comparisonLabel,'기록 시작 이후');await page.keyboard.press('Escape');console.log('PASS v6 browser import initializes partial-year baseline and closes normally');
 // A year-end mandatory tutorial event is handled before the report.
 await fixture('sparrow',null);await page.evaluate(async()=>{const {activateTutorial,scheduleTutorial,skipTutorial}=await import('/src/game/tutorial.ts');const {collectAnnualReport}=await import('/src/game/annual.ts');const d=window.birdKingdomDebug,base=d.getGameState();let g=activateTutorial(base);g.turn=13;g.date={year:2031,month:1};g.tutorial.stepId='event-wait';g=scheduleTutorial(g);g=skipTutorial(g);g=collectAnnualReport({...base,date:{year:2030,month:12}},g);d.setGameState(g);});await page.locator('.event-dialog').waitFor();assert.equal(await page.locator('.annual-dialog').count(),0);assert.equal(await button.isDisabled(),true);await page.locator('.event-dialog').getByRole('button').first().click();await page.locator('.annual-dialog').waitFor();await page.keyboard.press('Escape');console.log('PASS mandatory event then annual report, no softlock');
 await fixture('sparrow',null);await page.evaluate(async()=>{const {createGame,advanceMonth}=await import('/src/game/engine.ts');const {activateTutorial}=await import('/src/game/tutorial.ts');let g=createGame('sparrow');const tutorial=activateTutorial(g).tutorial;for(let i=0;i<12;i++)g=advanceMonth(g,{mortalityRiskOverride:0,electionRandom:()=>0,eventOccurrenceRandom:()=>.999999,crisisRandom:()=>.999999,strategicAI:false});g={...g,tutorial};window.birdKingdomDebug.setGameState(g);});await page.locator('.tutorial-guide').waitFor();assert.equal(await page.locator('.annual-dialog').count(),0);assert.equal((await state()).annual.summaries.length,1);console.log('PASS tutorial suppresses automatic report');
 await fixture('sparrow',null);for(let i=0;i<11;i++)await button.click();await page.evaluate(()=>window.birdKingdomDebug.setMortalityRisk(1));await button.click();await page.getByText('GOOD END',{exact:true}).waitFor();assert.equal(await page.locator('.annual-dialog').count(),0);assert.equal((await state()).annual.summaries.length,1);console.log('PASS simultaneous annual and game over prioritizes ending');
 assert.deepEqual(errors,[]);console.log('REPORTS_BROWSER_RESULT 0',mobile?'mobile':'desktop');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
