import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createGame, advanceMonth } from './legacyEngine';
import { applySecessionAction, calculateReferendumSupport, canOrganize, canRequestReferendum, canDeclareUnilaterally, createBreakawayCountry, movementRuntime, updateWorldSecession, centralResponse } from '../src/game/secession';
import { allEventDefinitions, calculateEventChance, generateWorldEvents, resolvePendingEvent } from './legacyEvents';
import { countryInfo, derivedCountryRuntime, ownedRegions } from '../src/game/runtime';
import { selectControlledRuntime } from '../src/game/world';
import { updateWorldSpeciesPolitics } from '../src/game/speciesPolitics';
import { setControlledTaxPolicy } from '../src/game/taxPolicy';
import { setControlledBudgetPolicy } from '../src/game/budgetPolicy';
import { createSeededRandom } from '../src/game/random';
import { taxFields, taxPolicyConfig } from '../src/game/fiscalConfig';
import type { GameState, Jurisdiction, SpeciesId } from '../src/game/types';
const eagle:Jurisdiction={kind:'region',id:'eagle-state'},sparrow:Jurisdiction={kind:'country',id:'sparrow'};
const opts={economyRandom:()=>.5,electionRandom:()=>0,mortalityRandom:()=>.99,eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5,secessionRandom:()=>.99};
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<Math.max(1,Math.abs(b))*1e-10,`${a} != ${b}`);
function scenario(j=eagle,id:SpeciesId='eagle') {const g=j.kind==='region'?createGame('pigeon',j.id):createGame('sparrow');const r=j.kind==='region'?g.world.regions[j.id]:g.world.countries[j.id];Object.assign(r.speciesPolitics![id]!,{satisfaction:20,autonomyDemand:90,independenceSentiment:90});r.governance!.integration=20;return g;}
function event(g:GameState,j:Jurisdiction,id:SpeciesId,stage:string,choice='balance'){
  const eventId=`secession-${id}-${stage}`;g={...g,events:{...g.events,pendingEvent:{id:`${g.turn}:${eventId}`,eventId,date:{...g.date},turn:g.turn,jurisdiction:j,severity:2}}};
  return resolvePendingEvent(g,choice,()=>.5,()=>.99);
}
function wait(g:GameState,n:number){for(let i=0;i<n;i++)g=updateWorldSecession({...g,turn:g.turn+1});return g;}
function prepared(j=eagle,id:SpeciesId='eagle'){
  let g=scenario(j,id);g=event(g,j,id,'organize');g=wait(g,6);g=event(g,j,id,'charter');g=wait(g,18);g=event(g,j,id,'request');
  // 주정부의 극단 조건에서는 중앙 기본 대응이 거부. 합법 경로는 완화된 요구를 사용합니다.
  const r=j.kind==='region'?g.world.regions[j.id]:g.world.countries[j.id];r.speciesPolitics![id]!.independenceSentiment=75;
  g=event(g,j,id,'approval','invest');g=wait(g,6);g=event(g,j,id,'ballot');return g;
}
function verify(g:GameState){for(const r of [...Object.values(g.world.countries),...Object.values(g.world.regions)]){near(r.economy.gdp,Object.values(r.economy.industries).reduce((s,i)=>s+i.output,0));assert.equal(r.population.total,Object.values(r.population.species).reduce((s,p)=>s+p.population,0));for(const p of Object.values(r.population.species))assert.ok(Number.isSafeInteger(p.population)&&p.population>=0);for(const m of Object.values(r.secession??{}))assert.ok(m.grantedAutonomy>=0&&m.grantedAutonomy<=100);for(const n of [r.economy.gdp,r.fiscal.treasury,r.fiscal.debt])assert.ok(Number.isFinite(n)&&n>=0);}for(const r of Object.values(g.world.regions))assert.ok(g.world.countries[r.ownerCountryId]);for(const c of Object.values(g.world.countries))if(c.simulationMode==='aggregate_regions'){near(c.economy.gdp,ownedRegions(g.world,c.id).reduce((s,r)=>s+r.economy.gdp,0));assert.equal(c.population.total,ownedRegions(g.world,c.id).reduce((s,r)=>s+r.population.total,0));}}
function freeze<T>(v:T):T{if(v&&typeof v==='object'){Object.freeze(v);Object.values(v).forEach(freeze);}return v;}
for(const country of ['sparrow','pigeon-state','eagle-state','owl-state','duck-state'])test(`${country} 주요종족 운동 초기 inactive·타이머0·자치범위·독립객체`,()=>{const g=createGame('sparrow'),r=country==='sparrow'?g.world.countries.sparrow:g.world.regions[country];assert.equal(Object.keys(r.secession!).length,4);for(const m of Object.values(r.secession!)){assert.equal(m.phase,'inactive');assert.equal(m.monthsActive,0);assert.equal(m.referendumScheduledInMonths,null);assert.ok(m.grantedAutonomy>=10&&m.grantedAutonomy<=60);}verify(g);});
test('초기 실제자치10/20/15/15 및 연방주류55/60/58/58',()=>{const g=createGame('sparrow');assert.deepEqual(Object.values(g.world.countries.sparrow.secession!).map(m=>m.grantedAutonomy),[10,20,15,15]);assert.deepEqual(['pigeon','eagle','owl','duck'].map(id=>g.world.regions[`${id}-state`].secession![id as SpeciesId]!.grantedAutonomy),[55,60,58,58]);});
test('자치 확대는 만족도 상승·요구/독립 완화 target·작은 통합 부담',()=>{const g=scenario(sparrow,'crow'),a=applySecessionAction(g,sparrow,'crow','expand');assert.equal(a.world.countries.sparrow.secession!.crow!.grantedAutonomy,40);assert.ok(a.world.countries.sparrow.speciesPolitics!.crow!.satisfaction>g.world.countries.sparrow.speciesPolitics!.crow!.satisfaction);assert.ok(a.world.countries.sparrow.governance!.integration<g.world.countries.sparrow.governance!.integration);const base=structuredClone(g);base.world.countries.sparrow.speciesPolitics=structuredClone(a.world.countries.sparrow.speciesPolitics);base.world.countries.sparrow.governance=structuredClone(a.world.countries.sparrow.governance);const aNext=updateWorldSpeciesPolitics(a.world),bNext=updateWorldSpeciesPolitics(base.world);assert.ok(aNext.countries.sparrow.speciesPolitics!.crow!.autonomyDemand<=bNext.countries.sparrow.speciesPolitics!.crow!.autonomyDemand);assert.ok(aNext.countries.sparrow.speciesPolitics!.crow!.independenceSentiment<=bNext.countries.sparrow.speciesPolitics!.crow!.independenceSentiment);});
test('자치 거부는 독립 상승·거부턴 보관·100 자치상한',()=>{let g=scenario();const b=g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment;g=applySecessionAction(g,eagle,'eagle','refuse');assert.ok(g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment>b);assert.equal(g.world.regions[eagle.id].secession!.eagle!.lastRefusalTurn,g.turn);for(let i=0;i<10;i++)g=applySecessionAction(g,eagle,'eagle','expand');assert.equal(g.world.regions[eagle.id].secession!.eagle!.grantedAutonomy,100);verify(g);});
test('낮은 독립은 운동 후보 아님·극단 숫자도 직접 국가생성 금지',()=>{const g=createGame('sparrow');assert.equal(canOrganize(movementRuntime(g,eagle),'eagle'),false);const high=scenario();assert.equal(canOrganize(movementRuntime(high,eagle),'eagle'),true);assert.throws(()=>createBreakawayCountry(high,eagle,'eagle'));assert.throws(()=>applySecessionAction(high,eagle,'eagle','approve'));});
test('최소6개월 헌장·최소24개월 운동·캠페인12개월·단계순서',()=>{let g=scenario();g=event(g,eagle,'eagle','organize');assert.throws(()=>event(g,eagle,'eagle','charter'));g=wait(g,6);g=event(g,eagle,'eagle','charter');g=wait(g,12);assert.equal(canRequestReferendum(movementRuntime(g,eagle),'eagle'),false);g=wait(g,6);assert.equal(canRequestReferendum(movementRuntime(g,eagle),'eagle'),true);g=event(g,eagle,'eagle','request');assert.equal(g.world.regions[eagle.id].secession!.eagle!.phase,'referendum_campaign');assert.equal(g.world.regions[eagle.id].secession!.eagle!.monthsInPhase,0);});
test('승인6개월 정확한 예정·투표 RNG 1회·가결은 즉시 국가 생성 아님',()=>{let g=scenario();const m=g.world.regions[eagle.id].secession!.eagle!;m.phase='referendum_campaign';m.monthsActive=24;g=applySecessionAction(g,eagle,'eagle','approve');let calls=0;for(let i=0;i<5;i++){g=updateWorldSecession(g);assert.throws(()=>applySecessionAction(g,eagle,'eagle','vote',()=>{calls++;return .99}));}assert.equal(calls,0);g=updateWorldSecession(g);g=applySecessionAction(g,eagle,'eagle','vote',()=>{calls++;return .99});assert.equal(calls,1);assert.equal(g.world.regions[eagle.id].secession!.eagle!.phase,'transition');assert.equal(Object.keys(g.world.countries).length,2);assert.throws(()=>createBreakawayCountry(g,eagle,'eagle'));});
test('주민투표 지지 계산은 RNG 재현·독립 상승/통합 하락 영향',()=>{const g=scenario(),a=calculateReferendumSupport(g,eagle,'eagle',createSeededRandom(42));assert.equal(a,calculateReferendumSupport(g,eagle,'eagle',createSeededRandom(42)));g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment-=20;assert.ok(calculateReferendumSupport(g,eagle,'eagle',createSeededRandom(42))<a);g.world.regions[eagle.id].governance.integration=90;assert.ok(calculateReferendumSupport(g,eagle,'eagle',createSeededRandom(42))<a);assert.throws(()=>calculateReferendumSupport(g,eagle,'eagle',()=>NaN));});
test('찬성 정확50 부결·낮은 지지 부결·독립 미발생',()=>{let g=scenario();const r=g.world.regions[eagle.id];Object.assign(r.speciesPolitics.eagle!,{independenceSentiment:50,autonomyDemand:100,satisfaction:50});r.governance.integration=50;r.secession!.eagle!.phase='referendum_scheduled';r.secession!.eagle!.referendumScheduledInMonths=0;g=applySecessionAction(g,eagle,'eagle','vote',()=>0);assert.equal(g.world.regions[eagle.id].secession!.eagle!.lastReferendumResult!.yesShare,50);assert.equal(g.world.regions[eagle.id].secession!.eagle!.lastReferendumResult!.passed,false);assert.equal(Object.keys(g.world.countries).length,2);});
test('NPC 중앙 기본 규칙은 보통 요구 양보·투표지지 승인·극단 거부',()=>{const g=scenario();assert.equal(centralResponse(g,eagle,'eagle'),'refuse');g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment=65;assert.equal(centralResponse(g,eagle,'eagle'),'approve');g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment=35;assert.equal(centralResponse(g,eagle,'eagle'),'concede');});
test('독수리 합법독립 E2E·소유 변경/상태승계·연방 제외·국가집계·이중재정 없음',()=>{let g=prepared();g=wait(g,6);const before=structuredClone(g.world.regions[eagle.id]);g=event(g,eagle,'eagle','foundation');const c=g.world.countries['eagle-republic-1'],r=g.world.regions[eagle.id];assert.equal(r.ownerCountryId,c.id);assert.equal(c.identity!.name,'독수리공화국');assert.equal(c.identity!.status,'established');for(const key of ['economy','population','social','governance','fiscal'] as const)assert.deepEqual(r[key],before[key]);assert.equal(r.speciesPolitics.eagle!.autonomyDemand,10);assert.equal(r.speciesPolitics.eagle!.independenceSentiment,5);assert.equal(c.fiscal.treasury,before.fiscal.treasury);verify(g);const n=advanceMonth(g,opts);assert.equal(n.world.countries[c.id].fiscal.treasury,n.world.regions[eagle.id].fiscal.treasury);assert.notDeepEqual(n.world.regions[eagle.id].economy,r.economy);verify(n);});
test('주지사→대통령·control 국가/null·임기/승리/기록/나이 유지·새국 정책/선거',()=>{let g=wait(prepared(),6);g.player.career.monthsInCurrentTerm=42;g.player.career.termNumber=3;g.player.career.electionsWon=2;const before=structuredClone(g.player);g=event(g,eagle,'eagle','foundation');assert.equal(g.player.controlledCountryId,'eagle-republic-1');assert.equal(g.player.controlledRegionId,null);assert.equal(g.player.career.office,'president');assert.equal(g.player.career.monthsInCurrentTerm,42);assert.equal(g.player.career.termNumber,3);assert.equal(g.player.career.electionsWon,2);assert.equal(g.player.ageMonths,before.ageMonths);assert.equal(g.gameOverReason,null);const runtime=selectControlledRuntime(g);g=setControlledTaxPolicy(g,{...runtime.fiscal.taxPolicy,incomeTaxRate:11});g=setControlledBudgetPolicy(g,{...runtime.fiscal.budgetPolicy,education:1});assert.equal(g.world.regions[eagle.id].fiscal.taxPolicy.incomeTaxRate,11);assert.equal(g.world.regions[eagle.id].fiscal.budgetPolicy.education,1);for(let i=0;i<6;i++){g=advanceMonth(g,opts);if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',()=>.5,()=>.99);}assert.equal(g.player.career.termNumber,4);assert.equal(g.player.career.electionsWon,3);});
test('까마귀 중앙국 분리 E2E·동적 영토·인구/산업/GDP/국고/부채 보존·부모 플레이 유지',()=>{let g=wait(prepared(sparrow,'crow'),6);const before=structuredClone(g.world.countries.sparrow);g=event(g,sparrow,'crow','foundation');const child=g.world.countries['crow-republic-1'],parent=g.world.countries.sparrow,r=g.world.regions['crow-nest-1'];assert.ok(r.regionIdentity!.isDynamic);assert.equal(child.identity!.name,'까마귀공화국');assert.equal(g.player.controlledCountryId,'sparrow');assert.equal(child.population.total+parent.population.total,before.population.total);near(child.economy.gdp+parent.economy.gdp,before.economy.gdp);for(const id of Object.keys(before.economy.industries) as (keyof typeof before.economy.industries)[])near(child.economy.industries[id].output+parent.economy.industries[id].output,before.economy.industries[id].output);near(parent.fiscal.treasury+child.fiscal.treasury,before.fiscal.treasury);near(parent.fiscal.debt+child.fiscal.debt,before.fiscal.debt);assert.ok(child.economy.gdp/before.economy.gdp<.25);assert.equal(parent.speciesPolitics!.crow!.independenceSentiment,before.speciesPolitics!.crow!.independenceSentiment);assert.equal(parent.secession!.crow!.phase,'completed');verify(g);});
test('반올림 인구 흐름·모든종족 정확보존·input freeze·정치/사회범위',()=>{const g=wait(prepared(sparrow,'crow'),6),before=structuredClone(g);const n=createBreakawayCountry(freeze(g),sparrow,'crow');assert.deepEqual(g,before);for(const id of Object.keys(before.world.countries.sparrow.population.species) as SpeciesId[]){const a=n.world.countries.sparrow.population.species[id]!,b=n.world.regions['crow-nest-1'].population.species[id]!,old=before.world.countries.sparrow.population.species[id]!;for(const key of ['population','birthsLastMonth','deathsLastMonth','migrationLastMonth'] as const)assert.equal(a[key]+b[key],old[key]);}verify(n);});
test('일방 독립: 기간/최근거부/극단 모두필수·disputed와 재통합flag·전투없음',()=>{let g=scenario();g.world.regions[eagle.id].secession!.eagle!.phase='autonomy_campaign';assert.equal(canDeclareUnilaterally(g,movementRuntime(g,eagle),'eagle'),false);g=wait(g,24);assert.equal(canDeclareUnilaterally(g,movementRuntime(g,eagle),'eagle'),false);g=applySecessionAction(g,eagle,'eagle','refuse');assert.equal(canDeclareUnilaterally(g,movementRuntime(g,eagle),'eagle'),true);g=event(g,eagle,'eagle','declaration','restrict');const c=g.world.countries['eagle-republic-1'];assert.equal(c.identity!.status,'disputed_breakaway');assert.equal(c.identity!.territorialDispute,'parent_claims_reunification');assert.equal(g.gameOverReason,null);assert.equal('battles' in g.world,false);verify(g);});
test('NPC 까마귀 신생국 모든월 시스템과 사건 계속·플레이어pending로오인 없음',()=>{let g=event(wait(prepared(sparrow,'crow'),6),sparrow,'crow','foundation'),r=g.world.regions['crow-nest-1'];const before=structuredClone(r);g=advanceMonth(g,opts);r=g.world.regions[r.id];for(const key of ['economy','fiscal','population','social','speciesPolitics','governance'] as const)assert.notDeepEqual(r[key],before[key]);g=generateWorldEvents(g,{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>.5,secessionRandom:()=>.99});assert.ok(g.events.history.some(e=>e.jurisdiction.id===r.id&&!e.playerChoice));assert.notEqual(g.events.pendingEvent?.jurisdiction.id,r.id);verify(g);});
test('동적 ID 충돌회피·원본역사/이벤트 지역명·런타임국가메타',()=>{let g=event(wait(prepared(sparrow,'crow'),6),sparrow,'crow','foundation');const r=g.world.countries.sparrow;r.secession!.crow!.phase='transition';r.secession!.crow!.monthsInPhase=6;r.secession!.crow!.lastReferendumResult={date:g.date,yesShare:80,passed:true};g=createBreakawayCountry(g,sparrow,'crow');assert.ok(g.world.countries['crow-republic-2']);assert.notEqual(countryInfo(g,'crow-republic-1').name,countryInfo(g,'crow-republic-2').name);verify(g);});
test('소유권집계: 마지막주까지분리 후 빈연방 GDP/인구0·ghostsimulation 없음',()=>{let g=createGame('sparrow');for(const r of Object.values(g.world.regions))r.ownerCountryId='sparrow';g=advanceMonth(g,opts);assert.equal(g.world.countries.pigeon.economy.gdp,0);assert.equal(g.world.countries.pigeon.population.total,0);assert.equal(g.world.countries.pigeon.social,undefined);verify(g);});
test('11종 정치 사건×8종족·기존29개 유지·3선택과소속관점',()=>{assert.ok(allEventDefinitions.length>=117);for(const e of allEventDefinitions.slice(29))assert.equal(e.choices.length,3);const g=scenario(),e=allEventDefinitions.find(e=>e.id==='secession-eagle-negotiation')!;assert.match(e.choices[0].labelFor!({game:g,jurisdiction:eagle,runtime:movementRuntime(g,eagle)}),/연방정부/);});
test('기존집회/청원이 조직확률을 상승·낮은성향후보0',()=>{const g=scenario();const id='secession-eagle-organize',base=calculateEventChance(id,g,eagle);g.events.history.push({id:'prior',eventId:'eagle-assembly',title:'집회',choiceId:'restrict',choiceLabel:'거부',category:'species',date:g.date,turn:g.turn,jurisdiction:eagle,severity:2,playerChoice:true});assert.ok(calculateEventChance(id,g,eagle)>base);g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment=10;assert.equal(calculateEventChance(id,g,eagle),0);});
test('투표/수립 일정사건은 RNG 없이 우선·pending1개·확정후역사 기록',()=>{const g=prepared();assert.equal(g.world.regions[eagle.id].secession!.eagle!.phase,'transition');const due=wait(g,6);const n=generateWorldEvents(due,{eventOccurrenceRandom:()=>.999999,eventOutcomeRandom:()=>.5});assert.equal(n.events.pendingEvent!.eventId,'secession-eagle-foundation');const done=resolvePendingEvent(n,'balance',()=>.5,()=>.99);assert.ok(done.events.history[0].eventId.endsWith('foundation'));assert.ok(done.logs.some(l=>/독수리공화국 수립/.test(l.message)));});
test('secession RNG는비투표월 경제/사망/선거/사건 RNG 소비와 결과에 영향없음',()=>{const g=createGame('sparrow');const a=advanceMonth(g,{...opts,secessionRandom:()=>{throw new Error('투표 아님')}}),b=advanceMonth(g,{...opts,secessionRandom:()=>.01});assert.deepEqual(a,b);});
test('독립 후 투표 결과와 소수 종족 실제자치 보존',()=>{let g=wait(prepared(),6);const result=structuredClone(g.world.regions[eagle.id].secession!.eagle!.lastReferendumResult);g.world.regions[eagle.id].secession!.owl!.grantedAutonomy=65;g=event(g,eagle,'eagle','foundation');assert.deepEqual(g.world.regions[eagle.id].secession!.eagle!.lastReferendumResult,result);assert.equal(g.world.regions[eagle.id].secession!.owl!.grantedAutonomy,65);});
test('거부24개월 만료·낮은 독립/높은통합은 일방선언 제외',()=>{let g=scenario();g.world.regions[eagle.id].secession!.eagle!.phase='autonomy_campaign';g=wait(g,24);g=applySecessionAction(g,eagle,'eagle','refuse');assert.equal(canDeclareUnilaterally(g,movementRuntime(g,eagle),'eagle'),true);g=wait(g,25);assert.equal(canDeclareUnilaterally(g,movementRuntime(g,eagle),'eagle'),false);g=applySecessionAction(g,eagle,'eagle','refuse');g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment=79;assert.equal(canDeclareUnilaterally(g,movementRuntime(g,eagle),'eagle'),false);g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment=90;g.world.regions[eagle.id].governance.integration=70;assert.equal(canDeclareUnilaterally(g,movementRuntime(g,eagle),'eagle'),false);});
test('투표난수 편차는 세계/경제/선거/사망/사건 난수 소비에 영향없음',()=>{let g=prepared();g.world.regions[eagle.id].secession!.eagle!.phase='referendum_scheduled';g.world.regions[eagle.id].secession!.eagle!.referendumScheduledInMonths=0;const a=event(g,eagle,'eagle','ballot');let pending=structuredClone(g);pending.events.pendingEvent={id:'vote',eventId:'secession-eagle-ballot',date:g.date,turn:g.turn,jurisdiction:eagle,severity:2};const b=resolvePendingEvent(pending,'balance',()=>.5,()=>0);assert.notEqual(a.world.regions[eagle.id].secession!.eagle!.lastReferendumResult!.yesShare,b.world.regions[eagle.id].secession!.eagle!.lastReferendumResult!.yesShare);assert.deepEqual(a.player,b.player);assert.deepEqual(a.world.regions[eagle.id].economy,b.world.regions[eagle.id].economy);assert.deepEqual(a.world.regions[eagle.id].population,b.world.regions[eagle.id].population);});
test('독립한 NPC 국가240개월 정상 계산·유한·집계·고아소유권 없음',()=>{let g=event(wait(prepared(sparrow,'crow'),6),sparrow,'crow','foundation');const streams={economyRandom:createSeededRandom(2066),eventOccurrenceRandom:createSeededRandom(2067),eventOutcomeRandom:createSeededRandom(2068),secessionRandom:createSeededRandom(2069)};for(let i=0;i<240;i++){g=advanceMonth(g,{...opts,...streams});if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',streams.eventOutcomeRandom,streams.secessionRandom);verify(g);}assert.ok(g.world.countries['crow-republic-1'].population.total>0);});
test('지속적인 심각한 사회/경제 위기360개월은 독립60+·운동→투표요구 후보',()=>{let g=createGame('pigeon','eagle-state');const r=g.world.regions[eagle.id];Object.assign(r.economy,{growth:-5,unemployment:25,inflation:15});Object.assign(r.social,{livingStandard:0,education:0,healthcare:0,publicSafety:0,inequality:100});r.governance.integration=0;for(const id of taxFields)r.fiscal.taxPolicy[id]=taxPolicyConfig[id].max;for(let i=0;i<360;i++){g={...g,turn:g.turn+1,world:updateWorldSpeciesPolitics(g.world)};g=updateWorldSecession(g);const runtime=movementRuntime(g,eagle),m=runtime.secession!.eagle!;if(canOrganize(runtime,'eagle'))g=event(g,eagle,'eagle','organize');else if(m.phase==='organizing'&&m.monthsInPhase>=6)g=event(g,eagle,'eagle','charter');}const runtime=movementRuntime(g,eagle);assert.ok(runtime.speciesPolitics.eagle!.independenceSentiment>=60);assert.equal(canRequestReferendum(runtime,'eagle'),true);console.log('SECESSION CRISIS360',JSON.stringify({autonomy:runtime.speciesPolitics.eagle!.autonomyDemand,independence:runtime.speciesPolitics.eagle!.independenceSentiment,phase:runtime.secession!.eagle!.phase}));});
test('주정부의 청원 철회는 중앙 거부 이력으로 기록하지 않음',()=>{let g=scenario();const m=g.world.regions[eagle.id].secession!.eagle!;m.phase='referendum_campaign';m.monthsActive=24;g=event(g,eagle,'eagle','approval','restrict');assert.equal(g.world.regions[eagle.id].secession!.eagle!.lastRefusalTurn,null);assert.equal(g.world.regions[eagle.id].secession!.eagle!.phase,'autonomy_campaign');});
test('기본정책600개월·과도한독립없음·소유/집계/유한·정상독수리',()=>{let g=createGame('sparrow');const random={economyRandom:createSeededRandom(2030),eventOccurrenceRandom:createSeededRandom(5544),eventOutcomeRandom:createSeededRandom(9966),secessionRandom:createSeededRandom(600)};for(let i=0;i<600;i++){g=advanceMonth(g,{...opts,...random});if(g.events.pendingEvent)g=resolvePendingEvent(g,'balance',random.eventOutcomeRandom,random.secessionRandom);verify(g);}assert.equal(Object.keys(g.world.countries).length,2);console.log('SECESSION NORMAL600',JSON.stringify({countries:Object.keys(g.world.countries).length,eaglePhase:g.world.regions[eagle.id].secession!.eagle!.phase,eagleIndependence:g.world.regions[eagle.id].speciesPolitics.eagle!.independenceSentiment}));});
