const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const mobile=!!process.env.BIRD_MOBILE,context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5175');
 await page.getByRole('button',{name:'튜토리얼 건너뛰기',exact:true}).click();await page.getByRole('button',{name:'공화국 운영 시작',exact:true}).click();
 const state=()=>page.evaluate(()=>window.birdKingdomDebug.getGameState());
 const nav=async name=>{const b=page.getByRole('button',{name:'메뉴 열기',exact:true});if(await b.isVisible())await b.click();await page.getByRole('navigation',{name:'정부 운영 메뉴'}).getByRole('button',{name,exact:true}).click();};
 const debug=()=>page.evaluate(()=>{window.birdKingdomDebug.setMortalityRisk(0);window.birdKingdomDebug.setElectionRoll(0);window.birdKingdomDebug.setEventRoll(.999999);window.birdKingdomDebug.setCrisisRoll(.999999);window.birdKingdomDebug.setStrategicAIEnabled(false);});
 const fixture=async kind=>{await page.evaluate(async kind=>{const {stateFixture}=await import('/tests/stateFixtures.ts');window.birdKingdomDebug.setGameState(stateFixture(kind));},kind);await debug();await nav('정치');};
 const section=()=>page.getByRole('region',{name:'연방 내부관계',exact:true});
 const pair=(g,a,b)=>Object.values(g.world.statePolitics.relations).find(r=>[r.stateAId,r.stateBId].includes(a)&&[r.stateAId,r.stateBId].includes(b));
 const select=async id=>section().getByRole('combobox',{name:'상대 주',exact:true}).selectOption(id);
 const action=async label=>section().getByRole('button',{name:label,exact:true}).click();
 await nav('정치');assert.equal(await section().count(),0);
 await fixture('friend');await select('owl-state');let before=await state();await action('상대 주 공개 비판');let g=await state(),r=pair(g,'eagle-state','owl-state');assert.ok(r.relations<pair(before,'eagle-state','owl-state').relations);assert.ok(r.rivalry>pair(before,'eagle-state','owl-state').rivalry);assert.equal(r.history.at(-1).action,'criticize');assert.equal(await section().getByRole('button',{name:'상대 주 공개 비판',exact:true}).isEnabled(),false);
 for(let i=0;i<3;i++){assert.equal(await page.getByRole('button',{name:'다음 달',exact:true}).isEnabled(),true);await page.getByRole('button',{name:'다음 달',exact:true}).click();}assert.equal(await section().getByRole('button',{name:'상대 주 공개 비판',exact:true}).isEnabled(),true);console.log('PASS actual criticism, response, 3-month cooldown and free time progression');
 await fixture('friend');await select('duck-state');await action('자치 공동전선 제안');g=await state();assert.equal(g.world.statePolitics.blocs.filter(b=>b.active&&b.purpose==='autonomy').length,1);for(const id of ['eagle-state','duck-state'])assert.equal(g.world.federalPolitics[id].history.at(-1).action,'autonomy');
 await page.getByRole('button',{name:'저장 / 불러오기',exact:true}).click();await page.locator('[data-slot="manual-1"]').getByRole('button',{name:'저장',exact:true}).click();if(await page.locator('.save-confirm').count())await page.locator('.save-confirm').getByRole('button',{name:'확인',exact:true}).click();await page.getByText('저장되었습니다.',{exact:true}).waitFor();await page.keyboard.press('Escape');await page.reload();await page.getByRole('button',{name:'이어하기',exact:true}).click();await page.locator('[data-slot="manual-1"]').getByRole('button',{name:'불러오기',exact:true}).click();await page.locator('.topbar').waitFor();await debug();await nav('정치');g=await state();assert.equal(g.world.statePolitics.blocs.filter(b=>b.active).length,1);assert.equal(pair(g,'eagle-state','duck-state').history.at(-1).action,'joint_autonomy');assert.equal(g.world.statePolitics.actionCooldowns['eagle-state'],g.turn+3);console.log('PASS joint front calls both existing federal APIs and manual save/load preserves it');
 await fixture('biased');await select('pigeon-state');before=await state();await action('연방 조사·중재 요구');g=await state();r=pair(g,'eagle-state','pigeon-state');assert.equal(r.mediations.at(-1).favoredStateId,'pigeon-state');assert.ok(g.world.regions['eagle-state'].governance.integration<before.world.regions['eagle-state'].governance.integration);assert.ok(g.world.regions['eagle-state'].speciesPolitics.eagle.autonomyDemand>before.world.regions['eagle-state'].speciesPolitics.eagle.autonomyDemand);console.log('PASS actual biased federal mediation and losing-state backlash');
 const inherited=[];
 for(const kind of ['friend','hostile']){await fixture(kind);const declare=async()=>{await page.getByRole('region',{name:'연방정치',exact:true}).getByRole('button',{name:'일방 독립 선언',exact:true}).click();await page.getByRole('button',{name:'일방 독립 확정',exact:true}).click();};await declare();g=await state();const eagle=g.player.controlledCountryId;assert.notEqual(eagle,'pigeon');assert.equal(await section().count(),0);
 // Move the observer to the second governor, preserving the real first declaration and world.
 await page.evaluate(()=>{const g=window.birdKingdomDebug.getGameState();g.player.controlledCountryId='pigeon';g.player.controlledRegionId='duck-state';g.player.career.office='governor';g.gameOverReason=null;window.birdKingdomDebug.setGameState(g);});await nav('정치');await declare();g=await state();const duck=g.player.controlledCountryId,international=Object.values(g.world.diplomacy.relations).find(x=>[x.countryA,x.countryB].includes(eagle)&&[x.countryA,x.countryB].includes(duck));assert.ok(international,'two new countries have real international relation');inherited.push(international);assert.equal(pair(g,'eagle-state','duck-state').active,false);assert.equal(await section().count(),0);console.log('PASS',kind,'two actual independence declarations inherit partial bias',international.relations,international.trust);}
 assert.ok(inherited[0].relations>inherited[1].relations);assert.ok(inherited[0].trust>inherited[1].trust);assert.ok(inherited[0].relations<82);assert.ok(inherited[1].relations>15-50);
 if(mobile){for(const width of [320,390,640]){await page.setViewportSize({width,height:844});await fixture('friend');await select('duck-state');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await action('정치협력 제안');assert.equal((await state()).world.statePolitics.blocs.filter(b=>b.active).length,1);await section().scrollIntoViewIfNeeded();await page.screenshot({path:'.test-output/state-mobile-'+width+'.png'});}}
 else {await fixture('friend');await select('duck-state');await action('자치 공동전선 제안');await section().scrollIntoViewIfNeeded();await page.screenshot({path:'.test-output/state-pc.png'});}
 assert.deepEqual(errors,[]);console.log('STATE_BROWSER_RESULT 0',mobile?'mobile':'pc');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});

