const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const mobile=!!process.env.BIRD_MOBILE,page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('bird-kingdom:annual-autopopup','false'));await page.goto('http://127.0.0.1:5175');await page.getByRole('button',{name:'튜토리얼 건너뛰기',exact:true}).click();await page.getByRole('button',{name:'공화국 운영 시작',exact:true}).click();
const state=()=>page.evaluate(()=>window.birdKingdomDebug.getGameState());
const fixture=async kind=>page.evaluate(async kind=>{const {invasionFixture,federalStrategyFixture}=await import('/tests/strategyFixtures.ts');const {pressureFixture}=await import('/tests/pressureFixtures.ts');let g=kind==='attack'||kind==='restraint'?invasionFixture():kind==='bloc'?pressureFixture('unstable'):federalStrategyFixture();g.turn=29;g.date={year:2032,month:5};
if(kind==='attack'){Object.assign(g.world.countries.sparrow.military,{readiness:10,mobilization:0,mobilizationTarget:0,effectiveDefenseBudget:0,fatigue:80});Object.assign(g.world.countries.pigeon.military,{readiness:90,mobilization:60,mobilizationTarget:60,fatigue:0});}
if(kind==='restraint'){g.world.countries.pigeon.fiscal.treasury=0;Object.assign(g.world.countries.pigeon.military,{readiness:20,fatigue:70});}
if(kind==='retreat'){const r=g.world.regions['eagle-state'];r.governance.approval=20;r.governance.stability=20;r.fiscal.treasury=0;}
if(kind==='independence'){g.turn=35;g.date={year:2032,month:11};for(const h of g.world.federalPolitics['eagle-state'].history){h.turn=35;h.date=g.date;}g.world.regions['eagle-state'].governance.integration=15;}
window.birdKingdomDebug.setGameState(g);window.birdKingdomDebug.setMortalityRisk(0);window.birdKingdomDebug.setElectionRoll(0);window.birdKingdomDebug.setEventRoll(.999999);window.birdKingdomDebug.setCrisisRoll(.999999);window.birdKingdomDebug.setStrategicAIEnabled(true);},kind);
const month=async()=>{const button=page.getByRole('button',{name:'거절',exact:true});while(await button.count()){await button.first().click();}await page.getByRole('button',{name:'다음 달',exact:true}).click();};
await fixture('attack');await month();let g=await state();assert.ok(Object.values(g.world.warfare.wars).some(w=>w.legitimacy==='unjustified'));const menu=page.getByRole('button',{name:'메뉴 열기',exact:true});if(await menu.isVisible())await menu.click();await page.getByRole('navigation',{name:'정부 운영 메뉴'}).getByRole('button',{name:'외교',exact:true}).click();assert.ok(await page.getByText(/상대의 군사적 약점과 자국의 지지/).count());console.log('PASS AI actual monthly unjustified war and visible explanation');
await fixture('restraint');await month();g=await state();assert.equal(Object.keys(g.world.warfare.wars).length,0);console.log('PASS AI restraint');
await fixture('federal');await month();g=await state();assert.ok(Object.values(g.world.federalPolitics).some(p=>p.history.some(h=>h.turn===30)));console.log('PASS AI federal demand');
await fixture('retreat');await month();g=await state();const d=await page.evaluate(async()=>{const {evaluateNPCFederalActions}=await import('/src/game/federalStrategy.ts');return evaluateNPCFederalActions(window.birdKingdomDebug.getGameState(),'eagle-state');});assert.ok(d.retreat>30);assert.ok(!g.world.federalPolitics['eagle-state'].history.some(h=>h.turn===30&&h.action==='declare'));console.log('PASS AI retreat');
await fixture('bloc');await month();g=await state();assert.ok(g.world.statePolitics.blocs.some(b=>b.purpose==='autonomy'));assert.ok(Object.values(g.world.federalPolitics).some(p=>p.history.some(h=>h.turn===30&&h.action==='autonomy')));console.log('PASS bloc joint federal action');
await fixture('independence');await month();g=await state();assert.notEqual(g.world.regions['eagle-state'].ownerCountryId,'pigeon');assert.ok(Object.keys(g.world.internalConflicts).length);console.log('PASS AI unilateral independence');
assert.deepEqual(errors,[]);if(mobile)assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:'.test-output/strategy-'+(mobile?'mobile':'pc')+'.png'});console.log('STRATEGY_BROWSER_RESULT 0',mobile?'mobile':'pc');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
