import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createGame,advanceMonth} from '../src/game/engine';
import {activateTutorial,acknowledgeTutorial,observeTutorialAction,scheduleTutorial,skipTutorial,tutorialStep,validateTutorial} from '../src/game/tutorial';
import {tutorialSteps} from '../src/game/tutorialSteps';
import {markTutorialOffered,shouldOfferTutorial,tutorialPreferenceKey} from '../src/game/preferences';
import {selectAttention} from '../src/game/attention';
import {selectControlledRuntime} from '../src/game/world';
import {setControlledTaxPolicy} from '../src/game/taxPolicy';
import {setControlledBudgetPolicy} from '../src/game/budgetPolicy';
import {policyChangeBlock} from '../src/game/policySchedule';
import {setResearch,researchBlock} from '../src/game/technology';
import {technologyDefinitions} from '../src/game/technologyDefinitions';
import {performDiplomaticAction,getBilateralRelation} from '../src/game/diplomacy';
import {getEventDefinition,resolvePendingEvent,generateWorldEvents} from '../src/game/events';
import {respondToForeignProposal} from '../src/game/strategicCommands';
import {respondToAllyRequest} from '../src/game/warfare';
import {createSaveData,serializeSave,deserializeSave,loadGame} from '../src/game/save';
import {resolveElection} from '../src/game/election';
import {startCrisis} from '../src/game/crisis';
import {formatEconomyNumber} from '../src/components/EconomyMetrics';
import {formatPopulation} from '../src/components/PopulationView';
import {contextHelp,glossary} from '../src/game/help';
const fresh=()=>createGame('sparrow',null,2030),start=()=>activateTutorial(fresh());
const setStep=(id:string)=>{const g=start();g.tutorial!.stepId=id;return g;};
function unblock(g:ReturnType<typeof start>){
 if(g.events.pendingEvent)g=observeTutorialAction(g,resolvePendingEvent(g,getEventDefinition(g.events.pendingEvent.eventId).choices[0].id));
 for(const p of g.world.foreignProposals??[])if(p.targetId===g.player.controlledCountryId)g=respondToForeignProposal(g,p.id,false);
 for(const p of g.world.warfare!.allyRequests)if(p.status==='pending'&&p.allyCountryId===g.player.controlledCountryId)g=respondToAllyRequest(g,p.id,false);
 return g;
}
function act(g:ReturnType<typeof start>){const s=tutorialStep(g)!,r=selectControlledRuntime(g);if(s.kind==='read')return acknowledgeTutorial(g,s.menu);
 if(s.id==='tax')return observeTutorialAction(g,setControlledTaxPolicy(g,{...r.fiscal.taxPolicy,incomeTaxRate:r.fiscal.taxPolicy.incomeTaxRate+.5}));
 if(s.id==='budget')return observeTutorialAction(g,setControlledBudgetPolicy(g,{...r.fiscal.budgetPolicy,infrastructure:r.fiscal.budgetPolicy.infrastructure+.3}));
 if(s.id==='technology'){g=setResearch(g,'industry',null);const d=technologyDefinitions.find(d=>!researchBlock(selectControlledRuntime(g).technology!,d.id)&&selectControlledRuntime(g).technology!.domains[d.domain].currentResearchId!==d.id)!;return observeTutorialAction(g,setResearch(g,d.domain,d.id));}
 if(s.id==='diplomacy')return observeTutorialAction(g,performDiplomaticAction(g,'sparrow','pigeon','improve'));
 return advanceMonth(g,{mortalityRiskOverride:0,electionRandom:()=>0});}
function complete(){let g=start();for(let i=0;i<180&&g.tutorial?.mode==='active';i++){g=unblock(g);if(g.tutorial?.mode==='active')g=act(g);}assert.equal(g.tutorial?.mode,'completed');return g;}
test('first play offer persists independently of saves',()=>{const m=new Map<string,string>(),s={getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>{m.set(k,v);}};assert.ok(shouldOfferTutorial(s));markTutorialOffered(s);assert.equal(shouldOfferTutorial(s),false);assert.equal(m.get(tutorialPreferenceKey),'true');});
test('unavailable preferences do not block play',()=>{const s={getItem:()=>{throw Error();},setItem:()=>{throw Error();}};assert.ok(shouldOfferTutorial(s));assert.doesNotThrow(()=>markTutorialOffered(s));});
test('immediate skip does not create tutorial simulation state',()=>{assert.equal(skipTutorial(fresh()).tutorial,undefined);assert.deepEqual(skipTutorial(fresh()),fresh());});
test('tutorial uses normal initial values, country and seed streams',()=>{const g=start(),n=fresh();assert.deepEqual(g.world,n.world);assert.deepEqual(g.random,n.random);assert.deepEqual(g.player,n.player);assert.equal(g.tutorial!.stepId,'overview');});
test('tutorial rejects federal start',()=>assert.throws(()=>activateTutorial(createGame('pigeon','owl-state',2030))));
test('tutorial rejects hard start',()=>assert.throws(()=>activateTutorial(createGame('sparrow',null,2030,'hard'))));
test('read step requires correct screen',()=>assert.equal(acknowledgeTutorial(start(),'budget').tutorial!.stepId,'overview'));
test('read completion is unique and advances',()=>{const g=acknowledgeTutorial(start(),'overview');assert.deepEqual(g.tutorial!.completedStepIds,['overview']);assert.equal(g.tutorial!.stepId,'month');assert.equal(acknowledgeTutorial(g,'overview'),g);});
test('next month blocked until current read/action',()=>assert.equal(advanceMonth(start()).turn,1));
test('actual first month increments date/age and advances guide',()=>{const g=acknowledgeTutorial(start(),'overview'),n=advanceMonth(g,{mortalityRiskOverride:0});assert.equal(n.date.month,2);assert.equal(n.player.ageMonths,g.player.ageMonths+1);assert.equal(n.tutorial!.stepId,'economy');});
test('tax tutorial applies real API without recalculating current GDP',()=>{const g=setStep('tax'),r=selectControlledRuntime(g),n=observeTutorialAction(g,setControlledTaxPolicy(g,{...r.fiscal.taxPolicy,incomeTaxRate:r.fiscal.taxPolicy.incomeTaxRate+.5}));assert.equal(selectControlledRuntime(n).fiscal.taxPolicy.incomeTaxRate,r.fiscal.taxPolicy.incomeTaxRate+.5);assert.equal(selectControlledRuntime(n).economy.gdp,r.economy.gdp);assert.equal(n.tutorial!.stepId,'budget');assert.match(policyChangeBlock(n,'country:sparrow','tax')!,/3개월/);});
test('unchanged tax API cannot fake step completion',()=>{const g=setStep('tax');assert.equal(observeTutorialAction(g,setControlledTaxPolicy(g,selectControlledRuntime(g).fiscal.taxPolicy)),g);});
test('budget tutorial preserves real annual lock',()=>{const g=setStep('budget'),n=observeTutorialAction(g,setControlledBudgetPolicy(g,{...selectControlledRuntime(g).fiscal.budgetPolicy,infrastructure:3}));assert.equal(n.tutorial!.stepId,'population');assert.match(policyChangeBlock(n,'country:sparrow','budget')!,/12개월/);});
test('research tutorial assigns real technology slot',()=>{const g=setResearch(setStep('technology'),'industry',null),d=technologyDefinitions.find(d=>!researchBlock(selectControlledRuntime(g).technology!,d.id)&&selectControlledRuntime(g).technology!.domains[d.domain].currentResearchId!==d.id)!,n=observeTutorialAction(g,setResearch(g,d.domain,d.id));assert.equal(n.tutorial!.stepId,'diplomacy');assert.equal(selectControlledRuntime(n).technology!.domains[d.domain].currentResearchId,d.id);});
test('diplomacy tutorial pays real cost and improves real relations',()=>{const g=setStep('diplomacy'),n=observeTutorialAction(g,performDiplomaticAction(g,'sparrow','pigeon','improve'));assert.equal(n.tutorial!.stepId,'crisis-wait');assert.ok(selectControlledRuntime(n).fiscal.treasury<selectControlledRuntime(g).fiscal.treasury);assert.equal(getBilateralRelation(n.world,'sparrow','pigeon')!.relations,getBilateralRelation(g.world,'sparrow','pigeon')!.relations+6);});
test('petition exactly July2030 without random draws',()=>{const g=setStep('event-wait');g.turn=7;g.date={year:2030,month:7};const n=scheduleTutorial(g);assert.equal(n.events.pendingEvent!.eventId,'crow-petition');assert.equal(n.events.pendingEvent!.severity,1);assert.deepEqual(n.random,g.random);assert.equal(n.tutorial!.stepId,'event');});
test('petition is not duplicated',()=>{const g=setStep('event-wait');g.turn=7;const n=scheduleTutorial(g);assert.deepEqual(scheduleTutorial(n),n);});
test('scripted choice uses production event API/history and results',()=>{const g=setStep('event-wait');g.turn=7;const n=scheduleTutorial(g),r=observeTutorialAction(n,resolvePendingEvent(n,getEventDefinition('crow-petition').choices[0].id));assert.equal(r.tutorial!.stepId,'technology');assert.equal(r.events.pendingEvent,null);assert.ok(r.events.history.some(h=>h.eventId==='crow-petition'&&h.playerChoice));assert.ok(r.logs.some(h=>h.message.includes('까마귀')));});
test('script priority suppresses random player popup while NPC events remain',()=>{let calls=0;const n=generateWorldEvents(start(),{eventOccurrenceRandom:()=>{calls++;return 0;},eventOutcomeRandom:()=>.5});assert.equal(n.events.pendingEvent,null);assert.ok(calls>0);assert.ok(n.events.history.some(h=>!h.playerChoice));});
test('storm exactly January2032 at moderate strength',()=>{const g=setStep('crisis-wait');g.turn=25;g.date={year:2032,month:1};const n=scheduleTutorial(g),c=Object.values(n.world.crises!.activeCrises).find(c=>c.jurisdictionId==='sparrow')!;assert.equal(c.type,'great_storm');assert.equal(c.severity,60);assert.equal(n.tutorial!.stepId,'crisis');assert.deepEqual(n.random,g.random);});
test('storm scheduler has no duplicate crisis',()=>{const g=setStep('crisis-wait');g.turn=25;const n=scheduleTutorial(g);assert.deepEqual(scheduleTutorial(n),n);});
test('moderate storm cannot bypass emergency rule',()=>{const g=setStep('crisis-wait');g.turn=25;const n=scheduleTutorial(g);assert.match(policyChangeBlock(n,'country:sparrow','budget',true)!,/75/);});
test('real severe crisis can unlock emergency API and retains locks',()=>{let g=setStep('emergency');g=startCrisis(g,{kind:'country',id:'sparrow'},'great_storm',80);const n=setControlledBudgetPolicy(g,{...selectControlledRuntime(g).fiscal.budgetPolicy,infrastructure:3},true);assert.equal(n.policySchedules!['country:sparrow'].emergencyNextChangeTurn,g.turn+6);assert.equal(n.policySchedules!['country:sparrow'].budgetNextChangeTurn,g.turn+12);});
test('fast-forward visits fixed event month rather than jumping',()=>{let g=setStep('event-wait');for(let i=0;i<10&&!g.events.pendingEvent;i++)g=advanceMonth(unblock(g),{mortalityRiskOverride:0});assert.equal(g.turn,7);assert.equal(g.date.month,7);assert.equal(g.player.ageMonths,18);});
test('fast-forward blocked by unresolved player event',()=>{const g=setStep('event-wait');g.turn=7;const n=scheduleTutorial(g);assert.equal(advanceMonth(n),n);});
for(const mode of ['active','skipped','completed'] as const)test('save/load tutorial '+mode,()=>{const g=start();if(mode!=='active')g.tutorial={...g.tutorial!,mode,stepId:null,scriptedScenarioEnabled:false};const r=loadGame(deserializeSave(serializeSave(createSaveData(g,'manual-1'))));assert.deepEqual(r.tutorial,g.tutorial);assert.deepEqual(r.random,g.random);});
test('active scripted event survives save/load with exact guide',()=>{const g=setStep('event-wait');g.turn=7;g.date.month=7;const n=scheduleTutorial(g),r=loadGame(createSaveData(n,'quick'));assert.deepEqual(r.events.pendingEvent,n.events.pendingEvent);assert.equal(r.tutorial!.stepId,'event');assert.deepEqual(r.tutorial!.firedScriptIds,['petition']);});
test('pre-tutorial saves load with no tutorial field',()=>{const n=loadGame(createSaveData(fresh(),'manual-1'));assert.equal(n.tutorial,undefined);});
test('malformed tutorial cannot be imported',()=>{const g=start();g.tutorial!.stepId='unknown';assert.throws(()=>createSaveData(g,'manual-1'));});
test('duplicate completed steps rejected',()=>{const g=start();g.tutorial!.completedStepIds=['overview','overview'];assert.throws(()=>validateTutorial(g.tutorial));});
test('inactive script flag rejected on import',()=>{const g=skipTutorial(start());g.tutorial!.scriptedScenarioEnabled=true;assert.throws(()=>validateTutorial(g.tutorial));});
test('mid-skip preserves world, date, policies, pending event and RNG',()=>{const g=setStep('event-wait');g.turn=7;const n=scheduleTutorial(g),r=skipTutorial(n);for(const k of ['world','player','date','events','random','history'] as const)assert.deepEqual(r[k],n[k]);assert.equal(r.tutorial!.mode,'skipped');assert.equal(r.tutorial!.scriptedScenarioEnabled,false);});
test('skip stops future fixed storm',()=>{const g=skipTutorial(start());g.turn=25;assert.equal(scheduleTutorial(g),g);assert.equal(Object.keys(g.world.crises!.activeCrises).length,0);});
test('normal player events resume after skip',()=>{const g=skipTutorial(start()),n=generateWorldEvents(g,{eventOccurrenceRandom:()=>0,eventOutcomeRandom:()=>.5});assert.ok(n.events.pendingEvent);});
test('skipped guide has no simulation restrictions',()=>{const g=skipTutorial(start());assert.equal(advanceMonth(g,{mortalityRiskOverride:0}).turn,2);});
for(const stream of ['economy','election','eventOccurrence','mortality'] as const)test('scheduler does not consume '+stream+' RNG',()=>{const g=setStep('crisis-wait');g.turn=25;assert.deepEqual(scheduleTutorial(g).random![stream],g.random![stream]);});
test('first election at exactly 2034January completes and releases scripts',()=>{const g=complete();assert.deepEqual(g.date,{year:2034,month:1});assert.equal(g.turn,49);assert.equal(g.player.career.electionsWon,1);assert.equal(g.tutorial!.scriptedScenarioEnabled,false);assert.equal(g.gameOverReason,null);});
test('election defeat uses real gameover and still releases tutorial',()=>{let g=setStep('election');g.date={year:2034,month:1};g.turn=49;g.player.career.monthsInCurrentTerm=48;g=scheduleTutorial(resolveElection(g,()=>.999999));assert.equal(g.gameOverReason,'election_defeat');assert.ok(g.tutorial!.completedStepIds.includes('election'));assert.equal(g.tutorial!.mode,'completed');assert.equal(g.tutorial!.scriptedScenarioEnabled,false);});
test('tutorial does not force election victory',()=>{const g=setStep('election');g.player.career.monthsInCurrentTerm=48;assert.equal(resolveElection(g,()=>0).gameOverReason,null);assert.equal(resolveElection(g,()=>.999999).gameOverReason,'election_defeat');});
test('replay constructs fresh tutorial without altering previous completed game',()=>{const g=complete(),copy=structuredClone(g),r=start();assert.equal(r.turn,1);assert.equal(r.tutorial!.mode,'active');assert.deepEqual(g,copy);});
test('history excludes instructional step meta records',()=>{const g=complete();assert.ok(!g.history!.timeline.some(h=>/튜토리얼|Step|확인했어요/.test(h.title+' '+h.description)));});
test('attention identifies pending event as critical and deduplicates',()=>{const g=setStep('event-wait');g.turn=7;const n=selectAttention(scheduleTutorial(g));assert.equal(n.find(i=>i.id==='event')!.level,'critical');assert.equal(new Set(n.map(i=>i.id)).size,n.length);});
test('attention identifies moderate crisis as warning',()=>{const g=startCrisis(fresh(),{kind:'country',id:'sparrow'},'great_storm',60);assert.equal(selectAttention(g).find(i=>i.id==='crisis')!.level,'warning');});
test('attention includes imminent election and navigation target',()=>{const g=fresh();g.player.career.monthsInCurrentTerm=44;assert.equal(selectAttention(g).find(i=>i.id==='election')!.menu,'politics');});
test('attention includes available policies and empty research',()=>{const a=selectAttention(setResearch(fresh(),'industry',null));assert.equal(a.find(i=>i.id==='policy')!.menu,'budget');assert.equal(a.find(i=>i.id==='research')!.menu,'technology');});
test('compact formatting for huge economy/population and sane decimals',()=>{assert.ok(formatEconomyNumber(1e14).length<15);assert.ok(formatPopulation(1e14).length<15);assert.equal(formatEconomyNumber(5.238472),'5.2');});
test('help covers all navigation and required terms',()=>{for(const menu of ['overview','economy','budget','species','society','politics','diplomacy','military','technology','history'])assert.ok(contextHelp[menu]?.text);assert.equal(glossary.length,8);});
test('full tutorial has all learning milestones, completed ids unique',()=>{const g=complete();assert.equal(g.tutorial!.completedStepIds.length,tutorialSteps.length);assert.equal(new Set(g.tutorial!.completedStepIds).size,tutorialSteps.length);assert.deepEqual(g.tutorial!.firedScriptIds,['petition','storm']);});
test('completion followed by 120 real months has no script recurrence',()=>{let g=complete();const initial=g.events.history.filter(h=>h.id.startsWith('tutorial:')).length;for(let i=0;i<120;i++)g=advanceMonth(unblock(g),{mortalityRiskOverride:0,electionRandom:()=>0});assert.equal(g.turn,169);assert.equal(g.events.history.filter(h=>h.id.startsWith('tutorial:')).length,initial);assert.equal(g.tutorial!.mode,'completed');});
test('skipped normal vs normal 600 months identical world, AI, history, RNG',()=>{let a=skipTutorial(start()),b=fresh();for(let i=0;i<600;i++){a=advanceMonth(unblock(a),{mortalityRiskOverride:0,electionRandom:()=>0});b=advanceMonth(unblock(b),{mortalityRiskOverride:0,electionRandom:()=>0});}const {tutorial,...without}=a;assert.equal(a.turn,601);assert.deepEqual(without,b);});
