import {createGame,advanceMonth} from '../src/game/engine';
import {createElectionSnapshot} from '../src/game/election';
import {calculateMonthlyMortalityRisk,calculateBaseMonthlyMortalityRisk} from '../src/game/mortality';
import {startCrisis,updateLeaderRisk} from '../src/game/crisis';
import {createSeededRandom} from '../src/game/random';
import {getEventDefinition,resolvePendingEvent} from '../src/game/events';
import {respondToForeignProposal} from '../src/game/strategicCommands';
import {respondToAllyRequest} from '../src/game/warfare';
import {distribution,runSimulation,modules} from './harness';
import {writeFileSync,mkdirSync} from 'node:fs';
import {difficultyNames} from '../src/game/difficulty';
import type {Difficulty} from '../src/game/difficulty';
function lifetimes(difficulty:Difficulty,exposed:boolean){let g=createGame('sparrow',undefined,2030,difficulty);if(exposed)g=updateLeaderRisk(startCrisis(g,{kind:'country',id:'sparrow'},'great_storm',95));const ages:number[]=[],risks:number[]=[],natural:number[]=[];for(let age=13;age<2400;age++){g.player.ageMonths=age;risks.push(calculateMonthlyMortalityRisk(g));natural.push(calculateBaseMonthlyMortalityRisk(age));}let naturalDeaths=0;for(let i=0;i<10000;i++){const random=createSeededRandom(i*7919+17);for(let k=0;k<risks.length;k++){const inCrisis=exposed&&k%36<8,base=natural[k],risk=inCrisis?risks[k]:base,roll=random();if(roll<risk){ages.push((k+13)/12);naturalDeaths+=Number(roll<base);break;}}}return {difficulty,exposed,leaders:10000,age:distribution(ages),naturalDeathShare:naturalDeaths/ages.length};}
async function player(seed:number,difficulty:Difficulty){let g=startCrisis(createGame('sparrow',undefined,seed,difficulty),{kind:'country',id:'sparrow'},'great_storm',95),steps=0,approval=0,chance=0,risk=0;for(let i=0;i<240&&!g.gameOverReason;i++){
 if(g.events.pendingEvent){const def=getEventDefinition(g.events.pendingEvent.eventId);g=resolvePendingEvent(g,def.nonPlayerChoiceId);}
 for(const p of [...(g.world.foreignProposals??[])])if(p.targetId===g.player.controlledCountryId)g=respondToForeignProposal(g,p.id,true);
 for(const r of [...g.world.warfare!.allyRequests])if(r.status==='pending'&&r.allyCountryId===g.player.controlledCountryId)g=respondToAllyRequest(g,r.id,false);
 if(g.gameOverReason)break;g=advanceMonth(g);steps++;approval+=g.world.countries[g.player.controlledCountryId].governance?.approval??0;chance+=createElectionSnapshot(g).reelectionChance;risk+=g.player.currentMortalityRisk;
 }return {seed,difficulty,months:steps,alive:g.player.alive,gameOverReason:g.gameOverReason,age:g.player.ageMonths/12,averageApproval:approval/Math.max(1,steps),averageElectionChance:chance/Math.max(1,steps),averageMortality:risk/Math.max(1,steps),crisisDamage:Object.values(g.history!.crises).reduce((s,c)=>s+c.totalPopulationImpact,0)};}
const mortality=difficultyNames.flatMap(d=>[lifetimes(d,false),lifetimes(d,true)]),players=[];for(const seed of [91,2030,8451,1001,8920,16839,24758,32677,40596,48515])for(const d of difficultyNames)players.push(await player(seed,d));
const elections=[];for(const [name,approval,growth,unemployment] of [['excellent',85,4,3],['average',55,2,6],['poor',28,-2,16],['crisis',18,-7,24]] as const){for(const d of difficultyNames){const g=createGame('sparrow',undefined,2030,d),r=g.world.countries.sparrow;Object.assign(r.governance!,{approval,stability:approval,integration:approval});Object.assign(r.economy,{growth,unemployment});for(const p of Object.values(r.speciesPolitics!))p.satisfaction=approval;g.player.career.history=Array.from({length:48},()=>({approval,growth,unemployment,inflation:name==='crisis'?15:2}));const probability=createElectionSnapshot(g).reelectionChance;const rand=createSeededRandom(2030);let won=0;for(let i=0;i<10000;i++)won+=Number(rand()<probability);elections.push({name,difficulty:d,probability,observedWinShare:won/10000});}}
const m=await modules(),resilience=[];for(const level of [2,5,9]){let g=createGame('sparrow',undefined,2030),r=g.world.countries.sparrow;Object.assign(r.social!,{healthcare:level*10,publicSafety:level*10});r.fiscal.budgetPolicy.healthcare=level*.5;r.fiscal.budgetPolicy.infrastructure=level*.4;for(const domain of Object.values(r.technology!.domains))domain.level=level;g=startCrisis(g,{kind:'country',id:'sparrow'},'great_storm',95);for(let i=0;i<12;i++)g=advanceMonth(g,{autonomousWorld:true,domesticAI:false,strategicAI:false,eventOccurrenceRandom:()=>.99999,crisisRandom:()=>.99,mortalityRiskOverride:0,electionRandom:()=>0});resilience.push({level,damage:Object.values(g.history!.crises).reduce((s,c)=>s+c.totalPopulationImpact,0),fiscalCost:Object.values(g.history!.crises).reduce((s,c)=>s+c.totalFiscalCost,0),duration:Object.values(g.history!.crises).map(c=>c.durationMonths)});}
const technology=[];for(const strategy of ['industry','ai','research'])technology.push(await runSimulation(2030,1200,'src','normal','normal',strategy));
// Paired stronger/weaker and simultaneous-war fixtures use real military inputs, not forced battle RNG.
const wars=[];for(const seed of [91,2030,8451])for(const source of ['.test-output/10b-baseline','src'])for(const name of ['asymmetric','multiwar'])wars.push(await runSimulation(seed,240,source,name));
mkdirSync('simulation/results/comparisons',{recursive:true});writeFileSync('simulation/results/comparisons/results.json',JSON.stringify({mortality,players,elections,resilience,technology,wars},null,2));console.log('COMPLETE comparisons',JSON.stringify({mortality,resilience,elections}));
