import {pathToFileURL} from 'node:url';import {resolve} from 'node:path';import {mkdirSync,writeFileSync} from 'node:fs';
const source=process.argv[2]??'.test-output/10b1-baseline',tag=process.argv[3]??'before';const load=(s:string)=>import(pathToFileURL(resolve(source,'game',s+'.ts')).href);
const [engine,events,budget,fiscal,trade,tech,crisis,config,bconfig,balance,econ]=await Promise.all(['engine','events','budget','fiscal','diplomacyEffects','technologyEffects','crisis','economyConfig','budgetConfig','balanceConfig','economy'].map(load));
let g=engine.createGame('sparrow',undefined,99101);const sums:Record<string,number>={},checkpoints:any[]=[];let period=0;
for(let i=0;i<6000;i++){const w=events.tickEventState(g).world,rs=[w.countries.sparrow,...Object.values(w.regions).filter((r:any)=>r.simulationRole!=='administrative')] as any[],total=rs.reduce((s,r)=>s+r.economy.gdp,0),v:Record<string,number>={base:0,productivity:0,technology:0,research:0,infrastructure:0,industrySupport:0,trade:0,tax:0,otherBudget:0,crisis:0,maturity:0,event:Math.log(rs.reduce((s,r)=>s+r.economy.gdp,0)/(g.world.countries.sparrow.economy.gdp+g.world.countries.pigeon.economy.gdp))*1200};
for(const r of rs){const own=r.ownerCountryId??r.id,j={kind:r.ownerCountryId?'region':'country',id:r.id},profile=config.initialEconomyProfiles[r.id],sources={technology:tech.getTechnologyIndustryModifiers(r.technology),trade:trade.getDiplomaticTradeModifiers(w,own),tax:fiscal.getTaxIndustryModifiers(r.fiscal),crisis:crisis.getCrisisIndustryModifiers(w,j)};
for(const [id,industry] of Object.entries(r.economy.industries) as any[]){const weight=industry.output/total,spec=config.industryConfig[id],pressure=profile?Math.max(0,industry.output/r.economy.gdp/profile.shares[id]-balance.balanceAdjustments.sectorShareThreshold)*balance.balanceAdjustments.sectorGrowthPressure:0;v.base+=(spec.annualGrowth-pressure)*weight*100;v.productivity+=spec.annualProductivityGrowth*weight*100;
for(const [name,s] of Object.entries(sources) as any[])v[name]+=weight*100*((s[id]?.annualGrowthAdjustment??0)+spec.annualProductivityGrowth*((s[id]?.productivityMultiplier??1)-1));
for(const category of bconfig.budgetCategoryIds){const delta=r.fiscal.budgetPolicy[category]-r.fiscal.baselineBudgetPolicy[category],e=bconfig.budgetIndustryEffects[category][id];v[['research','infrastructure','industrySupport'].includes(category)?category:'otherBudget']+=weight*100*delta*((e?.annualGrowthAdjustment??0)+spec.annualProductivityGrowth*(e?.productivityAdjustment??0));}
if(tag!=='before'){const all=budget.combineIndustryModifiers(budget.getBudgetIndustryModifiers(r.fiscal),...Object.values(sources));const mod=all[id],positive=spec.annualGrowth+Math.max(0,mod.annualGrowthAdjustment??0);v.maturity+=weight*100*(positive*(econ.matureGrowthFactor(industry.productivity)-1)+spec.annualProductivityGrowth*(econ.diminishedProductivityMultiplier(industry.productivity,mod.productivityMultiplier??1)-(mod.productivityMultiplier??1)));}
}}
for(const [k,n] of Object.entries(v))sums[k]=(sums[k]??0)+n;period++;g=engine.advanceMonth(g,{autonomousWorld:true,mortalityRiskOverride:0,electionRandom:()=>0});if([600,2400,4800,6000].includes(i+1)){checkpoints.push({month:i+1,expectedAnnualContribution:Object.fromEntries(Object.entries(sums).map(([k,n])=>[k,n/period])),aiPolicyMemo:((sums.research??0)+(sums.infrastructure??0)+(sums.industrySupport??0)+(sums.otherBudget??0)+(sums.tax??0))/period,gdp:Object.values(g.world.countries).reduce((s:number,c:any)=>s+c.economy.gdp,0),growth:Object.values(g.world.countries).map((c:any)=>({id:c.id,growth:c.economy.growth})),productivity:rs.map(r=>({id:r.id,sectors:Object.fromEntries(Object.entries(r.economy.industries).map(([id,d]:any)=>[id,d.productivity]))}))});for(const k in sums)sums[k]=0;period=0;}}
mkdirSync('simulation/results/convergence',{recursive:true});writeFileSync('simulation/results/convergence/'+tag+'-contributions.json',JSON.stringify({source,seed:99101,method:'GDP weighted expected annual percentage-point contributions; AI memo overlaps budget/tax. Event is realized ongoing-effect annual log impulse; random cycles and immediate new events are excluded.',checkpoints},null,2));console.log('COMPLETE contributions',tag,JSON.stringify(checkpoints.map(c=>({month:c.month,...c.expectedAnnualContribution}))));
