import {distribution,mean} from './harness';import {readFileSync,writeFileSync} from 'node:fs';
const load=(p:string)=>JSON.parse(readFileSync(p,'utf8')),old=load('simulation/results/final/aggregate.json').results,now=load('simulation/results/convergence/aggregate.json'),cb=load('simulation/results/convergence/before-contributions.json'),ca=load('simulation/results/convergence/after-contributions.json'),wd=load('simulation/results/convergence/war-diagnostics.json');
const n=(v:number)=>v.toLocaleString('en-US',{maximumFractionDigits:4}),table=(heads:string[],rows:any[][])=>'| '+heads.join(' | ')+' |\n| '+heads.map(()=>'---').join(' | ')+' |\n'+rows.map(r=>'| '+r.join(' | ')+' |').join('\n');
const pairs=(months:number)=>{const after=now.results.filter((r:any)=>r.months===months&&r.scenario==='normal');return {after,before:after.map((r:any)=>old.find((b:any)=>b.months===months&&b.seed===r.seed))};};
const compare=(months:number)=>{const {before,after}=pairs(months);return table(['기간','시드 수','이전 GDP배 평균','수정 GDP배 평균','이전 연평균 성장','수정 연평균 성장','시드별 GDP 상대차 범위'],[[months,after.length,n(mean(before.map((r:any)=>r.gdpRatio))),n(mean(after.map((r:any)=>r.gdpRatio))),n(mean(before.map((r:any)=>r.annualGrowth)))+'%',n(mean(after.map((r:any)=>r.annualGrowth)))+'%',n(Math.min(...after.map((r:any,i:number)=>(r.gdpRatio/before[i].gdpRatio-1)*100)))+'% ~ '+n(Math.max(...after.map((r:any,i:number)=>(r.gdpRatio/before[i].gdpRatio-1)*100)))+'%']]);};
const ultra=pairs(6000).after[0],beforeUltra=pairs(6000).before[0],lastCon=ca.checkpoints.at(-1),warStat=(source:string,key:string)=>distribution(now.results.filter((r:any)=>r.months===120&&(source==='before'?r.source!=='src':r.source==='src')).flatMap((r:any)=>r[key]??[]));
const warTable=table(['항목','이전 평균','수정 평균','이전 중앙','수정 중앙','이전 P90','수정 P90','이전 최대','수정 최대'],['warDurations','warActiveMonths','firstWarPause'].map(k=>{const b=warStat('before',k),a=warStat('after',k);return[k,...['mean','median','p90','max'].flatMap(f=>[n((b as any)[f]),n((a as any)[f])])];}));
const lateCagr=(r:any)=>100*(Math.pow(r.gdpRatio/r.checkpoints.find((c:any)=>c.months===4800).gdpRatio,1/100)-1);
const axis=['base','productivity','technology','research','infrastructure','industrySupport','trade','event','tax','otherBudget','crisis','maturity'];
const sections:[string,string][]=[
['초장기 성장의 실제 원인',table(['마지막100년 기대 연율 기여(%p)','이전','수정'],axis.map(k=>[k,n(cb.checkpoints.at(-1).expectedAnnualContribution[k]),n(lastCon.expectedAnnualContribution[k])]))+'\n\nGDP 가중 기대 연율 계수 분해입니다. base는 산업 기본 성장에서 기존 산업 비중 압력을 뺀 값이고 productivity는 기본 생산성 증가입니다. 기술 성장·생산성 보정, 연구/인프라/산업지원 예산의 직접 계수를 각각 분리했습니다. research의 지식 축적 효과는 technology에도 간접 반영됩니다. 사건은 실제 지속효과의 연율 로그 충격이며 신규 즉시 사건·경기순환 난수는 이 기대 계수표에서 제외했습니다. 그러므로 이 표는 실제 성장률의 정확한 합계나 요소를 껐을 때의 인과 효과가 아닙니다. AI 정책 메모(예산+세율 효과, 위 항목과 중복)는 이전 '+n(cb.checkpoints.at(-1).aiPolicyMemo)+'%p, 수정 '+n(lastCon.aiPolicyMemo)+'%p입니다. 주원인은 기술 직접효과가 아니라 고정 구조 성장률을 생산성 수준과 무관하게 계속 누적하던 부분이었습니다.'],
['변경한 경제 config·공식','growthConvergenceConfig: matureProductivity=150, growthResponse=8, productivityBonusResponse=1, highTechStart=8, highTechGrowthResponse=0.5.\n\n생산성 P의 성숙도 계수 M=1/[1+8·max(0,ln(P/150))²]. 산업의 기본 구조 성장과 양의 성장 보정에 M을 적용합니다. 음의 보정·경기순환·충격·기존 산업비중 압력은 유지합니다. 양의 생산성 추가 배율은 1+(multiplier−1)/[1+max(0,P/150−1)]로 완화하며 기본 생산성 증가를 없애지 않습니다. 평균 기술 Lv8 초과의 경제 성장 보정만 1/[1+0.5·(평균Lv−8)]로 완화합니다. 기술의 사회·군사·위기 보호·연구 효과와 기존 diffusion은 유지합니다. 고용·물가의 정상 성장 기준도 현재 산업 구성의 남은 구조적 잠재성장에 맞춥니다. 기존 잠재성장 대비 생산성 성숙으로 줄어든 부분의 비율을 2% 기준에 반영하고, 초기 생산성에서는 기존 기준과 정확히 같습니다. 성장 둔화만 적용했을 때 생겼던 성숙기 상시 실업·지지도 붕괴를 방지하며 실제 침체·음의 충격의 비용은 유지합니다. GDP 값에 대한 상한·임계 패널티가 없고 동일 생산성에서는 경제규모가 달라도 같은 성장 계수를 받습니다.\n\n연방 기술 평균의 10.000000000000002 같은 반올림 초과도 원래 범위 안으로 보정했습니다. 새로운 GameState 필드·저장 schema·게임 시스템은 추가하지 않았습니다.'],
['50년 전후 비교',compare(600)+'\n\n동일20seed. 최초50년은 성숙 임계구간 이전이라 세계 GDP 결과가 반올림 오차 수준에서 같습니다. 시작국·초기 정책·난이도 규칙은 그대로입니다.'],
['200년 전후 비교',compare(2400)+'\n\n동일5seed. 성장과 지역 규모 차이는 유지되며 기술국의 경제 우위가 사라지지 않았습니다.\n\n'+table(['seed1001 관할','이전200년 GDP','수정200년 GDP'],pairs(2400).after[0].checkpoints.at(-1).profiles.map((p:any)=>[p.id,n(pairs(2400).before[0].checkpoints.at(-1).profiles.find((b:any)=>b.id===p.id).gdp),n(p.gdp)]))],
['500년 전후 비교',compare(6000)+`\n\nseed99101의 GDP 증가 배수는 ${n(beforeUltra.gdpRatio)}→${n(ultra.gdpRatio)}, 감소 ${n((1-ultra.gdpRatio/beforeUltra.gdpRatio)*100)}%. 마지막100년 세계 GDP의 실제 연평균 성장률은 ${n(lateCagr(beforeUltra))}%→${n(lateCagr(ultra))}%로 수렴했습니다. 마지막 한 달을 연율로 표시한 국가 성장률은 ${lastCon.growth.map((r:any)=>r.id+' '+n(r.growth)+'%').join(', ')}이며, 이 값은 사건·경기 변동을 포함한 단월 관측으로 장기 평균과 다릅니다. 큰 역사적 누적 성장 자체를 제거한 것은 아니지만 고정 고성장 복리가 유지되는 경로는 완화됐습니다.\n\n국가 GDP 격차(최대/최소): 이전 ${n(Math.max(...beforeUltra.checkpoints.at(-1).profiles.slice(0,2).map((p:any)=>p.gdp))/Math.min(...beforeUltra.checkpoints.at(-1).profiles.slice(0,2).map((p:any)=>p.gdp)))} → 수정 ${n(Math.max(...ultra.checkpoints.at(-1).profiles.slice(0,2).map((p:any)=>p.gdp))/Math.min(...ultra.checkpoints.at(-1).profiles.slice(0,2).map((p:any)=>p.gdp)))}. 정규화한 격차의 전체 checkpoint도 원자료에 보존했습니다. 최종500년 고용·지지도·생활 수준도 아래에 기록합니다.\n\n${table(['관할','실업률','정부 지지도','생활 수준'],ultra.checkpoints.at(-1).profiles.filter((p:any)=>p.governance).map((p:any)=>[p.id,n(p.unemployment),n(p.governance.approval),n(p.social.livingStandard)]))}\n\n 6,000개월의 유한값·비음수·산업/인구 합계·소유자·역사ID 검사 통과. full-save ${ultra.saveBytes}bytes, 실제 불러오기 후120개월 추가 진행(턴${ultra.loadAdditionalTurn}) 통과.`],
['전쟁 조기평화의 실제 원인','기존 전략 사건 평가에서 hold 상태의 보급/계속 행동 효용이 −10, 협상/휴전은 +5라 정상 방어국도 첫 사건에서 협상을 선호했습니다. unilateral 행동이 전체 전선 상태를 협상으로 바꾸므로 전투는 일찍 멈추고 낮은 평화 합의 효용 때문에 나머지 기간만 협상에서 기다렸습니다. 공격측은 초기 통제0~15를 6개월 뒤 생존 위기로 평가해 우세한 공격도 포기할 수 있었습니다. 초기 피로(기본1.1/월), 전쟁 지지도(피로계수0.42), 전선 변동(월±5 한도), 국내 위기 압력(65 이상)은 분리 관찰했고 주원인이 아니어서 변경하지 않았습니다. 상세 월별 fatigue·warSupport·capability·peaceUtility·control은 war-diagnostics.json에 남겼습니다.'],
['변경한 전쟁·AI 공식','hold의 보급/계속 행동 효용을15로 바꿔 정상 초기 협상5보다 높게 했습니다. 우세 press_advantage40, 소진/위기 시 협상70은 유지합니다. 낮은 통제의 생존 판정은 상대 능력이 자신의1.5배를 넘는 경우로 한정했고, 피로85/지지도15의 붕괴는 계속 생존 위기로 처리합니다.\n\nwarGoalProgress=min(1,통제/(응징75,그외90)). 초기 목표 의지에 따라 공격측 현상유지/평화 효용을 최대35·(1−진행도)·min(1,전력비)·exp(−전쟁개월/18) 만큼 낮춥니다. 방어측은 초기 방어 지지도를 같은 시간감쇠로 반영합니다. 낮은 평균 전진속도의 교착 proxy=max(0,개월−12)·max(0,1−통제/(개월·0.8))를 평화 효용과 전략 판단에 반영합니다. 이 값은 월별 전선 이력을 새로 저장하는 시스템이 아니라 기존 상태에서 계산하는 진행 정체 지표입니다. 방어목표를 달성한 방어측의 defense_success 협정에는35 효용을 더해 상대가 붕괴하면 조기에 끝낼 수 있게 했습니다. 피로·지지도·군사 capability helper와 전투 RNG, 목표의 법적 협정 조건·truce·CB는 유지했습니다. 강제 최소기간은 없습니다.'],
['평균·median·P90·max 전쟁기간 전후',warTable+'\n\n동일10seed×동급/강약/복수전쟁, 전후각30실험입니다. 복수전쟁2개를 포함하므로 기간 표본은 각40전쟁입니다. warDurations는 협상까지 포함한 총기간, warActiveMonths는 실제 교전월, firstWarPause는 첫 전선 중단월입니다. 이전 총기간이 길어도 교전은 대부분 몇 달뿐이었습니다. 총기간만 늘리는 것이 목표가 아니어서 교전 연장과 조기 합의 개선을 같이 봅니다.'],
['짧은 전쟁 사례','seed2030 collapse: 기존 상태의 공격측 피로95·전쟁지지도0을 준 통제 실험.\n\n'+table(['규칙','교전개월','첫 중단','종결개월'],wd.filter((r:any)=>r.scenario==='collapse').map((r:any)=>[r.source,r.activeMonths,r.firstPause,r.resolved]))+'\n\n붕괴 시 초기 휴전과 방어성공 합의가 가능하며 정상 공격측은 같은 초기 협정을 자동 수락하지 않습니다. 압도적 전력의 월 전선 우위와 크게 패배한 방어측의 survival/영토협정 효용도 별도 테스트했습니다. 희귀 승패를 강제하는 전투 난수는 추가하지 않았습니다.'],
['장기 교착 사례',table(['seed2030 규칙/상황','교전개월','첫 중단','종결개월'],wd.filter((r:any)=>r.scenario!=='collapse').map((r:any)=>[r.source+' '+r.scenario,r.activeMonths,r.firstPause,r.resolved]))+'\n\n동급전에서 초기 몇 달만에 끝나지 않고 전황을 시도한 뒤 낮은 전진속도·피로·지지 비용이 평화로 이어졌습니다. 40개월 통제정체의 평화 효용 증가도 테스트합니다. 기존 장기전120개월 중재 규칙은 유지했고 이번 표본에 100년 전쟁은 없습니다.'],
['InternalConflict 회귀','6C conflict.ts·militaryPower.ts·공통 capability/fatigue 공식은 변경하지 않았습니다. 기존 내전·강제/협의 재통합·국가삭제·영토이전·정책주기·전쟁 병행 회귀 테스트를 유지합니다. 신규 테스트도 초기 전쟁 피로와 공통 기본 capability가 변하지 않았음을 확인합니다. 전후 복수전쟁 fixture의 내부 분쟁 참조 검사 통과.'],
['테스트 총 개수','기존1,271개 모두 유지 + 신규32개 = 총1,303개. 최종 전체 실행 결과는 .test-output/convergence-consistent-tests.txt에 보존했습니다.'],
['TypeScript','게임 tsc -b 및 simulation 도구 전체 strict noEmit 검사 통과.'],
['빌드','최종 pnpm build 통과.'],
['브라우저 회귀','기존21개 PC·모바일·production 시나리오와 난이도·저장 이관 시나리오를 확인했습니다. 경제·월 진행·군사·휴전/협정·내전·독립·동원·역사·저장·게임오버 흐름을 유지합니다. 보안프로그램404는 이전 요청대로 오류 판정에서 제외했습니다.'],
['10B-2로 넘길 잔여 이슈','500년 누적 GDP 자체는 여전히 큰 값이며 한 시드로 모든 장기 경제정책을 증명하지는 못합니다. 인구의 초장기 증가·평시 국가수/전쟁빈도·기술트리 확장은 이번 요청 범위 밖이라 변경하지 않았습니다. 교착 proxy는 평균 진행속도에 기반하며 왕복 전선의 세부 이력까지 판단하지 않습니다. 이번 표본의 강약전은 초기 약2배 전력으로 점령/영토승리가 항상 나오는 조건이 아닙니다. 기술의 생산성 수준 가치와 성장률 수확체감, 교전기간과 협상기간 구분, 정책 비용을10B-2 안내에서 설명하는 것이 필요합니다. 성숙기 고용·물가 기준과 성장률 수렴을 함께 설명해야 합니다. 새 튜토리얼·UX·게임 시스템·엔딩은 추가하지 않았습니다.']
];
writeFileSync('BALANCE_FIXES.md','# Bird Kingdom 10B-1 장기 밸런스 보정\n\n요청된 두 문제만 수정했습니다. 세부 원자료: [배치](simulation/results/convergence/aggregate.json), [이전 기여도](simulation/results/convergence/before-contributions.json), [수정 기여도](simulation/results/convergence/after-contributions.json), [전쟁 경로](simulation/results/convergence/war-diagnostics.json).\n\n재실행: `pnpm balance:convergence` (20×600,5×2400,1×6000 및 전후전쟁60실험). 비교하려면 먼저 `source-10b1.zip`을 `.test-output/10b1-baseline`으로 압축 해제하세요. 기여도는 `pnpm exec tsx simulation/contributions.ts .test-output/10b1-baseline before`와 `pnpm exec tsx simulation/contributions.ts src after`, 월별 전쟁 진단은 `pnpm exec tsx simulation/convergenceWars.ts`입니다.\n\n'+sections.map(([title,body],i)=>'## '+(i+1)+'. '+title+'\n\n'+body+'\n').join('\n'));
console.log('REPORT',sections.length);
