import {readFileSync,writeFileSync} from 'node:fs';
import {distribution,mean} from './harness';
const load=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const f=load('simulation/results/final/aggregate.json'),b=load('simulation/results/baseline/aggregate.json'),c=load('simulation/results/comparisons/results.json'),a=load('simulation/results/audit/results.json');
const n=(v:number)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:3}):String(v),pct=(v:number)=>n(v*100)+'%',short=f.results.filter((r:any)=>r.months===600),long=f.results.filter((r:any)=>r.months===2400),ultra=f.results.find((r:any)=>r.months===6000),stress=[...new Map<string,any>(f.results.filter((r:any)=>r.months===240&&r.difficulty==='normal').map((r:any)=>[r.scenario+':'+r.seed,r])).values()],strategies=f.results.filter((r:any)=>r.months===1200),baseStress=load('simulation/results/baseline-stress/results.json');
const table=(headers:string[],rows:any[][])=>'| '+headers.join(' | ')+' |\n| '+headers.map(()=>'---').join(' | ')+' |\n'+rows.map(row=>'| '+row.join(' | ')+' |').join('\n');
const stats=(d:any)=>['mean','median','p10','p90','min','max'].map(k=>n(d[k]));
const metricTable=(set:any)=>table(['지표','평균','중앙값','P10','P90','최소','최대'],Object.entries(set).map(([k,v])=>[k,...stats(v)]));
const profiles=a.observations.flatMap((x:any)=>x.profiles),last=a.observations.at(-1).profiles;
const metric=(type:string,k:string)=>distribution(profiles.map((p:any)=>p[type][k]));
const profTable=table(['관할','생활','교육','의료','안전','불평등','지지도','안정','통합','국고/GDP','부채/GDP'],last.map((p:any)=>[p.id,...['livingStandard','education','healthcare','publicSafety','inequality'].map(k=>n(p.social[k])),...['approval','stability','integration'].map(k=>n(p.governance[k])),n(p.treasuryRatio),n(p.debtRatio)]));
const warDurations=distribution(stress.flatMap((r:any)=>r.warDurations));
const crisisDurations:any={};for(const r of short)for(const v of r.crisisDurations)if(v.ended)(crisisDurations[v.type]??=[]).push(v.months);
const sections:[string,string][]=[
['추가·수정 파일','새 파일: src/game/difficulty.ts, src/game/balanceConfig.ts, tests/difficulty.test.ts, simulation/harness.ts·run.ts·comparisons.ts·audit.ts·warPath.ts·generateReport.ts. 수정: engine·types·economy·fiscal·aiEvaluation·crisis·population·social·mortality·election·saveConfig·saveMigrations·saveValidation, App·Setup·Dashboard·CSS, package.json·README, 기존 저장 테스트의 schema 기대값. 기존 게임 시스템을 교체하지 않았습니다.'],
['Difficulty 구조','Difficulty = easy | normal | hard. 새 게임 생성 4번째 인자, 기본 normal. 국가→주 선택 사이 선택 유지. GameState에 보존하며 개요에서 읽기만 가능. 변경 명령 없음. 타입의 optional은 이전 단계 fixture를 위한 호환 경계이며 schema 2 저장은 유효한 값이 필수입니다.'],
['난이도별 modifier',table(['효과','쉬움','보통','어려움'],[['극단 음의 산업 충격','0.9','1','1.1'],['위기 피해','0.9','1','1.1'],['위기 회복','1.1','1','0.9'],['선거 허용도','+4%p','0','−4%p'],['상황 사망위험 추가분','0.9','1','1.1']])+'\n\n플레이어의 현재 관할만 보정합니다. 연방 총합에 중복 적용하지 않습니다. NPC 자원·정보·전쟁 RNG 및 자연 노화는 동일합니다. 경제 보정은 극단 음의 산업 난수에만 적용하고 경기순환 전체를 늘리지 않습니다.'],
['난이도 Save migration','saveVersion 1→2: difficulty가 없는 기존 저장을 normal로 이관. 세계·정책 주기·난수는 그대로 복원. schema 2의 누락·잘못된 난이도는 거부합니다. 실제 10A JSON의 브라우저 가져오기·불러오기도 통과했습니다. 앱 버전과 저장 schema는 별개입니다.'],
['Balance config 정리','balanceConfig는 기존 도메인 설정을 참조하는 조회 레지스트리입니다. 각 경제·재정·사회·기술 등의 설정 파일은 계속 기준입니다. 자연 사망 설정과 이번 3개 조정값을 중앙에 모았고 실제 사용한 설정을 simulation/results/final/config.json에 남겼습니다.'],
['경제 밸런스 결과',metricTable(Object.fromEntries(['growth','unemployment','inflation'].map(k=>[k,metric('economy',k)])))+'\n\n'+`정상 50년 연평균 성장 ${n(f.short.annualGrowth.mean)}%, 범위 ${n(f.short.annualGrowth.min)}–${n(f.short.annualGrowth.max)}%. 200년 세계 GDP 평균 ${n(f.long.gdpRatio.mean)}배. 기준선 ${n(b.long.gdpRatio.mean)}배에서 완화됐습니다. 산업 초기 비중의 1.5배를 넘는 분야에만 성장 압력을 적용하며 GDP를 직접 잘라내지 않습니다.\n\n${table(['관할','200년 첨단 비중','200년 농업 비중'],long[0].checkpoints.at(-1).profiles.map((p:any)=>[p.id,pct(p.industryShares.advanced),pct(p.industryShares.agriculture)]))}`],
['재정 밸런스 결과',`정상 50년 관측 최대 부채/GDP의 시드 평균 ${n(f.short.peakDebt.mean)}, 최대 ${n(f.short.peakDebt.max)}. 부채/GDP ≤1은 기존 이자식을 유지합니다. 300% 고부채 3시드의 최대 부채/GDP ${stress.filter((r:any)=>r.scenario==='debt').map((r:any)=>n(r.peakDebt)).join(', ')}. seed2030 기존 최대 ${n(baseStress.find((r:any)=>r.scenario==='debt').peakDebt)}. 아래 국가·주 표와 스트레스 표는 회복과 정책 비용을 함께 보여줍니다. 국고 누적 자체를 강제로 없애지 않았습니다.\n\n${profTable}`],
['인구 장기결과',`200년 평균 ${n(f.long.popRatio.mean)}배, 범위 ${n(f.long.popRatio.min)}–${n(f.long.popRatio.max)}배. 초기 인구 유지·지역 종족 구성 차이를 확인했습니다. 이민·출생을 통한 장기 양의 성장은 남아 있으며 500년에는 ${n(ultra.popRatio)}배로 커집니다. 수치 안정성 통과와 무한한 기간의 현실적 균형 달성은 구분합니다. 20년 침체 stress에서는 인구가 시작의 약 79%로 감소하여 불리한 조건의 감소도 관측했습니다.\n\n${table(['관할','200년 인구','월 출생','월 사망','월 순이민','종족 비중'],last.map((p:any)=>[p.id,n(p.population.total),n(p.population.births),n(p.population.deaths),n(p.population.migration),Object.entries(p.population.shares).map(([k,v])=>k+' '+pct(v as number)).join(', ')]))}`],
['사회 장기결과','seed2030, 10년 간격 200년 표본의 분포입니다. 변화량 필드는 0~100 지표와 구분했습니다. 모든 지표의 일괄 0/100 수렴은 없으나 상한에 가까운 분야가 있어 투자 설명이 중요합니다.\n\n'+metricTable(Object.fromEntries(['livingStandard','education','healthcare','publicSafety','inequality'].map(k=>[k,metric('social',k)])))],
['governance·종족정치 분포',metricTable(Object.fromEntries(['approval','stability','integration'].map(k=>[k,metric('governance',k)])))+'\n\n'+metricTable(Object.fromEntries(['satisfaction','autonomyDemand','independenceSentiment'].map(k=>[k,distribution(profiles.flatMap((p:any)=>Object.values(p.speciesPolitics).map((s:any)=>s[k])))])))+'\n\n위기는 실제로 지표를 내리고 분리주의 fixture는 독립·내전으로 연결됩니다. 평시 표본의 높은 지지도 집중은 여전히 플레이 경험의 과제입니다.'],
['선거 밸런스',table(['정부','난이도','계산 확률','10,000회 관측 승리'],c.elections.map((x:any)=>[x.name,x.difficulty,pct(x.probability),pct(x.observedWinShare)]))+'\n\n좋은 정부도 98% 상한으로 희귀 패배가 가능합니다. 나쁜 정부의 2% 희귀 승리도 유지했습니다. 단기 RNG 결과를 난이도별 확정 승패로 바꾸지 않습니다.'],
['이벤트 빈도',`정상 50년 세계 발생 평균 ${n(f.short.events.mean)}회, 관할 5개 합계 월 ${n(f.short.events.mean/600)}회. 이는 플레이어 팝업 빈도가 아닙니다. seed2030 200년 정의의 tone 분류: ${JSON.stringify(a.tones)}. mixed는 중립적인 손익으로 단정할 수 없습니다. 관할별 사건 간격 평균 ${n(a.eventGaps.mean)}개월, 중앙 ${n(a.eventGaps.median)}, P90 ${n(a.eventGaps.p90)}, 최대 ${n(a.eventGaps.max)}. 조건·시즌·쿨다운을 유지했습니다.`],
['독립 빈도',`평시 50시드×50년 및 10시드×200년 독립 ${n(f.short.independences.mean)} / ${n(f.long.independences.mean)}건. 억압·불만을 강하게 준 stress의 국가 수·독립 건수는 아래 표에 별도 기록했습니다. 평시 빈도 0을 고치기 위해 자동 독립 확률을 넣지 않았습니다.`],
['내전 빈도','평시 내전 0. unilateral_crisis→breakaway의 공개 기존 API로 만든 분리주의·복수전쟁 stress에서 실제 분쟁 진행·해결·참조 유지 확인. 여기서 내전 건수는 역사에 생성된 internalConflicts 수이며 전 구간이 항상 교전 상태라는 뜻은 아닙니다.'],
['외교 패턴',`seed2030 200년 실제 행동 집계 ${JSON.stringify(a.diplomaticActions)}. 정상 50년 마지막 관계 범위 ${n(Math.min(...short.flatMap((r:any)=>r.relations.map((x:any)=>x.relations))))}–${n(Math.max(...short.flatMap((r:any)=>r.relations.map((x:any)=>x.relations))))}. 평시 무역·불가침 위주이며 방위조약·제재가 반드시 생기도록 유도하지 않았습니다. 기존 전쟁·신생국·제재/해제 브라우저 회귀와 자동 테스트도 유지했습니다.`],
['국제전쟁 빈도','정상 초기 두 국가는 평화적인 정책·관계여서 평시 배치 전쟁 0. 3시드에서 동급전·강약전·복수전쟁을 각각 검증했습니다. 복수전쟁은 실제 국제전쟁 2개와 독립 분쟁을 동시에 시작합니다. 강약전은 실제 GDP·군수투자·준비도 차이를 주며 전투 RNG를 조작하지 않습니다.'],
['평균·최대 전쟁기간',`stress normal 표본: ${JSON.stringify(warDurations)}. 평시 전쟁 표본이 없으므로 평시 평균 0을 기간의 추정치로 해석하지 않습니다. 100년 미해결 전쟁은 이번 표본에서 없었습니다. 동급·강약·복수전쟁 표본은 모두 현상유지 평화였고 영토 이전은 없었습니다. 추가 seed2030 경로 관찰에서 강한 공격측의 첫 달 능력 79.6 대 39.5와 통제 +2.58%p는 나타났지만, 양측 사건/AI 협상 선택으로 6개월 이내 전선이 고정됐습니다. 따라서 강국의 전술 우위는 확인했고 최종 승패 다양성은 충분히 입증하지 못했습니다. simulation/results/war-path/results.json에 원경로를 남겼습니다.`],
['동원 장기상태',`정상 200년 최종 동원: ${JSON.stringify(long[0].mobilization)}. 전쟁 후 동원 회복과 지속 중인 분쟁의 비용은 기존 규칙을 따릅니다. 전쟁 표본의 최종 미해결 건수 합계 ${stress.reduce((s:number,r:any)=>s+r.openWars,0)}.`],
['기술 진행속도',table(['전략','50년 플레이어 평균 Lv','100년 플레이어 평균 Lv','50년 GDP','100년 GDP'],c.technology.map((r:any)=>{const p=(m:number)=>r.checkpoints.find((x:any)=>x.months===m).profiles.find((p:any)=>p.id==='sparrow');return [r.strategy,n(mean(Object.values(p(600).technology) as number[])),n(mean(Object.values(p(1200).technology) as number[])),n(p(600).gdp),n(p(1200).gdp)];}))+'\n\n동일 seed2030, 저세율 산업투자·AI 기준·고연구/교육 투자 비교. 자동화 플레이어는 실제 연구 명령으로 빈 슬롯을 채우고 같은 기술 순서를 사용합니다. 연구 예산만 바꾼 순수 인과 실험은 아니며 교육·세율의 기회비용도 포함합니다.'],
['technology saturation',`정상 50년 평균 Lv ${n(f.short.technologyMean.mean)}, Lv10 비중 ${pct(f.short.level10Share.mean)}. 200년 평균 Lv ${n(f.long.technologyMean.mean)}, Lv10 비중 ${pct(f.long.level10Share.mean)}. 시작 수십 년 내 전 분야 포화는 없고 200년 이후 기술 선택의 여지는 줄어듭니다. 기술 트리 연장은 이번 범위에 포함하지 않았습니다.`],
['crisis 빈도',`정상 50년 평균 ${n(f.short.crises.mean)}건/세계, 200년 평균 ${n(f.long.crises.mean)}건. 여러 관할의 위기이므로 세계 합계입니다. 가장 큰 사건·위기를 별도 API로 주입한 stress와 자연 발생 통계를 구분했습니다.`],
['위기 지속기간',table(['종류','건수','평균','중앙','P10','P90','최소','최대'],Object.entries(crisisDurations).map(([k,v])=>[k,(v as number[]).length,...stats(distribution(v as number[]))]))+'\n\n종료된 위기만 기간 분포에 넣었습니다. resilience 저/중/고 수준의 동일 storm 피해·회복 비교: '+JSON.stringify(c.resilience)],
['지도자 mortality 분포',table(['난이도','반복 상황노출','표본','평균 나이','중앙','P10','P90','최대','자연 사망 비중'],c.mortality.map((r:any)=>[r.difficulty,r.exposed,r.leaders,n(r.age.mean),n(r.age.median),n(r.age.p10),n(r.age.p90),n(r.age.max),pct(r.naturalDeathShare)]))+'\n\n총 60,000가상 지도자. 실제 자연 위험 함수를 월별 판정. 노출군은 36개월 중 8개월씩 동일한 강한 폭풍의 leaderRisk 추가분을 적용하는 통제 실험이며 전체 세계 생애를 모사한 것은 아닙니다. 자연 노화가 주원인이고 난이도별 자연 수명은 같습니다.'],
['정책 cadence 영향',`세율 3개월·예산 12개월·긴급 예산 6개월 유지. 연간 전략 변경은 API 허용 시점에만 적용합니다. 고부채 AI는 새 일정 하에서 재정 urgency≥85인 경우 후보 세율 폭을 0.5→1.5%p로 확대합니다. 변경 잠금이나 상한을 우회하지 않습니다. stress의 긴급 예산 수정 관측 합계 ${stress.reduce((s:number,r:any)=>s+r.emergencyChanges,0)}회(모든 정부). 이전 free-policy fixture의 1,218개 회귀 규칙도 유지했습니다.`],
['AI profile 차이','industrial·social·research·agricultural·security·balanced의 기존 우선순위·효용 판단 유지. 아래 시작 관할별 산업·사회·기술 결과가 다릅니다. research는 연구·교육, agricultural은 농업 기반, security는 군수 우선이며 같은 난이도 규칙과 정책 API를 사용합니다. 미래 정보·AI 전용 자원은 추가하지 않았습니다.'],
['시작국 밸런스',profTable+'\n\n공화국 직접정부, 연방 4개 실제 주 정부를 비교했습니다. 연방 총합은 주들과 같은 관할로 중복 집계하지 않습니다. 오리 농업·독수리 제조/군수·부엉이 첨단 등 특화가 장기에도 남습니다.'],
['scripted strategy 비교',table(['전략','100년 GDP','부채/GDP','생활','지지도','평균 기술 Lv'],strategies.map((r:any)=>{const p=r.checkpoints.at(-1).profiles.find((p:any)=>p.id==='sparrow');return [r.strategy,n(p.gdp),n(p.debtRatio),n(p.social.livingStandard),n(p.governance.approval),n(mean(Object.values(p.technology) as number[]))];}))+'\n\n복지·산업·연구·군사 전략은 세율과 예산을 함께 조절합니다. NPC는 월말 동일 국내 AI가 운영합니다. 플레이어는 고정 정책·동일 연구 슬롯 순서, 사건의 정의상 nonPlayerChoice를 사용합니다.'],
['dominant strategy 여부','단일 seed2030에서 성장·사회·재정·기술 성과의 교환관계를 확인했습니다. 이 표본으로 모든 상황의 지배전략 부재를 증명하지는 못합니다. 산업 전략의 고부채, 연구/복지의 세율·성장 비용, 군사의 민간 투자 비용을 그대로 남겼습니다. 10B-2에서는 플레이어가 이런 비용을 읽기 쉽게 표현해야 합니다.'],
['simulation harness 구조','실제 advanceMonth와 저장 PRNG를 사용. 독립 프로세스 4개, 고정 seed. 매 120개월 합계·유한값·범위·지역 소유자·역사 국가 참조·연표 ID 중복 검사. 세계 관찰 배치는 autonomousWorld와 사망확률 0/선거 난수 0으로 관찰을 계속하므로 지도자 생존율과 구분합니다. 생존/선거는 comparisons에서 정상 종료 조건으로 별도 검증합니다. 매 완료 작업 JSON, aggregate의 평균·중앙·P10/P90·최소/최대 보존.'],
['50-seed ×600개월 결과',metricTable(f.short)+'\n\nseed=1001+i×7919, i=0…49. debt는 각 run의 기간 중 국가 최대 debt/GDP를 집계한 값이며 최종 평균 부채가 아닙니다.'],
['10-seed ×2400개월 결과',metricTable(f.long)+'\n\n첫 10개 동일 seed. 모든 장기 저장을 실제 역직렬화 후 120개월 더 진행하고 참조·합계·유한성을 재검사했습니다.'],
['500년 endurance 결과',`seed99101, 실제 ${ultra.months}개월 + 불러온 후 120개월. GDP ${n(ultra.gdpRatio)}배, 인구 ${n(ultra.popRatio)}배. 역사 ${n(ultra.historyBytes)}bytes, 저장 ${n(ultra.saveBytes)}bytes. 미해결 전쟁 ${ultra.openWars}, loadAdditionalTurn=${ultra.loadAdditionalTurn}. NaN·Infinity·음수·ID/소유자 오류 없음. 다만 수백만 배 GDP와 수천 배 인구는 500년 플레이 밸런스의 한계로 남고 현실적 평형 달성으로 주장하지 않습니다.`],
['stress scenario 결과',table(['상황','seed','국가 수','독립','분쟁','전쟁','미해결 전쟁','GDP배','최대 부채/GDP','인구배','위기 피해인구'],stress.filter((r:any)=>r.scenario!=='normal').map((r:any)=>[r.scenario,r.seed,r.finalCountryCount,r.independences,r.internalConflicts,r.wars,r.openWars,n(r.gdpRatio),n(r.peakDebt),n(r.popRatio),n(r.crisisPopulationDamage)]))+'\n\n각 240개월. recession·debt·disease·storm·separatism·war·asymmetric·multiwar·prosperity 각 3시드. fixture는 기존 상태/API로 주입하고 이후 정상 RNG를 사용합니다. 회복·패배를 확정하는 난수는 쓰지 않습니다.'],
['Easy/Normal/Hard 비교',table(['난이도','10개 게임 평균 운영개월','240개월 유지','종료시 생존','평균 지지도','평균 재선확률','평균 월 사망위험','평균 위기 피해'],['easy','normal','hard'].map(d=>{const p=c.players.filter((r:any)=>r.difficulty===d);return [d,n(mean(p.map((r:any)=>r.months))),p.filter((r:any)=>r.months===240&&!r.gameOverReason).length,p.filter((r:any)=>r.alive).length,n(mean(p.map((r:any)=>r.averageApproval))),pct(mean(p.map((r:any)=>r.averageElectionChance))),(mean(p.map((r:any)=>r.averageMortality))*100).toFixed(6)+'%',n(mean(p.map((r:any)=>r.crisisDamage)))];}))+'\n\n동일 10시드, 240개월 상한의 실제 게임(사망·선거 패배 종료 적용)입니다. 이 20년 표본에서는 사망이 발생하지 않았고 유지 실패는 선거 패배였습니다. 자연 수명·상황 노출은 별도 60,000명 실험에서 확인했습니다. 외교 알림에는 공통 고정 응답을 사용합니다. 도중 종료와 발생 조건의 분기로 총 피해가 반드시 난이도 순으로 늘어나지는 않습니다. 동일 storm의 같은 시점 피해·회복 순서는 단위 테스트와 240개월 observer 비교에서 확인했습니다.'],
['수정한 주요 config 값','이번 변경값은 sectorShareThreshold=1.5, sectorGrowthPressure=0.02, distressedDebtRatio=1, distressedInterestCeiling=8, distressedInterestScale=0.6, fiscalEmergencyUrgency=85, fiscalEmergencyTaxStep=1.5입니다. 난이도 외 전체 일괄 배율·세율 2배·전쟁 강제 억제를 추가하지 않았습니다.'],
['수정 전/후 비교',table(['지표','보존한 10A 기준','최종Normal'],[['50년 연평균 성장',n(b.short.annualGrowth.mean)+'%',n(f.short.annualGrowth.mean)+'%'],['200년 GDP평균 배수',n(b.long.gdpRatio.mean),n(f.long.gdpRatio.mean)],['200년 인구평균 배수',n(b.long.popRatio.mean),n(f.long.popRatio.mean)],['50년 crisis 평균',n(b.short.crises.mean),n(f.short.crises.mean)],['200년 기술 평균Lv',n(b.long.technologyMean.mean),n(f.long.technologyMean.mean)]])],
['장기병리 발견사항','첨단산업 비중의 장기 압도와 고부채 이자 악순환을 수정했습니다. 평시 고지지도/평화 쏠림, 매우 장기 기술 포화, 500년 인구·GDP의 높은 복리 성장, 일부 전략의 부채 누적, 전쟁 사건의 조기 협상과 현상유지 종결 쏠림은 남은 한계입니다. 전쟁을 강제로 연장하거나 승자를 정하는 패치는 넣지 않았습니다. 이번 배치의 수치 안정성은 통과했지만 모든 seed와 모든 정책의 무한기간 안정성을 보장하는 보고가 아닙니다.'],
['save/load 회귀','schema1 실제 JSON 가져오기→normal, 3난이도별 저장·새로고침·불러오기. 200년 10개+500년1개 full-save→load→120추가개월, 세계/난수·정책 잠금·참조 검증. 이전 수동/자동/빠른 저장·내보내기·가져오기·게임오버 후 저장 브라우저 시나리오 유지.'],
['테스트 총 개수','기존 1,218개 유지 + 난이도/밸런스/검증 53개 = 1,271개. 최종 전체 실행에서 1,271개 통과, 실패·스킵 0. 결과는 .test-output/10b-final-tests.txt에 기록했습니다.'],
['TypeScript','최종 tsc -b 통과. simulation 도구는 실행 검증 외에 별도의 strict noEmit 검사도 수행했습니다.'],
['빌드','최종 pnpm build 통과. production 난이도·월 진행·디버그 미노출 실제 브라우저 확인.'],
['브라우저 검증','기존 21개 PC·모바일 시나리오 통과(현재 기록 탭/저장 PRNG에 맞게 오래된 검증 선택자 갱신). 신규3난이도 선택·읽기 전용·저장/재시작·연방 주 선택 유지·390px 화면·v1 migration·production 확인, pageerror 0. 보안프로그램 404는 요청대로 검증 실패로 취급하지 않았습니다.'],
['10B-2 UX/튜토리얼 개선 목록','세계 전체 위기 수와 플레이어 위기 수 구분; 정책 잠금/긴급 변경과 재정 정상화의 시간 설명; 산업 성장 압력·이자 곡선의 쉬운 안내; 고지지도여도 남는 선거 위험; 연구 슬롯과 장기 포화 표시; 국고·GDP 절대값보다 비율 우선; 평시 장기간의 선택 밀도; 전쟁/독립은 조건부이고 자동 발동이 아니라는 설명; 500년 관찰 결과의 성장 한계. 이번 단계에서 튜토리얼·UI 전면 개편을 구현하지 않았습니다.'],
['11단계 game-over reason 연결점',"기존 GameOverReason의 death | election_defeat | state_defeat와 player 사망일·career·역사 자료를 다음 단계의 연결점으로 유지했습니다. 이번 단계에서 새로운 종료조건·Good/Bad·최종점수·업적·엔딩 분류를 추가하지 않았습니다."]
];
const intro='# Bird Kingdom 10B-1 완료 보고\n\n실제 최종 코드 실행 결과입니다. Normal은 기준 규칙, Easy/Hard는 플레이어 관할의 작은 보정입니다. 표본의 안정성과 남은 플레이 밸런스 한계를 구분합니다.\n\n## 실행·재현\n\n```sh\npnpm dev\npnpm test\npnpm build\npnpm exec tsx simulation/run.ts final src\npnpm exec tsx simulation/comparisons.ts\npnpm exec tsx simulation/audit.ts\npnpm exec tsx simulation/generateReport.ts\npnpm balance  # 같은 배치를 candidate 폴더에 새로 실행\n```\n\n배치는 기본적으로 새로 실행합니다. 중단 결과를 이어갈 때만 `--resume`을 붙이세요. 최종 원자료는 [final](simulation/results/final/aggregate.json), 수정 전 [baseline](simulation/results/baseline/aggregate.json), [실세계·선거·수명 비교](simulation/results/comparisons/results.json), [200년 세부 관찰](simulation/results/audit/results.json), [실행 설정](simulation/results/final/config.json)입니다.\n\n새 환경에서는 comparisons 실행 전에 아래 원본 소스를 먼저 압축 해제해야 합니다. 수정 전 소스는 [source-10a.zip](simulation/results/baseline/source-10a.zip)에 보존했습니다. PowerShell에서 `Expand-Archive -LiteralPath simulation/results/baseline/source-10a.zip -DestinationPath .test-output/10b-baseline` 후 `pnpm exec tsx simulation/run.ts baseline-replay .test-output/10b-baseline --baseline`으로 원규칙의61배치를 재실행할 수 있습니다. 캐시 결과를 새 설정의 결과로 재사용하지 마세요.\n\n집계는 run별 통계, 10년 checkpoint의 관할 표본, 또는 발생 사건별 통계인지 각 항목에 표시합니다. 동일 seed라도 수치 변화가 조건·사건 분기를 바꾸므로 이후 모든 난수 소비 시점이 같다고 가정하지 않습니다.\n\n';
writeFileSync('BALANCE.md',intro+sections.map(([title,body],i)=>'## '+(i+1)+'. '+title+'\n\n'+body+'\n').join('\n'));
console.log('REPORT',sections.length,'sections');
