import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import type {GameState} from '../src/game/types';
export const mean=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
export const percentile=(v:number[],p:number)=>{if(!v.length)return 0;const s=[...v].sort((a,b)=>a-b),i=(s.length-1)*p,lo=Math.floor(i);return s[lo]+(s[Math.ceil(i)]-s[lo])*(i-lo);};
export const distribution=(v:number[])=>({count:v.length,mean:mean(v),median:percentile(v,.5),p10:percentile(v,.1),p90:percentile(v,.9),min:v.length?Math.min(...v):0,max:v.length?Math.max(...v):0});
export async function modules(source='src'){const load=(file:string)=>import(pathToFileURL(resolve(source,'game',file+'.ts')).href);const [engine,crisis,secession,cb,war,events,save,election,tax,budget,tech,ai,commands,defs]=await Promise.all(['engine','crisis','secession','casusBelli','warfare','events','save','election','taxPolicy','budgetPolicy','technology','ai','strategicCommands','technologyDefinitions'].map(load));return {engine,crisis,secession,cb,war,events,save,election,tax,budget,tech,ai,commands,defs};}
export function assertWorld(game:GameState){const check=(v:unknown)=>{if(typeof v==='number'&&!Number.isFinite(v))throw new Error('Non-finite world value at turn '+game.turn);if(v&&typeof v==='object')for(const x of Object.values(v))check(x);};check(game.world);for(const c of Object.values(game.world.countries))if(c.economy.gdp<0||c.population.total<0||c.fiscal.debt<0||c.fiscal.treasury<0)throw new Error('Negative state');for(const r of Object.values(game.world.regions))if(!game.world.countries[r.ownerCountryId])throw new Error('Dangling region');for(const r of [...Object.values(game.world.countries),...Object.values(game.world.regions)]){const pop=Object.values(r.population.species).reduce((n,p)=>n+p.population,0),gdp=Object.values(r.economy.industries).reduce((n,i)=>n+i.output,0);if(pop!==r.population.total||Math.abs(gdp-r.economy.gdp)>Math.max(1,r.economy.gdp)*1e-8)throw new Error('Aggregate mismatch');for(const k of ['livingStandard','education','healthcare','publicSafety','inequality'] as const){const n=r.social?.[k];if(typeof n==='number'&&(n<0||n>100))throw new Error('Social bounds');}for(const d of Object.values(r.technology?.domains??{}))if(d.level<0||d.level>10)throw new Error('Technology bounds');}const h=game.history!;for(const id of Object.keys(game.world.countries))if(!h.countries[id])throw new Error('Missing historical country');if(new Set(h.timeline.map(e=>e.id)).size!==h.timeline.length)throw new Error('Historical ID collision');}
export async function scenario(g:GameState,name:string,m:Awaited<ReturnType<typeof modules>>){const c=g.world.countries.sparrow,r=g.world.regions['eagle-state'];
 if(name==='recession'){for(const x of [c,...Object.values(g.world.regions)]){x.economy.cycle=-1;x.economy.growth=-7;x.economy.unemployment=22;x.fiscal.treasury=x.economy.gdp*.01;}}
 if(name==='debt'){for(const x of [c,...Object.values(g.world.regions)]){x.fiscal.debt=x.economy.gdp*3;x.fiscal.treasury=0;}}
 if(name==='disease'||name==='storm')g=m.crisis.startCrisis(g,{kind:'country',id:'sparrow'},name==='disease'?'respiratory_outbreak':'great_storm',95);
 if(name==='separatism'||name==='multiwar'){Object.assign(r.speciesPolitics.eagle!,{satisfaction:5,autonomyDemand:98,independenceSentiment:98});r.governance.integration=10;Object.assign(r.secession!.eagle!,{phase:'unilateral_crisis',monthsActive:36,monthsInPhase:6,lastRefusalTurn:1});g=m.secession.createBreakawayCountry(g,{kind:'region',id:r.id},'eagle',true);}
 if(['war','asymmetric','multiwar'].includes(name)){g=m.cb.addCasusBelli(g,'sparrow','pigeon','territorial_dispute','duck-state');g=m.war.declareWar(g,'sparrow',Object.keys(g.world.warfare!.casusBelli)[0],'border_claim',true,true);if(name==='asymmetric'){Object.assign(g.world.countries.sparrow.military!,{readiness:95,logistics:95,capability:95});Object.assign(g.world.countries.pigeon.military!,{readiness:15,logistics:15,capability:15});const strong=g.world.countries.sparrow;strong.economy.gdp*=3;for(const industry of Object.values(strong.economy.industries))industry.output*=3;strong.fiscal.budgetPolicy.defense=6;strong.military!.effectiveDefenseBudget=6;}}
 if(name==='multiwar'){const target='eagle-republic-1';g=m.cb.addCasusBelli(g,'sparrow',target,'territorial_dispute','eagle-state');const id=Object.values(g.world.warfare!.casusBelli).find(c=>c.targetCountryId===target&&!c.consumed)!.id;g=m.war.declareWar(g,'sparrow',id,'border_claim',true,true);}
 if(name==='prosperity'){for(const x of [c,...Object.values(g.world.regions)]){x.fiscal.treasury=x.economy.gdp*.5;for(const d of Object.values(x.technology!.domains))d.level=9;}}
 return g;
}
export async function runSimulation(seed:number,months:number,source='src',scenarioName='normal',difficulty='normal',strategy='ai',observer?:(game:GameState)=>void){
 const m=await modules(source);let g:GameState=m.engine.createGame('sparrow',undefined,seed,difficulty);g=await scenario(g,scenarioName,m);const initialGDP=Object.values(g.world.countries).reduce((s,c)=>s+c.economy.gdp,0),initialPop=Object.values(g.world.countries).reduce((s,c)=>s+c.population.total,0);
 let activeCountrySum=0,singleCountryMonths=0;let peakDebt=0,maxInflation=-Infinity,minInflation=Infinity,approval=0,risk=0,chance=0,activeCrisisMonths=0,emergencyChanges=0;const checkpoints:any[]=[],warActiveMonths:Record<string,number>={},firstWarPause:Record<string,number>={};
 for(let i=0;i<months;i++){
  // Observer world experiments intentionally bypass only leader death/election defeat; actual world RNGs remain persisted.
  if(strategy!=='ai'){
   const c=g.world.countries.sparrow;if(c&&g.turn%12===1){const profiles:any={welfare:{incomeTaxRate:29,corporateTaxRate:25,consumptionTaxRate:17},industry:{incomeTaxRate:15,corporateTaxRate:14,consumptionTaxRate:10},research:{incomeTaxRate:23,corporateTaxRate:22,consumptionTaxRate:14},military:{incomeTaxRate:25,corporateTaxRate:23,consumptionTaxRate:15}};try{g=m.tax.setControlledTaxPolicy(g,profiles[strategy]);const p={...c.fiscal.budgetPolicy};if(strategy==='welfare')Object.assign(p,{welfare:5,healthcare:4});if(strategy==='industry')Object.assign(p,{industrySupport:3,infrastructure:3,welfare:1});if(strategy==='research')Object.assign(p,{research:4,education:4,defense:1});if(strategy==='military')Object.assign(p,{defense:6,research:1,welfare:1});g=m.budget.setControlledBudgetPolicy(g,p);}catch(e){if(!(e instanceof Error)||!e.message.includes('개월'))throw e;}}
  }
  if(strategy!=='ai'){for(const def of m.defs.technologyDefinitions){const t=g.world.countries.sparrow.technology!;if(!t.domains[def.domain as keyof typeof t.domains].currentResearchId&&!m.tech.researchBlock(t,def.id))g=m.tech.setResearch(g,def.domain,def.id);}}
  for(const w of Object.values(g.world.warfare!.wars))if(w.status==='active')warActiveMonths[w.id]=(warActiveMonths[w.id]??0)+1;
  const before=g;g=m.engine.advanceMonth(g,{autonomousWorld:true,domesticAI:strategy==='ai',mortalityRiskOverride:0,electionRandom:()=>0});if(strategy!=='ai')g=m.ai.updateDomesticAI(g);for(const w of Object.values(g.world.warfare!.wars))if(w.status!=='active'&&firstWarPause[w.id]===undefined)firstWarPause[w.id]=w.monthsAtWar; if(g.turn===before.turn)throw new Error('Observer turn blocked '+g.gameOverReason);
  observer?.(g);
  activeCountrySum+=Object.keys(g.world.countries).length;singleCountryMonths+=Number(Object.keys(g.world.countries).length===1);
  for(const [id,c] of Object.entries(g.world.countries)){peakDebt=Math.max(peakDebt,c.fiscal.debt/Math.max(1,c.economy.gdp));maxInflation=Math.max(maxInflation,c.economy.inflation);minInflation=Math.min(minInflation,c.economy.inflation);}
  for(const [id,b] of Object.entries(g.policySchedules??{})){const a=before.policySchedules?.[id];if(a&&b.emergencyNextChangeTurn>a.emergencyNextChangeTurn)emergencyChanges++;}
  approval+=g.world.countries[g.player.controlledCountryId].governance?.approval??0;risk+=g.player.leaderRisk?.mortalityModifierLastMonth??0;chance+=m.election.createElectionSnapshot(g).reelectionChance;activeCrisisMonths+=Number(Object.keys(g.world.crises!.activeCrises).length>0);
  if((i+1)%120===0){assertWorld(g);const countries=Object.values(g.world.countries);checkpoints.push({months:i+1,countryCount:countries.length,gdpRatio:countries.reduce((s,c)=>s+c.economy.gdp,0)/initialGDP,popRatio:countries.reduce((s,c)=>s+c.population.total,0)/initialPop,profiles:[...countries,...Object.values(g.world.regions).filter(r=>r.simulationRole!=='administrative')].map(c=>({id:c.id,gdp:c.economy.gdp,treasuryRatio:c.fiscal.treasury/Math.max(1,c.economy.gdp),debtRatio:c.fiscal.debt/Math.max(1,c.economy.gdp),unemployment:c.economy.unemployment,inflation:c.economy.inflation,social:c.social,governance:c.governance,industryShares:Object.fromEntries(Object.entries(c.economy.industries).map(([id,v])=>[id,v.output/Math.max(1,c.economy.gdp)])),technology:Object.fromEntries(Object.entries(c.technology!.domains).map(([id,d])=>[id,d.level]))}))});}
 }
 assertWorld(g);const h=g.history!,last=checkpoints.at(-1),wars=Object.values(h.wars),crises=Object.values(h.crises),levels=Object.values(g.world.regions).filter(r=>r.simulationRole!=='administrative').flatMap(r=>Object.values(r.technology!.domains).map(d=>d.level));
 let saveBytes=0,historyBytes=Buffer.byteLength(JSON.stringify(h)),loadAdditionalTurn:number|undefined;if(months>=2400){const text=m.save.serializeSave(m.save.createSaveData(g,'simulation'));saveBytes=Buffer.byteLength(text);let loaded=m.save.deserializeSave(text).game;for(let i=0;i<120;i++)loaded=m.engine.advanceMonth(loaded,{autonomousWorld:true,mortalityRiskOverride:0,electionRandom:()=>0});assertWorld(loaded);loadAdditionalTurn=loaded.turn;}
 return {initialDissolved:Object.values(h.countries).filter(c=>c.foundingType==='initial'&&c.dissolvedDate).length,singleCountryMonths,meanActiveCountries:activeCountrySum/months,seed,months,source,scenario:scenarioName,difficulty,strategy,finalCountryCount:Object.keys(g.world.countries).length,independences:Object.values(h.countries).filter(c=>c.foundingType!=='initial').length,dissolved:Object.values(h.countries).filter(c=>c.dissolvedDate).length,internalConflicts:Object.keys(h.internalConflicts).length,wars:wars.length,warDurations:wars.map(w=>w.durationMonths),warActiveMonths:Object.values(warActiveMonths),firstWarPause:Object.values(firstWarPause),warResults:wars.map(w=>({result:w.result,status:w.status,territorialChanges:w.territorialChanges.length})),openWars:wars.filter(w=>!w.endedDate).length,crises:crises.length,crisisDurations:crises.map(c=>({type:c.type,months:c.durationMonths,ended:!!c.endedDate})),crisisPopulationDamage:crises.reduce((s,c)=>s+c.totalPopulationImpact,0),activeCrisisShare:activeCrisisMonths/months,events:g.events.history.length,eventCategories:g.events.history.reduce((s:any,e)=>{s[e.category]=(s[e.category]??0)+1;return s;},{}),peakDebt,maxInflation,minInflation,gdpRatio:last?.gdpRatio,popRatio:last?.popRatio,annualGrowth:last?Math.expm1(Math.log(last.gdpRatio)/(months/12))*100:0,averageApproval:approval/months,averageElectionChance:chance/months,averageSituationalRisk:risk/months,technologyMean:mean(levels),level10Share:levels.filter(l=>l>=10).length/levels.length,completedCountries:Object.values(g.world.countries).filter(c=>Object.values(c.technology!.domains).every(d=>d.level>=10)).length,relations:Object.values(g.world.diplomacy!.relations).map(r=>({relations:r.relations,trade:r.tradeLevel,nap:r.nonAggressionPact,defense:r.defensePact,sanctions:r.sanctionsAtoB||r.sanctionsBtoA})),mobilization:Object.values(g.world.countries).map(c=>({id:c.id,target:c.military!.mobilizationTarget,actual:c.military!.mobilization})),emergencyChanges,saveBytes,historyBytes,loadAdditionalTurn,checkpoints};
}


