import {runSimulation} from './harness';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';import {spawn} from 'node:child_process';
import type {GameState} from '../src/game/types';
export function strategyObserver(){const seen=new Set<string>(),counts:Record<string,number>={},byActor:Record<string,Record<string,number>>={},wars=new Map<string,any>();let activeMonths=0,months=0,peakCountries=0,last:GameState;
 const count=(key:string,actor:string,id:string)=>{if(seen.has(id))return;seen.add(id);counts[key]=(counts[key]??0)+1;const p=byActor[actor]??={};p[key]=(p[key]??0)+1;};
 return {observe(g:GameState){last=g;months++;peakCountries=Math.max(peakCountries,Object.keys(g.world.countries).length);activeMonths+=Number(Object.values(g.world.warfare!.wars).some(w=>w.status!=='resolved'));
 for(const w of Object.values(g.world.warfare!.wars))wars.set(w.id,{legitimacy:w.legitimacy,months:w.monthsAtWar,status:w.status});
 for(const [id,p] of Object.entries(g.world.federalPolitics??{}))for(const h of p.history)count('federal:'+h.action,id,h.id);
 for(const p of Object.values(g.world.statePolitics!.relations)){for(const h of p.history)count('state:'+h.action,h.actorId,h.id);for(const m of p.mediations)count('mediation:'+m.outcome,'pigeon',m.id);}
 for(const b of g.world.statePolitics!.blocs){count('bloc:'+b.purpose,'states',b.id);if(!b.active)count('bloc_ended:'+b.endReason,'states','ended:'+b.id);}
 for(const d of g.world.diplomacy!.history)if(['sanction','defense','improve'].includes(d.action))count(d.action,d.actorId,d.id);
 },result(){const list=[...wars.values()],resolved=list.filter(w=>w.status==='resolved');return {actions:counts,byActor,warsStarted:list.length,justified:list.filter(w=>w.legitimacy==='justified').length,unjustified:list.filter(w=>w.legitimacy==='unjustified').length,warsPer100Years:list.length/(months/1200),meanWarDuration:resolved.reduce((s,w)=>s+w.months,0)/Math.max(1,resolved.length),worldWarMonthShare:activeMonths/Math.max(1,months),peakCountries,activeCountries:Object.keys(last.world.countries).length,newCountries:Object.values(last.history!.countries).filter(c=>c.foundingType!=='initial').length,startingDissolutions:Object.values(last.history!.countries).filter(c=>c.foundingType==='initial'&&c.dissolvedDate).length,internalConflicts:Object.keys(last.history!.internalConflicts).length,worldUnifications:Object.keys(last.world.countries).length===1?1:0,reverseFederationFalsePositive:Number(last.achievements?.unlocked.some(a=>a.achievementId==='reverse-federation')&&!last.player.origin?.startedAsFederationState)};}};
}
const args=process.argv.slice(2),dir='.test-output/strategy-long';mkdirSync(dir,{recursive:true});
if(process.argv[1]?.endsWith('strategyRun.ts')&&args[0]==='worker'){const [,seed,months,file]=args,observer=strategyObserver(),start=Date.now();const result=await runSimulation(+seed,+months,'src','normal','normal','ai',observer.observe);writeFileSync(file,JSON.stringify({...result,strategyAudit:observer.result(),elapsedMs:Date.now()-start}));}
else if(process.argv[1]?.endsWith('strategyRun.ts')&&args[0]!=='import'){const jobs=[...Array.from({length:20},(_,i)=>({seed:1001+i*7919,months:600})),...Array.from({length:5},(_,i)=>({seed:1001+i*7919,months:2400}))];let index=0;const results:any[]=[];await Promise.all(Array.from({length:2},async()=>{while(index<jobs.length){const n=index++,j=jobs[n],file=`${dir}/run-${n}.json`;await new Promise<void>((ok,bad)=>{const p=spawn(process.execPath,['--import','tsx','simulation/strategyRun.ts','worker',String(j.seed),String(j.months),file],{stdio:'inherit',windowsHide:true});p.on('error',bad);p.on('exit',code=>code===0?ok():bad(new Error('worker '+n+' failed')));});results.push(JSON.parse(readFileSync(file,'utf8')));console.log('COMPLETE',n,j.months);}}));writeFileSync(`${dir}/aggregate.json`,JSON.stringify({results},null,2));console.log('DONE',results.length);}
