import {useState} from 'react';
import type {AnnualSummary,AnnualMetricChange} from '../game/annualTypes';
import type {GameState} from '../game/types';
import {formatEconomyNumber} from './EconomyMetrics';
import {formatPopulation} from './PopulationView';
import {useDialog} from './useDialog';
export function formatAnnualValue(value:number,m:AnnualMetricChange){if(m.key==='population')return formatPopulation(value)+' 명';if(m.unit==='십억 BK')return formatEconomyNumber(value)+' 십억 BK';return value.toFixed(1)+(m.unit==='%p'?'%':'점');}
export function formatAnnualChange(m:AnnualMetricChange){const delta=['gdp','population','debt'].includes(m.key)&&m.percentageChange!==undefined?m.percentageChange:m.absoluteChange;const unit=['gdp','population','debt'].includes(m.key)&&m.percentageChange!==undefined?'%':m.unit;return (delta>0?'+':'')+delta.toFixed(1)+unit;}
export function AnnualReportBody({report}:{report:AnnualSummary}){return <article className="annual-body"><span className="eyebrow">{report.jurisdictionName} · {report.comparisonLabel}</span><h3>{report.headline}</h3><p>{report.description}</p><p className="annual-period">{report.startDate.year}.{String(report.startDate.month).padStart(2,'0')} — {report.endDate.year}.{String(report.endDate.month).padStart(2,'0')}</p><section aria-label="주요 수치 변화" className="annual-metrics">{report.metrics.map(m=><div key={m.key}><span>{m.label}</span><strong>{formatAnnualValue(m.startValue,m)} → {formatAnnualValue(m.endValue,m)}</strong><b>{formatAnnualChange(m)}</b></div>)}</section><h4>주요 사건</h4>{report.majorEvents.length?<ul className="annual-events">{report.majorEvents.map(e=><li key={e.historyId}><span>{e.date.year}년 {e.date.month}월</span><strong>{e.title}</strong><p>{e.description}</p></li>)}</ul>:<p>기록된 주요 사건이 없습니다.</p>}</article>;}
export function AnnualReportDialog({report,onClose}:{report:AnnualSummary;onClose:()=>void}){const ref=useDialog(onClose);return <div className="report-overlay"><section ref={ref} className="report-dialog annual-dialog" role="dialog" aria-modal="true" aria-labelledby="annual-title" tabIndex={-1}><header><h2 id="annual-title">{report.year}년 연간 보고</h2><button className="secondary" onClick={onClose}>닫기</button></header><div className="report-scroll"><AnnualReportBody report={report}/></div></section></div>;}
export function AnnualReportHistory({game}:{game:GameState}){const [selected,setSelected]=useState<string|null>(null),reports=[...(game.annual?.summaries??[])].reverse(),report=reports.find(r=>r.id===selected);return <section aria-label="연간 보고서"><h3>연간 보고서</h3>{reports.length?reports.map(r=><button key={r.id} className="annual-history-card secondary" onClick={()=>setSelected(r.id)}><strong>{r.year}년 · {r.jurisdictionName}</strong><span>{r.headline} →</span></button>):<p>첫 12개월을 진행하면 연간 보고서가 기록됩니다.</p>}{report&&<AnnualReportDialog report={report} onClose={()=>setSelected(null)}/>}</section>;}
