import {crisisDefinitions} from '../game/crisisConfig';
import {useState} from 'react';
import {selectHistoricalCountries,selectCountryLineage} from '../game/historySelectors';
import {formatDate} from '../game/engine';
import {species} from '../game/data';
import type {HistoryState} from '../game/historyTypes';
export default function CountryHistoryView({history}:{history:HistoryState}){const list=selectHistoricalCountries(history),[selected,setSelected]=useState(list[0]?.countryId??''),c=history.countries[selected]??list[0];if(!c)return <p>국가 기록이 없습니다.</p>;const milestones=history.technologyMilestones.filter(t=>t.countryId===c.countryId),crises=Object.values(history.crises).filter(t=>t.countryId===c.countryId&&t.maxSeverity>=60);return <section aria-label="국가 생애 기록"><label>역사적 국가<select aria-label="역사적 국가" value={c.countryId} onChange={e=>setSelected(e.target.value)}>{list.map(r=><option value={r.countryId} key={r.countryId}>{r.currentOrFinalName} · {r.foundedDate.year}–{r.dissolvedDate?.year??'현재'}{r.dissolvedDate?' · 소멸':''}</option>)}</select></label><article className="panel history-detail"><h2>{c.currentOrFinalName}</h2><p>{c.foundedDate.year}–{c.dissolvedDate?.year??'현재'} · {c.dissolvedDate?'소멸 국가':'현재 국가'}</p><dl><div><dt>건국</dt><dd>{formatDate(c.foundedDate)}</dd></div><div><dt>소멸</dt><dd>{c.dissolvedDate?formatDate(c.dissolvedDate):'존속 중'}</dd></div><div><dt>주요 종족</dt><dd>{species.find(s=>s.id===c.primarySpeciesId)?.name??c.primarySpeciesId}</dd></div><div><dt>상태</dt><dd>{{active:'존속',reunified:'재통합',annexed:'영토 상실',state_defeat:'국가 패배'}[c.endType]}</dd></div><div><dt>최고 인구</dt><dd>{Math.round(c.peakPopulation.value).toLocaleString()}명 · {formatDate(c.peakPopulation.date)}</dd></div><div><dt>최고 GDP</dt><dd>{c.peakGDP.value.toFixed(1)}십억 BK · {formatDate(c.peakGDP.date)}</dd></div><div><dt>최장 전쟁</dt><dd>{c.longestWarMonths}개월</dd></div><div><dt>선거</dt><dd>{c.electionsHeld}회</dd></div><div><dt>기술 기록 / 주요 재난</dt><dd>{milestones.length} / {crises.length}</dd></div><div><dt>획득 / 상실 둥지권</dt><dd>{c.territorialChanges.filter(t=>t.toId===c.countryId).length} / {c.territorialChanges.filter(t=>t.fromId===c.countryId).length}</dd></div></dl><p>기원 계보: {selectCountryLineage(history,c.countryId).map(id=>history.countries[id]?.nameAtFounding??id).join(' → ')}</p><p>후속 국가: {c.successorCountryIds.map(id=>history.countries[id]?.currentOrFinalName??id).join(' / ')||'없음'}</p></article><h3>기술 발전</h3>{milestones.map(t=><p key={t.id}>{formatDate(t.date)} · {t.technologyName} {t.worldFirst?'· 세계 최초':''}</p>)}<h3>주요 재난</h3>{crises.map(t=><article className="panel event-record" key={t.crisisId}><h3>{t.jurisdictionName} · {crisisDefinitions[t.type].name}</h3><p>{formatDate(t.startedDate)}–{t.endedDate?formatDate(t.endedDate):'진행 중'} · {t.durationMonths}개월 · 최대 강도 {t.maxSeverity.toFixed(1)}</p><p>재정비용 {t.totalFiscalCost.toFixed(2)}십억 BK · 인구영향 {Math.round(t.totalPopulationImpact).toLocaleString()}명</p></article>)}</section>;}



