import WarDeclaration from './WarDeclaration';
import { countriesAtWar } from '../game/military';
import { warStatusLabels } from '../game/warfareConfig';
import { getDiplomaticPairKey } from '../game/diplomacy';
import { useState } from 'react';
import { countryName, getBilateralRelation, getDiplomaticActionBlock, getDiplomaticCooldown, isRecognized, isSanctioning, relationCategory, threatCategory } from '../game/diplomacy';
import { diplomaticActionDescriptions, diplomaticActionLabels } from '../game/diplomacyConfig';
import type { DiplomaticAction, GameState, WarGoal } from '../game/types';
export default function DiplomacyView({game,onAction,onDeclare}:{onDeclare:(id:string,goal:WarGoal)=>void;game:GameState;onAction:(target:string,action:DiplomaticAction)=>void}){
  const actor=game.player.controlledCountryId,ids=Object.keys(game.world.countries).filter(id=>id!==actor).sort();
  const [selected,setSelected]=useState<string|null>(null);const target=selected&&ids.includes(selected)?selected:ids[0];
  const r=target?getBilateralRelation(game.world,actor,target):undefined;
  return <section className="diplomacy-view" aria-label="국가 외교"><div className="panel diplomacy-scope"><strong>{countryName(game.world,actor)}의 국가 간 외교</strong><p>공동 비행회랑과 대사 횃대를 통해 각국과 관계를 맺습니다. 조약 제안은 상대국의 관계·신뢰·위협을 바탕으로 수락 여부를 판단합니다.</p></div>
    <div className="diplomacy-layout"><div className="diplomatic-nations panel"><h2>상대 국가</h2>{ids.map(id=>{const rel=getBilateralRelation(game.world,actor,id);return <button key={id} className={`diplomatic-country ${target===id?'selected':''}`} onClick={()=>setSelected(id)}><strong>{countryName(game.world,id)}</strong><span>{game.world.countries[id].identity?.status==='disputed_breakaway'?'분쟁 중 · ':''}{rel?relationCategory(rel.relations):'관계 준비 중'}</span>{rel&&<small>관계 {rel.relations.toFixed(1)} · 신뢰 {rel.trust.toFixed(1)} · 위협 {(actor===rel.countryA?rel.threatAtoB:rel.threatBtoA).toFixed(1)}<br/>무역 {rel.tradeLevel.toFixed(1)} · {isRecognized(rel,actor)?'승인':'미승인'} · {rel.defensePact?'방위조약':rel.nonAggressionPact?'불가침조약':'조약 없음'} · {isSanctioning(rel,actor)?'제재 부과':isSanctioning(rel,id)?'제재 받음':'제재 없음'}</small>}</button>})}</div>
    {r&&target?<div className="diplomacy-detail"><section className="panel"><div className="panel-heading"><h2>{countryName(game.world,target)}</h2><span>{relationCategory(r.relations)}</span></div><div className="diplomacy-metrics">{[['관계도',r.relations],['신뢰',r.trust],['위협',actor===r.countryA?r.threatAtoB:r.threatBtoA],['무역 수준',r.tradeLevel]].map(([label,value])=><div key={label}><span>{label}</span><strong>{Number(value).toFixed(1)}</strong></div>)}</div><p>{countriesAtWar(game.world,actor,target)?'현재 전쟁 중 · '+Object.values(game.world.warfare!.wars).filter(w=>w.status!=='resolved'&&w.participants[actor]&&w.participants[target]).map(w=>warStatusLabels[w.status]).join(', '):'전쟁 없음'} · 전후 휴전 {game.world.warfare!.truces[getDiplomaticPairKey(actor,target)]?.remainingMonths??0}개월</p><p>위협: {threatCategory(actor===r.countryA?r.threatAtoB:r.threatBtoA)} · 월 관계 변화 {r.relationsDeltaLastMonth.toFixed(2)}</p><p>내 승인: {isRecognized(r,actor)?'승인':'미승인'} / 상대 승인: {isRecognized(r,target)?'승인':'미승인'}</p><p>조약: {r.defensePact?'상호방위조약 (불가침 포함)':r.nonAggressionPact?'불가침조약':'없음'}{r.migratoryPassageAgreement?' · 철새 이동협정':''}</p><p>제재: {isSanctioning(r,actor)?'내가 부과함 ':''}{isSanctioning(r,target)?'상대가 부과함':!isSanctioning(r,actor)?'없음':''} · 행동 대기 {getDiplomaticCooldown(r,actor,game.turn)}개월</p></section>
    <WarDeclaration key={target} game={game} target={target} onDeclare={onDeclare}/><section className="panel diplomatic-actions"><h2>외교 행동</h2>{(Object.keys(diplomaticActionLabels) as DiplomaticAction[]).map(action=>{const block=getDiplomaticActionBlock(game,actor,target,action);return <div className="diplomatic-action" key={action}><div><strong>{diplomaticActionLabels[action]}</strong><p>{diplomaticActionDescriptions[action]}</p><small className={block?'action-blocked':''}>{block??'실행 가능 · 실행 후 같은 국가 대상 3개월 대기'}</small></div><button className="secondary" data-diplomacy-action={action} disabled={!!block} onClick={()=>onAction(target,action)}>{diplomaticActionLabels[action]}</button></div>})}</section></div>:<section className="panel"><p>외교 상대국이 없습니다.</p></section>}</div></section>;
}
