import HistoryView from './HistoryView';
import AchievementView from './AchievementView';
import {useState} from 'react';
import {ArrowLeft,Flag,Feather} from 'lucide-react';
import Brand from './Brand';
import {formatDate} from '../game/engine';
import {formatAge,formatDuration} from '../game/mortality';
import {calculateEndingResult} from '../game/endings';
import type {GameState} from '../game/types';
export default function GameOver({game,onExit,onSave}:{game:GameState;onExit:()=>void;onSave?:()=>void}){
 const [showHistory,setShowHistory]=useState(false),result=calculateEndingResult(game),defeated=game.gameOverReason==='election_defeat';
 return <div className="setup-shell game-over-shell"><header className="setup-header"><Brand/><span className="version">END OF TERM</span></header><main className="game-over-content"><div className="game-over-emblem"><Feather size={44} strokeWidth={1.1}/></div><span className={'ending-alignment '+result.alignment}>{result.alignment.toUpperCase()} END</span><h1>{result.title}</h1><p className="game-over-description">{result.description}</p><p>엔딩은 통치가 끝난 방식이며, 점수와 등급은 통치 중 이룬 업적을 평가합니다.</p>{game.tutorial&&game.tutorial.mode!=='skipped'&&<p className="tutorial-complete">{defeated?'Bird Kingdom에서는 재선 실패도 통치의 종료입니다. 메인 메뉴에서 튜토리얼을 다시 시작할 수 있습니다.':'메인 메뉴에서 튜토리얼을 다시 시작할 수 있습니다.'}</p>}<section className="game-over-summary" aria-label="최종 운영 기록"><div className="game-over-jurisdiction"><Flag size={22}/><div><strong>{result.countryName}</strong>{result.regionName&&<span>{result.regionName} · 주 정부</span>}</div></div><dl><div><dt>최종 나이</dt><dd>{formatAge(result.finalAge)}</dd></div><div><dt>집권 기간</dt><dd>{formatDuration(result.reignMonths)}</dd></div><div><dt>마지막 플레이 날짜</dt><dd>{formatDate(result.date)}</dd></div><div><dt>선거 승리</dt><dd>{result.electionsWon}회</dd></div><div><dt>국제전쟁 / 승전</dt><dd>{result.summary.wars}회 / {result.summary.victories}회</dd></div><div><dt>건국 / 주요 위기</dt><dd>{result.summary.countriesFounded}회 / {result.summary.majorCrises}회</dd></div><div><dt>엔딩 원인</dt><dd>{({death:'플레이어 사망',election_defeat:'재선 실패',state_defeat:'국가 패배'})[result.gameOverReason]}</dd></div></dl></section><AchievementView game={{...game,endingResult:result}} earnedOnly/><button className="secondary" onClick={()=>setShowHistory(!showHistory)}>{showHistory?'결과 요약으로 돌아가기':'전체 역사 보기'}</button>{showHistory&&<HistoryView game={game}/>}<div className="ending-save">{onSave&&<button className="secondary" onClick={onSave}>저장 / 불러오기</button>}</div><button className="primary" onClick={onExit}><ArrowLeft size={17}/> 메인 메뉴로 돌아가기</button></main><footer className="setup-footer"><span>BIRD KINGDOM / 국가 운영 시뮬레이션</span><span>운영 종료</span></footer></div>;
}
