import { militaryCommitments } from '../game/military';
import { derivedCountryRuntime, regionInfo } from '../game/runtime';
import { getPeaceBlock } from '../game/peace';
import { warGoalLabels, warStatusLabels } from '../game/warfareConfig';
import type { GameState, WarAction, WarResolution } from '../game/types';
export interface MilitaryActions {onMobilization:(target:number)=>void;onWarAction:(warId:string,action:WarAction)=>void;onPeace:(warId:string,resolution:WarResolution)=>void}
const peaceLabels:Record<WarResolution,string>={status_quo:'현상유지 평화',territory_transfer:'목표 영토 이전',recognition:'독립 승인',abandon_reunification:'재통합 주장 포기',reparations:'일시 국고 배상',defense_success:'방어 성공 협정'};
export default function MilitaryView({game,onMobilization,onWarAction,onPeace}:MilitaryActions&{game:GameState}){
 const id=game.player.controlledCountryId,r=derivedCountryRuntime(game.world,id),m=r.military!,blocked=!!game.events.pendingEvent||game.world.warfare!.allyRequests.some(r=>r.allyCountryId===id&&r.status==='pending');
 const expand=militaryCommitments(game.world,id)>0||Object.values(game.world.diplomacy!.relations).some(r=>(r.countryA===id||r.countryB===id)&&r.threat>=60);
 const wars=Object.values(game.world.warfare!.wars).filter(w=>w.participants[id]).reverse();
 return <section aria-label="국가 군사"><div className="panel"><h2>곡물 보급망과 국가 군사 수행력</h2><p>비행회랑·대형 횃대·안전한 휴식지를 유지하는 국가의 전략 역량입니다. 동원과 국방예산은 수개월에 걸쳐 반영됩니다.</p><div className="diplomacy-metrics">{[['군사 준비도',m.readiness],['동원 수준',m.mobilization],['보급',m.logistics],['군사 수행력',m.capability],['전쟁 지지도',m.warSupport],['전쟁 피로',m.fatigue]].map(([label,value])=><div key={label}><span>{label}</span><strong>{Number(value).toFixed(1)} / 100</strong><div className="gauge"><span style={{width:Number(value)+'%'}}/></div></div>)}</div><p>준비도 월 변화 {m.readinessDeltaLastMonth.toFixed(2)} · 국방예산 {r.fiscal.budgetPolicy.defense.toFixed(1)}% · 반영된 국방예산 {m.effectiveDefenseBudget.toFixed(2)}% · 방위산업 생산 {r.economy.industries.defense.output.toFixed(1)}</p><h3>동원 목표 {m.mobilizationTarget}%</h3><div className="war-actions"><button className="secondary" disabled={blocked||!expand||m.mobilizationTarget>=100} onClick={()=>onMobilization(Math.min(100,m.mobilizationTarget+20))}>동원 확대</button><button className="secondary" disabled={blocked} onClick={()=>onMobilization(m.mobilizationTarget)}>동원 유지</button><button className="secondary" disabled={blocked||m.mobilizationTarget<=0} onClick={()=>onMobilization(Math.max(0,m.mobilizationTarget-20))}>동원 축소</button></div><small>{expand?'확대 가능 · 월 최대 5%p 변화 · 동원은 국고와 생활 부담을 높입니다.':'확대는 전쟁 또는 심각한 외교위기에서 가능합니다.'}</small></div>
 {wars.length?wars.map(w=><article className="panel war-card" key={w.id}><div className="panel-heading"><h2>{w.countryNames[w.primaryAttacker]} / {w.countryNames[w.primaryDefender]}</h2><span>{warStatusLabels[w.status]}</span></div><p>정당성: {w.legitimacy==='unjustified'?'침략전쟁':'정당화됨'}</p><p>{warGoalLabels[w.warGoal]} · {w.monthsAtWar}개월 · {w.resolution?peaceLabels[w.resolution]:'진행 중'}</p><div className="war-participants">{Object.values(w.participants).map(p=><div key={p.countryId}><strong>{w.countryNames[p.countryId]} · {p.side==='attacker'?'공격 진영':'방어 진영'}</strong><span>지지도 {p.warSupport.toFixed(1)} · 피로 {p.fatigue.toFixed(1)} · 기여 {p.contribution.toFixed(1)}%</span></div>)}</div>{w.fronts.length?w.fronts.map(f=><div className="war-front" key={f.regionId}><strong>{regionInfo(game,f.regionId)?.name??f.regionId}</strong><p>법적 소유: {game.world.countries[game.world.regions[f.regionId]?.ownerCountryId]?.identity?.name??w.countryNames[f.originalOwnerCountryId]} · 관제: {game.world.countries[f.controllerCountryId]?.identity?.name??w.countryNames[f.controllerCountryId]}</p><div className="gauge" role="meter" aria-label="공격측 통제" aria-valuenow={f.control} aria-valuemin={0} aria-valuemax={100}><span style={{width:f.control+'%'}}/></div><p>{w.countryNames[w.primaryAttacker]} {f.control.toFixed(1)}% / {w.countryNames[w.primaryDefender]} {(100-f.control).toFixed(1)}% · 결정적 통제 {f.decisiveMonths}개월</p></div>):<p>영토 획득 없는 회랑 대치 · 공격측 전략 통제 {w.strategicControl.toFixed(1)}%</p>}
 {w.status!=='resolved'&&<><div className="war-actions"><button className="secondary" disabled={blocked||w.status!=='active'} onClick={()=>onWarAction(w.id,'ceasefire')}>휴전</button><button className="secondary" disabled={blocked||w.status==='peace_negotiation'} onClick={()=>onWarAction(w.id,'negotiate')}>평화협상</button><button className="secondary" disabled={blocked||w.status==='active'} onClick={()=>onWarAction(w.id,'resume')}>충돌 재개</button></div>{w.status==='peace_negotiation'&&<div className="peace-options">{(Object.keys(peaceLabels) as WarResolution[]).map(result=>{const reason=getPeaceBlock(game,w.id,result);return <div key={result}><button className="secondary" disabled={blocked||!!reason} onClick={()=>onPeace(w.id,result)}>{peaceLabels[result]}</button>{reason&&<small>{reason}</small>}</div>})}</div>}</>}
 </article>):<div className="panel"><h2>진행 중인 전쟁이 없습니다</h2><p>외교 화면에서 선전포고를 검토할 수 있습니다. 명분 없는 공격은 침략전쟁으로 기록되어 외교적 비용을 남깁니다.</p></div>}</section>;
}
