import {latestPatch} from '../game/patchNotes';
import PatchNotes from './PatchNotes';
import {useState} from 'react';
import {difficultyConfig,difficultyNames,type Difficulty} from '../game/difficulty';
import { ArrowLeft, ArrowRight, Building2, ChevronRight, Feather, Flag, GraduationCap, Landmark, Shield, Sprout } from 'lucide-react';
import Brand from './Brand';
import { countries, regions, species } from '../game/data';
import type { StartingCountryId, RegionId } from '../game/types';

type SetupScreen = 'menu' | 'countries' | 'regions';
interface Props { onTutorial?:()=>void; hasSaves?:boolean;onContinue?:()=>void; screen: SetupScreen; onScreen: (screen: SetupScreen) => void; onStart: (country: StartingCountryId, region: RegionId|undefined,difficulty:Difficulty) => void }
const regionIcons = [Landmark, Shield, GraduationCap, Sprout];

export default function Setup({ screen, onScreen, onStart,hasSaves,onContinue,onTutorial }: Props) {
  const [difficulty,setDifficulty]=useState<Difficulty>('normal');
  return <div className="setup-shell"><header className="setup-header"><Brand /><span className="version">v{latestPatch.version} <b>{latestPatch.title}</b></span></header>
    {screen === 'menu' ? <main className="menu-main"><div className="menu-copy"><span className="eyebrow"><span className="status-dot" /> A NEW ERA BEGINS</span><h1>BIRD<br /><span>KINGDOM</span><span className="title-period">.</span></h1><p className="menu-subtitle">조류 국가 운영 시뮬레이션</p><p className="menu-description">하나의 국가. 다양한 종족. 당신의 첫 번째 임기.<br />2030년, 새로운 정부 운영을 시작하세요.</p><div className="menu-actions"><button className="primary" onClick={() => onScreen('countries')}>새 게임 <ArrowRight size={19} /></button><button className="secondary" disabled={!hasSaves} onClick={onContinue}>이어하기</button><button className="secondary" onClick={onContinue}>저장 / 불러오기</button></div><button className="secondary tutorial-replay" onClick={onTutorial}>튜토리얼 다시 시작</button><PatchNotes/><div className="menu-note">CHAPTER 01 <span>국가 운영의 시작</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-grid" /><Feather className="hero-feather" strokeWidth={0.65} /><span className="hero-coordinate">37° 34′ N / 126° 58′ E</span><div className="hero-caption"><span>WORLD STATUS</span><strong>새로운 시대의 시작</strong><small>JANUARY 2030</small></div></div></main> : <main className="selection-main"><button className="back-button" onClick={() => onScreen(screen === 'regions' ? 'countries' : 'menu')}><ArrowLeft size={16} /> {screen === 'regions' ? '국가 선택으로' : '메인 메뉴로'}</button><div className="selection-heading"><div><span className="eyebrow">{screen === 'countries' ? '01 / SELECT YOUR NATION' : '02 / SELECT YOUR STATE'}</span><h1>{screen === 'countries' ? '어디에서 시작하시겠습니까?' : '운영할 주를 선택하세요.'}</h1><p>{screen === 'countries' ? '국가의 체제를 살펴보고, 새로운 정부 운영을 시작하세요.' : '비둘기민주연방의 네 개 주 중 하나의 주 정부를 운영합니다.'}</p></div><span className="date-chip">2030년 1월 시작</span></div>
      <section className='difficulty-selection' aria-label='난이도 선택'><h2>난이도</h2><div>{difficultyNames.map(id=><label className={difficulty===id?'selected':' '} key={id}><input type='radio' name='difficulty' value={id} checked={difficulty===id} onChange={()=>setDifficulty(id)}/><strong>{difficultyConfig[id].label}</strong><span>{difficultyConfig[id].description}</span></label>)}</div></section>{screen === 'countries' ? <div className="country-grid">{countries.map((country, index) => <article className={`selection-card country-card country-${country.id}`} key={country.id}><div className="card-top"><span className="selection-emblem">{index === 0 ? <Flag size={38} strokeWidth={1.2} /> : <Building2 size={38} strokeWidth={1.2} />}</span><span className="card-number">0{index + 1}</span></div><span className="eyebrow">{country.englishName}</span><h2>{country.name}</h2><span className="tag">{country.governmentLabel}</span><p className="card-description">{country.description}</p><div className="country-facts"><span>주요 종족<strong>{country.speciesIds.map(id => species.find(item => item.id === id)!.name).join(' / ')}</strong></span><span>운영 범위<strong>{country.playScope}</strong></span>{country.id === 'pigeon' && <span>연방 구성<strong>4개의 주</strong></span>}</div><button className="card-select" onClick={() => country.id === 'sparrow' ? onStart('sparrow',undefined,difficulty) : onScreen('regions')}>{country.id === 'sparrow' ? '공화국 운영 시작' : '연방의 주 선택'}<ArrowRight size={18} /></button></article>)}</div> : <div className="region-grid">{regions.map((region, index) => { const Icon = regionIcons[index]; return <article className="selection-card region-card" key={region.id}><div className="card-top"><span className="selection-emblem"><Icon size={32} strokeWidth={1.3} /></span><span className="card-number">0{index + 1}</span></div><span className="eyebrow">{region.englishName}</span><h2>{region.name}</h2><span className="tag">{region.isCapital ? '연방 수도 소재' : '연방 구성 주'}</span><h3>{region.specialty}</h3><p className="card-description">{region.description}</p><button className="card-select" onClick={() => onStart('pigeon', region.id,difficulty)}>주 운영 시작<ChevronRight size={18} /></button></article>; })}</div>}
      <p className="selection-note">국가와 주의 산업 구성·사회 기반이 서로 다릅니다. 선택한 관할의 정책을 직접 운영합니다.</p></main>}
    <footer className="setup-footer"><span>BIRD KINGDOM / 국가 운영 시뮬레이션</span><span>국가 운영 · 첫 임기 안내</span></footer></div>;
}



