import {useState} from 'react';
import {federalStateIds,isActiveFederalState} from '../game/stateRelationsModel';
import {getStateRelation,stateActionLabels,stateResponseLabels,stateActionBlock,evaluateStateActionSupport,blocPurposeLabels,mediationLabels} from '../game/stateRelations';
import {regionInfo} from '../game/runtime';
import {formatDate} from '../game/engine';
import type {GameState,StateAction,BlocPurpose} from '../game/types';
export default function StateRelationsView({game,onAction}:{game:GameState;onAction:(target:string,action:StateAction,purpose:BlocPurpose,rival:string|null)=>void}){
 const [target,setTarget]=useState('owl-state'),[purpose,setPurpose]=useState<BlocPurpose>('economic'),[rival,setRival]=useState('pigeon-state');
 const actor=game.player.controlledRegionId;if(!actor||!isActiveFederalState(game.world,actor))return null;
 const members=federalStateIds.filter(id=>isActiveFederalState(game.world,id)),targets=members.filter(id=>id!==actor),selected=targets.includes(target as typeof targets[number])?target:targets[0];
 const pairs=Object.values(game.world.statePolitics?.relations??{}).filter(r=>r.active),name=(id:string)=>regionInfo(game,id)?.name??id;
 const r=selected?getStateRelation(game,actor,selected):null,rivals=members.filter(id=>id!==actor&&id!==selected),selectedRival=rivals.includes(rival as typeof rivals[number])?rival:rivals[0]??null;
 return <section className="panel state-relations" aria-label="연방 내부관계"><div className="panel-heading"><h2>연방 내부관계</h2><span>주정부 간 정치관계</span></div><p className="panel-description">서로 다른 이해관계를 가진 주들과 협력하거나 경쟁할 수 있습니다. 정치블록은 임시 공동전선이며 군사동맹이 아닙니다.</p>
 <div className="state-pair-grid">{pairs.map(pair=><article key={pair.stateAId+pair.stateBId}><h3>{name(pair.stateAId)} ↔ {name(pair.stateBId)}</h3><dl><div><dt>관계</dt><dd>{pair.relations.toFixed(1)}</dd></div><div><dt>경쟁</dt><dd>{pair.rivalry.toFixed(1)}</dd></div><div><dt>협력</dt><dd>{pair.cooperation.toFixed(1)}</dd></div></dl><p>최근 행동: {pair.history.at(-1)?stateActionLabels[pair.history.at(-1)!.action]:'없음'}</p></article>)}</div>
 {r&&selected?<><div className="state-action-settings"><label>상대 주 <select aria-label="상대 주" value={selected} onChange={e=>setTarget(e.target.value)}>{targets.map(id=><option value={id} key={id}>{name(id)}</option>)}</select></label><label>정치블록 목적 <select aria-label="정치블록 목적" value={purpose} onChange={e=>setPurpose(e.target.value as BlocPurpose)}>{Object.entries(blocPurposeLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>{purpose==='anti_rival'&&<label>공동 견제 대상 <select aria-label="공동 견제 대상" value={selectedRival??''} onChange={e=>setRival(e.target.value)}>{rivals.map(id=><option key={id} value={id}>{name(id)}</option>)}</select></label>}</div>
 <div className="federal-action-grid">{(Object.keys(stateActionLabels) as StateAction[]).map(action=>{const reason=stateActionBlock(game,actor,selected,action,action==='joint_autonomy'?'autonomy':purpose,selectedRival),support=evaluateStateActionSupport(game,actor,selected,action);return <article key={action}><h3>{stateActionLabels[action]}</h3><p>주민 반응: {support.reaction}<br/>상대 반발: {['criticize','counter_policy'].includes(action)?'높음':'보통'}<br/>정치적 위험: {support.risk}<br/>연방 개입: {r.rivalry>=65?'높음':'보통'}</p><button className="secondary" disabled={!!reason} title={reason??stateActionLabels[action]} onClick={()=>onAction(selected,action,action==='joint_autonomy'?'autonomy':purpose,selectedRival)}>{stateActionLabels[action]}</button>{reason&&<small>{reason}</small>}</article>})}</div>
 <h3>{name(selected)}과 최근 행동</h3><ul className="federal-history">{r.history.slice(-6).reverse().map(h=><li key={h.id}>{formatDate(h.date)} · {name(h.actorId)}: {stateActionLabels[h.action]} · 상대 {stateResponseLabels[h.response]}</li>)}</ul><h3>연방 중재 기록</h3><ul className="federal-history">{r.mediations.slice(-4).reverse().map(m=><li key={m.id}>{formatDate(m.date)} · {m.favoredStateId?`${name(m.favoredStateId)} 입장 지지`:mediationLabels[m.outcome]}</li>)}</ul></>:<p>현재 협상 가능한 다른 연방 주가 없습니다.</p>}
 <h3>정치블록</h3>{game.world.statePolitics?.blocs.filter(b=>b.active).length?game.world.statePolitics.blocs.filter(b=>b.active).map(b=><div key={b.id} className="state-bloc"><strong>{blocPurposeLabels[b.purpose]}</strong><p>{b.memberStateIds.map(name).join(' + ')}{b.rivalStateId?` · ${name(b.rivalStateId)} 견제`:''}</p><p>결속 {b.cohesion.toFixed(1)} / 100 · 최대 {Math.max(0,b.expiresTurn-game.turn)}개월 남음</p></div>):<p>활성 정치블록이 없습니다. 협력 관계가 충분한 주에 제안할 수 있습니다.</p>}
 </section>;
}
