import { countryName } from '../game/diplomacy';
import { postureLabels } from '../game/strategicConfig';
import { diplomaticActionLabels } from '../game/diplomacyConfig';
import { formatDate } from '../game/engine';
import type { GameState, DiplomaticAction } from '../game/types';
import type { AIStrategicDecisionRecord } from '../game/strategicTypes';
const otherLabels:Record<string,string>={declare_war:'선전포고',mobilization:'동원 조정',ceasefire:'휴전',peace_proposal:'평화 제안',status_quo:'현상유지 평화',territory_transfer:'영토 합의',reparations:'배상 합의',recognition:'독립 승인 평화',abandon_reunification:'재통합 주장 포기',defense_success:'방어 평화',ally_join:'방위조약 참전',ally_decline:'참전 거절',proposal_accepted:'제안 수락',proposal_declined:'제안 거절',pressure:'분쟁 압박',escalate:'무력충돌',negotiate:'중재 협상',accept_autonomy:'재통합 협의',force_reintegrate:'둥지권 재통합',defend_independence:'독립 방어'};
export function strategicRecordLabel(r:AIStrategicDecisionRecord){const label=diplomaticActionLabels[r.action as DiplomaticAction]??otherLabels[r.action];return label?label+(r.targetName?' · '+r.targetName:''):r.summary;}
export default function StrategicView({game}:{game:GameState}){return <section className="strategic-view" aria-label="세계 대외정책"><div className="section-heading"><h2>세계 대외정책</h2><span>국가별 공개 동향</span></div><div className="government-policy-grid">{Object.keys(game.world.countries).sort().map(id=>{const s=game.world.strategicAI?.[id],last=s?.recentStrategicDecisions[0],m=game.world.countries[id].military!;return <article className="panel government-policy-card" key={id}><h3>{countryName(game.world,id)}</h3><strong>대외정책: {id===game.player.controlledCountryId?'직접 운영':postureLabels[s?.foreignPolicy??'cautious']}</strong><p>{last?strategicRecordLabel(last):'현재 국제관계를 유지하고 있습니다.'}</p><small>현재 동원 {m.mobilization.toFixed(0)}% · 목표 {m.mobilizationTarget}%</small></article>;})}</div><div className="strategic-recent">{Object.values(game.world.strategicAI??{}).flatMap(s=>s.recentStrategicDecisions).filter(r=>['recognize','sanction','lift_sanctions','defense','declare_war','territory_transfer','reparations','status_quo','recognition','abandon_reunification','defense_success'].includes(r.action)).sort((a,b)=>b.turn-a.turn||a.countryId.localeCompare(b.countryId)).slice(0,8).map((r,i)=><p key={`${r.countryId}-${r.turn}-${r.action}-${i}`}><time>{formatDate(r.date)}</time> {countryName(game.world,r.countryId)} · {strategicRecordLabel(r)}</p>)}</div></section>;}
