import {regionInfo} from '../game/runtime';
import { useState } from 'react';
import { getWarDeclarationBlock } from '../game/casusBelli';
import { getDefenseAllies } from '../game/warfare';
import { countryName } from '../game/diplomacy';
import { warGoalLabels, casusBelliLabels } from '../game/warfareConfig';
import type { GameState, WarGoal } from '../game/types';
export default function WarDeclaration({game,target,onDeclare}:{game:GameState;target:string;onDeclare:(belliId:string,goal:WarGoal)=>void}){
 const actor=game.player.controlledCountryId,bellis=Object.values(game.world.warfare!.casusBelli).filter(b=>b.holderCountryId===actor&&b.targetCountryId===target&&!b.consumed&&b.expiresInMonths!==0);
 const [selection,setSelection]=useState<{id:string;goal:WarGoal}|null>(null);const goals=Object.keys(warGoalLabels) as WarGoal[];
 return <><section className="panel"><h2>전쟁명분</h2>{bellis.length?bellis.map(b=><div className="diplomatic-action" key={b.id}><div><strong>{casusBelliLabels[b.type]}</strong><p>{b.expiresInMonths===null?'지속 명분':b.expiresInMonths+'개월 남음'}{b.targetRegionId?' · 목표 둥지권 '+(regionInfo(game,b.targetRegionId)?.name??b.targetRegionId):''}</p>{getWarDeclarationBlock(game,actor,b.id,goals.find(goal=>!getWarDeclarationBlock(game,actor,b.id,goal))??'punitive')&&<small>{getWarDeclarationBlock(game,actor,b.id,'punitive')}</small>}</div><button className="secondary" disabled={!goals.some(goal=>!getWarDeclarationBlock(game,actor,b.id,goal))} onClick={()=>setSelection({id:b.id,goal:goals.find(goal=>!getWarDeclarationBlock(game,actor,b.id,goal))!})}>선전포고</button></div>):<p>유효한 전쟁명분이 없습니다.</p>}</section>
 {selection&&<div className="modal-backdrop"><section className="event-dialog panel" role="dialog" aria-modal="true" aria-labelledby="war-confirm-title"><h2 id="war-confirm-title">선전포고 확인</h2><p>예상 상대: {countryName(game.world,target)} · 현재 준비도 {game.world.countries[actor].military!.readiness.toFixed(1)}</p><label>전쟁 목표 <select aria-label="전쟁 목표" value={selection.goal} onChange={e=>setSelection({...selection,goal:e.target.value as WarGoal})}>{goals.map(goal=><option key={goal} disabled={!!getWarDeclarationBlock(game,actor,selection.id,goal)} value={goal}>{warGoalLabels[goal]}</option>)}</select></label><p>상대 방위조약 · 예상 참전국: {getDefenseAllies(game,target,actor).map(id=>countryName(game.world,id)).join(', ')||'없음'}</p><p>명분을 소비합니다. 전시비용과 피로가 발생하며 영토 이전은 평화협정에서 확정됩니다.</p><div className="war-actions"><button className="secondary" autoFocus onClick={()=>setSelection(null)}>취소</button><button className="primary" onClick={()=>{onDeclare(selection.id,selection.goal);setSelection(null);}}>선전포고 확정</button></div></section></div>}</>;
}
